import type { AuditSession, AuditSnapshot, AuditScope, AuditEvent, AuditMetric, AuditPromptPage, AuditEvidence, AuditProject, AuditConversation, AuditWorkBar } from '../../../core/src/analytics/contracts.js';

export interface AuditTerminalOptions { color?:boolean; ascii?:boolean; width?:number; motion?:boolean; private?:boolean; onScopeRequest?:(scope:AuditScope)=>void; }
export type AuditTerminalResult={snapshot:AuditSnapshot;reason:'quit'|'cancelled'|'complete'};
export type AuditSection='home'|'work'|'projects'|'activity'|'conversations'|'usage'|'words'|'sources';
export interface AuditNavFrame { section:AuditSection; view:'section'|'conversations'|'prompts'|'evidence'|'receipt'|'source'; selectedId:string|null; selectedIndex:number; scroll:number; projectId:string|null; conversationId:string|null; phraseId:string|null; sourceHarness:string|null; category:string|null; query:string; }
export interface AuditNavigation extends AuditNavFrame { stack:readonly AuditNavFrame[]; screenshot:boolean; help:boolean; editing:'search'|'scope'|'semantic'|null; }
export interface AuditRow { id:string; label:string; value:string; kind:'project'|'conversation'|'prompt'|'source'|'metric'|'work'|'activity'|'phrase'|'usage'; }
export interface AuditScreenOptions extends AuditTerminalOptions { columns?:number; rows?:number; widthOf?:(text:string)=>number; frame?:number; promptPage?:AuditPromptPage|null; evidence?:AuditEvidence|null; busy?:boolean; notice?:string; scopeDraft?:AuditScope; scopeField?:number; }
export type AuditTone='normal'|'dim'|'amberDim'|'amber'|'amberLight'|'cyan'|'green'|'violet'|'blue';
export interface AuditSegment { text:string; tone:AuditTone; }
export type AuditLine=readonly AuditSegment[];
const SECTIONS:readonly AuditSection[]=['home','work','projects','activity','conversations','usage','words','sources'];
const LABELS:Record<AuditSection,string>={home:'home',work:'work',projects:'projects',activity:'activity',conversations:'threads',usage:'usage',words:'words',sources:'sources'};
const HARNESS_NAMES:Record<string,string>={claude:'Claude',codex:'Codex',pi:'pi',opencode:'OpenCode'};
const HARNESS_TONES:Record<string,AuditTone>={claude:'amber',codex:'cyan',pi:'green',opencode:'violet'};
const PALETTE:Record<AuditTone,string>={normal:'#e9e8e0',dim:'#77858b',amberDim:'#be7337',amber:'#f9ae56',amberLight:'#ffd89b',cyan:'#47d7e2',green:'#79c9a3',violet:'#b29ddb',blue:'#80ade0'};
const BUSY_STATES=new Set(['discovering','parsing','normalizing']);
const WORK_LABELS:Record<string,string>={feature_build:'feature build',bug_fix:'bug requests',ui_design:'UI design',tests:'tests',refactor:'refactor',code_review:'code review',pr_management:'PR management',research:'research',explanation_learning:'learning',planning_architecture:'planning',deploy_operations:'operations',documentation_writing:'documentation',agent_coordination:'coordination',other:'other',mixed:'mixed',insufficient_context:'insufficient context',unclassified:'unclassified','other labels':'other labels'};
function workLabel(label:string):string{return WORK_LABELS[label]??WORK_LABELS[label.replaceAll(' ','_')]??'unclassified';}
const numberFormat=new Intl.NumberFormat('en-US',{maximumFractionDigits:1});
const segmenter=new Intl.Segmenter('en',{granularity:'grapheme'});

function clean(text:string):string { return text.replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g,'').replace(/\x1b\[[0-?]*[ -/]*[@-~]/g,'').replace(/[\x00-\x08\x0b-\x1f\x7f-\x9f]/g,''); }
function single(text:string):string {return clean(text).replace(/[\r\n\t]/g,' ');}
function graphemes(text:string):string[]{return [...segmenter.segment(text)].map(part=>part.segment);}
/** Used only by dependency-free public/plain output. Interactive clipping uses string-width. */
export function auditCellWidth(text:string):number {return graphemes(single(text)).reduce((sum,g)=>sum+( /[\p{Extended_Pictographic}\p{Regional_Indicator}\u20e3\u1100-\u115f\u2329\u232a\u2e80-\ua4cf\uac00-\ud7a3\uf900-\ufaff\ufe10-\ufe19\ufe30-\ufe6f\uff01-\uff60\uffe0-\uffe6]/u.test(g)?2:/^\p{Mark}+$/u.test(g)?0:1),0);}
export function auditClip(text:string,width:number,widthOf:(text:string)=>number=auditCellWidth):string {let result='';for(const g of graphemes(single(text))){if(widthOf(result+g)>Math.max(0,width))break;result+=g;}return result;}
function pad(text:string,width:number,widthOf:(text:string)=>number):string{const value=auditClip(text,width,widthOf);return value+' '.repeat(Math.max(0,width-widthOf(value)));}
function n(value:number|null|undefined,ascii=false):string{return value===null||value===undefined||!Number.isFinite(value)?ascii?'?':'—':numberFormat.format(value);}
function metricValue(metric:AuditMetric,ascii=false):string{return metric.state==='unavailable'||metric.state==='not_run'?ascii?'?':'—':n(metric.value,ascii);}
function units(unit:string):string {const known:Record<string,string>={eligible_human_input_event:'human prompts',human_prompt:'human prompts',prompt:'prompts',prompts:'prompts',top_level_conversation:'conversations',conversation:'conversations',conversations:'conversations',known_project:'projects',supported_child_source:'linked children',elapsed_days:'elapsed days',day:'days',days:'days',event:'events',events:'events',containing_prompts:'containing prompts'};return known[unit]??'observations';}
export function auditProjectAlias(snapshot:AuditSnapshot,id:string|null):string {const index=snapshot.projects.findIndex(p=>p.id===id);const project=snapshot.projects[index];if(project&&/^Project [A-Z]+$/.test(project.alias))return project.alias;return index<0?'Unattributed':`Project ${letters(index)}`;}
function letters(index:number):string{let result='';for(let v=index+1;v>0;v=Math.floor((v-1)/26))result=String.fromCharCode(65+(v-1)%26)+result;return result;}
function conversationAlias(snapshot:AuditSnapshot,c:AuditConversation):string{return /^Conversation \d+$/.test(c.alias)?c.alias:`Conversation ${snapshot.conversations.findIndex(value=>value.id===c.id)+1}`;}
function projectLabel(snapshot:AuditSnapshot,project:AuditProject,privateView:boolean):string{return privateView?single(project.displayName):auditProjectAlias(snapshot,project.id);}
function conversationLabel(snapshot:AuditSnapshot,c:AuditConversation,privateView:boolean):string{return privateView&&c.title?single(c.title):conversationAlias(snapshot,c);}
function safeScope(snapshot:AuditSnapshot):string {const scope=snapshot.scope;const range=scope.eventFrom||scope.asOf?`${scope.eventFrom?.slice(0,10)??'start'} → ${scope.asOf?.slice(0,10)??'now'}`:'all recorded dates';const project=scope.project?snapshot.projects.find(p=>p.path===scope.project):null;return `${range} · ${scope.project?project?auditProjectAlias(snapshot,project.id):'selected project':'all projects'} · ${scope.timezone} · local`;}
function friendlyGap(code:string):string{if(code.includes('origin')||code.includes('human_marker'))return 'human origin incomplete';if(code.includes('policy')||code.includes('tombstone')||code.includes('ignore'))return 'privacy policy unavailable';if(code.includes('unsupported')||code.includes('parts_unread'))return 'native layout unsupported';if(code.includes('limit')||code.includes('oversize'))return 'scan limit reached';if(code.includes('time'))return 'event dates incomplete';if(code.includes('projection'))return 'projection fidelity';if(code.includes('unverified'))return 'capture unverified';return 'capture gap';}
function safeFinding(snapshot:AuditSnapshot,index:number):string {const finding=snapshot.insights[index];if(!finding)return '';const caption=single(finding.publicCaption);const privateTerms=[...snapshot.projects.flatMap(p=>[p.path,p.displayName]),...snapshot.conversations.flatMap(c=>[c.title,c.nativeSessionId]),...(snapshot.phrases??[]).map(p=>p.text)].filter((v):v is string=>Boolean(v&&v.length>2));const unsafe=privateTerms.some(term=>caption.toLowerCase().includes(term.toLowerCase()))||/[\/\\“”"\x1b]/.test(caption);return unsafe?`Recorded finding · ${metricValue(finding.value)} ${units(finding.value.unit)}`:caption;}

export function createAuditNavigation(section:AuditSection='home'):AuditNavigation{return {section,view:'section',selectedId:null,selectedIndex:0,scroll:0,projectId:null,conversationId:null,phraseId:null,sourceHarness:null,category:null,query:'',stack:[],screenshot:false,help:false,editing:null};}
function frameOf(nav:AuditNavigation):AuditNavFrame {const {stack:_stack,screenshot:_screenshot,help:_help,editing:_editing,...frame}=nav;return frame;}
export function auditPush(nav:AuditNavigation,next:Partial<AuditNavFrame>):AuditNavigation{return {...nav,...next,stack:[...nav.stack,frameOf(nav)],selectedId:null,selectedIndex:0,scroll:0,query:'',help:false,editing:null};}
export function auditBack(nav:AuditNavigation):AuditNavigation {if(nav.help||nav.editing)return {...nav,help:false,editing:null};const parent=nav.stack.at(-1);return parent?{...nav,...parent,stack:nav.stack.slice(0,-1)}:nav;}
export function auditSelectSection(nav:AuditNavigation,section:AuditSection):AuditNavigation{return {...createAuditNavigation(section),screenshot:nav.screenshot};}
export function auditMove(nav:AuditNavigation,rows:readonly AuditRow[],delta:number,visible=10):AuditNavigation {if(!rows.length)return {...nav,selectedId:null,selectedIndex:0,scroll:0};const current=nav.selectedId?rows.findIndex(r=>r.id===nav.selectedId):-1;const index=Math.max(0,Math.min(rows.length-1,(current<0?nav.selectedIndex:current)+delta));let scroll=Math.min(nav.scroll,Math.max(0,rows.length-visible));if(index<scroll)scroll=index;if(index>=scroll+visible)scroll=index-visible+1;return {...nav,selectedId:rows[index]!.id,selectedIndex:index,scroll};}
export function reconcileAuditNavigation(nav:AuditNavigation,rows:readonly AuditRow[],visible=10):AuditNavigation{return auditMove(nav,rows,0,visible);}
/** Reject source/model events from a different run or an older sequence. */
export function applyAuditEvent(snapshot:AuditSnapshot,event:AuditEvent):AuditSnapshot {if(event.type!=='snapshot'&&event.snapshotId!==snapshot.snapshotId)return snapshot;if(event.type==='snapshot')return event.snapshot.snapshotId===snapshot.snapshotId&&event.snapshot.sequence>=snapshot.sequence?event.snapshot:snapshot;if(event.type==='progress')return event.sequence>=snapshot.sequence?{...snapshot,sequence:event.sequence,status:event.progress.stage,progress:event.progress,sources:event.sources}:snapshot;return snapshot;}

export function auditRows(snapshot:AuditSnapshot,nav:AuditNavigation,page:AuditPromptPage|null=null,privateView=false):AuditRow[]{
 let rows:AuditRow[]=[];
 if(nav.view==='prompts'||nav.view==='evidence'||nav.view==='receipt')rows=(page?.snapshotId===snapshot.snapshotId&&page.conversationId===nav.conversationId?page.prompts:[]).map((p,i)=>({id:p.id,label:privateView?single(p.text):`Prompt ${page!.offset+i+1}`,value:p.eligibleHuman?'human':'origin unknown',kind:'prompt'}));
 else if(nav.view==='conversations'||nav.section==='conversations')rows=snapshot.conversations.filter(c=>(!nav.projectId||c.projectId===nav.projectId)&&(!nav.phraseId||snapshot.phrases?.find(p=>p.id===nav.phraseId)?.conversationIds.includes(c.id))&&(!nav.category||snapshot.judgments?.some(j=>j.conversationId===c.id&&j.primaryIntent===nav.category&&!j.abstained))).map(c=>({id:c.id,label:conversationLabel(snapshot,c,privateView),value:`${n(c.promptCount)} prompts${c.child?' · child':''}`,kind:'conversation'}));
 else if(nav.section==='projects')rows=snapshot.projects.map(p=>({id:p.id,label:projectLabel(snapshot,p,privateView),value:`${n(p.humanPrompts)} prompts`,kind:'project'}));
 else if(nav.section==='sources'||nav.view==='source')rows=snapshot.sources.map(s=>({id:s.harness,label:HARNESS_NAMES[s.harness]??'Source',value:`${s.state} · ${n(s.conversations)} conversations`,kind:'source'}));
 else if(nav.section==='activity')rows=snapshot.activity.map(bucket=>({id:bucket.date,label:bucket.date,value:`${n(bucket.count)} human prompts`,kind:'activity'}));
 else if(nav.section==='words')rows=(snapshot.phrases??[]).map((p,i)=>({id:p.id,label:privateView?single(p.text):`Phrase ${i+1}`,value:`${n(p.prompts)} containing prompts`,kind:'phrase'}));
 else if(nav.section==='work')rows=(snapshot.semantics.qualified?snapshot.semantics.work:[]).map((bar,i)=>({id:`work:${i}`,label:workLabel(bar.label),value:`${n(bar.count)} / ${n(bar.denominator)} prompts`,kind:'work'}));
 else if(nav.section==='usage')rows=[{id:'input',label:'Input tokens',value:n(snapshot.usage.inputTokens),kind:'usage'},{id:'output',label:'Output tokens',value:n(snapshot.usage.outputTokens),kind:'usage'},{id:'cache',label:'Cache tokens',value:n(snapshot.usage.cacheTokens),kind:'usage'},{id:'reasoning',label:'Reasoning tokens',value:n(snapshot.usage.reasoningTokens),kind:'usage'},{id:'cost',label:'Cost',value:snapshot.usage.costUsd===null?'unavailable':`$${snapshot.usage.costUsd.toFixed(4)}`,kind:'usage'}];
 else rows=[{id:'humanPrompts',label:'Human prompts',value:metricValue(snapshot.metrics.humanPrompts),kind:'metric'},{id:'conversations',label:'Conversations',value:metricValue(snapshot.metrics.conversations),kind:'metric'},{id:'projects',label:'Projects',value:metricValue(snapshot.metrics.projects),kind:'metric'},{id:'linkedChildren',label:'Linked children',value:metricValue(snapshot.metrics.linkedChildren),kind:'metric'}];
 if(!nav.query)return rows;const q=nav.query.toLocaleLowerCase();return rows.filter(row=>{const c=snapshot.conversations.find(c=>c.id===row.id),p=snapshot.projects.find(p=>p.id===row.id),phrase=snapshot.phrases?.find(p=>p.id===row.id);return [row.label,c?.title,p?.displayName,phrase?.text].some(text=>text?.toLocaleLowerCase().includes(q));});
}

export function compactAuditWork(work:readonly AuditWorkBar[],limit=4):AuditWorkBar[]{if(work.length<=limit)return [...work];const shown=work.slice(0,Math.max(1,limit-1)),rest=work.slice(shown.length);if(!rest.every(r=>r.denominator===rest[0]!.denominator))return work.slice(0,limit).map((bar,i)=>i===limit-1?{...bar,label:`${work.length-limit+1} more labels · open`}:bar);return [...shown,{label:'other labels',count:rest.reduce((sum,bar)=>sum+bar.count,0),denominator:rest[0]!.denominator,state:rest.some(r=>r.state==='partial')?'partial':'observed'}];}
function calendarDay(date:string):number|null {if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return null;const at=Date.parse(`${date}T00:00:00Z`);return Number.isFinite(at)&&new Date(at).toISOString().slice(0,10)===date?Math.floor(at/86400000):null;}
export function auditActivityRange(activity:AuditSnapshot['activity']):{from:string|null;to:string|null;days:number}{let first=Infinity,last=-Infinity;for(const bucket of activity){const day=calendarDay(bucket.date);if(day!==null){first=Math.min(first,day);last=Math.max(last,day);}}return Number.isFinite(first)?{from:new Date(first*86400000).toISOString().slice(0,10),to:new Date(last*86400000).toISOString().slice(0,10),days:last-first+1}:{from:null,to:null,days:0};}
/** Empty calendar days stay in the timeline; storage is bounded by screen width. */
export function auditSparkline(activity:AuditSnapshot['activity'],width:number,ascii=false):string {const range=auditActivityRange(activity);if(!range.days||width<1)return '';const first=calendarDay(range.from!)!,bins=Math.min(Math.floor(width),range.days),values=Array.from({length:bins},()=>0);for(const bucket of activity){const day=calendarDay(bucket.date);if(day!==null&&Number.isFinite(bucket.count)&&bucket.count>=0)values[Math.min(bins-1,Math.floor((day-first)*bins/range.days))]!+=bucket.count;}const max=Math.max(...values,1),glyphs=ascii?'._-=+*#@':'▁▂▃▄▅▆▇█';return values.map(value=>value===0?' ':glyphs[Math.min(7,Math.floor(value/max*7))]!).join('');}
function wrap(text:string,width:number,widthOf:(text:string)=>number):string[]{const out:string[]=[];for(const original of clean(text).split('\n')){let row='';for(const g of graphemes(original)){if(widthOf(row+g)>width){out.push(row);row=g;}else row+=g;}out.push(row);}return out;}
function definition(snapshot:AuditSnapshot,nav:AuditNavigation):string {if(nav.section==='home'){const key=nav.selectedId as keyof AuditSnapshot['metrics']|null;return key&&snapshot.metrics[key]?snapshot.metrics[key].definition:'Human prompts are recorded eligible input events. Unknown origin remains unknown; this is not completed work.';}const defs:Record<AuditSection,string>={home:'Recorded facts in this snapshot.',work:'Request intent describes what was asked for, not completed work. Unclassified and uncertain prompts retain their own denominator.',projects:'Prompt counts attributed to known projects. Other combines the remaining displayed project rows.',activity:'Recorded human prompts by event date in the declared timezone. Unknown event clocks are outside this graph.',conversations:'Top-level conversations and declared child links retain harness-native identity. Enter reads recorded prompts.',usage:'Original host token and cost fields are reported only when captured. Missing usage is unavailable, never zero.',words:'A source phrase counts containing prompts separately from total occurrences. Enter follows its recorded conversation routes.',sources:'Source capability records format, human-origin and evidence fidelity. A discovered source is not proof of complete capture.'};return defs[nav.section];}

/** One bounded cell plan feeds Ink, plain fallback and safe SVG. No source counting. */
export function buildAuditScreen(snapshot:AuditSnapshot,nav:AuditNavigation=createAuditNavigation(),options:AuditScreenOptions={}):AuditLine[]{
 const columns=Math.max(12,Math.min(180,Math.floor(options.columns??options.width??80))),height=Math.max(4,Math.min(60,Math.floor(options.rows??24))),w=columns-4,widthOf=options.widthOf??auditCellWidth,ascii=Boolean(options.ascii),privateView=Boolean(options.private)&&!nav.screenshot,active=BUSY_STATES.has(snapshot.status),rows=auditRows(snapshot,nav,options.promptPage??null,privateView||(!nav.screenshot&&nav.view!=='section'));
 const lines:AuditSegment[][]=Array.from({length:height},()=>[]);const put=(y:number,text:string,tone:AuditTone='normal')=>{if(y>=0&&y<height)lines[y]=[{text:'  ',tone:'normal'},{text:auditClip(text,w,widthOf),tone}];};
 const pair=(y:number,left:string,right:string,leftTone:AuditTone='normal',rightTone:AuditTone='blue')=>{if(y>=0&&y<height){const half=Math.floor(w*.53);lines[y]=[{text:'  ',tone:'normal'},{text:pad(left,half,widthOf),tone:leftTone},{text:auditClip(right,w-half,widthOf),tone:rightTone}];}};
 const title=nav.view==='section'?nav.section==='home'?'':` / ${LABELS[nav.section]}`:nav.view==='conversations'?' / conversations':nav.view==='prompts'?' / prompts':nav.view==='evidence'?' / exact evidence':nav.view==='receipt'?' / read receipt':' / source';
 put(0,`potsherd / audit${title}${nav.screenshot?' · screenshot':''}`,'amber');put(1,`${safeScope(snapshot)} · ${snapshot.coverage.state==='complete_snapshot'?'captured':snapshot.coverage.state}${nav.query?' · list filtered':''}`,'dim');
 const footer=height-2,summary=height-4,mainEnd=summary-1,selected=rows.find(row=>row.id===nav.selectedId)??rows[Math.min(nav.selectedIndex,Math.max(0,rows.length-1))];
 put(footer,columns<60?'jk/↑↓ enter esc / f ? S q':'↑↓/jk  enter open  esc back  / find  f scope  ?  S freeze  C preview  q quit','cyan');put(footer+1,columns<60?'1-8 sections · C preview':'1 home 2 work 3 projects 4 activity 5 threads 6 usage 7 words 8 sources','dim');
 const coverage=`${snapshot.coverage.unknownOriginEvents?`${n(snapshot.coverage.unknownOriginEvents)} origin unknown · `:''}${snapshot.coverage.gapCodes.length?friendlyGap(snapshot.coverage.gapCodes[0]!):'local facts'}${snapshot.usage.state==='unavailable'?' · usage n/a':''}${snapshot.semantics.state==='not_run'||snapshot.semantics.state==='no_key'?' · semantics not run':''}`;
 put(summary+1,options.notice??(options.busy?'Reading source…':coverage),'dim');
 const list=(start:number,heading:string)=>{put(start,heading,'dim');const visible=Math.max(1,mainEnd-start-1),scroll=Math.min(nav.scroll,Math.max(0,rows.length-visible));rows.slice(scroll,scroll+visible).forEach((row,i)=>put(start+1+i,`${row.id===selected?.id?ascii?'> ':'▎ ':'  '}${pad(row.label,Math.max(8,w-24),widthOf)} ${row.value}`,row.id===selected?.id?'cyan':'normal'));if(!rows.length)put(start+2,options.busy?'Reading…':nav.query?'No matching rows.':'Nothing measured in this section.','amber');if(rows.length>visible)put(summary,`${scroll+1}–${Math.min(rows.length,scroll+visible)} / ${rows.length} · scroll to browse`,'dim');};
 if(nav.editing==='search'){put(4,nav.screenshot?'SEARCH · text hidden':`SEARCH / ${nav.query}_`,'cyan');put(6,'Searches this list; snapshot totals stay fixed.','dim');put(8,'enter apply · esc cancel','dim');}
 else if(nav.editing==='scope'){
  const draft=options.scopeDraft??snapshot.scope,fields=[`Period   ${draft.eventFrom?.slice(0,10)??'all dates'} → ${draft.asOf?.slice(0,10)??'now'}`,`Project  ${draft.project?auditProjectAlias(snapshot,snapshot.projects.find(p=>p.path===draft.project)?.id??null):'all projects'}`,`Sources  ${draft.harnesses.map(h=>HARNESS_NAMES[h]).join(' + ')}`,`Timezone ${draft.timezone}`,options.onScopeRequest?'Apply fresh scan':'Fresh scan required'];put(4,'SCOPE · a fresh snapshot on Apply','amber');fields.forEach((text,i)=>put(6+i,`${i===(options.scopeField??0)?ascii?'> ':'▎ ':'  '}${text}`,i===(options.scopeField??0)?'cyan':'normal'));put(summary,'←→ presets · enter apply · esc cancel','dim');
 }else if(nav.editing==='semantic'){put(4,'OPTIONAL SEMANTICS','amber');put(6,`State: ${snapshot.semantics.state.replaceAll('_',' ')} · ${n(snapshot.semantics.eligiblePrompts)} eligible prompts`);put(8,'No content sent from this preview.','green');put(10,'Local facts and exact source reads remain available.','dim');put(summary,'Provider preview/consent required · esc back','dim');}
 else if(nav.help){put(4,selected?.label.toUpperCase()??LABELS[nav.section].toUpperCase(),'amber');wrap(nav.screenshot?'Recorded snapshot units, scope and coverage remain visible. Source identities and quoted text are hidden.':definition(snapshot,nav),w,widthOf).slice(0,mainEnd-6).forEach((line,i)=>put(6+i,line));put(summary,'esc closes · focus stays on the same row','dim');}
 else if(nav.view==='receipt'){
  put(4,'EXACT READ ROUTE · source-owned receipt','dim');if(nav.screenshot)put(7,'Read identity hidden · public screenshot view','amber');else if(options.evidence)wrap(JSON.stringify(options.evidence.route,null,2),w,widthOf).slice(nav.scroll,nav.scroll+Math.max(1,mainEnd-6)).forEach((line,i)=>put(6+i,line));else put(7,'Read receipt unavailable','amber');put(summary,'jk scroll · esc returns to exact evidence','dim');
 }else if(nav.view==='evidence'){
  const evidence=options.evidence,prompt=options.promptPage?.prompts.find(p=>p.id===nav.selectedId),role=evidence?.role==='user'?prompt?.eligibleHuman?'HUMAN':'USER RECORD · origin not established':'SOURCE';put(4,`${role} · ${evidence?.eventAt?.slice(0,16)??'date unknown'} · ${evidence?.route.basis??'exact read'}`,'dim');
  if(nav.screenshot)put(7,'Source text hidden · public screenshot view','amber');else if(options.busy)put(7,'Reading exact source…','cyan');else if(evidence?.state==='stale')put(7,'Source changed · exact read is stale','amber');else if(evidence?.state!=='available')put(7,'Exact source unavailable · coverage retained','amber');else wrap(evidence.text??'',w,widthOf).slice(nav.scroll,nav.scroll+Math.max(1,mainEnd-6)).forEach((line,i)=>put(6+i,line));
  put(summary,nav.screenshot?'No paths, names, refs or excerpts in this view':evidence?.state==='available'?clean(evidence.text??'')!==evidence.text?'Exact read · terminal controls hidden · r receipt':'Exact redacted source · r read receipt · jk scroll':'Esc returns to the selected prompt','dim');
 }else if(nav.view==='source'){
  const source=snapshot.sources.find(s=>s.harness===nav.sourceHarness);put(4,HARNESS_NAMES[nav.sourceHarness??'']??'SOURCE','amber');if(source){[`State         ${source.state}`,`Conversations ${n(source.conversations)}`,`Human prompts ${n(source.humanPrompts)}`,`Origin        ${source.humanOrigin}`,`Evidence      ${source.evidence}`,`Usage         ${source.usage}`,`First gap     ${source.gapCodes.length?friendlyGap(source.gapCodes[0]!):'none recorded'}`].forEach((text,i)=>put(6+i,text,i===6?'amber':'normal'));if(!nav.screenshot&&source.firstUnsupportedStep)put(summary,source.firstUnsupportedStep,'dim');}
 }else if(nav.view==='conversations'||nav.view==='prompts'){
  const project=snapshot.projects.find(p=>p.id===nav.projectId);list(4,nav.view==='prompts'?`RECORDED PROMPTS · ${options.promptPage?.coverage.state??snapshot.coverage.state}`:`${project?auditProjectAlias(snapshot,project.id):nav.category?workLabel(nav.category).toUpperCase():'RECORDED'} CONVERSATIONS`);if(project&&!nav.screenshot)put(summary,`${single(project.displayName)}${project.path?` · ${single(project.path)}`:''}`,'amber');if(nav.view==='prompts'&&options.promptPage&&options.promptPage.nextOffset!==null)put(summary,'n next page · p previous · enter exact source','dim');
 }else if(nav.section==='home'&&active){
  const progress=snapshot.progress,phase=options.frame??0;put(4,'LOCAL SOURCES → NORMALIZE → FACTS','dim');
  const gem:AuditLine[]=[[{text:'  ▄  ',tone:'amberDim'}],[{text:' ▄',tone:'amberDim'},{text:'█',tone:'amberLight'},{text:'▄ ',tone:'amber'}],[{text:'▄',tone:'amberDim'},{text:'█',tone:'amber'},{text:'█',tone:'amberLight'},{text:'█',tone:'amber'},{text:'▄',tone:'amberDim'}],[{text:' ▀',tone:'amber'},{text:'█',tone:'amberLight'},{text:'▀ ',tone:'amberDim'}],[{text:'  ▀  ',tone:'amberDim'}]];
  const pending=snapshot.progress.stage==='discovering'&&snapshot.coverage.knownSources===0;
  if(columns>=60){
   lines[5]=[{text:'  ',tone:'normal'},{text:pad('CANDIDATE FILES',26,widthOf),tone:'dim'},...gem[0]!];
   const joins=['╮','┤','┤','╯'],fans=['╭─','├─','├─','╰─'],facts=['conversations','human prompts','projects','dated activity'];
   Array.from({length:4},(_,i)=>snapshot.sources[i]).forEach((source,i)=>{const lane=Array.from({length:4},(_,j)=>j===phase%4?'━':'─').join('');lines[6+i]=[{text:'  ',tone:'normal'},{text:pad(source?HARNESS_NAMES[source.harness]??'Source':'',10,widthOf),tone:source?HARNESS_TONES[source.harness]??'dim':'dim'},{text:pad(source?pending?'checking':n(source.candidateFiles):'',9,widthOf),tone:source?HARNESS_TONES[source.harness]??'dim':'dim'},{text:source?lane:'    ',tone:source?HARNESS_TONES[source.harness]??'dim':'dim'},{text:source?joins[i]!:' ',tone:'dim'},{text:i===1?'──▶':'   ',tone:'dim'},...gem[i+1]!,{text:i===1?'──▶':'   ',tone:'amber'},{text:fans[i]!,tone:'cyan'},{text:facts[i]!,tone:'cyan'}];});
  }else{put(4,'CANDIDATE FILES','dim');snapshot.sources.slice(0,4).forEach((source,i)=>put(5+i,`${pad(HARNESS_NAMES[source.harness]??'Source',10,widthOf)} ${pending?'checking':n(source.candidateFiles)}`,HARNESS_TONES[source.harness]));put(9,'    │','dim');gem.forEach((line,i)=>{if(10+i<summary)lines[10+i]=[{text:'    ',tone:'normal'},...line];});if(height>=20)put(15,'    ↓ measured facts','cyan');}
  put(summary,`${progress.stage} · ${n(progress.completed)}${progress.total===null?' / total unknown':` / ${n(progress.total)}`} ${progress.unit.replaceAll('_',' ')}`,'amber');put(summary+1,'Counts provisional · q cancels · browse with 1–8','dim');
 }else if(nav.section==='home'){
  const m=snapshot.metrics;put(4,columns<60?`${metricValue(m.conversations,ascii)} conversations · ${metricValue(m.humanPrompts,ascii)} prompts`:`${metricValue(m.conversations,ascii)} conversations   ${metricValue(m.humanPrompts,ascii)} human prompts   ${metricValue(m.projects,ascii)} projects   ${metricValue(m.linkedChildren,ascii)} linked children`);if(columns<60)put(5,`${metricValue(m.projects,ascii)} projects · ${metricValue(m.linkedChildren,ascii)} linked children`);
  const classified=snapshot.semantics.qualified&&snapshot.semantics.work.length>0,work=compactAuditWork(snapshot.semantics.work,columns<60?3:4),left=classified?work.map(bar=>({label:workLabel(bar.label),value:bar.count})):snapshot.sources.map(s=>({label:HARNESS_NAMES[s.harness]??'Source',value:s.humanPrompts}));
  const projectRows=snapshot.projects.slice(0,3).map(p=>({label:auditProjectAlias(snapshot,p.id),value:p.humanPrompts}));if(snapshot.projects.length>3)projectRows.push({label:'other',value:snapshot.projects.slice(3).reduce((sum,p)=>sum+p.humanPrompts,0)});const leftMax=Math.max(1,...left.map(row=>row.value??0)),projectMax=Math.max(1,...projectRows.map(row=>row.value));const bars=(value:number|null,max:number,size:number)=>value===null?ascii?'?':'—':(ascii?'#':'█').repeat(Math.max(0,Math.round(value/max*size)));
  if(columns>=60){pair(7,classified?'WHAT YOU ASKED FOR':'RECORDED HUMAN PROMPTS','PROJECTS · PROMPTS','dim','dim');for(let i=0;i<4;i++){const l=left[i],r=projectRows[i];pair(8+i,l?`${pad(l.label,14,widthOf)} ${pad(n(l.value,ascii),6,widthOf)} ${bars(l.value,leftMax,Math.max(4,Math.floor(w*.15)))}`:'',r?`${pad(r.label,10,widthOf)} ${pad(n(r.value),6,widthOf)} ${bars(r.value,projectMax,Math.max(4,Math.floor(w*.12)))}`:'',i===0?'cyan':'normal',i===0?'cyan':'blue');}const range=auditActivityRange(snapshot.activity);put(13,range.days?`DAILY HUMAN PROMPTS · ${range.from} → ${range.to} · ${snapshot.scope.timezone}`:'DAILY HUMAN PROMPTS · dates unavailable','dim');put(14,auditSparkline(snapshot.activity,w,ascii)||'No dated human prompts.','cyan');}
  else{put(7,classified?'REQUEST INTENT':'RECORDED HUMAN PROMPTS','dim');const compactLeft=left.length<=3?left:[...left.slice(0,2),{label:'other sources',value:left.slice(2).every(r=>r.value!==null)?left.slice(2).reduce((sum,r)=>sum+(r.value??0),0):null}];compactLeft.forEach((row,i)=>put(8+i,`${pad(row.label,11,widthOf)} ${pad(n(row.value,ascii),6,widthOf)} ${bars(row.value,leftMax,8)}`,i===0?'cyan':'normal'));put(12,'PROJECTS · HUMAN PROMPTS','dim');put(13,snapshot.projects.length?`${auditProjectAlias(snapshot,snapshot.projects[0]!.id)} ${n(snapshot.projects[0]!.humanPrompts)} · other ${n(snapshot.projects.slice(1).reduce((sum,p)=>sum+p.humanPrompts,0))}`:'No known projects','blue');const range=auditActivityRange(snapshot.activity);put(14,range.days?`DAILY · ${range.from?.slice(5)}→${range.to?.slice(5)} ${snapshot.scope.timezone}`:'DAILY · dates unavailable','dim');put(15,auditSparkline(snapshot.activity,w,ascii)||'No dated prompts.','cyan');}
  snapshot.insights.slice(0,columns>=100?2:1).forEach((_,i)=>put(summary-i,safeFinding(snapshot,i),'amber'));if(snapshot.status==='cancelled')put(summary,'Scan cancelled · completed facts retained','amber');else if(snapshot.status==='error')put(summary,'Scan interrupted · completed facts retained','amber');else if(m.conversations.value===0)put(summary,'No conversations measured · 8 source coverage','amber');
 }else if(nav.section==='work'&&(!snapshot.semantics.qualified||!snapshot.semantics.work.length)){const ran=!['not_run','no_key'].includes(snapshot.semantics.state);put(4,ran?'REQUEST INTENT · EXPERIMENTAL':'REQUEST INTENT · NOT RUN','dim');put(7,ran?`${snapshot.semantics.state} · judgments not qualified`:snapshot.semantics.state==='no_key'?'No key · no semantic labels':'Local facts ready · semantic labels not run','amber');put(9,ran?`${n(snapshot.semantics.classifiedPrompts)} recorded judgments · prominence withheld`:'C opens preview · no content sent automatically','dim');}
 else if(nav.section==='activity'){const range=auditActivityRange(snapshot.activity);put(4,`DAILY HUMAN PROMPTS · ${range.days} calendar dates`,'dim');put(5,range.days?`${range.from} → ${range.to} · ${snapshot.scope.timezone} · recorded window`:'Event dates unavailable','dim');put(6,auditSparkline(snapshot.activity,w,ascii)||'No dated human prompts.','cyan');list(8,'RECORDED DATES');}
 else if(nav.section==='usage'&&snapshot.usage.state==='unavailable'){put(4,'ORIGINAL HOST USAGE','dim');put(7,'Tokens          unavailable');put(9,'Cost            unavailable');put(11,'Usage fields were not captured.','amber');put(summary,'8 source capabilities · ? definition','dim');}
 else {list(4,nav.section==='words'?'SOURCE PHRASES · CONTAINING PROMPTS':nav.section==='work'?`REQUEST INTENT · ${n(snapshot.semantics.classifiedPrompts)} classified prompts`:LABELS[nav.section].toUpperCase());}
 if(nav.screenshot)put(summary+1,`Frozen · ${snapshot.coverage.state==='complete_snapshot'?'captured':snapshot.coverage.state}${snapshot.coverage.unknownOriginEvents?` · ${n(snapshot.coverage.unknownOriginEvents)} origin unknown`:' · public aliases'}`,'green');
 if(columns<38||height<18){for(let i=2;i<height-2;i++)lines[i]=[];put(3,'Resize to browse · q exits','amber');if(height>7)put(5,`${metricValue(snapshot.metrics.conversations,ascii)} conversations · ${metricValue(snapshot.metrics.humanPrompts,ascii)} prompts`);}
 put(footer,columns<60?'jk/↑↓ enter esc / f ? S q':'↑↓/jk  enter open  esc back  / find  f scope  ?  S freeze  C preview  q quit','cyan');put(footer+1,columns<60?'1-8 sections · C preview':'1 home 2 work 3 projects 4 activity 5 threads 6 usage 7 words 8 sources','dim');
 if(ascii){const replacements:Record<string,string>={'→':'->','↑':'^','↓':'v','←':'<','↵':'enter','·':'|','—':'?','–':'-','…':'...','▎':'>','─':'-','━':'-','▄':'#','█':'#','▀':'#','×':'x','▶':'>','╮':'+','┤':'+','╯':'+','╭':'+','├':'+','╰':'+','│':'|'};return lines.map(line=>{let remaining=columns;return line.map(segment=>{const text=(nav.view==='evidence'||nav.view==='receipt')&&!nav.screenshot&&segment.tone==='normal'?segment.text:segment.text.replace(/[→↑↓←↵·—–…▎─━▄█▀×▶╮┤╯╭├╰│]/g,char=>replacements[char]!);const clipped=auditClip(text,remaining,widthOf);remaining-=widthOf(clipped);return {...segment,text:clipped};});});}return lines;
}

export function renderAuditPlain(snapshot:AuditSnapshot,options:AuditTerminalOptions={}):string{return buildAuditScreen(snapshot,createAuditNavigation(),{...options,private:false,columns:options.width??80,rows:24}).map(line=>line.map(segment=>segment.text).join('').trimEnd()).join('\n').trimEnd()+'\n';}
export function renderAuditShareSvg(snapshot:AuditSnapshot,options:{width?:number;ascii?:boolean}={}):string{const width=Math.max(40,Math.min(160,options.width??80)),nav={...createAuditNavigation(),screenshot:true},lines=buildAuditScreen(snapshot,nav,{columns:width,rows:24,ascii:options.ascii,private:false});const escape=(text:string)=>text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');let text='';lines.forEach((line,y)=>{let x=0;for(const segment of line){text+=`<text x="${16+x*10}" y="${28+y*20}" fill="${PALETTE[segment.tone]}">${escape(segment.text)}</text>`;x+=auditCellWidth(segment.text);}});const description=`Sources: ${snapshot.scope.harnesses.map(h=>HARNESS_NAMES[h]).join(', ')}. ${safeScope(snapshot)}. Coverage: ${snapshot.coverage.state}. Units: recorded conversations, eligible human prompts, known projects, supported linked children. Calendar graph uses recorded dates in ${snapshot.scope.timezone}.`;return `<svg xmlns="http://www.w3.org/2000/svg" width="${width*10+32}" height="512" viewBox="0 0 ${width*10+32} 512"><desc>${escape(description)}</desc><rect width="100%" height="100%" rx="12" fill="#0b1013"/><g font-family="ui-monospace, monospace" font-size="16" xml:space="preserve">${text}</g></svg>\n`;}

/** Dependencies initialize only after the interactive entry is invoked. */
export async function runAuditTerminal(session:AuditSession,options:AuditTerminalOptions={}):Promise<AuditTerminalResult>{
 if(!process.stdin.isTTY||!process.stdout.isTTY)return {snapshot:await session.run(),reason:'complete'};
 const [{default:React,useState,useRef,useEffect},{render,Box,Text,useInput,useApp,useWindowSize,useAnimation},{default:stringWidth}]=await Promise.all([import('react'),import('ink'),import('string-width')]);
 let finalSnapshot=session.snapshot(),reason:AuditTerminalResult['reason']='quit',scanSettled=false;let scan:Promise<AuditSnapshot>|null=null;
 function App(){
  const [liveSnapshot,setSnapshot]=useState(finalSnapshot),[frozenSnapshot,setFrozenSnapshot]=useState<AuditSnapshot|null>(null),[nav,setNav]=useState<AuditNavigation>(createAuditNavigation()),[page,setPage]=useState<AuditPromptPage|null>(null),[evidence,setEvidence]=useState<AuditEvidence|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[scopeDraft,setScopeDraft]=useState<AuditScope>(liveSnapshot.scope),[scopeField,setScopeField]=useState(0);
  const snapshot=nav.screenshot&&frozenSnapshot?frozenSnapshot:liveSnapshot;
  const {columns,rows:terminalRows}=useWindowSize(),{exit}=useApp(),operation=useRef(0),readInFlight=useRef(false),mounted=useRef(true),pending=useRef<ReturnType<typeof setTimeout>|null>(null),searchBefore=useRef<AuditNavigation|null>(null);
  const active=BUSY_STATES.has(liveSnapshot.status),{frame}=useAnimation({interval:100,isActive:active&&nav.section==='home'&&nav.view==='section'&&options.motion!==false&&!nav.screenshot});
  const privateView=Boolean(options.private)&&!nav.screenshot||!nav.screenshot&&nav.view!=='section',items=auditRows(snapshot,nav,page,privateView),visible=Math.max(1,terminalRows-10);
  useEffect(()=>{mounted.current=true;const publish=(event:AuditEvent)=>{finalSnapshot=applyAuditEvent(finalSnapshot,event);if(event.type==='error'&&mounted.current)setNotice('A source could not be read · inspect coverage');if(pending.current===null)pending.current=setTimeout(()=>{pending.current=null;if(mounted.current)setSnapshot(finalSnapshot);},100);};scan=Promise.resolve().then(()=>session.run(publish)).then(value=>{finalSnapshot=value;scanSettled=true;if(pending.current!==null){clearTimeout(pending.current);pending.current=null;}if(mounted.current)setSnapshot(value);return value;},()=>{scanSettled=true;finalSnapshot={...finalSnapshot,status:'error',progress:{...finalSnapshot.progress,stage:'error',cancellable:false},coverage:{...finalSnapshot.coverage,state:finalSnapshot.coverage.parsedSources?'partial':'unavailable',gapCodes:[...finalSnapshot.coverage.gapCodes,'audit_run_failed']}};if(pending.current!==null){clearTimeout(pending.current);pending.current=null;}if(mounted.current){setSnapshot(finalSnapshot);setNotice('Local scan interrupted · retained coverage shown');}return finalSnapshot;});return()=>{mounted.current=false;operation.current++;if(pending.current!==null){clearTimeout(pending.current);pending.current=null;}};},[]);
  const stop=()=>{reason=active?'cancelled':'quit';if(active)session.cancel();exit();};
  const readPrompts=async(next:AuditNavigation,offset=0)=>{if(readInFlight.current){setNotice('Finishing previous source read…');return;}readInFlight.current=true;const token=++operation.current;setBusy(true);setNotice('');setEvidence(null);setPage(null);setNav(next);try{const result=await session.prompts(next.conversationId!,offset,20);if(mounted.current&&operation.current===token&&result.snapshotId===finalSnapshot.snapshotId&&result.conversationId===next.conversationId){setPage(result);setNav(current=>({...current,selectedId:result.prompts[0]?.id??null,selectedIndex:0,scroll:0}));}}catch{if(mounted.current&&operation.current===token)setNotice('Prompt page unavailable · esc returns');}finally{readInFlight.current=false;if(mounted.current&&operation.current===token)setBusy(false);}};
  const open=async()=>{if(readInFlight.current){setNotice('Finishing previous source read…');return;}const selected=items.find(row=>row.id===nav.selectedId)??items[Math.min(nav.selectedIndex,Math.max(0,items.length-1))]??items[0];if(!selected)return;
   if(selected.kind==='project')setNav(auditPush(nav,{view:'conversations',projectId:selected.id,conversationId:null}));
   else if(selected.kind==='conversation')await readPrompts(auditPush(nav,{view:'prompts',conversationId:selected.id}));
   else if(selected.kind==='work'){const bar=snapshot.semantics.work[Number(selected.id.split(':')[1])];if(bar)setNav(auditPush(nav,{view:'conversations',category:bar.label,projectId:null,conversationId:null}));}
   else if(selected.kind==='phrase')setNav(auditPush(nav,{view:'conversations',phraseId:selected.id}));
   else if(selected.kind==='source')setNav(auditPush(nav,{view:'source',sourceHarness:selected.id}));
   else if(selected.kind==='prompt'){const prompt=page?.prompts.find(p=>p.id===selected.id);if(!prompt)return;readInFlight.current=true;const token=++operation.current;setNav({...auditPush(nav,{view:'evidence'}),selectedId:prompt.id});setEvidence(null);setBusy(true);try{const value=await session.evidence(prompt.route);if(mounted.current&&operation.current===token)setEvidence(value);}catch{if(mounted.current&&operation.current===token)setNotice('Exact source unavailable · esc returns');}finally{readInFlight.current=false;if(mounted.current&&operation.current===token)setBusy(false);}}
   else setNav(current=>({...current,help:true}));
  };
  const scopePreset=(delta:number)=>{setScopeDraft(current=>{if(scopeField===0){const presets=[null,7,30,90],old=current.eventFrom?Math.round((Date.parse(snapshot.measuredAt)-Date.parse(current.eventFrom))/86400000):null,index=presets.findIndex(v=>v===old),days=presets[(Math.max(0,index)+delta+presets.length)%presets.length];return {...current,eventFrom:days?new Date(Date.parse(snapshot.measuredAt)-days*86400000).toISOString():null,asOf:null};}if(scopeField===1){const paths=[null,...snapshot.projects.map(p=>p.path).filter((p):p is string=>Boolean(p))],index=paths.indexOf(current.project);return {...current,project:paths[(Math.max(0,index)+delta+paths.length)%paths.length]??null};}if(scopeField===2){const sources:readonly AuditScope['harnesses'][]=[['claude','codex','pi','opencode'],...(['claude','codex','pi','opencode'] as const).map(h=>[h])],index=sources.findIndex(value=>JSON.stringify(value)===JSON.stringify(current.harnesses));return {...current,harnesses:sources[(Math.max(0,index)+delta+sources.length)%sources.length]!};}if(scopeField===3)return {...current,timezone:current.timezone==='UTC'?snapshot.scope.timezone==='UTC'?Intl.DateTimeFormat().resolvedOptions().timeZone:snapshot.scope.timezone:'UTC'};return current;});};
  useInput((input,key)=>{
   if(key.ctrl&&input==='c'){stop();return;}if(input==='S'){setFrozenSnapshot(nav.screenshot?null:liveSnapshot);setNav(current=>({...current,screenshot:!current.screenshot}));return;}
   if(nav.editing==='search'){if(key.escape){setNav(searchBefore.current??{...nav,editing:null});return;}if(key.return){setNav(current=>reconcileAuditNavigation({...current,editing:null},auditRows(snapshot,{...current,editing:null},page,privateView),visible));return;}if(key.backspace||key.delete)setNav(current=>({...current,query:graphemes(current.query).slice(0,-1).join('')}));else if(!key.ctrl&&!key.meta&&input)setNav(current=>({...current,query:(current.query+single(input)).slice(0,200)}));return;}
   if(nav.editing==='scope'){if(key.escape){setNav(current=>({...current,editing:null}));return;}if(key.upArrow||input==='k')setScopeField(i=>Math.max(0,i-1));else if(key.downArrow||input==='j')setScopeField(i=>Math.min(4,i+1));else if(key.leftArrow)scopePreset(-1);else if(key.rightArrow)scopePreset(1);else if(key.return){if(scopeField<4){scopePreset(1);return;}if(options.onScopeRequest){options.onScopeRequest(scopeDraft);reason='cancelled';session.cancel();exit();}else{setNotice('Fresh scan required · quit, then audit --overview --project / --harness / --since');setNav(current=>({...current,editing:null}));}}return;}
   if(key.escape){operation.current++;setBusy(false);setNotice('');setNav(auditBack(nav));return;}if(nav.help||nav.editing==='semantic'){return;}
   if(input==='q'){stop();return;}if(/^[1-8]$/.test(input)){operation.current++;setBusy(false);setNav(auditSelectSection(nav,SECTIONS[Number(input)-1]!));return;}
   if(input==='/'){searchBefore.current=nav;setNav(current=>({...current,editing:'search',query:''}));return;}if(input==='f'){setScopeDraft(snapshot.scope);setScopeField(0);setNav(current=>({...current,editing:'scope'}));return;}if(input==='?'){setNav(current=>({...current,help:true}));return;}if(input==='C'||input==='c'){setNav(current=>({...current,editing:'semantic'}));return;}
   if(nav.view==='prompts'&&(input==='n'||input==='p')){const offset=input==='n'?page?.nextOffset:Math.max(0,(page?.offset??0)-20);if(offset!==null&&offset!==undefined)void readPrompts({...nav,selectedId:null,scroll:0,selectedIndex:0},offset);return;}
   if(nav.view==='evidence'&&input==='r'){setNav(auditPush(nav,{view:'receipt'}));return;}
   if(key.downArrow||input==='j'){if(nav.view==='evidence'||nav.view==='receipt')setNav(current=>({...current,scroll:current.scroll+1}));else setNav(auditMove(nav,items,1,visible));return;}if(key.upArrow||input==='k'){if(nav.view==='evidence'||nav.view==='receipt')setNav(current=>({...current,scroll:Math.max(0,current.scroll-1)}));else setNav(auditMove(nav,items,-1,visible));return;}if(key.return)void open();
  });
  const screen=buildAuditScreen(snapshot,nav,{...options,columns:Math.min(columns,options.width??columns),rows:terminalRows,widthOf:stringWidth,frame,promptPage:page,evidence,busy,notice:notice||undefined,scopeDraft,scopeField});
  return React.createElement(Box,{flexDirection:'column',width:Math.min(columns,options.width??columns),height:terminalRows},...screen.map((line,index)=>React.createElement(Box,{key:index,height:1,flexShrink:0,width:'100%'},React.createElement(Text,{wrap:'truncate'},...line.map((segment,i)=>React.createElement(Text,{key:i,color:options.color===false?undefined:PALETTE[segment.tone]},segment.text))))));
 }
 // Ink preserves the inherited cursor when entering its alternate buffer.
 // Anchor that buffer once, including after Node/dependency startup warnings.
 // All drawing, raw-mode management and alternate-screen cleanup remain Ink's.
 const originalWrite=process.stdout.write;
 process.stdout.write=(function(...args:Parameters<typeof originalWrite>):boolean{if(typeof args[0]==='string'&&args[0].includes('\x1b[?1049h'))args[0]=args[0].replace('\x1b[?1049h','\x1b[?1049h\x1b[H');return originalWrite.apply(process.stdout,args);}) as typeof originalWrite;
 let app:ReturnType<typeof render>;
 try{app=render(React.createElement(App),{alternateScreen:true,incrementalRendering:true,maxFps:12,exitOnCtrlC:false,patchConsole:false});}finally{process.stdout.write=originalWrite;}
 try{await app.waitUntilExit();if(!scanSettled)session.cancel();if(scan)finalSnapshot=await scan;return {snapshot:finalSnapshot,reason};}finally{if(!scanSettled)session.cancel();app.unmount();await app.waitUntilRenderFlush();}
}
