import type {AuditEvidence,AuditEvidenceRoute,AuditSnapshot,AuditEvent,AuditMetric,AuditWordTerm} from '../../../core/src/analytics/contracts.js';
import type {ModelAggregate} from '../../../core/src/analytics/launch-contracts.js';
import type {AuditLine,AuditTone,AuditTerminalOptions} from './index.js';
import {auditCellWidth,auditClip} from './index.js';
import {launchAnalysisStatus,launchGaps,launchIsLoading} from './report-status.js';
export interface ReportOptions extends AuditTerminalOptions {columns?:number;rows?:number;widthOf?:(text:string)=>number;frame?:number;transfer?:Extract<AuditEvent,{type:'transfer'}>|null;evidence?:AuditEvidence|null;busy?:boolean;notice?:string;}
export interface ReportAnchor {row:number;label:string;route?:AuditEvidenceRoute;conversationId?:string;promptIds?:readonly string[];}
export interface ReportDocument {lines:AuditLine[];anchors:ReportAnchor[];}
const nf=new Intl.NumberFormat('en-US',{maximumFractionDigits:1}),cf=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
export const reportNumber=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'unknown':nf.format(value);
const dollars=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'unpriced':cf.format(value);
const equivalent=(value:{valueUsd:number|null;referenceValueUsd:number|null})=>value.valueUsd===null&&value.referenceValueUsd===null?null:(value.valueUsd??0)+(value.referenceValueUsd??0);
const metric=(value:AuditMetric|undefined)=>!value||['unavailable','not_run'].includes(value.state)?null:value.value;
const modelDisplayNameForHelp=(model:ModelAggregate)=>model.canonicalModel??model.model??'Unidentified model';
const name=(model:ModelAggregate)=>model.canonicalModel??model.model??'Unidentified model';
const stageNames={discovering:'Checking local history',sizing:'Measuring recorded usage',preparing:'Preparing selected work',analyzing:'Reading work insights',assembling:'Building your report',ready:'Report ready'};
const sourceNames:Record<string,string>={claude:'Claude Code',codex:'Codex',pi:'pi',opencode:'OpenCode'};
const sourceTones:Record<string,AuditTone>={claude:'normal',codex:'normal',pi:'normal',opencode:'normal'};
const segments=new Intl.Segmenter('en',{granularity:'grapheme'});
export function cleanReportText(text:string):string{return text.replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g,'').replace(/\x1b\[[0-?]*[ -/]*[@-~]/g,'').replace(/[\x00-\x08\x0b-\x1f\x7f-\x9f]/g,'').replace(/[\r\t]/g,' ');}
function glyphs(text:string,ascii:boolean):string{return ascii?text.replaceAll('·','|').replaceAll('━','#').replaceAll('─','-').replaceAll('“','"').replaceAll('”','"').replaceAll('×','x').replaceAll('→','>').replaceAll('–','-').replaceAll('↑','^').replaceAll('↓','v'):text;}
export function reportWrap(text:string,width:number,widthOf:(text:string)=>number=auditCellWidth):string[]{const rows:string[]=[];for(const paragraph of cleanReportText(text).split('\n')){let rest=paragraph;if(!rest){rows.push('');continue;}while(widthOf(rest)>width){const clipped=auditClip(rest,width,widthOf);if(!clipped)break;const split=clipped.lastIndexOf(' '),useWordBoundary=split>Math.floor(clipped.length*.55);const part=useWordBoundary?clipped.slice(0,split):clipped;rows.push(part);rest=rest.slice(part.length+(useWordBoundary?1:0));}rows.push(rest);}return rows;}

function builder(width:number,options:ReportOptions):ReportDocument&{add:(text:string,tone?:AuditTone)=>void;blank:()=>void;anchor:(value:Omit<ReportAnchor,'row'>)=>void}{const doc:ReportDocument={lines:[],anchors:[]},widthOf=options.widthOf??auditCellWidth;return {...doc,add:(text,tone='normal')=>{for(const row of reportWrap(glyphs(text,Boolean(options.ascii)),width,widthOf))doc.lines.push([{text:row,tone}]);},blank:()=>doc.lines.push([{text:'',tone:'normal'}]),anchor:value=>doc.anchors.push({...value,row:Math.max(0,doc.lines.length-1)})};}
function bar(value:number|null,width:number,ascii=false):string{if(value===null||!Number.isFinite(value))return '';const fill=Math.min(width,Math.max(0,Math.round(value*width)));return (ascii?'#':'━').repeat(fill)+(ascii?'.':'─').repeat(width-fill);}
function spark(values:readonly number[],width:number,ascii=false):string{const length=Math.min(width,values.length);if(!length)return '';const valuesByCell=Array.from({length},(_,i)=>values.slice(Math.floor(i*values.length/length),Math.floor((i+1)*values.length/length)).reduce((sum,value)=>sum+value,0)),max=Math.max(...valuesByCell,1),chars=ascii?' .:-=+*#':' ▁▂▃▄▅▆▇█';return valuesByCell.map(value=>chars[Math.round(value/max*(chars.length-1))]).join('');}
function append(doc:ReportDocument,block:ReportDocument):void{const offset=doc.lines.length;doc.lines.push(...block.lines);doc.anchors.push(...block.anchors.map(anchor=>({...anchor,row:anchor.row+offset})));}
function pair(doc:ReportDocument,left:ReportDocument,right:ReportDocument,width:number,options:ReportOptions):void{if(!left.lines.length){append(doc,right);return;}if(!right.lines.length){append(doc,left);return;}const column=Math.floor((width-4)/2),widthOf=options.widthOf??auditCellWidth,offset=doc.lines.length;for(let i=0;i<Math.max(left.lines.length,right.lines.length);i++){const l=left.lines[i]??[],r=right.lines[i]??[],used=l.reduce((sum,s)=>sum+widthOf(s.text),0);doc.lines.push([...l,{text:' '.repeat(Math.max(0,column-used)+4),tone:'normal'},...r]);}doc.anchors.push(...left.anchors.map(a=>({...a,row:a.row+offset})),...right.anchors.map(a=>({...a,row:a.row+offset})));}
function shortScope(snapshot:AuditSnapshot):string {if(snapshot.scope.eventFrom)return `${snapshot.scope.eventFrom.slice(0,10)} to ${(snapshot.scope.asOf??snapshot.measuredAt).slice(0,10)}`;return 'All recorded history';}
function knownTokens(snapshot:AuditSnapshot):number|null {const facts=snapshot.launch?.facts;if(!facts||facts.knownTokenResponses===0)return null;const values=facts.models.map(model=>model.knownTokens??model.totalTokens).filter((value):value is number=>value!==null&&value!==undefined);return values.length?values.reduce((sum,value)=>sum+value,0):null;}
function modelsBlock(snapshot:AuditSnapshot,width:number,options:ReportOptions):ReportDocument{const b=builder(width,options),facts=snapshot.launch?.facts;if(!facts?.models.length)return b;b.add('MODELS','amber');if(facts.favourite)b.add(`Favourite  ${name(facts.favourite)}`,'cyan');const max=Math.max(...facts.models.map(model=>model.knownTokens??model.totalTokens??0),1);for(const model of facts.models){const known=model.knownTokens??model.totalTokens,total=known===0&&model.totalTokens===null?null:known,visual=bar(total===null?null:(total??0)/max,width<45?9:14,options.ascii),tail=`${visual}  ${reportNumber(total)}${model.totalTokens===null?' known':''} tokens  ${dollars(equivalent(model))}`;if(width<45){b.add(name(model));b.add(tail,model.id===facts.favourite?.id?'amber':'violet');}else{b.add(name(model));b.add('  '+tail,model.id===facts.favourite?.id?'amber':'violet');}}b.blank();return b;}
function projectsBlock(snapshot:AuditSnapshot,width:number,options:ReportOptions):ReportDocument{const b=builder(width,options);if(!snapshot.projects.length)return b;b.add('PROJECTS','cyan');const max=Math.max(...snapshot.projects.map(project=>project.humanPrompts),1);for(const project of snapshot.projects){const visual=bar((project.nativeUserInputs??project.humanPrompts)/max,width<45?9:15,options.ascii);b.add(`${project.displayName}  ${reportNumber(project.nativeUserInputs??project.humanPrompts)} inputs`);b.add(visual,'cyan');}b.blank();return b;}
function activityBlock(snapshot:AuditSnapshot,width:number,options:ReportOptions):ReportDocument{const b=builder(width,options);if(!snapshot.activity.length)return b;b.add('ACTIVITY · recorded inputs','violet');b.add(spark(snapshot.activity.map(day=>day.count),width,options.ascii),'violet');b.add(`${snapshot.activity[0]!.date} to ${snapshot.activity.at(-1)!.date}`,'dim');b.blank();return b;}
function wordsBlock(snapshot:AuditSnapshot,width:number,options:ReportOptions):ReportDocument{const b=builder(width,options),lines=[...(snapshot.launch?.languageLines??[])].filter(line=>line.text.trim().split(/\s+/).length>1&&line.occurrences>0).sort((a,b)=>b.occurrences-a.occurrences);if(!lines.length)return b;b.add('YOUR REPEATED LINES','amber');for(const line of lines){b.add(`“${line.text}” ×${reportNumber(line.occurrences)}`,'amber');if(line.models.length)b.add(line.models.filter(model=>model.model!==null).map(model=>`${model.model} ${reportNumber(model.occurrences)}`).join(' · '),'dim');const sample=line.samples[0];if(sample)b.anchor({label:line.text,route:sample.route});}b.blank();return b;}
function feedbackBlock(snapshot:AuditSnapshot,width:number,options:ReportOptions):ReportDocument{const b=builder(width,options),models=snapshot.launch?.modelFeedback??[];if(!models.some(model=>model.model!==null&&(model.directedNegativeInputs>0||model.praiseInputs>0)))return b;b.add('RECORDED REACTIONS','amber');for(const [label,key] of [['Roasted','directedNegativeInputs'],['Praised','praiseInputs']] as const){const ranked=[...models].filter(model=>model.model!==null&&model.associatedInputs>0&&model[key]>0&&model[key]<=model.associatedInputs).sort((a,b)=>b[key]/b.associatedInputs-a[key]/a.associatedInputs);if(ranked.length)b.add(label,'dim');for(const model of ranked)b.add(`${model.model} ${model[key]}/${model.associatedInputs} ${((model[key]/model.associatedInputs)*100).toFixed(1)}%`);}b.add('Recorded reactions, not objective model quality.','dim');b.blank();return b;}
export function buildReportDocument(snapshot:AuditSnapshot,options:ReportOptions={}):ReportDocument {
 const width=Math.max(12,Math.min(options.columns??80,options.width??Infinity)),inner=Math.max(10,width-4),b=builder(inner,options),facts=snapshot.launch?.facts,sem=snapshot.launch?.semantics,status=launchAnalysisStatus(snapshot),wide=width>=110;
 b.add(`Slopie  ·  ${shortScope(snapshot)}`,'dim');
 if(facts){
  const value=equivalent(facts);b.add(value===null?'Value unavailable':dollars(value),'amberLight');b.add('API-equivalent value · current rates','dim');
  const tokens=knownTokens(snapshot);b.add(tokens===null?'Known token total unavailable':`${reportNumber(tokens)} known tokens`,'cyan');b.add(`${reportNumber(metric(snapshot.metrics.conversations))} chats · ${reportNumber(metric(snapshot.metrics.projects))} projects`);
  if(facts.referenceValueUsd!==null)b.add(`Includes ${[...new Set(facts.referenceProviders.map(ref=>ref.provider))].join(', ')||'first-party'} reference pricing; actual provider unknown`,'dim');
 }else{b.add('Value unavailable','amberLight');b.add('Recorded usage could not be valued.','dim');}
 if(snapshot.coverage.state!=='complete_snapshot'||facts?.gaps.length)b.add('Partial history / usage · known portions shown','dim');b.blank();
 if(wide){const column=Math.floor((inner-4)/2),left=builder(column,options),right=builder(column,options);append(left,modelsBlock(snapshot,column,options));append(left,wordsBlock(snapshot,column,options));append(right,projectsBlock(snapshot,column,options));append(right,activityBlock(snapshot,column,options));pair(b,left,right,inner,options);}else{append(b,modelsBlock(snapshot,inner,options));append(b,projectsBlock(snapshot,inner,options));append(b,activityBlock(snapshot,inner,options));append(b,wordsBlock(snapshot,inner,options));}append(b,feedbackBlock(snapshot,inner,options));
 const supported=(sem?.stories??[]).filter(story=>story.outcome==='supported'&&story.promptIds.length>0),work=(sem?.judgments.length?sem.work:[]).filter(item=>item.count>0&&!['other','mixed','insufficient_context','unclassified'].includes(item.label));
 if(supported.length||work.length){b.add('WORK THEMES','green');const selected=sem?.window.selected;if(selected)b.add(selected.selection?`${selected.selection.selected}/${selected.selection.available} selected episodes · partial calendar scope`:selected.period==='all'?'All available work':`Recent ${selected.period} days`,'dim');for(const item of work)b.add(`${item.label.replaceAll('_',' ')}  ${reportNumber(item.count)} segments`,'green');for(const story of supported.slice(0,4)){b.add(`${story.caption}${story.project?' · '+story.project:''}`);b.anchor({label:story.caption,conversationId:story.conversationId,promptIds:story.promptIds});}b.blank();}
 const quotes=(sem?.hallOfFame??[]).filter(story=>story.quote&&story.promptIds.length>0&&story.outcome!=='uncertain').slice(0,2);for(const story of quotes){b.add(`“${story.quote!}”`,'green');if(story.project)b.add(story.project,'dim');b.anchor({label:story.quote!,conversationId:story.conversationId,promptIds:story.promptIds});b.blank();}
 if(status.kind==='local'){if(status.summary)b.add(status.summary,'amber');if(status.action)b.add(status.action,'dim');if((sem?.attempts??0)===0)b.add('No analysis requests made','dim');}else if(status.kind!=='ready'&&status.summary)b.add(status.kind==='loading'?'Work insights are still being prepared.':status.summary,'dim');
 if(options.notice)b.add(options.notice,'amber');
 return {lines:b.lines.map(line=>[{text:'  ',tone:'normal'},...line]),anchors:b.anchors};
}
export function buildReportHelp(snapshot:AuditSnapshot,options:ReportOptions={},transfers:readonly Extract<AuditEvent,{type:'transfer'}>[]=[]):ReportDocument {
 const width=Math.max(10,(options.columns??80)-4),b=builder(width,options),facts=snapshot.launch?.facts,sem=snapshot.launch?.semantics;
 b.add('Wallboard help','amber');b.blank();b.add('← / →             Mixed layout pages');b.add('? / Esc            Help / return to wallboard');b.add('S                  Freeze data and motion; keep paging');b.add('Enter              Captured source on this page');b.add('Paste              Ignored as a command');b.add('q / Ctrl-C         Quit; cancel unfinished work');b.blank();
 b.add('Reading this report','cyan');b.add('Value revalues recorded usage at the captured current catalog. It is not an invoice or subscription bill. Unknown usage and unmatched prices are excluded from known totals.');b.add('Chats are top-level conversations; model participation includes recorded subagent usage. Native user-role inputs are observed roles, not universal human attestation.');if(snapshot.metrics.nativeUserInputs)b.add(`${reportNumber(metric(snapshot.metrics.nativeUserInputs))} observed native user-role inputs`);b.add('Repeated-line counts come from all eligible direct input. Roasted/Praised ranks show directed reaction inputs divided by associated inputs, sorted by rate. They are observations, not objective model quality. Quoted, code, unknown and self-directed material remain separate. Captured source samples are bounded independently of counts.');
 if(snapshot.launch?.languageGaps?.length)b.add('Language gaps: '+snapshot.launch.languageGaps.join(', '),'dim');for(const model of facts?.models??[])b.add(`Model identity: ${modelDisplayNameForHelp(model)} · ${model.provider??'provider unknown'}`,'dim');
 if(snapshot.profanity)for(const bucket of snapshot.profanity.buckets)b.add(`${bucket.kind.replaceAll('_',' ')}: ${reportNumber(bucket.occurrences)} matches / ${reportNumber(bucket.containingPrompts)} inputs`,'dim');b.blank();
 if(facts){b.add('Pricing and usage','cyan');b.add(`Catalog ${facts.pricing.retrievedAt}`);b.add(`SHA-256 ${facts.pricing.sha256}`);b.add(facts.pricing.source);b.add(`${facts.knownTokenResponses}/${facts.recordedResponses} responses with known normalized tokens; ${facts.equivalentPricedResponses} reference-valued responses.`);b.add(`Recorded endpoint portion ${dollars(facts.valueUsd)}; first-party reference portion ${dollars(facts.referenceValueUsd)}.`);if(facts.favourite)b.add(`Favourite combines token and conversation share equally. ${facts.favourite.tokenShare===null?'unknown':reportNumber(facts.favourite.tokenShare*100)+'%'} known-token share / ${reportNumber(facts.favourite.conversationShare*100)}% usage-chat share.`);b.blank();}
 if(snapshot.funnel){b.add('Coverage funnel','cyan');for(const [label,count] of Object.entries(snapshot.funnel))if(typeof count==='number')b.add(`${label}: ${reportNumber(count)}`);for(const [reason,count] of Object.entries(snapshot.funnel.excludedReasons))b.add(`${reason}: ${reportNumber(count)}`);b.blank();}
 if(sem?.window.selected){const selected=sem.window.selected;b.add('Selected work scope','cyan');b.add(`${selected.from??'unknown start'} to ${selected.until}`);if(selected.selection)b.add(`${selected.selection.selected}/${selected.selection.available} newest episodes; ${selected.selection.eventFrom??'unknown'} to ${selected.selection.eventTo??'unknown'}; partial calendar coverage.`);for(const choice of sem.window.choices)b.add(`${choice.period}: ${choice.estimatedInputTokens} input tokens / ${(choice.estimatedLatencyMs/1000).toFixed(1)}s remaining-analysis estimate / ${choice.fits?'fits':'does not fit'}`);b.blank();}
 b.add('Actual transfers during this run','cyan');if(!transfers.length)b.add('No transfer event was observed. Offline and cache-only work do not imply an external send.');else for(const event of transfers)b.add(`${event.recipients.join(', ')} · ${event.model} · attempt ${event.attempt}\n${event.notice}`);
 const gaps=[...launchGaps(snapshot)];if(gaps.length){b.blank();b.add('Coverage details','cyan');for(const gap of gaps)b.add(gap,'dim');}
 return {lines:b.lines.map(line=>[{text:'  ',tone:'normal'},...line]),anchors:[]};
}
export function buildEvidenceDocument(evidence:AuditEvidence|null|undefined,options:ReportOptions={}):ReportDocument{const b=builder(Math.max(10,(options.columns??80)-4),options);b.add('Captured source','cyan');b.blank();if(options.busy)b.add('Reading the captured source…','dim');else if(evidence?.state==='available'&&evidence.text!==null){b.add(`${evidence.role??'recorded role'} · ${evidence.eventAt?.slice(0,10)??'date unknown'}`,'dim');b.add(evidence.text);}else b.add(evidence?.state==='stale'?'Privacy authority changed. This source can no longer be read.':'Captured source is unavailable.','dim');if(options.notice)b.add(options.notice,'amber');return {lines:b.lines.map(line=>[{text:'  ',tone:'normal'},...line]),anchors:[]};}
export function buildReportLoader(snapshot:AuditSnapshot,options:ReportOptions={}):AuditLine[]{const width=Math.max(12,options.columns??80),height=Math.max(4,(options.rows??24)-1),b=builder(Math.max(10,width-4),options),frame=options.frame??0,blink=frame%14===0,mark=options.ascii?['  ___  ',' /###\\ ',blink?'|#- -#|':'|#o o#|',' \\###/ ','  ---  ']:['  ▄▄▄  ',' █████ ',blink?'▐█− −█▌':'▐█• •█▌',' █▄▄▄█ ','  ▀▀▀  '];
 for(const row of mark)b.lines.push([...row].map((text,column)=>({text,tone:text===' '?'normal':column===frame%7?'normal':'amber'})));b.blank();
 const chips=snapshot.sources.map(source=>{const census=source.census,checking=source.state==='checking'||!census?.checked&&!['unavailable','unsupported'].includes(source.state);const status=checking?'checking':source.state==='unavailable'?'unavailable':source.state==='unsupported'?'unsupported':census?.checked?`${reportNumber(census.files)} ${census.unit==='database'?'databases':'files'}`:'unknown';return {text:`${sourceNames[source.harness]??source.harness} ${status}`,tone:checking?'dim':'normal' as AuditTone};});
 let current:typeof chips=[];let used=0;for(const chip of chips){const size=(options.widthOf??auditCellWidth)(chip.text);if(current.length&&used+3+size>width-4){b.lines.push(current.flatMap((item,index)=>[...(index?[{text:'   ',tone:'normal' as AuditTone}]:[]),item]));current=[];used=0;}current.push(chip);used+=size+(current.length>1?3:0);}if(current.length)b.lines.push(current.flatMap((item,index)=>[...(index?[{text:'   ',tone:'normal' as AuditTone}]:[]),item]));b.blank();b.add(snapshot.progress.label??stageNames[snapshot.launch?.stage??'discovering'],'dim');
 const output:AuditLine[]=[],top=Math.max(0,Math.floor((height-b.lines.length)/2)),widthOf=options.widthOf??auditCellWidth;for(let i=0;i<top;i++)output.push([{text:'',tone:'normal'}]);for(const row of b.lines){const cells=row.reduce((sum,s)=>sum+widthOf(s.text),0);output.push([{text:' '.repeat(Math.max(0,Math.floor((width-cells)/2))),tone:'normal'},...row]);}return output.slice(0,height);}
