import type {AuditSnapshot,AuditEvidenceRoute,AuditWordTerm} from '../../../core/src/analytics/contracts.js';
import type {ModelAggregate,AuditLanguageLine,AuditModelFeedback} from '../../../core/src/analytics/launch-contracts.js';
import type {AuditLine,AuditTone} from './index.js';
import {auditCellWidth,auditClip} from './index.js';
import {reportWrap,reportNumber,cleanReportText} from './report-document.js';
import type {ReportOptions,ReportAnchor,ReportDocument} from './report-document.js';
import {launchAnalysisStatus} from './report-status.js';
export type WallCardId='value'|'models'|'projects'|'phrases'|'reactions'|'moment';
export interface WallCard {id:WallCardId;lines:AuditLine[];anchors:ReportAnchor[];}
export interface WallPage {lines:AuditLine[];cards:WallCardId[];anchor:WallCardId;anchors:ReportAnchor[];}
export interface WallLayout {pages:WallPage[];columns:number;rows:number;}
const cf=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const dollars=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'—':cf.format(value);
export const wallEquivalent=(value:{valueUsd:number|null;referenceValueUsd:number|null})=>value.valueUsd===null&&value.referenceValueUsd===null?null:(value.valueUsd??0)+(value.referenceValueUsd??0);
export const modelDisplayName=(model:ModelAggregate)=>model.canonicalModel??model.model??'Unidentified model';
const number=(value:number|null|undefined)=>reportNumber(value);
const asciiText=(text:string,ascii:boolean)=>ascii?text.replaceAll('━','#').replaceAll('─','-').replaceAll('×','x').replaceAll('“','"').replaceAll('”','"').replaceAll('…','...').replaceAll('—','?').replaceAll('·','|'):text;
function textLine(text:string,tone:AuditTone='normal'):AuditLine{return [{text,tone}];}
function clipped(text:string,width:number,options:ReportOptions):string {text=asciiText(cleanReportText(text).replaceAll('\n',' '),Boolean(options.ascii));const widthOf=options.widthOf??auditCellWidth;if(widthOf(text)<=width)return text;const end=options.ascii?'...':'…';return auditClip(text,Math.max(0,width-widthOf(end)),widthOf)+end;}
function bar(value:number|null,width:number,ascii:boolean):string {if(value===null||!Number.isFinite(value))return '';const fill=Math.min(width,Math.max(0,Math.round(value*width)));return (ascii?'#':'━').repeat(fill)+(ascii?'.':'─').repeat(width-fill);}
function knownTokens(snapshot:AuditSnapshot):number|null {const facts=snapshot.launch?.facts;if(!facts||facts.knownTokenResponses===0)return null;const values=facts.models.map(model=>model.knownTokens??model.totalTokens).filter((value):value is number=>value!=null);return values.length?values.reduce((sum,value)=>sum+value,0):null;}
function observed(metric:AuditSnapshot['metrics']['conversations']|undefined):number|null{return !metric||metric.state==='unavailable'||metric.state==='not_run'?null:metric.value;}
export function buildWallHero(snapshot:AuditSnapshot,width:number,options:ReportOptions={}):AuditLine[]{
 const facts=snapshot.launch?.facts,value=facts?wallEquivalent(facts):null,rows:AuditLine[]=[textLine(value===null?'Value unavailable':`${dollars(value)}  API-equivalent`,'amberLight')];
 const tokens=knownTokens(snapshot),counts=`${number(observed(snapshot.metrics.conversations))} chats · ${number(observed(snapshot.metrics.projects))} projects`;
 for(const line of reportWrap(asciiText(`${tokens===null?'Tokens unavailable':number(tokens)+' known tokens'} · ${counts}`,Boolean(options.ascii)),width,options.widthOf))rows.push(textLine(line));
 const partial=snapshot.coverage.state!=='complete_snapshot'||Boolean(facts?.gaps.length),refs=facts?.referenceValueUsd!=null?[...new Set(facts.referenceProviders.map(ref=>ref.provider))].join(', '):'';
 const cue=refs?`${partial?'Partial · ':''}${refs} reference; provider unknown`:partial?'Estimate · known usage only':'Current-rate estimate';
 for(const line of reportWrap(asciiText(cue,Boolean(options.ascii)),width,options.widthOf))rows.push(textLine(line,'dim'));
 return rows;
}
function modelCard(snapshot:AuditSnapshot,width:number,options:ReportOptions):WallCard|null {
 const facts=snapshot.launch?.facts;if(!facts?.models.length)return null;const sorted=[...facts.models].filter(model=>model.model!==null||model.canonicalModel!==null).sort((a,b)=>(b.knownTokens??b.totalTokens??-1)-(a.knownTokens??a.totalTokens??-1)||a.id.localeCompare(b.id)),models=sorted.slice(0,5);if(facts.favourite&&!models.some(model=>model.id===facts.favourite!.id))models[models.length-1]=facts.favourite;
 const widthOf=options.widthOf??auditCellWidth,max=Math.max(...models.map(model=>model.knownTokens??model.totalTokens??0),1),lines:AuditLine[]=[textLine('MODELS + PRICING')];
 if(facts.favourite)lines.push(textLine(clipped('Favourite '+modelDisplayName(facts.favourite),width,options),'amber'));
 for(const model of models){const known=model.knownTokens??model.totalTokens,tokens=known===0&&model.totalTokens===null?null:known,price=options.ascii&&wallEquivalent(model)===null?'-':dollars(wallEquivalent(model)),label=modelDisplayName(model),visual=bar(tokens===null?null:(tokens??0)/max,width<45?7:8,Boolean(options.ascii));
  if(width<45){const tail='  '+price,nameWidth=Math.max(8,width-widthOf(tail));lines.push(textLine(clipped(label,nameWidth,options)+tail));lines.push(textLine(clipped(`${visual} ${number(tokens)} ${model.totalTokens===null?'known ':''}tokens`,width,options),'dim'));}
  else{const tail=` ${visual} ${number(tokens)} ${price}`,nameWidth=Math.max(8,width-widthOf(tail));lines.push([{text:clipped(label,nameWidth,options),tone:'normal'},{text:tail,tone:model.id===facts.favourite?.id?'amber':'dim'}]);}
 }
 return {id:'models',lines,anchors:[]};
}
function projectCard(snapshot:AuditSnapshot,width:number,options:ReportOptions):WallCard|null {
 if(!snapshot.projects.length)return null;const lines:AuditLine[]=[textLine('TOP 3 PROJECTS + WORK')],anchors:ReportAnchor[]=[];
 for(const project of snapshot.projects.slice(0,3)){const count=project.nativeUserInputs??project.humanPrompts,tail=` ${number(count)} inputs`,widthOf=options.widthOf??auditCellWidth;lines.push(textLine(clipped(project.displayName,Math.max(8,width-widthOf(tail)),options)+tail));
  const focus=(project.focus??[]).filter(item=>item.inputs>0&&(item.promptIds.length>0||item.evidenceRoutes.length>0)).sort((a,b)=>b.inputs-a.inputs).slice(0,2);if(focus.length){lines.push(textLine(clipped('Requests: '+focus.map(item=>item.label).join(' · '),width,options),'dim'));const first=focus.find(item=>item.evidenceRoutes.length);if(first)anchors.push({row:lines.length-1,label:project.displayName+' requested work',route:first.evidenceRoutes[0]});}
 }
 return {id:'projects',lines,anchors};
}
export function repeatedLines(snapshot:AuditSnapshot):AuditLanguageLine[]{return [...(snapshot.launch?.languageLines??[])].filter(line=>line.text.trim().split(/\s+/).length>1&&line.occurrences>0&&line.samples.length>0).sort((a,b)=>b.occurrences-a.occurrences||a.id.localeCompare(b.id)).slice(0,6);}
function phraseCard(snapshot:AuditSnapshot,width:number,options:ReportOptions):WallCard|null {const phrases=repeatedLines(snapshot);if(!phrases.length)return null;const lines:AuditLine[]=[textLine(phrases.every(line=>line.occurrences>1)?'YOUR REPEATED LINES':'YOUR LINES')],anchors:ReportAnchor[]=[],widthOf=options.widthOf??auditCellWidth;for(const phrase of phrases){const tail=` ×${number(phrase.occurrences)}`,quoteWidth=Math.max(4,width-widthOf(asciiText(tail,Boolean(options.ascii)))-2);lines.push(textLine(asciiText('“'+clipped(phrase.text,quoteWidth,options)+'”'+tail,Boolean(options.ascii)),'amber'));const sample=phrase.samples[0]!;anchors.push({row:lines.length-1,label:phrase.text,route:sample.route});}return {id:'phrases',lines,anchors};}
export function rankedFeedback(snapshot:AuditSnapshot,kind:'negative'|'praise'):AuditModelFeedback[]{const key=kind==='negative'?'directedNegativeInputs':'praiseInputs';return [...(snapshot.launch?.modelFeedback??[])].filter(model=>model.model!==null&&Number.isFinite(model.associatedInputs)&&model.associatedInputs>0&&model[key]>0&&model[key]<=model.associatedInputs).sort((a,b)=>b[key]/b.associatedInputs-a[key]/a.associatedInputs||b[key]-a[key]||a.model!.localeCompare(b.model!)).slice(0,3);}
function feedbackCard(snapshot:AuditSnapshot,width:number,options:ReportOptions):WallCard|null {const negative=rankedFeedback(snapshot,'negative'),praise=rankedFeedback(snapshot,'praise');if(!negative.length&&!praise.length)return null;const lines:AuditLine[]=[textLine('RECORDED REACTIONS')],widthOf=options.widthOf??auditCellWidth,limit=width<45?2:3;for(const [title,models,key] of [['Roasted',negative,'directedNegativeInputs'],['Praised',praise,'praiseInputs']] as const){if(!models.length)continue;lines.push(textLine(title,'dim'));for(const model of models.slice(0,limit)){const tail=` ${model[key]}/${model.associatedInputs} ${((model[key]/model.associatedInputs)*100).toFixed(1)}%`;lines.push(textLine(clipped(model.model!,Math.max(8,width-widthOf(tail)),options)+tail));}}return {id:'reactions',lines,anchors:[]};}
function momentCard(snapshot:AuditSnapshot,width:number,options:ReportOptions):WallCard|null {const moment=snapshot.launch?.semantics?.hallOfFame.find(story=>story.quote&&story.promptIds.length>0&&story.outcome!=='uncertain');if(!moment)return null;const text='“'+moment.quote+'”'+(moment.project?' · '+moment.project:''),lines=[textLine(clipped(text,width,options),'amber')];return {id:'moment',lines,anchors:[{row:0,label:moment.quote!,conversationId:moment.conversationId,promptIds:moment.promptIds}]};}
function appendCard(page:WallPage,card:WallCard,gap=true):void{if(gap&&page.lines.length)page.lines.push(textLine(''));const offset=page.lines.length;page.lines.push(...card.lines);page.cards.push(card.id);page.anchors.push(...card.anchors.map(anchor=>({...anchor,row:anchor.row+offset})));if(page.anchor==='value')page.anchor=card.id;}
function addPair(page:WallPage,left:WallCard|null,right:WallCard|null,width:number,options:ReportOptions):void{if(!left&&!right)return;if(!left||!right){appendCard(page,(left??right)!);return;}if(page.lines.length)page.lines.push(textLine(''));const column=Math.floor((width-3)/2),offset=page.lines.length,widthOf=options.widthOf??auditCellWidth;for(let i=0;i<Math.max(left.lines.length,right.lines.length);i++){const l=left.lines[i]??[],r=right.lines[i]??[],used=l.reduce((sum,segment)=>sum+widthOf(segment.text),0);page.lines.push([...l,{text:' '.repeat(Math.max(0,column-used)+3),tone:'normal'},...r]);}page.cards.push(left.id,right.id);page.anchors.push(...left.anchors.map(anchor=>({...anchor,row:anchor.row+offset})),...right.anchors.map(anchor=>({...anchor,row:anchor.row+offset})));if(page.anchor==='value')page.anchor=left.id;}
function splitCard(card:WallCard,capacity:number):WallCard[]{if(card.lines.length<=capacity)return [card];const header=card.lines[0]!,size=Math.max(1,capacity-1),chunks:WallCard[]=[];for(let start=1;start<card.lines.length;start+=size){const slice=card.lines.slice(start,start+size);chunks.push({...card,lines:[header,...slice],anchors:card.anchors.filter(anchor=>anchor.row>=start&&anchor.row<start+size).map(anchor=>({...anchor,row:anchor.row-start+1}))});}return chunks;}
/** Data-driven mixed card pages. No viewport offsets or discarded card tails. */
export function buildWallboard(snapshot:AuditSnapshot,options:ReportOptions={}):WallLayout {
 const columns=Math.max(12,Math.min(options.columns??80,options.width??Infinity)),rows=Math.max(4,options.rows??24),width=Math.max(8,columns-4),visible=rows-1,hero=buildWallHero(snapshot,width,options),pages:WallPage[]=[],make=()=>({lines:[...hero],cards:['value' as WallCardId],anchor:'value' as WallCardId,anchors:[] as ReportAnchor[]}),wide=columns>=120&&rows>=32,column=Math.floor((width-3)/2);
 if(columns<40||rows<18)return {columns,rows,pages:[{lines:[textLine(clipped('Resize to 40 × 20 or larger',Math.max(8,columns-4),options),'dim')],cards:['value'],anchor:'value',anchors:[]}]};
 const models=modelCard(snapshot,wide?column:columns>=75?column:width,options),projects=projectCard(snapshot,wide?column:columns>=75?column:width,options),phrases=phraseCard(snapshot,wide?column:columns>=75?column:width,options),feedback=feedbackCard(snapshot,wide?column:columns>=75?column:width,options),moment=momentCard(snapshot,width,options);
 if(columns>=75){const first=make();addPair(first,models,projects,width,options);if(wide){addPair(first,phrases,feedback,width,options);if(moment)appendCard(first,moment);if(first.lines.length<=visible){pages.push(first);}else{const main=make();addPair(main,models,projects,width,options);if(moment)appendCard(main,moment);pages.push(main);const second=make();addPair(second,phrases,feedback,width,options);pages.push(second);}}
  else{if(moment)appendCard(first,moment);pages.push(first);if(phrases||feedback){const second=make();addPair(second,phrases,feedback,width,options);pages.push(second);}}
 }else{let current=make();const remaining=Math.max(2,visible-hero.length-1);for(const original of [models,projects,moment,phrases,feedback].filter((card):card is WallCard=>Boolean(card))){let card=original;const free=visible-current.lines.length-1;if(card.id==='phrases'&&free>=3&&card.lines.length>free){const first={...card,lines:card.lines.slice(0,free),anchors:card.anchors.filter(a=>a.row<free)};appendCard(current,first);pages.push(current);current=make();card={...card,lines:[card.lines[0]!,...card.lines.slice(free)],anchors:card.anchors.filter(a=>a.row>=free).map(a=>({...a,row:a.row-free+1}))};}for(const chunk of splitCard(card,remaining)){if(current.lines.length+chunk.lines.length+1>visible&&current.cards.length>1){pages.push(current);current=make();}appendCard(current,chunk);}}pages.push(current);}
 // Oversized measured wide cards fall back to complete stacked chunks, never clipping.
 if(pages.some(page=>page.lines.length>visible)){const stacked:WallPage[]=[],capacity=Math.max(2,visible-hero.length-1);let current=make();for(const card of [modelCard(snapshot,width,options),projectCard(snapshot,width,options),moment,phraseCard(snapshot,width,options),feedbackCard(snapshot,width,options)].filter((card):card is WallCard=>Boolean(card))){for(const chunk of splitCard(card,capacity)){if(current.lines.length+chunk.lines.length+1>visible&&current.cards.length>1){stacked.push(current);current=make();}appendCard(current,chunk);}}stacked.push(current);pages.splice(0,pages.length,...stacked);}
 const status=launchAnalysisStatus(snapshot);if(status.kind==='local'||(!snapshot.launch?.facts&&status.summary)){const page=pages[0]!;for(const line of reportWrap(status.summary??'Local history unavailable',width,options.widthOf))page.lines.push(textLine(line,'dim'));if(status.kind==='local'&&(snapshot.launch?.semantics?.attempts??0)===0)page.lines.push(textLine('No analysis requests made','dim'));}
 else if(status.kind==='provider'){const page=pages.at(-1)!;if(status.summary&&page.lines.length<visible)page.lines.push(textLine(status.summary,'dim'));}
 return {columns,rows,pages:pages.filter(page=>page.cards.length>1||pages.length===1||status.kind==='local'||!snapshot.launch?.facts&&Boolean(status.summary)).map(page=>({...page,lines:page.lines.map(line=>[{text:'  ',tone:'normal'},...line])}))};
}
