import {createHash} from 'node:crypto';
import {auditProfanity,proseLabels} from './profanity.js';
import type {AuditPrompt,AuditEvidenceRoute} from './contracts.js';
import type {ContextRecord,AuditLanguageLine,AuditModelFeedback} from './launch-contracts.js';
export type ProfaneLine=AuditLanguageLine;
export type ModelFeedback=AuditModelFeedback;
/** Explicit lexical feedback, not inferred sentiment, authorship or coding quality. */
export function summarizeDirectedLanguage(prompts:readonly AuditPrompt[],records:readonly ContextRecord[]):{languageLines:ProfaneLine[];modelFeedback:ModelFeedback[];languageGaps:string[]}{
 const namedModels=new Map<string,Map<string,Set<string|null>>>(),seenRecords=new Set<string>();const preceding=new Map<string,{model:string|null;provider:string|null}>(),groups=new Map<string,ContextRecord[]>();for(const r of records){const unique=JSON.stringify([r.conversationId,r.project,r.role,r.id]);if(seenRecords.has(unique))continue;seenRecords.add(unique);if(r.role==='assistant'&&r.model){const names=namedModels.get(r.conversationId)??new Map<string,Set<string|null>>(),providers=names.get(r.model)??new Set<string|null>();providers.add(r.provider);names.set(r.model,providers);namedModels.set(r.conversationId,names);}const key=JSON.stringify([r.conversationId,r.project]);const rows=groups.get(key)??[];rows.push(r);groups.set(key,rows);}
 for(const rows of groups.values()){let models=new Map<string,{model:string|null;provider:string|null}>();for(const r of rows){if(r.role==='user'){preceding.set(r.id,models.size===1?[...models.values()][0]!:{model:null,provider:null});models=new Map();}else if(r.role==='assistant')models.set(JSON.stringify([r.model,r.provider]),{model:r.model,provider:r.provider});}}
 const lines=new Map<string,{text:string;count:number;ids:Set<string>;models:Map<string,{provider:string|null;model:string|null;occurrences:number}>;samples:ProfaneLine['samples'][number][]}>(),feedback=new Map<string,{model:string|null;provider:string|null;negative:Set<string>;praise:Set<string>;associated:Set<string>;ids:Set<string>}>,gaps=new Set<string>(['lexical_directed_feedback_only','unknown_authorship_not_universally_attested']);
 for(const prompt of prompts){if(prompt.languageEligible===false||!(prompt.eligibleNativeInput??prompt.eligibleHuman))continue;const fullLabels=proseLabels(prompt.text);let owner=preceding.get(prompt.id)??{model:null,provider:null};const named=new Map<string,{model:string;providers:Set<string|null>}>();for(const [model,providers] of namedModels.get(prompt.conversationId)??[]){const at=prompt.text.indexOf(model);if(at<0||fullLabels[at]!==0||/[\p{L}\p{N}_/-]/u.test(prompt.text[at-1]??'')||/[\p{L}\p{N}_/-]/u.test(prompt.text[at+model.length]??''))continue;named.set(model,{model,providers});}if(named.size===1){const item=[...named.values()][0]!;owner={model:item.model,provider:item.providers.size===1?[...item.providers][0]!:null};}if(!preceding.has(prompt.id))gaps.add('language_context_capture_partial');if(owner.model){const key=JSON.stringify(owner),row=feedback.get(key)??{...owner,negative:new Set<string>(),praise:new Set<string>(),associated:new Set<string>(),ids:new Set<string>()};row.associated.add(prompt.id);feedback.set(key,row);}let offset=0,negative=false,praise=false;
  for(const line of prompt.text.split('\n')){const start=offset;offset+=line.length+1;const trimmed=line.trim();if(!trimmed)continue;const at=start+line.indexOf(trimmed),end=at+trimmed.length;
   // Classify this exact line independently so quotes/code never become feedback.
   const local=auditProfanity([{...prompt,text:line}]);const direct=local.terms?.some(t=>t.kind==='direct_prose'&&t.samples.some(sample=>fullLabels[start+sample.startUtf16]===0))??false;const nonprose=local.terms?.some(t=>t.kind!=='direct_prose')??false;
   const address=named.size===1||/\b(?:you|your|you['’]re)\b/iu.test(trimmed),positiveMatch=trimmed.match(/\b(?:good (?:work|job)|well done|you understood (?:me|it)|you (?:got|nailed) (?:it|this)|you(?:['’]re| are) (?:fucking )?(?:great|awesome))\b/iu),positive=!!positiveMatch&&fullLabels[at+(positiveMatch.index??0)]===0,negated=/\b(?:not|never|don['’]?t|didn['’]?t|no)\b.{0,35}\b(?:good|well done|understood|nailed|great|awesome)\b/iu.test(trimmed);
   const quoted=fullLabels[at]!==0||/^\s*(?:>|[`~]{3}|["“'])/u.test(line)||/^ {4}|^\t/u.test(line);const explicitNegative=address&&direct&&!positive&&/\b(?:wrong|broken|stupid|missed|failed|why|mess|didn['’]?t|not|bullshit|fuck(?:ed|ing)? (?:up|off))\b/iu.test(trimmed);
   if(!quoted&&!nonprose){negative||=explicitNegative;praise||=positive&&!negated;}
   if(!direct||quoted||(trimmed.match(/[\p{L}\p{N}]+/gu)?.length??0)<2)continue;const candidates=trimmed.length<=160?[{text:trimmed,start:at,end}]:[...trimmed.matchAll(/[^.!?;\n]+[.!?;]?/gu)].map(match=>{const value=match[0].trim(),begin=at+match.index!+match[0].indexOf(value);return {text:value,start:begin,end:begin+value.length};}).filter(span=>span.text.length<=160&&(span.text.match(/[\p{L}\p{N}]+/gu)?.length??0)>=2&&auditProfanity([{...prompt,text:span.text}]).terms?.some(t=>t.kind==='direct_prose'&&fullLabels[span.start+t.samples[0]!.startUtf16]===0));if(!candidates.length)gaps.add('long_profane_lines_not_displayed');for(const span of candidates){
   const key=span.text.toLocaleLowerCase('en').replace(/\s+/gu,' ').replace(/[\p{P}]+$/gu,'').trim(),item=lines.get(key)??{text:span.text,count:0,ids:new Set(),models:new Map(),samples:[] as ProfaneLine['samples'][number][]};item.count++;item.ids.add(prompt.id);if(item.samples.length<3)item.samples.push({promptId:prompt.id,conversationId:prompt.conversationId,startUtf16:span.start,endUtf16:span.end,route:prompt.route});if(explicitNegative&&!quoted&&!nonprose&&owner.model){const k=JSON.stringify(owner),row=item.models.get(k)??{...owner,occurrences:0};row.occurrences++;item.models.set(k,row);}lines.set(key,item);}
  }
  if((negative||praise)&&owner.model){const key=JSON.stringify(owner),row=feedback.get(key)??{...owner,negative:new Set<string>(),praise:new Set<string>(),associated:new Set<string>(),ids:new Set<string>()};if(negative)row.negative.add(prompt.id);if(praise)row.praise.add(prompt.id);row.ids.add(prompt.id);feedback.set(key,row);}else if(negative||praise)gaps.add('feedback_model_unattributed');
 }
 return {languageLines:[...lines.entries()].map(([key,row])=>({id:createHash('sha256').update(key).digest('hex').slice(0,20),text:row.text,occurrences:row.count,containingInputs:row.ids.size,models:[...row.models.values()].sort((a,b)=>b.occurrences-a.occurrences),samples:row.samples})).sort((a,b)=>b.occurrences-a.occurrences||a.text.localeCompare(b.text)).slice(0,6),modelFeedback:[...feedback.values()].map(row=>({provider:row.provider,model:row.model,associatedInputs:row.associated.size,directedNegativeInputs:row.negative.size,praiseInputs:row.praise.size,promptIds:[...row.ids].slice(0,12)})).sort((a,b)=>b.directedNegativeInputs-a.directedNegativeInputs||b.praiseInputs-a.praiseInputs||(a.model??'').localeCompare(b.model??'')),languageGaps:[...gaps]};
}
