import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {extractTypedText,extractTextFromContent,isRecord} from '../parser/content.js';
import {hasExclusionMarker} from '../markers.js';
import {sourceId} from '../memory/source.js';
import {clean,clock,digest,type NativeEvent,type NativeFacts} from './source.js';
import {createNativeUsageAccumulator} from './native-usage.js';
import type {AuditHarness} from './contracts.js';
import type {RecordedInference,ContextRecord} from './launch-contracts.js';
export interface StreamedNative {facts:NativeFacts;usage:RecordedInference[];language:ContextRecord[];hash:string;bytes:number;counts:{observed:number;excluded:number;deduplicated:number};}
/** Full native inference metadata and observed role inputs; no assistant/tool bodies retained. */
export async function streamNativeFacts(file:string,harness:Exclude<AuditHarness,'opencode'>,options:{signal:AbortSignal;maxBytes:number;maxRecords?:number;maxPromptBytes?:number;captureBytes?:number;accept:(project:string|null,eventAt:string|null)=>boolean}):Promise<StreamedNative>{
 const before=fs.statSync(file,{bigint:true});if(!before.isFile()||before.size>BigInt(options.maxBytes))throw new Error('native_usage_bytes_limit');
 let nativeId=path.basename(file,'.jsonl'),project:string|null=null,parent:string|null=null,records=0,offset=0,promptBytes=0,maintenance=false,programmatic=false,currentModel:string|null=null,currentProvider:string|null=null;const events:NativeEvent[]=[],language:ContextRecord[]=[],gaps=new Set<string>(),seen=new Set<string>(),hash=createHash('sha256');let usage:ReturnType<typeof createNativeUsageAccumulator>|null=null;
 let held:Buffer=Buffer.alloc(0);const chunks:Buffer[]=[];let captureBytes=0;
 const process=(raw:Buffer,end:number)=>{if(++records>(options.maxRecords??1000000)){gaps.add('native_usage_records_limit');return;}if(raw.length>8*1024*1024){gaps.add('native_record_bytes_limit');return;}const line=raw.toString('utf8');let r:Record<string,unknown>;try{const parsed=JSON.parse(line);if(!isRecord(parsed))return;r=parsed;}catch{gaps.add('malformed_record');return;}
  if(r.entrypoint==='sdk-ts'||r.originator==='codex_exec')programmatic=true;
  const p=isRecord(r.payload)?r.payload:r,m=isRecord(r.message)?r.message:{};if(typeof r.cwd==='string')project=r.cwd;if(typeof p.cwd==='string')project=p.cwd;
  if(harness==='claude'&&typeof r.sessionId==='string'){if(file.includes(`${path.sep}subagents${path.sep}`)||r.isSidechain===true){parent=r.sessionId;nativeId=`${parent}:${path.basename(file,'.jsonl')}`;}else nativeId=r.sessionId;}
  if(harness==='codex'&&r.type==='session_meta'){nativeId=typeof p.id==='string'?p.id:typeof p.session_id==='string'?p.session_id:nativeId;const source=isRecord(p.source)?p.source:{},sub=isRecord(source.subagent)?source.subagent:{},spawn=isRecord(sub.thread_spawn)?sub.thread_spawn:{};if(typeof spawn.parent_thread_id==='string')parent=spawn.parent_thread_id;}
  if(harness==='pi'&&r.type==='session'){if(typeof r.id==='string')nativeId=r.id;if(typeof r.parentSessionId==='string')parent=r.parentSessionId;}
  if(r.type==='turn_context'||r.type==='session_meta'||r.type==='model_change'){currentModel=typeof p.model==='string'?p.model:typeof r.modelId==='string'?r.modelId:currentModel;currentProvider=typeof p.model_provider==='string'?p.model_provider:typeof r.provider==='string'?r.provider:currentProvider;}
  if(!usage)usage=createNativeUsageAccumulator(harness,sourceId(harness,nativeId),{maxRecords:1000000,acceptRecord:(_r,scope)=>!maintenance&&options.accept(scope.project,scope.eventAt)});usage.pushLine(line);
  let text='',identity='',origin:NativeEvent['origin']='unknown',eligible=false,excluded:string|null=null;const time=clock(r.timestamp),key=typeof r.uuid==='string'?r.uuid:typeof r.id==='string'?r.id:typeof p.id==='string'?p.id:`record:${records}`;
  if(harness==='claude'&&r.type==='user'&&m.role==='user'){if(Array.isArray(m.content)&&m.content.some(b=>isRecord(b)&&b.type==='tool_result'))return;text=extractTypedText(m.content);identity=typeof r.promptId==='string'?`prompt:${r.promptId}`:`record:${key}`;origin=typeof r.promptId==='string'?'claude_prompt_id':'unknown';eligible=typeof r.promptId==='string'&&!programmatic;}
  else if(harness==='codex'&&r.type==='event_msg'&&p.type==='user_message'){text=typeof p.message==='string'?p.message:'';identity=`marker:${offset}`;origin='codex_human_marker';eligible=true;}
  else if(harness==='pi'&&r.type==='message'&&m.role==='user'){text=extractTypedText(m.content);identity=`node:${key}`;origin='pi_user_projection';}
  else{const info=isRecord(p.info)?p.info:{};const observedModel=typeof m.model==='string'?m.model:typeof p.model==='string'?p.model:typeof info.model==='string'?info.model:currentModel,observedProvider=typeof m.provider==='string'?m.provider:typeof p.provider==='string'?p.provider:currentProvider;if((m.role==='assistant'||harness==='codex'&&r.type==='event_msg'&&p.type==='token_count')&&observedModel!=='<synthetic>'&&r.isSynthetic!==true&&options.accept(project,time))language.push({id:`metadata:${records}`,conversationId:sourceId(harness,nativeId),parentId:parent,harness,eventAt:time,project,role:'assistant',text:'',model:observedModel,provider:observedProvider,directUser:false,route:null});return;}
  if(!text.trim())return;if(hasExclusionMarker(text)){maintenance=true;excluded='maintenance_exclusion_marker';}else if(r.isMeta===true||r.isSynthetic===true||m.isSynthetic===true)excluded='declared_meta_or_synthetic_input';else if(parent&&events.length===0)excluded='child_initialization';else if(typeof r.session_id==='string'&&r.session_id!==nativeId)excluded='inherited_native_event';
  if(seen.has(identity))return;seen.add(identity);if(!options.accept(project,time))return;const redacted=clean(text);if(promptBytes+Buffer.byteLength(redacted)>(options.maxPromptBytes??64*1024*1024)){gaps.add('native_input_text_limit');return;}promptBytes+=Buffer.byteLength(redacted);
  language.push({id:digest(`${sourceId(harness,nativeId)}:${identity}`).slice(0,32),conversationId:sourceId(harness,nativeId),parentId:parent,harness,eventAt:time,project,role:'user',text:'',model:null,provider:null,directUser:excluded===null,route:null});
  events.push({key,rawStart:offset,rawEnd:end,role:'user',text:redacted,eventAt:time,project,origin,eligible:eligible&&excluded===null,excluded,identity,observed:excluded===null});
 };
 const stream=fs.createReadStream(file,{highWaterMark:64*1024,end:Number(before.size)-1});try{for await(const chunk of stream){if(options.signal.aborted){stream.destroy();throw new Error('cancelled');}const bytes=chunk as Buffer;hash.update(bytes);const room=(options.captureBytes??0)-captureBytes;if(room>0){const kept=Buffer.from(bytes.subarray(0,room));chunks.push(kept);captureBytes+=kept.length;}held=held.length?Buffer.concat([held,bytes]):bytes;let newline=held.indexOf(10);while(newline>=0){const end=offset+newline+1;process(held.subarray(0,newline),end);offset=end;held=held.subarray(newline+1);newline=held.indexOf(10);}if(held.length>8*1024*1024){stream.destroy();throw new Error('native_record_bytes_limit');}}}finally{stream.destroy();}
 if(held.length)gaps.add('unfinished_tail');const after=fs.statSync(file,{bigint:true});if(before.dev!==after.dev||before.ino!==after.ino||before.size!==after.size||before.mtimeNs!==after.mtimeNs||before.ctimeNs!==after.ctimeNs)throw new Error('source_changed');
 if(maintenance){gaps.add('maintenance_source_excluded');for(const event of events){event.observed=false;event.eligible=false;event.excluded='maintenance_exclusion_marker';}}
 const artifactHash=hash.digest('hex'),acc=usage as ReturnType<typeof createNativeUsageAccumulator>|null,all=acc?.records()??[];let captured=Buffer.concat(chunks,captureBytes);captured=captured.subarray(0,captured.lastIndexOf(10)+1);if(captured.length<Number(before.size))gaps.add('context_capture_partial');return {facts:{nativeId,project,parent,child:parent!==null,title:null,events,gaps:[...gaps],hash:artifactHash,consumed:offset,bytes:captured},usage:maintenance?[]:all,language:maintenance?[]:language,hash:artifactHash,bytes:Number(before.size),counts:acc?.counts()??{observed:0,excluded:0,deduplicated:0}};
}
