import {StringDecoder} from 'node:string_decoder';
import {EXCLUSION_MARKERS} from '../markers.js';
type ImageBody={frame:Frame;chunks:string[];bytes:number;overflow:boolean};
type Frame={path:string[];omitImage:boolean;array:boolean;state:'key'|'keyRequired'|'colon'|'value'|'valueRequired'|'comma';key:string|null;keep:boolean;value:Record<string,unknown>|unknown[]|null};
/** Validates one complete JSON record while omitting body values, with bounded retained metadata. */
export class NativeMetadataProjection {
 private readonly decoder=new StringDecoder('utf8');private frames:Frame[]=[];private root:unknown;private done=false;private mode:'idle'|'string'|'number'|'literal'='idle';private token='';private isKey=false;private keep=false;private escape=false;private unicode='';private markerTail='';private retained=0;private error:string|null=null;private marker=false;private scanString=false;private scanEscape=false;private scanUnicode='';private scanTail='';
 // Defer the producer check until the whole record is known, retaining unknown values only within the shared metadata budget.
 private imageBodies:ImageBody[]=[];private imageCandidate:ImageBody|null=null;private imageBytes=0;
 private trimImages():void{for(let i=this.imageBodies.length-1;i>=0&&this.retained+this.imageBytes>this.maxBytes;i--){const body=this.imageBodies[i]!;this.imageBytes-=body.bytes;body.chunks=[];body.bytes=0;body.overflow=true;}}
 constructor(private readonly maxBytes=8*1024*1024,private readonly harness:string|null=null){}
 private fail(code='native_metadata_invalid'):void{this.error??=code;}
 private add(c:string):void{if(this.keep||this.isKey){this.retained+=Buffer.byteLength(JSON.stringify(c))-2;if(this.retained>this.maxBytes||this.isKey&&this.token.length>32768){this.fail('native_metadata_bytes_limit');return;}this.token+=c;this.trimImages();}if(this.imageCandidate&&!this.imageCandidate.overflow){const bytes=Buffer.byteLength(JSON.stringify(c))-2;this.imageCandidate.bytes+=bytes;this.imageBytes+=bytes;this.imageCandidate.chunks.push(c);this.trimImages();}const searchable=this.markerTail+c;if(EXCLUSION_MARKERS.some(m=>searchable.includes(m)))this.marker=true;this.markerTail=searchable.slice(-256);}
 private expectedValue():boolean{const f=this.frames.at(-1);return f?f.state==='value'||f.state==='valueRequired':!this.done;}
 private imageBody(f:Frame):boolean{return this.harness==='codex'&&f.key==='image_url'&&f.path.length===3&&f.path[0]==='payload'&&f.path[1]==='output'&&f.path[2]==='[]';}
 private retainValue():boolean{const f=this.frames.at(-1);return !f||f.keep&&!(f.key==='content'||f.key==='text'||f.omitImage);}
 private accept(value:unknown):void{if(this.retainValue()){this.retained+=16;this.trimImages();if(this.retained>this.maxBytes){this.fail('native_metadata_bytes_limit');return;}}const f=this.frames.at(-1);if(!f){if(this.done){this.fail();return;}this.root=value;this.done=true;return;}if(f.state!=='value'&&f.state!=='valueRequired'){this.fail();return;}if(f.keep){if(f.array)(f.value as unknown[]).push(value);else if(f.key!==null&&this.retainValue())Object.defineProperty(f.value!,f.key,{value,writable:true,enumerable:true,configurable:true});}f.key=null;f.omitImage=false;f.state='comma';}
 private scalarEnd():void{if(this.mode==='number'){if(!/^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$/.test(this.token)){this.fail();return;}this.accept(this.keep?Number(this.token):null);}else if(this.mode==='literal'){if(!['true','false','null'].includes(this.token)){this.fail();return;}this.accept(this.keep?JSON.parse(this.token):null);}this.mode='idle';this.token='';}
 private char(c:string):void{
  if(this.error)return;
  if(this.mode==='string'){
   if(this.unicode){if(!/[0-9a-f]/i.test(c)){this.fail();return;}this.unicode+=c;if(this.unicode.length===5){this.add(String.fromCharCode(parseInt(this.unicode.slice(1),16)));this.unicode='';}return;}
   if(this.escape){this.escape=false;if(c==='u'){this.unicode='u';return;}const decoded:Record<string,string>={'"':'"','\\':'\\','/':'/','b':'\b','f':'\f','n':'\n','r':'\r','t':'\t'};if(!(c in decoded)){this.fail();return;}this.add(decoded[c]!);return;}
   if(c==='\\'){this.escape=true;return;}if(c==='"'){if(this.isKey){const f=this.frames.at(-1)!;f.key=this.token;f.state='colon';}else this.accept(this.keep?this.token:null);this.mode='idle';this.token='';this.imageCandidate=null;this.markerTail='';return;}if(c.charCodeAt(0)<32){this.fail();return;}this.add(c);return;
  }
  if(this.mode==='number'||this.mode==='literal'){const allowed=this.mode==='number'?/[0-9eE+.-]/:/[a-z]/;if(allowed.test(c)){if(this.token.length>=256){this.fail('native_metadata_scalar_limit');return;}this.token+=c;return;}this.scalarEnd();if(this.error)return;}
  if(/\s/.test(c)){if(![' ','\t','\r','\n'].includes(c))this.fail();return;}
  const f=this.frames.at(-1);
  if(c==='"'){this.isKey=!!f&&!f.array&&(f.state==='key'||f.state==='keyRequired');if(!this.isKey&&!this.expectedValue()){this.fail();return;}if(!this.isKey&&f&&this.imageBody(f)){f.omitImage=true;this.imageCandidate={frame:f,chunks:[],bytes:0,overflow:false};this.imageBodies.push(this.imageCandidate);}this.keep=this.isKey||this.retainValue()&&f?.key!=='message';this.token='';this.markerTail='';this.mode='string';return;}
  if(c==='{'||c==='['){if(!this.expectedValue()||this.frames.length>=128){this.fail('native_metadata_depth_limit');return;}const keep=this.retainValue();this.frames.push({path:f?[...f.path,f.array?'[]':f.key!]:[],omitImage:false,array:c==='[',state:c==='['?'value':'key',key:null,keep,value:keep?(c==='['?[]:{}):null});return;}
  if(c==='}'||c===']'){if(!f||f.array!==(c===']')||!['comma',f.array?'value':'key'].includes(f.state)){this.fail();return;}this.frames.pop();this.accept(f.value);return;}
  if(c===':'){if(!f||f.state!=='colon'){this.fail();return;}f.state='valueRequired';return;}
  if(c===','){if(!f||f.state!=='comma'){this.fail();return;}f.state=f.array?'valueRequired':'keyRequired';return;}
  if(!this.expectedValue()){this.fail();return;}this.keep=this.retainValue();this.token=c;if(c==='-'||/[0-9]/.test(c))this.mode='number';else if(/[tfn]/.test(c))this.mode='literal';else this.fail();
 }
 private scanMarkers(text:string):void{const special=/["\\]/g;let at=0;const add=(value:string)=>{const combined=this.scanTail+value;if(EXCLUSION_MARKERS.some(m=>combined.includes(m)))this.marker=true;this.scanTail=combined.slice(-256);};while(at<text.length){if(this.scanString&&!this.scanEscape&&!this.scanUnicode){special.lastIndex=at;const hit=special.exec(text),end=hit?.index??text.length;add(text.slice(at,end));at=end;if(at>=text.length)break;}const c=text[at++]!;if(this.scanUnicode){this.scanUnicode+=c;if(this.scanUnicode.length===5){if(/^u[0-9a-f]{4}$/i.test(this.scanUnicode))add(String.fromCharCode(parseInt(this.scanUnicode.slice(1),16)));this.scanUnicode='';}continue;}if(this.scanEscape){this.scanEscape=false;if(c==='u')this.scanUnicode='u';else add(({n:'\n',r:'\r',t:'\t'} as Record<string,string>)[c]??c);continue;}if(c==='"'){this.scanString=!this.scanString;this.scanTail='';}else if(this.scanString&&c==='\\')this.scanEscape=true;}}
 push(bytes:Buffer):void{const text=this.decoder.write(bytes);this.scanMarkers(text);const special=/["\\\x00-\x1f]/g;let at=0;while(at<text.length&&!this.error){if(this.mode==='string'&&!this.escape&&!this.unicode){special.lastIndex=at;const hit=special.exec(text),end=hit?.index??text.length;if(end>at)this.add(text.slice(at,end));at=end;if(at>=text.length)break;}this.char(text[at++]!);}}
 finish():{record:Record<string,unknown>|null;code:string|null;exclusionMarker:boolean}{for(const c of this.decoder.end())this.char(c);if(this.mode==='number'||this.mode==='literal')this.scalarEnd();if(this.mode!=='idle'||this.frames.length||!this.done)this.fail();if(!this.error&&(!this.root||typeof this.root!=='object'||Array.isArray(this.root)))this.fail();if(!this.error&&this.imageBodies.length){const root=this.root as Record<string,unknown>,payload=root.payload as Record<string,unknown>|undefined;for(const body of this.imageBodies){if(root.type==='response_item'&&(payload?.type==='custom_tool_call_output'||payload?.type==='function_call_output')&&(body.frame.value as Record<string,unknown>|null)?.type==='input_image')continue;if(body.overflow)this.fail('native_metadata_bytes_limit');else Object.defineProperty(body.frame.value!,'image_url',{value:body.chunks.join(''),writable:true,enumerable:true,configurable:true});}}if(!this.error&&Buffer.byteLength(JSON.stringify(this.root))>this.maxBytes)this.fail('native_metadata_bytes_limit');return {record:this.error?null:this.root as Record<string,unknown>,code:this.error,exclusionMarker:this.marker};}
}
