import {describe,it,expect,vi} from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createAuditSession} from '../packages/core/src/analytics/index.js';
import {auditFixture,promptFixture,evidenceFixture} from './audit-ui/fixture.js';
import {auditCellWidth} from '../packages/cli/src/audit-ui/index.js';
import {buildLaunchScreen,createLaunchNavigation,launchRows,launchMove,launchPush,launchBack,launchSelectSection,launchFreeze,renderLaunchPlain,runLaunchTerminal,LAUNCH_SECTIONS} from '../packages/cli/src/audit-ui/launch-terminal.js';
import type {LaunchNavigation} from '../packages/cli/src/audit-ui/launch-terminal.js';
import type {AuditSession,AuditSnapshot} from '../packages/core/src/analytics/contracts.js';
function fixture():AuditSnapshot {
 const snapshot=auditFixture();snapshot.scope.eventFrom=null;snapshot.status='ready';snapshot.projects[0]!.displayName='Potsherd 界 👩‍💻';
 const model={id:'model-1',provider:'example-native',model:'native-id',canonicalModel:'Canonical Model',inputTokens:1000,outputTokens:500,totalTokens:1500,conversations:3,tokenShare:.75,conversationShare:.5,favouriteScore:.625,valueUsd:12.5,referenceValueUsd:null,gaps:[]};
 snapshot.launch={stage:'ready',notice:'Conversation text goes to Example relay, OpenCode and TypeSafe/Jev. Esc cancels.',facts:{records:[],models:[model,{...model,id:'model-2',model:null,canonicalModel:null,totalTokens:null,tokenShare:null,valueUsd:null}],favourite:model,valueUsd:12.5,referenceValueUsd:null,pricing:{retrievedAt:'2026-10-07T00:00:00Z',sha256:'abcdef1234567890abcdef',source:'https://models.dev'},recordedResponses:5,knownTokenResponses:4,pricedResponses:3,referencePricedResponses:0,equivalentPricedResponses:3,referenceProviders:[],unknownModelResponses:1,gaps:['usage_incomplete']},semantics:{state:'complete',recipientNotice:'Example relay, OpenCode and TypeSafe/Jev',model:'jev-free',window:{selected:{period:7,from:'2026-09-30T00:00:00Z',until:'2026-10-07T00:00:00Z',segments:2,estimatedInputTokens:1200,estimatedLatencyMs:2400,fits:true,reason:null},choices:[{period:45,from:'2026-08-23T00:00:00Z',until:'2026-10-07T00:00:00Z',segments:20,estimatedInputTokens:120000,estimatedLatencyMs:16000,fits:false,reason:'token_limit'},{period:7,from:'2026-09-30T00:00:00Z',until:'2026-10-07T00:00:00Z',segments:2,estimatedInputTokens:1200,estimatedLatencyMs:2400,fits:true,reason:null},{period:'all',from:null,until:'2026-10-07T00:00:00Z',segments:25,estimatedInputTokens:150000,estimatedLatencyMs:21000,fits:false,reason:'token_limit'}],tokenLimit:100000,reason:'45 days exceeds allowance'},stories:[{id:'story-1',conversationId:'conversation-0',project:'Potsherd',intent:'bug_fix',outcome:'supported',caption:'Fixed the renderer clipping',quote:'the tests pass',promptIds:['prompt-0'],confidence:.9}],hallOfFame:[{id:'hall-1',conversationId:'conversation-0',project:'Potsherd',intent:'tests',outcome:'assistant_reported',caption:'A memorable test request',quote:'make sure tests pass',promptIds:['prompt-0'],confidence:.8}],work:[{label:'bug_fix',count:3},{label:'tests',count:1}],tone:'witty',judgments:[],attempts:2,cacheHits:0,inputTokens:1200,outputTokens:30,gaps:[]}};
 snapshot.profanity={lexiconVersion:'test',language:'en-explicit-lexicon',measurementBasis:'direct native user',eligiblePrompts:15,occurrences:{...snapshot.metrics.humanPrompts,value:5},containingPrompts:{...snapshot.metrics.humanPrompts,value:2},buckets:[{kind:'direct_prose',occurrences:2,containingPrompts:1},{kind:'quoted',occurrences:3,containingPrompts:1}],coverageGaps:[],matches:[{term:'damn',kind:'direct_prose',promptId:'prompt-0',conversationId:'conversation-0',startUtf16:0,endUtf16:4,route:promptFixture().prompts[0]!.route},{term:'quoted-sentinel',kind:'quoted',promptId:'prompt-1',conversationId:'conversation-0',startUtf16:0,endUtf16:4,route:promptFixture().prompts[1]!.route}]};
 return snapshot;
}
const text=(snapshot:AuditSnapshot,nav=createLaunchNavigation(),columns=120,rows=40)=>buildLaunchScreen(snapshot,nav,{columns,rows}).map(line=>line.map(segment=>segment.text).join('')).join('\n');
describe('consumer launch wall',()=>{
 it('renders recorded facts, real names and evidence-bound semantics with independent time scopes',()=>{const output=text(fixture());expect(output).toContain('$12.50');expect(output).toContain('recorded API-equivalent');expect(output).toContain('All-time · 1,500 known tokens · 517 main chats');expect(output).not.toContain('abcdef123456');expect(output).not.toContain('50/50');expect(output).not.toContain('Current catalog');expect(output).toContain('75% known tokens · 3 usage chats');const models=text(fixture(),createLaunchNavigation('models'));expect(models).toContain('3/5 responses valued');expect(models).toContain('2026-10-07T00:00:00Z');expect(models).toContain('abcdef1234567890abcdef');expect(models).toContain('50/50');expect(output).toContain('Potsherd 界 👩‍💻');expect(output).toContain('7 days');expect(output).toContain('YOUR LANGUAGE  “damn” · 2 direct-use matches');expect(output).not.toContain('quoted-sentinel');expect(output).toContain('make sure tests pass');expect(output).toContain('assistant reports success');});
 it('labels reference value and provider uncertainty while preserving compact focus',()=>{const snapshot=fixture(),facts=snapshot.launch!.facts!;facts.valueUsd=null;facts.referenceValueUsd=4;facts.referencePricedResponses=3;facts.referenceProviders=[{provider:'Anthropic',model:'claude-opus-4-6',basis:'approved_first_party_reference',pricedResponses:3,valueUsd:4}];facts.models=[{...facts.models[0]!,provider:null,model:'claude-opus-4-6',canonicalModel:'Claude Opus 4.6',knownTokens:900,totalTokens:null,valueUsd:null,referenceValueUsd:4}];facts.favourite=facts.models[0]!;facts.knownTokenResponses=3;snapshot.launch!.semantics!.window.selected!.selection={kind:'newest_episodes',segmentIds:['episode-1'],available:57,selected:4,eventFrom:'2026-09-08T10:11:12.000Z',eventTo:'2026-09-08T10:21:12.000Z',gaps:['partial_calendar_coverage']};for(const [columns,rows] of [[80,24],[40,20]] as const){const output=text(snapshot,createLaunchNavigation(),columns,rows);expect(output).toContain('$4.00');expect(output).toContain('Anthropic first-party reference');expect(output).toContain('Actual provider unknown for reference');expect(output).toContain('900 known tokens');expect(output).toContain('517 main chats');expect(output).toContain('4/57 episodes · Sep 8 · partial');expect(output).toContain('HALL');expect(output).not.toContain('45 days');expect(output).not.toContain('abcdef');expect(output.match(/Coverage:/g)).toHaveLength(1);}const model=text(snapshot,{...createLaunchNavigation('models'),view:'detail',detailId:facts.favourite.id});expect(model).toContain('900 known tokens · total unknown');expect(model).toContain('first-party reference $4.00');expect(model).toContain('Native endpoint: unknown');expect(model).toContain('SHA-256 abcdef1234567890abcdef');const periods=text(snapshot,launchPush(createLaunchNavigation('work'),{view:'periods'}));expect(periods).toContain('2026-09-08T10:11:12.000Z');expect(periods.replace(/\s+/g,' ')).toContain('partial calendar coverage');expect(periods).not.toContain('7 days · selected');});
 it('does not turn an unknown token total into a decorative zero',()=>{const snapshot=fixture(),facts=snapshot.launch!.facts!;facts.knownTokenResponses=0;facts.models=[{...facts.models[0]!,knownTokens:0,totalTokens:null}];expect(text(snapshot)).toContain('unknown known tokens');facts.knownTokenResponses=1;facts.models[0]!.totalTokens=0;expect(text(snapshot)).toContain('0 known tokens');});
 it('uses only source-backed Hall lines and curated tone headers',()=>{const snapshot=fixture();snapshot.launch!.semantics!.hallOfFame=[{...snapshot.launch!.semantics!.hallOfFame[0]!,quote:null,caption:'Invented hall sentinel',promptIds:[]}];expect(text(snapshot)).not.toContain('Invented hall sentinel');expect(text(snapshot)).not.toContain('no supported selection');for(const [tone,caption] of [['elegant','your recorded work'],['witty','the receipts'],['chaotic','the session pile'],['roast','receipts, served cold']] as const){snapshot.launch!.semantics!.tone=tone;expect(text(snapshot)).toContain(caption);}});
 it('brands every terminal geometry Slopie while preserving recorded project names',()=>{const snapshot=fixture();for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const){for(const ascii of [true,false]){const screen=buildLaunchScreen(snapshot,createLaunchNavigation(),{columns,rows,ascii});const output=screen.map(line=>line.map(segment=>segment.text).join('')).join('\n');expect(output).toContain('SLOPIE');expect(output).not.toContain('POTSHERD');expect(output).toContain('Potsherd 界 👩‍💻');for(const line of screen)expect(auditCellWidth(line.map(segment=>segment.text).join(''))).toBeLessThanOrEqual(columns);}}});
 it('keeps unknown usage distinct from observed zero and unavailable semantics distinct from pending',()=>{const snapshot=fixture();snapshot.launch!.facts!.valueUsd=null;snapshot.launch!.facts!.favourite=null;snapshot.launch!.semantics!.state='unavailable';snapshot.launch!.semantics!.work=[];snapshot.launch!.semantics!.stories=[];snapshot.launch!.semantics!.hallOfFame=[];expect(text(snapshot)).toContain('unknown  recorded API-equivalent');expect(text(snapshot)).not.toContain('$0.00');expect(text(snapshot)).toContain('Analysis unavailable after attempted requests');expect(text(snapshot,createLaunchNavigation('work'))).toContain('Local results remain available');snapshot.launch!.facts!.valueUsd=0;expect(text(snapshot)).toContain('$0.00');snapshot.launch!.semantics!.state='pending';snapshot.launch!.stage='analyzing';expect(text(snapshot,createLaunchNavigation('work'))).toContain('Analysis pending');});
 it('shows the actual launch notice and source pipeline without an extra consent menu',()=>{const snapshot=fixture();snapshot.launch!.facts=null;snapshot.launch!.stage='preparing';snapshot.status='parsing';snapshot.launch!.semantics!.state='pending';const output=text(snapshot);expect(output).toContain('Example relay, OpenCode and TypeSafe/Jev');expect(output).toContain('Codex');expect(output).toContain('preparing');expect(output).not.toContain('Press Enter');expect(output).not.toContain('Send selected');expect(output).not.toContain('50% complete');});
 it('exposes all real period estimates and the selected analyzed scope',()=>{const snapshot=fixture(),nav=launchPush(createLaunchNavigation('work'),{view:'periods'});const output=text(snapshot,nav);expect(output).toContain('120,000 input tokens');expect(output).toContain('16.0s estimate');expect(output).toContain('does not fit');expect(output).toContain('7 days · selected');expect(output).toContain('All available history');expect(output).toContain('100,000 total input tokens');expect(output).toContain('remaining allowance');});
 for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const)it(`fits ${columns}×${rows} across sections, detail and source views`,()=>{const snapshot=fixture();for(const section of LAUNCH_SECTIONS){for(const view of ['section','detail','prompts','evidence','periods'] as const){const nav:LaunchNavigation={...createLaunchNavigation(section),view,detailId:section==='models'?'model-1':section==='work'?'story-1':section==='hall'?'hall-1':'language:0',conversationId:'conversation-0'};for(const ascii of [false,true]){const screen=buildLaunchScreen(snapshot,nav,{columns,rows,ascii,promptPage:promptFixture(),evidence:evidenceFixture()});expect(screen).toHaveLength(rows);for(const line of screen)expect(auditCellWidth(line.map(segment=>segment.text).join(''))).toBeLessThanOrEqual(columns);}}}});
 it('clips terminal controls from every screen including native source bodies',()=>{const snapshot=fixture();snapshot.projects[0]!.displayName='evil\x1b[2J\x1b]0;title\x07 safe';const output=text(snapshot);expect(output).not.toContain('\x1b');const screen=buildLaunchScreen(snapshot,{...createLaunchNavigation(),view:'evidence'},{evidence:{...evidenceFixture(),text:'secret\x1b[2J\nnext line'},columns:40,rows:20});expect(screen.flat().map(segment=>segment.text).join('')).not.toContain('\x1b');});
 it('does not turn stale or missing evidence into a source quote',()=>{const nav={...createLaunchNavigation('hall'),view:'evidence' as const};expect(buildLaunchScreen(fixture(),nav,{evidence:evidenceFixture('stale')}).flat().map(segment=>segment.text).join(' ')).toContain('Source changed');expect(buildLaunchScreen(fixture(),nav,{evidence:evidenceFixture('unavailable')}).flat().map(segment=>segment.text).join(' ')).not.toContain('PRIVATE_EXACT_TEXT');});
 it('uses actual counts for graph widths',()=>{const snapshot=fixture();const output=text(snapshot,createLaunchNavigation('work'));expect(output).toContain('3 segments');expect(output).toContain('1 segments');snapshot.launch!.semantics!.work=[{label:'tests',count:0}];expect(text(snapshot,createLaunchNavigation('work'))).toContain('0 segments');});
 it('preserves selection and return context while resize and freeze change presentation',()=>{const snapshot=fixture();let nav=createLaunchNavigation('projects');nav=launchMove(nav,launchRows(snapshot,nav),2,2);const selected=nav.selectedId;const detail=launchPush(nav,{view:'detail',detailId:selected});expect(launchBack(detail)).toEqual(nav);const frozen=launchFreeze(nav);expect(frozen.selectedId).toBe(selected);expect(frozen.scroll).toBe(nav.scroll);expect(text(snapshot,frozen,40,20)).toContain('FROZEN');expect(launchFreeze(frozen)).toEqual(nav);expect(launchSelectSection(nav,1).section).toBe('work');expect(launchSelectSection(createLaunchNavigation(),-1).section).toBe('timeline');});
 it('keeps the selected row visible after resizing and scrolling a dense section',()=>{const snapshot=fixture(),rows=Array.from({length:30},(_,index)=>({...snapshot.projects[0]!,id:`project-${index}`,displayName:`Named project ${index}`}));snapshot.projects=rows;let nav=createLaunchNavigation('projects');nav=launchMove(nav,launchRows(snapshot,nav),28,8);for(const [columns,height] of [[120,40],[80,24],[40,20]] as const){expect(text(snapshot,nav,columns,height)).toContain('Named project 28');expect(text(snapshot,nav,columns,height)).toContain('↑/↓ scroll');}expect(text(snapshot,launchFreeze(nav),40,20)).toContain('Named project 28');});
 it('handles empty lists and scroll boundaries without inventing rows',()=>{const snapshot=fixture();snapshot.launch!.facts!.models=[];const nav=createLaunchNavigation('models');expect(launchMove(nav,launchRows(snapshot,nav),1,3).selectedId).toBeNull();const projectNav=createLaunchNavigation('projects');const first=launchMove(projectNav,launchRows(snapshot,projectNav),-100,2),last=launchMove(first,launchRows(snapshot,projectNav),100,2);expect(first.selectedIndex).toBe(0);expect(last.selectedIndex).toBe(snapshot.projects.length-1);expect(last.scroll).toBe(2);});
 it('offers plain output without loading Ink or reading source bodies',async()=>{const snapshot=fixture(),run=vi.fn(async()=>snapshot),prompts=vi.fn(),session={run,snapshot:()=>snapshot,prompts,cancel:vi.fn(),dispose:vi.fn(),evidence:vi.fn(),classify:vi.fn()} as unknown as AuditSession;const result=await runLaunchTerminal(session);expect(result.reason).toBe('complete');expect(run).toHaveBeenCalledOnce();expect(prompts).not.toHaveBeenCalled();expect(renderLaunchPlain(result.snapshot,{ascii:true})).toContain('SLOPIE');});
});


function unanalysedFixture(codes:readonly string[]=[],retainFacts=false):AuditSnapshot {
 const snapshot=fixture();snapshot.status='partial';snapshot.launch!.stage='ready';snapshot.coverage.gapCodes=[...codes];
 if(!retainFacts){snapshot.launch!.facts=null;snapshot.projects=[];snapshot.conversations=[];snapshot.activity=[];snapshot.profanity=undefined;for(const metric of Object.values(snapshot.metrics)){metric.value=null;metric.state='unavailable';}}
 const sem=snapshot.launch!.semantics!;sem.state='unavailable';sem.attempts=0;sem.cacheHits=0;sem.stories=[];sem.hallOfFame=[];sem.work=[];sem.window={selected:null,choices:[],tokenLimit:100000,reason:null};sem.gaps=[...codes];return snapshot;
}
const flattened=(value:string)=>value.replace(/\s+/g,' ');
describe('launch local-loading and failure messages',()=>{
 const cases:readonly [string,string,string][]=[
  ['audit_sqlite_rollback_journal_unavailable','Local SQLite rollback journal is active','writer finish'],
  ['audit_sqlite_live_journal_unavailable','Local SQLite journal blocks safe reading','writer finish'],
  ['audit_sqlite_snapshot_stale','Local SQLite snapshot changed','writes settle'],
  ['audit_snapshot_stale','Local history changed during this audit','Run slopie audit again'],
  ['audit_sqlite_snapshot_byte_limit','Archive exceeds snapshot limit','archive size'],
  ['audit_sqlite_snapshot_disk_limit','Not enough free space for a safe snapshot','Free local disk space'],
  ['audit_sqlite_wal_index_unavailable','Local WAL commit boundary is unavailable','writer finish'],
  ['audit_sqlite_wal_integrity_unavailable','Local WAL committed data failed integrity checks','owned backup'],
  ['audit_sqlite_snapshot_time_limit','Local SQLite snapshot timed out','database activity settles'],
  ['audit_sqlite_format_unavailable','Local store is not readable SQLite','store path'],
  ['audit_sqlite_wal_header_unavailable','Local WAL snapshot failed integrity checks','writes settle'],
  ['audit_sqlite_wal_incomplete_tail','Local WAL snapshot is incomplete','writer finish'],
  ['audit_sqlite_snapshot_corrupt','Local SQLite snapshot failed integrity checks','owned backup'],
  ['ignore_policy_unavailable','Local ignore settings could not be read','ignore settings'],
  ['store_policy_unavailable','Local history policy could not be read','store access'],
  ['privacy_refresh_required','Local history needs a privacy refresh','privacy normalization'],
 ];
 it.each(cases)('explains %s as a local issue with an action and no fabricated provider failure',(code,reason,action)=>{
  const snapshot=unanalysedFixture(['store_policy_unavailable',code,'raw_lane_policy_hold']);
  for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const){for(const ascii of [false,true]){for(const section of ['overview','work','hall'] as const){const screen=buildLaunchScreen(snapshot,createLaunchNavigation(section),{columns,rows,ascii}),output=flattened(screen.map(line=>line.map(segment=>segment.text).join('')).join(' '));expect(output).toContain(reason);expect(output).toContain(action);expect(output).toContain('No analysis requests made');expect(output).not.toMatch(/Jev (?:route )?unavailable|window pending|Analysis pending/);expect(screen).toHaveLength(rows);for(const line of screen)expect(auditCellWidth(line.map(segment=>segment.text).join(''))).toBeLessThanOrEqual(columns);}}
  }
  const periods=flattened(text(snapshot,launchPush(createLaunchNavigation('work'),{view:'periods'})));expect(periods).toContain(reason);expect(periods).not.toContain('Enter uses');expect(periods).toContain('No period estimates are available');
 });
 it('keeps provider quota exhaustion distinct and retains local facts and navigation',()=>{const snapshot=unanalysedFixture(['free_quota_unavailable'],true),sem=snapshot.launch!.semantics!;sem.attempts=1;sem.window.selected=fixture().launch!.semantics!.window.selected;for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const){const output=flattened(text(snapshot,createLaunchNavigation(),columns,rows));expect(output).toContain('$12.50');expect(output).toContain('known tokens');expect(output).toContain('main chats');expect(output).toContain('Jev quota exhausted');expect(output).not.toContain('No analysis requests made');expect(output).not.toContain('Local history policy');}const work=text(snapshot,createLaunchNavigation('work'));expect(work).toContain('Retry when free capacity returns');expect(work).not.toContain('window pending');});
 it('does not claim a provider failure from a zero-attempt unavailable snapshot',()=>{const snapshot=unanalysedFixture(['free_quota_unavailable'],true);const output=flattened(text(snapshot,createLaunchNavigation('work')));expect(output).toContain('Analysis not run');expect(output).toContain('No analysis requests made');expect(output).not.toContain('Jev quota exhausted');expect(output).not.toContain('Jev unavailable');expect(output).not.toContain('quota');});
 it('distinguishes genuine preparation from a settled incomplete run',()=>{const snapshot=unanalysedFixture();snapshot.status='parsing';snapshot.launch!.stage='preparing';snapshot.launch!.semantics!.state='pending';expect(text(snapshot,createLaunchNavigation('work'))).toContain('Work window is being prepared');expect(text(snapshot,createLaunchNavigation('work'))).toContain('Analysis pending');snapshot.status='error';snapshot.launch!.stage='ready';for(const nav of [createLaunchNavigation(),createLaunchNavigation('work'),launchPush(createLaunchNavigation('work'),{view:'periods'})]){const output=text(snapshot,nav);expect(output).not.toMatch(/window pending|Analysis pending|being prepared/);expect(output).toContain('Audit did not finish');}});
 it('renders a completed empty scope without promising a later window or a provider outage',()=>{const snapshot=unanalysedFixture();snapshot.status='ready';snapshot.coverage.state='complete_snapshot';snapshot.metrics.humanPrompts.value=0;snapshot.metrics.humanPrompts.state='observed';for(const nav of [createLaunchNavigation(),createLaunchNavigation('work')]){const output=text(snapshot,nav);expect(output).toContain('No eligible user input in this scope');expect(output).not.toMatch(/pending|Jev unavailable|Jev route unavailable/);}});
 it('labels offline preparation with zero requests while keeping populated local facts',()=>{const snapshot=unanalysedFixture(['offline_requested'],true);expect(text(snapshot)).toContain('$12.50');expect(text(snapshot)).toContain('Offline mode');expect(text(snapshot,createLaunchNavigation('work'))).toContain('No analysis requests made');expect(text(snapshot)).not.toMatch(/Jev unavailable|window pending/);});
 it('shows the actual offline session result for malformed policy, corrupt SQLite and empty native roots',async()=>{
  const parent=fs.mkdtempSync(path.join(os.tmpdir(),'slopie-terminal-local-')),fetch=vi.spyOn(globalThis,'fetch').mockRejectedValue(new Error('network forbidden')),sessions:AuditSession[]=[];vi.stubEnv('POTSHERD_OFFLINE','1');
  try{for(const kind of ['policy','sqlite','empty','native'] as const){const root=path.join(parent,kind),store=path.join(root,'owned');fs.mkdirSync(store,{recursive:true});if(kind==='policy')fs.writeFileSync(path.join(store,'config.json'),'invalid policy JSON');if(kind==='sqlite')fs.writeFileSync(path.join(store,'potsherd.db'),Buffer.alloc(256,88));if(kind==='native'){const file=path.join(root,'claude','projects','public-fixture','session.jsonl');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,[{type:'user',sessionId:'public-session',uuid:'u',promptId:'u',cwd:'/public-fixture/export',timestamp:'2026-10-07T05:00:00Z',message:{role:'user',content:'Please repair the public fixture export.'}},{type:'assistant',sessionId:'public-session',uuid:'a',cwd:'/public-fixture/export',timestamp:'2026-10-07T05:01:00Z',message:{id:'a',role:'assistant',model:'claude-sonnet-4-6',provider:'anthropic',content:'The export tests passed.',usage:{input_tokens:1000,output_tokens:200,cache_read_input_tokens:0,cache_creation_input_tokens:0}}}].map(row=>JSON.stringify(row)).join('\n')+'\n');}const session=createAuditSession({potsherdDir:store,claudeDir:path.join(root,'claude'),codexDir:path.join(root,'codex'),piDir:path.join(root,'pi'),opencodeDir:path.join(root,'opencode'),launch:true,launchPrepareOnly:true});sessions.push(session);expect(text(session.snapshot(),createLaunchNavigation('work'))).toContain('Work window is being prepared');const snapshot=await session.run(),output=flattened(text(snapshot));expect(snapshot.launch!.stage).toBe('ready');expect(snapshot.launch!.semantics!.attempts).toBe(0);expect(output).not.toMatch(/pending|Jev unavailable|Jev route unavailable/);if(kind==='policy'){expect(snapshot.coverage.gapCodes).toContain('ignore_policy_unavailable');expect(output).toContain('Local ignore settings could not be read');expect(output).toContain('No analysis requests made');}else if(kind==='sqlite'){expect(snapshot.coverage.gapCodes).toContain('store_policy_unavailable');expect(output).toMatch(/Local store is not readable SQLite|Local history policy could not be read/);expect(output).toContain('No analysis requests made');}else if(kind==='native'){expect(snapshot.launch!.facts!.recordedResponses).toBe(1);expect(snapshot.launch!.facts!.knownTokenResponses).toBe(1);expect(output).toContain('1,200 known tokens');expect(output).toContain('1 main chats');expect(output).toContain('Preparation only');expect(output).not.toContain('Jev quota exhausted');}else{expect(snapshot.metrics.humanPrompts.value).toBe(0);expect(output).toContain('No eligible user input in this scope');}}expect(fetch).not.toHaveBeenCalled();}
  finally{sessions.forEach(session=>session.dispose());fs.rmSync(parent,{recursive:true,force:true});fetch.mockRestore();vi.unstubAllEnvs();}
 });
});
