import {describe,it,expect,vi} from 'vitest';
import {auditFixture,promptFixture,evidenceFixture} from './audit-ui/fixture.js';
import {auditCellWidth} from '../packages/cli/src/audit-ui/index.js';
import {buildLaunchScreen,createLaunchNavigation,launchRows,launchMove,launchPush,launchBack,launchSelectSection,launchFreeze,renderLaunchPlain,runLaunchTerminal,LAUNCH_SECTIONS} from '../packages/cli/src/audit-ui/launch-terminal.js';
import type {LaunchNavigation} from '../packages/cli/src/audit-ui/launch-terminal.js';
import type {AuditSession,AuditSnapshot} from '../packages/core/src/analytics/contracts.js';
function fixture():AuditSnapshot {
 const snapshot=auditFixture();snapshot.scope.eventFrom=null;snapshot.status='ready';snapshot.projects[0]!.displayName='Potsherd 界 👩‍💻';
 const model={id:'model-1',provider:'example-native',model:'native-id',canonicalModel:'Canonical Model',inputTokens:1000,outputTokens:500,totalTokens:1500,conversations:3,tokenShare:.75,conversationShare:.5,favouriteScore:.625,valueUsd:12.5,referenceValueUsd:null,gaps:[]};
 snapshot.launch={stage:'ready',notice:'Conversation text goes to Example relay, OpenCode and TypeSafe/Jev. Esc cancels.',facts:{records:[],models:[model,{...model,id:'model-2',model:null,canonicalModel:null,totalTokens:null,tokenShare:null,valueUsd:null}],favourite:model,valueUsd:12.5,referenceValueUsd:null,pricing:{retrievedAt:'2026-10-07T00:00:00Z',sha256:'abcdef1234567890abcdef',source:'https://models.dev'},recordedResponses:5,knownTokenResponses:4,pricedResponses:3,referencePricedResponses:0,equivalentPricedResponses:3,referenceProviders:[],unknownModelResponses:1,gaps:['usage_incomplete']},semantics:{state:'complete',recipientNotice:'Example relay, OpenCode and TypeSafe/Jev',model:'jev-free',window:{selected:{period:7,from:'2026-09-30T00:00:00Z',until:'2026-10-07T00:00:00Z',segments:2,estimatedInputTokens:1200,estimatedLatencyMs:2400,fits:true,reason:null},choices:[{period:45,from:'2026-08-23T00:00:00Z',until:'2026-10-07T00:00:00Z',segments:20,estimatedInputTokens:120000,estimatedLatencyMs:16000,fits:false,reason:'token_limit'},{period:7,from:'2026-09-30T00:00:00Z',until:'2026-10-07T00:00:00Z',segments:2,estimatedInputTokens:1200,estimatedLatencyMs:2400,fits:true,reason:null},{period:'all',from:null,until:'2026-10-07T00:00:00Z',segments:25,estimatedInputTokens:150000,estimatedLatencyMs:21000,fits:false,reason:'token_limit'}],tokenLimit:100000,reason:'45 days exceeds allowance'},stories:[{id:'story-1',conversationId:'conversation-0',project:'Potsherd',intent:'bug_fix',outcome:'supported',caption:'Fixed the renderer clipping',quote:'the tests pass',promptIds:['prompt-0'],confidence:.9}],hallOfFame:[{id:'hall-1',conversationId:'conversation-0',project:'Potsherd',intent:'tests',outcome:'assistant_reported',caption:'A memorable test request',quote:'make sure tests pass',promptIds:['prompt-0'],confidence:.8}],work:[{label:'bug_fix',count:3},{label:'tests',count:1}],tone:'witty',judgments:[],attempts:2,cacheHits:0,inputTokens:1200,outputTokens:30,gaps:[]}};
 snapshot.profanity={lexiconVersion:'test',language:'en-explicit-lexicon',measurementBasis:'direct native user',eligiblePrompts:15,occurrences:{...snapshot.metrics.humanPrompts,value:5},containingPrompts:{...snapshot.metrics.humanPrompts,value:2},buckets:[{kind:'direct_prose',occurrences:2,containingPrompts:1},{kind:'quoted',occurrences:3,containingPrompts:1}],coverageGaps:[],matches:[{term:'damn',kind:'direct_prose',promptId:'prompt-0',conversationId:'conversation-0',startUtf16:0,endUtf16:4,route:promptFixture().prompts[0]!.route},{term:'quoted-sentinel',kind:'quoted',promptId:'prompt-1',conversationId:'conversation-0',startUtf16:0,endUtf16:4,route:promptFixture().prompts[1]!.route}]};
 return snapshot;
}
const text=(snapshot:AuditSnapshot,nav=createLaunchNavigation(),columns=120,rows=40)=>buildLaunchScreen(snapshot,nav,{columns,rows}).map(line=>line.map(segment=>segment.text).join('')).join('\n');
describe('consumer launch wall',()=>{
 it('renders recorded facts, real names and evidence-bound semantics with independent time scopes',()=>{const output=text(fixture());expect(output).toContain('$12.50');expect(output).toContain('recorded API-equivalent');expect(output).toContain('All-time · 1,500 known tokens · 517 chats');expect(output).not.toContain('abcdef123456');expect(output).not.toContain('50/50');expect(output).not.toContain('Current catalog');expect(output).toContain('75% known tokens · 50% chats');const models=text(fixture(),createLaunchNavigation('models'));expect(models).toContain('3/5 responses valued');expect(models).toContain('2026-10-07T00:00:00Z');expect(models).toContain('abcdef1234567890abcdef');expect(models).toContain('50/50');expect(output).toContain('Potsherd 界 👩‍💻');expect(output).toContain('7 days');expect(output).toContain('YOUR LANGUAGE  “damn” · 2 direct-use matches');expect(output).not.toContain('quoted-sentinel');expect(output).toContain('make sure tests pass');expect(output).toContain('assistant reports success');});
 it('labels reference value and provider uncertainty while preserving compact focus',()=>{const snapshot=fixture(),facts=snapshot.launch!.facts!;facts.valueUsd=null;facts.referenceValueUsd=4;facts.referencePricedResponses=3;facts.referenceProviders=[{provider:'Anthropic',model:'claude-opus-4-6',basis:'approved_first_party_reference',pricedResponses:3,valueUsd:4}];facts.models=[{...facts.models[0]!,provider:null,model:'claude-opus-4-6',canonicalModel:'Claude Opus 4.6',knownTokens:900,totalTokens:null,valueUsd:null,referenceValueUsd:4}];facts.favourite=facts.models[0]!;facts.knownTokenResponses=3;snapshot.launch!.semantics!.window.selected!.selection={kind:'newest_episodes',segmentIds:['episode-1'],available:57,selected:4,eventFrom:'2026-09-08T10:11:12.000Z',eventTo:'2026-09-08T10:21:12.000Z',gaps:['partial_calendar_coverage']};for(const [columns,rows] of [[80,24],[40,20]] as const){const output=text(snapshot,createLaunchNavigation(),columns,rows);expect(output).toContain('$4.00');expect(output).toContain('Anthropic first-party reference');expect(output).toContain('Actual provider unknown for reference');expect(output).toContain('900 known tokens');expect(output).toContain('517 chats');expect(output).toContain('4/57 episodes · Sep 8 · partial');expect(output).toContain('HALL');expect(output).not.toContain('45 days');expect(output).not.toContain('abcdef');expect(output.match(/Coverage:/g)).toHaveLength(1);}const model=text(snapshot,{...createLaunchNavigation('models'),view:'detail',detailId:facts.favourite.id});expect(model).toContain('900 known tokens · total unknown');expect(model).toContain('first-party reference $4.00');expect(model).toContain('Native endpoint: unknown');expect(model).toContain('SHA-256 abcdef1234567890abcdef');const periods=text(snapshot,launchPush(createLaunchNavigation('work'),{view:'periods'}));expect(periods).toContain('2026-09-08T10:11:12.000Z');expect(periods.replace(/\s+/g,' ')).toContain('partial calendar coverage');expect(periods).not.toContain('7 days · selected');});
 it('does not turn an unknown token total into a decorative zero',()=>{const snapshot=fixture(),facts=snapshot.launch!.facts!;facts.knownTokenResponses=0;facts.models=[{...facts.models[0]!,knownTokens:0,totalTokens:null}];expect(text(snapshot)).toContain('unknown known tokens');facts.knownTokenResponses=1;facts.models[0]!.totalTokens=0;expect(text(snapshot)).toContain('0 known tokens');});
 it('uses only source-backed Hall lines and curated tone headers',()=>{const snapshot=fixture();snapshot.launch!.semantics!.hallOfFame=[{...snapshot.launch!.semantics!.hallOfFame[0]!,quote:null,caption:'Invented hall sentinel',promptIds:[]}];expect(text(snapshot)).not.toContain('Invented hall sentinel');expect(text(snapshot)).not.toContain('no supported selection');for(const [tone,caption] of [['elegant','your recorded work'],['witty','the receipts'],['chaotic','the session pile'],['roast','receipts, served cold']] as const){snapshot.launch!.semantics!.tone=tone;expect(text(snapshot)).toContain(caption);}});
 it('keeps unknown usage distinct from observed zero and unavailable semantics distinct from pending',()=>{const snapshot=fixture();snapshot.launch!.facts!.valueUsd=null;snapshot.launch!.facts!.favourite=null;snapshot.launch!.semantics!.state='unavailable';snapshot.launch!.semantics!.work=[];snapshot.launch!.semantics!.stories=[];snapshot.launch!.semantics!.hallOfFame=[];expect(text(snapshot)).toContain('unknown  recorded API-equivalent');expect(text(snapshot)).not.toContain('$0.00');expect(text(snapshot)).toContain('Jev route unavailable');expect(text(snapshot,createLaunchNavigation('work'))).toContain('free route has not supplied');snapshot.launch!.facts!.valueUsd=0;expect(text(snapshot)).toContain('$0.00');snapshot.launch!.semantics!.state='pending';expect(text(snapshot,createLaunchNavigation('work'))).toContain('Analysis pending');});
 it('shows the actual launch notice and source pipeline without an extra consent menu',()=>{const snapshot=fixture();snapshot.launch!.facts=null;snapshot.launch!.stage='preparing';snapshot.status='parsing';snapshot.launch!.semantics!.state='pending';const output=text(snapshot);expect(output).toContain('Example relay, OpenCode and TypeSafe/Jev');expect(output).toContain('Codex');expect(output).toContain('preparing');expect(output).not.toContain('Press Enter');expect(output).not.toContain('Send selected');expect(output).not.toContain('50% complete');});
 it('exposes all real period estimates and the selected analyzed scope',()=>{const snapshot=fixture(),nav=launchPush(createLaunchNavigation('work'),{view:'periods'});const output=text(snapshot,nav);expect(output).toContain('120,000 input tokens');expect(output).toContain('16.0s estimate');expect(output).toContain('does not fit');expect(output).toContain('7 days · selected');expect(output).toContain('All available history');expect(output).toContain('100,000 total input tokens');expect(output).toContain('remaining allowance');});
 for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const)it(`fits ${columns}×${rows} across sections, detail and source views`,()=>{const snapshot=fixture();for(const section of LAUNCH_SECTIONS){for(const view of ['section','detail','prompts','evidence','periods'] as const){const nav:LaunchNavigation={...createLaunchNavigation(section),view,detailId:section==='models'?'model-1':section==='work'?'story-1':section==='hall'?'hall-1':'language:0',conversationId:'conversation-0'};for(const ascii of [false,true]){const screen=buildLaunchScreen(snapshot,nav,{columns,rows,ascii,promptPage:promptFixture(),evidence:evidenceFixture()});expect(screen).toHaveLength(rows);for(const line of screen)expect(auditCellWidth(line.map(segment=>segment.text).join(''))).toBeLessThanOrEqual(columns);}}}});
 it('clips terminal controls from every screen including native source bodies',()=>{const snapshot=fixture();snapshot.projects[0]!.displayName='evil\x1b[2J\x1b]0;title\x07 safe';const output=text(snapshot);expect(output).not.toContain('\x1b');const screen=buildLaunchScreen(snapshot,{...createLaunchNavigation(),view:'evidence'},{evidence:{...evidenceFixture(),text:'secret\x1b[2J\nnext line'},columns:40,rows:20});expect(screen.flat().map(segment=>segment.text).join('')).not.toContain('\x1b');});
 it('does not turn stale or missing evidence into a source quote',()=>{const nav={...createLaunchNavigation('hall'),view:'evidence' as const};expect(buildLaunchScreen(fixture(),nav,{evidence:evidenceFixture('stale')}).flat().map(segment=>segment.text).join(' ')).toContain('Source changed');expect(buildLaunchScreen(fixture(),nav,{evidence:evidenceFixture('unavailable')}).flat().map(segment=>segment.text).join(' ')).not.toContain('PRIVATE_EXACT_TEXT');});
 it('uses actual counts for graph widths',()=>{const snapshot=fixture();const output=text(snapshot,createLaunchNavigation('work'));expect(output).toContain('3 segments');expect(output).toContain('1 segments');snapshot.launch!.semantics!.work=[{label:'tests',count:0}];expect(text(snapshot,createLaunchNavigation('work'))).toContain('0 segments');});
 it('preserves selection and return context while resize and freeze change presentation',()=>{const snapshot=fixture();let nav=createLaunchNavigation('projects');nav=launchMove(nav,launchRows(snapshot,nav),2,2);const selected=nav.selectedId;const detail=launchPush(nav,{view:'detail',detailId:selected});expect(launchBack(detail)).toEqual(nav);const frozen=launchFreeze(nav);expect(frozen.selectedId).toBe(selected);expect(frozen.scroll).toBe(nav.scroll);expect(text(snapshot,frozen,40,20)).toContain('FROZEN');expect(launchFreeze(frozen)).toEqual(nav);expect(launchSelectSection(nav,1).section).toBe('work');expect(launchSelectSection(createLaunchNavigation(),-1).section).toBe('timeline');});
 it('keeps the selected row visible after resizing and scrolling a dense section',()=>{const snapshot=fixture(),rows=Array.from({length:30},(_,index)=>({...snapshot.projects[0]!,id:`project-${index}`,displayName:`Named project ${index}`}));snapshot.projects=rows;let nav=createLaunchNavigation('projects');nav=launchMove(nav,launchRows(snapshot,nav),28,8);for(const [columns,height] of [[120,40],[80,24],[40,20]] as const){expect(text(snapshot,nav,columns,height)).toContain('Named project 28');expect(text(snapshot,nav,columns,height)).toContain('↑/↓ scroll');}expect(text(snapshot,launchFreeze(nav),40,20)).toContain('Named project 28');});
 it('handles empty lists and scroll boundaries without inventing rows',()=>{const snapshot=fixture();snapshot.launch!.facts!.models=[];const nav=createLaunchNavigation('models');expect(launchMove(nav,launchRows(snapshot,nav),1,3).selectedId).toBeNull();const projectNav=createLaunchNavigation('projects');const first=launchMove(projectNav,launchRows(snapshot,projectNav),-100,2),last=launchMove(first,launchRows(snapshot,projectNav),100,2);expect(first.selectedIndex).toBe(0);expect(last.selectedIndex).toBe(snapshot.projects.length-1);expect(last.scroll).toBe(2);});
 it('offers plain output without loading Ink or reading source bodies',async()=>{const snapshot=fixture(),run=vi.fn(async()=>snapshot),prompts=vi.fn(),session={run,snapshot:()=>snapshot,prompts,cancel:vi.fn(),dispose:vi.fn(),evidence:vi.fn(),classify:vi.fn()} as unknown as AuditSession;const result=await runLaunchTerminal(session);expect(result.reason).toBe('complete');expect(run).toHaveBeenCalledOnce();expect(prompts).not.toHaveBeenCalled();expect(renderLaunchPlain(result.snapshot,{ascii:true})).toContain('POTSHERD');});
});
