import type {AuditSnapshot} from '../packages/core/src/analytics/contracts.js';
import {auditFixture,promptFixture} from './audit-ui/fixture.js';
export function reportFixture():AuditSnapshot{
 const snapshot=auditFixture();snapshot.status='ready';snapshot.scope.eventFrom=null;snapshot.coverage={...snapshot.coverage,state:'partial',gapCodes:['usage_partial']};snapshot.progress={...snapshot.progress,stage:'ready',cancellable:false};snapshot.metrics.nativeUserInputs={...snapshot.metrics.humanPrompts,value:13204,measurementBasis:'observed_native_role'};
 snapshot.projects=snapshot.projects.slice(0,3).map((project,i)=>({...project,displayName:['Rotor Notes','Tide Tracker','Orchard Portal'][i]!}));snapshot.metrics.projects.value=3;
 const models=[['model-a','Claude Sonnet 4.6',7500,12.5,3,.75,.5],['model-b','GPT-5',2000,4,2,.2,.333],['model-c','Á CJK 界 👩‍💻 model',500,null,1,.05,.167]] as const;
 snapshot.launch={notice:'Old constructor notice must never announce a transfer.',stage:'ready',facts:{records:[],models:models.map(([id,model,tokens,value,conversations,tokenShare,conversationShare])=>({id,provider:'recorded-provider',model,canonicalModel:model,inputTokens:tokens,outputTokens:0,totalTokens:tokens,knownTokens:tokens,conversations,tokenShare,conversationShare,favouriteScore:(tokenShare+conversationShare)/2,valueUsd:value,referenceValueUsd:null,gaps:[]})),favourite:null,valueUsd:16.5,referenceValueUsd:null,recordedResponses:6,knownTokenResponses:5,pricedResponses:5,equivalentPricedResponses:5,referencePricedResponses:0,referenceProviders:[],unknownModelResponses:1,pricing:{retrievedAt:'2026-10-08T00:00:00Z',sha256:'pricing-sha-sentinel',source:'https://models.dev/private-sentinel'},gaps:['partial_pricing']},semantics:{state:'complete',recipientNotice:'Do not announce recipients without a transfer.',model:'jev-1.13-free',window:{selected:{period:7,from:'2026-10-01T00:00:00Z',until:'2026-10-08T00:00:00Z',segments:4,estimatedInputTokens:2000,estimatedLatencyMs:500,fits:true,reason:null},choices:[],tokenLimit:100000,reason:null},stories:[{id:'supported-story',conversationId:'conversation-0',project:'Rotor Notes',intent:'bug_fix',outcome:'supported',caption:'Fixed the export clipping',quote:'make the export fit',promptIds:['prompt-0'],confidence:.9},{id:'unsupported-story',conversationId:'conversation-1',project:'Tide Tracker',intent:'feature_build',outcome:'uncertain',caption:'Uncertain filler sentinel',quote:null,promptIds:['prompt-1'],confidence:.2}],hallOfFame:[{id:'quote-1',conversationId:'conversation-0',project:'Rotor Notes',intent:'tests',outcome:'attempted',caption:'A test request',quote:'make sure tests pass',promptIds:['prompt-0'],confidence:.85},{id:'quote-2',conversationId:'conversation-1',project:'Tide Tracker',intent:'code_review',outcome:'assistant_reported',caption:'A review request',quote:'show the evidence before calling it done',promptIds:['prompt-1'],confidence:.8}],work:[{label:'bug_fix',count:3},{label:'tests',count:1}],judgments:[{segmentId:'segment-1',conversationId:'conversation-0',model:'jev',answers:{},contentHash:'hash',questionVersion:'q1'}],tone:'witty',attempts:0,cacheHits:4,inputTokens:0,outputTokens:0,gaps:[]}};
 snapshot.launch.facts!.favourite=snapshot.launch.facts!.models[0]!;
 const route=promptFixture().prompts[0]!.route;
 snapshot.profanity={lexiconVersion:'fixture',language:'en-explicit-lexicon',measurementBasis:'full_eligible_direct_prose',eligiblePrompts:100,occurrences:{...snapshot.metrics.humanPrompts,value:16},containingPrompts:{...snapshot.metrics.humanPrompts,value:10},buckets:[{kind:'direct_prose',occurrences:13,containingPrompts:8},{kind:'quoted',occurrences:3,containingPrompts:2}],coverageGaps:[],matches:Array.from({length:8},(_,i)=>({term:'damn',kind:'direct_prose',promptId:`prompt-${i}`,conversationId:'conversation-0',startUtf16:0,endUtf16:4,route})),terms:[{term:'damn',kind:'direct_prose',occurrences:5,containingPrompts:4,models:[{provider:'a',model:'GPT-5',occurrences:3},{provider:'b',model:'Claude Sonnet 4.6',occurrences:2}],samples:[{promptId:'prompt-0',conversationId:'conversation-0',startUtf16:0,endUtf16:4,route}]},{term:'shit',kind:'direct_prose',occurrences:8,containingPrompts:4,models:[{provider:'b',model:'Claude Sonnet 4.6',occurrences:8}],samples:[]},{term:'quoted-sentinel',kind:'quoted',occurrences:3,containingPrompts:2,samples:[]}]};
 snapshot.projects=snapshot.projects.map((project,index)=>({...project,nativeUserInputs:project.humanPrompts,focus:[{label:['Debugging','Review','Documentation'][index]!,inputs:2,promptIds:['prompt-0'],evidenceRoutes:[route],basis:'lexical_requested_work_v1' as const}]}));
 snapshot.launch.facts!.models.push({...snapshot.launch.facts!.models[0]!,id:'model-d',model:'Gemini 2.5 Flash',canonicalModel:'Gemini 2.5 Flash',inputTokens:0,outputTokens:0,totalTokens:0,knownTokens:0,tokenShare:0,conversationShare:1/7,favouriteScore:1/14,valueUsd:0,conversations:1},{...snapshot.launch.facts!.models[0]!,id:'model-e',model:'Qwen3 Coder',canonicalModel:'Qwen3 Coder',inputTokens:0,outputTokens:0,totalTokens:0,knownTokens:0,tokenShare:0,conversationShare:1/7,favouriteScore:1/14,valueUsd:0,conversations:1});
 snapshot.launch.languageLines=['what the hell is this','fix this damn thing','this shit broke again','stop making the same damn bug','why the hell did it change','fuck yeah great work'].map((text,index)=>({id:'line-'+index,text,occurrences:[5,4,3,2,2,2][index]!,containingInputs:[5,4,3,2,2,2][index]!,models:[{provider:'a',model:'GPT-5',occurrences:1}],samples:[{promptId:'prompt-0',conversationId:'conversation-0',startUtf16:0,endUtf16:text.length,route}]}));
 snapshot.launch.modelFeedback=[{provider:'a',model:'GPT-5',directedNegativeInputs:14,praiseInputs:3,associatedInputs:100,promptIds:['prompt-0']},{provider:'b',model:'Claude Sonnet 4.6',directedNegativeInputs:9,praiseInputs:18,associatedInputs:300,promptIds:['prompt-0']},{provider:'c',model:'Gemini 2.5 Flash',directedNegativeInputs:1,praiseInputs:2,associatedInputs:25,promptIds:['prompt-0']},{provider:null,model:null,directedNegativeInputs:100,praiseInputs:99,associatedInputs:200,promptIds:[]}];
 snapshot.funnel={nativeFilesDiscovered:10,nativeFilesParsed:9,retainedSources:4,selectedSources:12,responsesObserved:7,responsesDeduplicated:1,responsesExcluded:0,responsesPriced:5,excludedReasons:{},gaps:['partial_pricing']};return snapshot;
}
export function loadingFixture():AuditSnapshot {const snapshot=reportFixture();snapshot.status='discovering';snapshot.launch!.stage='discovering';snapshot.launch!.facts=null;snapshot.launch!.semantics=null;snapshot.projects=[];snapshot.sources=snapshot.sources.map(source=>({...source,state:'checking',candidateFiles:0,census:{checked:false,files:0,bytes:0,roots:1,unit:source.harness==='opencode'?'database':'file'}}));snapshot.progress.label='Checking local history';return snapshot;}
