import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {performance} from 'node:perf_hooks';
import {openAuditSqliteSnapshot} from '../packages/core/src/audit-sqlite.js';
import {openDatabase,resetDriverCache,sqliteDriverName,type Db} from '../packages/core/src/sqlite-driver.js';
const dirs:string[]=[];let previous:string|undefined;
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'audit-live-wal-source-'));dirs.push(dir);const file=path.join(dir,'store.db'),writer=openDatabase(file);writer.pragma('journal_mode = WAL');writer.pragma('wal_autocheckpoint = 0');writer.exec("CREATE TABLE events(id INTEGER PRIMARY KEY,body TEXT);INSERT INTO events(body) VALUES('checkpoint')");writer.pragma('wal_checkpoint(TRUNCATE)');writer.exec("INSERT INTO events(body) VALUES('committed WAL')");return {dir,file,writer};}
function inventory(dir:string){return Object.fromEntries(fs.readdirSync(dir).sort().map(name=>{const file=path.join(dir,name),s=fs.statSync(file,{bigint:true});return [name,{identity:[s.dev,s.ino,s.size,s.mtimeNs,s.ctimeNs].join(':'),hash:createHash('sha256').update(fs.readFileSync(file)).digest('hex')}];}));}
function values(db:Db){return db.prepare('SELECT body FROM events ORDER BY id').all().map(r=>(r as {body:string}).body);}
function capturedDirectories(spy:ReturnType<typeof vi.spyOn>):string[]{return spy.mock.results.map(r=>r.value).filter((v):v is string=>typeof v==='string'&&path.basename(v).startsWith('slopie-audit-sqlite-'));}
for(const selected of ['better-sqlite3','node'] as const)describe(`private committed WAL snapshot with forced ${selected}`,()=>{
 beforeEach(()=>{previous=process.env.POTSHERD_SQLITE;process.env.POTSHERD_SQLITE=selected;resetDriverCache();});
 afterEach(()=>{vi.restoreAllMocks();if(previous===undefined)delete process.env.POTSHERD_SQLITE;else process.env.POTSHERD_SQLITE=previous;resetDriverCache();dirs.splice(0).forEach(dir=>fs.rmSync(dir,{recursive:true,force:true}));});
 it('uses the actual requested driver, includes committed WAL, excludes a live transaction, and leaves source DB/WAL/SHM unchanged',()=>{
  const {dir,file,writer}=fixture();try{expect(sqliteDriverName()).toBe(selected==='node'?'node:sqlite':'better-sqlite3');writer.exec("BEGIN;INSERT INTO events(body) VALUES('uncommitted')");const before=inventory(dir),snapshot=openAuditSqliteSnapshot(file);try{expect(values(snapshot.db)).toEqual(['checkpoint','committed WAL']);expect(()=>snapshot.db.exec("INSERT INTO events(body) VALUES('forbidden')")).toThrow();snapshot.assertCurrent();snapshot.assertIdentityCurrent();}finally{snapshot.db.close();}expect(inventory(dir)).toEqual(before);writer.exec('ROLLBACK');const rolled=openAuditSqliteSnapshot(file);try{expect(values(rolled.db)).toEqual(['checkpoint','committed WAL']);}finally{rolled.db.close();}}finally{writer.close();}
 });
 it('lets SQLite ignore complete uncommitted spilled frames while retaining the last valid commit',()=>{
  const {dir,file,writer}=fixture();try{writer.pragma('cache_size = 5');writer.pragma('cache_spill = ON');writer.exec('BEGIN');const insert=writer.prepare('INSERT INTO events(body) VALUES(?)');for(let i=0;i<40;i++)insert.run('uncommitted '+String(i)+' '+'.'.repeat(8192));expect(fs.statSync(file+'-wal').size).toBeGreaterThan(100_000);const before=inventory(dir),snapshot=openAuditSqliteSnapshot(file);try{expect(values(snapshot.db)).toEqual(['checkpoint','committed WAL']);snapshot.assertCurrent();}finally{snapshot.db.close();}expect(inventory(dir)).toEqual(before);writer.exec('ROLLBACK');}finally{writer.close();}
 });
 it('invalidates source commit/forget changes while keeping the frozen committed view usable',()=>{
  const {file,writer}=fixture();const first=openAuditSqliteSnapshot(file);try{writer.exec("INSERT INTO events(body) VALUES('new commit')");expect(()=>first.assertCurrent()).toThrow('audit_sqlite_snapshot_stale');expect(()=>first.assertIdentityCurrent()).toThrow('audit_sqlite_snapshot_stale');expect(values(first.db)).toEqual(['checkpoint','committed WAL']);const second=openAuditSqliteSnapshot(file);try{expect(second.hash).not.toBe(first.hash);writer.exec('DELETE FROM events WHERE id=2');expect(()=>second.assertCurrent()).toThrow('audit_sqlite_snapshot_stale');}finally{second.db.close();}}finally{first.db.close();writer.close();}
 });
 it('invalidates disappearance/checkpoint of source WAL, including progress identity fences',()=>{
  const {file,writer}=fixture();const snapshot=openAuditSqliteSnapshot(file);try{writer.pragma('wal_checkpoint(TRUNCATE)');expect(()=>snapshot.assertIdentityCurrent()).toThrow('audit_sqlite_snapshot_stale');expect(()=>snapshot.assertCurrent()).toThrow('audit_sqlite_snapshot_stale');expect(values(snapshot.db)).toEqual(['checkpoint','committed WAL']);}finally{snapshot.db.close();writer.close();}
 });
 it('rejects malformed WAL headers, truncated frames and nonempty rollback journals without touching source files',()=>{
  const {dir,file,writer}=fixture();try{const original=fs.readFileSync(file+'-wal');for(const [bad,code] of [[Buffer.from('invalid header'),'audit_sqlite_wal_header_unavailable'],[original.subarray(0,original.length-1),'audit_sqlite_wal_incomplete_tail'],[(()=>{const bytes=Buffer.from(original);bytes.writeUInt32BE(0,0);return bytes;})(),'audit_sqlite_wal_header_unavailable']] as const){fs.writeFileSync(file+'-wal',bad);const before=inventory(dir);expect(()=>openAuditSqliteSnapshot(file)).toThrow(code);expect(inventory(dir)).toEqual(before);}fs.writeFileSync(file+'-wal',original);fs.writeFileSync(file+'-journal','active rollback journal');const before=inventory(dir);expect(()=>openAuditSqliteSnapshot(file)).toThrow('audit_sqlite_rollback_journal_unavailable');expect(inventory(dir)).toEqual(before);fs.unlinkSync(file+'-journal');}finally{writer.close();}
 });
 it('refuses a damaged published committed forget instead of recovering an older privacy state',()=>{
  const {dir,file,writer}=fixture();try{writer.exec("DELETE FROM events WHERE body='committed WAL'");const original=fs.readFileSync(file+'-wal'),shm=fs.readFileSync(file+'-shm'),mxFrame=os.endianness()==='BE'?shm.readUInt32BE(16):shm.readUInt32LE(16),size=original.readUInt32BE(8),bad=Buffer.from(original);bad[32+(mxFrame-1)*(size+24)+24+100]^=1;fs.writeFileSync(file+'-wal',bad);const before=inventory(dir);expect(()=>openAuditSqliteSnapshot(file)).toThrow('audit_sqlite_wal_integrity_unavailable');expect(inventory(dir)).toEqual(before);fs.writeFileSync(file+'-wal',original);const good=openAuditSqliteSnapshot(file);try{expect(values(good.db)).toEqual(['checkpoint']);}finally{good.db.close();}}finally{writer.close();}
 });
 it('accepts recycled allocated old-cycle suffix only past the checksum-proven committed boundary',()=>{
  const {dir,file,writer}=fixture();try{const insert=writer.prepare('INSERT INTO events(body) VALUES(?)');writer.transaction(()=>{for(let i=0;i<100;i++)insert.run('old-cycle '+i+' '+'.'.repeat(8192));})();writer.pragma('wal_checkpoint(RESTART)');writer.exec("UPDATE events SET body='rewritten' WHERE id=1");const wal=fs.readFileSync(file+'-wal'),shm=fs.readFileSync(file+'-shm'),mxFrame=os.endianness()==='BE'?shm.readUInt32BE(16):shm.readUInt32LE(16);expect(wal.length).toBeGreaterThan(32+mxFrame*(wal.readUInt32BE(8)+24));const before=inventory(dir),snapshot=openAuditSqliteSnapshot(file);try{expect(snapshot.db.prepare('SELECT body FROM events WHERE id=1').get()).toEqual({body:'rewritten'});expect(snapshot.db.prepare('SELECT count(*) n FROM events').get()).toEqual({n:102});snapshot.assertCurrent();}finally{snapshot.db.close();}expect(inventory(dir)).toEqual(before);}finally{writer.close();}
 });
 it('holds unknown or corrupt commit-index metadata and ignores irrelevant external reader-mark changes',()=>{
  const {file,writer}=fixture();try{const original=fs.readFileSync(file+'-shm'),bad=Buffer.from(original);bad[8]^=1;fs.writeFileSync(file+'-shm',bad);expect(()=>openAuditSqliteSnapshot(file)).toThrow('audit_sqlite_wal_index_unavailable');fs.writeFileSync(file+'-shm',original);const snapshot=openAuditSqliteSnapshot(file);try{const reader=Buffer.from(original);reader[104]^=1;fs.writeFileSync(file+'-shm',reader);snapshot.assertIdentityCurrent();snapshot.assertCurrent();fs.writeFileSync(file+'-shm',original);}finally{snapshot.db.close();}const saved=file+'-shm.saved';fs.renameSync(file+'-shm',saved);try{expect(()=>openAuditSqliteSnapshot(file)).toThrow('audit_sqlite_wal_index_unavailable');}finally{fs.renameSync(saved,file+'-shm');}}finally{writer.close();}
 });
 it('loads committed schema that exists entirely in WAL on a fresh active store',()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'audit-live-wal-fresh-'));dirs.push(dir);const file=path.join(dir,'store.db'),writer=openDatabase(file);try{writer.pragma('journal_mode = WAL');writer.pragma('wal_autocheckpoint = 0');writer.exec("CREATE TABLE fresh(v TEXT);INSERT INTO fresh VALUES('fresh WAL schema')");const before=inventory(dir),snapshot=openAuditSqliteSnapshot(file);try{expect(snapshot.db.prepare('SELECT v FROM fresh').get()).toEqual({v:'fresh WAL schema'});}finally{snapshot.db.close();}expect(inventory(dir)).toEqual(before);}finally{writer.close();}
 });
 it('caps combined DB/WAL bytes and elapsed capture work before creating any private database',()=>{
  const {dir,file,writer}=fixture();try{const before=inventory(dir),dbBytes=fs.statSync(file).size;expect(()=>openAuditSqliteSnapshot(file,dbBytes)).toThrow('audit_sqlite_snapshot_byte_limit');const now=vi.spyOn(performance,'now');now.mockReturnValueOnce(0).mockReturnValue(2);expect(()=>openAuditSqliteSnapshot(file,64*1024*1024,{maxCaptureMs:1})).toThrow('audit_sqlite_snapshot_time_limit');now.mockRestore();expect(inventory(dir)).toEqual(before);}finally{writer.close();}
 });
 it('creates only private 0700/0600 files, cleans on close and cleans after SQLite setup failures',()=>{
  const {dir,file,writer}=fixture();try{const before=inventory(dir),spy=vi.spyOn(fs,'mkdtempSync');const snapshot=openAuditSqliteSnapshot(file);const captured=capturedDirectories(spy);expect(captured).toHaveLength(1);const temp=captured[0]!;expect(fs.statSync(temp).mode&0o777).toBe(0o700);for(const entry of fs.readdirSync(temp))expect(fs.statSync(path.join(temp,entry)).mode&0o777).toBe(0o600);snapshot.db.close();snapshot.db.close();expect(fs.existsSync(temp)).toBe(false);expect(inventory(dir)).toEqual(before);
   // Corrupt a checkpointed fixture's schema page while preserving the file signature.
   const bad=path.join(dir,'bad.db'),damaged=fs.readFileSync(file);damaged.fill(0xff,100,Math.min(damaged.length,400));fs.writeFileSync(bad,damaged);expect(()=>openAuditSqliteSnapshot(bad)).toThrow('audit_sqlite_snapshot_corrupt');for(const temp of capturedDirectories(spy))expect(fs.existsSync(temp)).toBe(false);
  }finally{writer.close();}
 });
});

describe('disk-bounded streaming snapshot',()=>{
 afterEach(()=>{vi.restoreAllMocks();dirs.splice(0).forEach(dir=>fs.rmSync(dir,{recursive:true,force:true}));});
 it('refuses insufficient private-copy disk headroom before creating private artifacts',()=>{
  const {dir,file,writer}=fixture();try{const before=inventory(dir),real=fs.statfsSync(os.tmpdir(),{bigint:true});vi.spyOn(fs,'statfsSync').mockReturnValue({...real,bavail:0n} as never);const temp=vi.spyOn(fs,'mkdtempSync');expect(()=>openAuditSqliteSnapshot(file)).toThrow('audit_sqlite_snapshot_disk_limit');expect(capturedDirectories(temp)).toHaveLength(0);expect(inventory(dir)).toEqual(before);}finally{writer.close();}
 });
});
