import {describe,it,expect,afterEach,vi} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {createBackgroundAuditSession} from '../packages/cli/src/audit-background.js';
import {createAuditSession} from '../packages/core/src/analytics/index.js';
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(root=>fs.rmSync(root,{recursive:true,force:true})));
function fixture(mode:'blocked'|'transfer'|'crash'){const root=fs.mkdtempSync(path.join(os.tmpdir(),'audit-background-public-'));roots.push(root);const options={launch:true,launchPrepareOnly:true,potsherdDir:path.join(root,'owned'),claudeDir:path.join(root,'absent'),codexDir:path.join(root,'absent'),piDir:path.join(root,'absent'),opencodeDir:path.join(root,'absent')};const initial=createAuditSession(options),snapshot=initial.snapshot();initial.dispose();const file=path.join(root,'worker.mjs');fs.writeFileSync(file,`import fs from 'node:fs';import os from 'node:os';import path from 'node:path';let snapshot=${JSON.stringify(snapshot)},waiting;process.on('message',m=>{if(m.kind==='init'){snapshot.snapshotId=m.options.sessionIdentity;process.send({kind:'ready',snapshot});if(${JSON.stringify(mode)}==='crash')setImmediate(()=>process.exit(5));}else if(m.kind==='request'&&m.op==='run'){fs.writeFileSync(path.join(os.tmpdir(),'captured-private-copy'),'synthetic');snapshot={...snapshot,status:'parsing',sequence:1,progress:{...snapshot.progress,stage:'parsing',label:'Reading local history'}};process.send({kind:'event',event:{type:'snapshot',snapshot}});if(${JSON.stringify(mode)}==='blocked'){const until=Date.now()+5000;while(Date.now()<until){};process.send({kind:'result',id:m.id,value:snapshot});}else{waiting=m.id;process.send({kind:'event',event:{type:'transfer',snapshotId:snapshot.snapshotId,sequence:2,model:'synthetic-public',recipients:['synthetic'],attempt:1,selectedSegments:1,notice:'Synthetic transfer visibility test',ackId:'visible'}});}}else if(m.kind==='transfer_ack'){snapshot={...snapshot,status:'ready',launch:{...snapshot.launch,stage:'ready'}};process.send({kind:'result',id:waiting,value:snapshot});}});`);return {root,options,file};}
describe('background audit ownership and transfer gates',()=>{
 it('hands off one identity and cancels a synchronous blocked child without blocking parent input or leaving owned copies',async()=>{const f=fixture('blocked'),before=new Set(fs.readdirSync(os.tmpdir())),session=createBackgroundAuditSession(f.options,f.file);let progressed=false;const promise=session.run(event=>{if(event.type==='snapshot'&&event.snapshot.status==='parsing')progressed=true;});await vi.waitFor(()=>expect(progressed).toBe(true));const identity=session.snapshot().snapshotId;expect(identity).not.toBeNull();const started=Date.now();session.cancel();const result=await promise;expect(result.status).toBe('cancelled');expect(Date.now()-started).toBeLessThan(500);session.dispose();await vi.waitFor(()=>expect(fs.readdirSync(os.tmpdir()).filter(name=>name.startsWith('slopie-audit-run-')&&!before.has(name))).toEqual([]),{timeout:2500});});
 it('rejects a crashed worker and cleans its owned job instead of leaving a pending request',async()=>{const f=fixture('crash'),before=new Set(fs.readdirSync(os.tmpdir())),session=createBackgroundAuditSession(f.options,f.file);await expect(session.run()).rejects.toThrow('audit_background_worker_unavailable');session.dispose();await vi.waitFor(()=>expect(fs.readdirSync(os.tmpdir()).filter(name=>name.startsWith('slopie-audit-run-')&&!before.has(name))).toEqual([]),{timeout:2500});});
 it('keeps dispatch suspended until the renderer acknowledges actual disclosure',async()=>{const f=fixture('transfer'),session=createBackgroundAuditSession(f.options,f.file);let transfer=false,finished=false;const result=session.run(event=>{if(event.type==='transfer'){transfer=true;expect(event.ackId).toBe('visible');}}).then(value=>{finished=true;return value;});await vi.waitFor(()=>expect(transfer).toBe(true));await new Promise(r=>setTimeout(r,30));expect(finished).toBe(false);session.acknowledgeTransfer!('visible');expect((await result).status).toBe('ready');session.dispose();});
});
