import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {open} from '../packages/core/src/db.js';
import {openDatabase,resetDriverCache} from '../packages/core/src/sqlite-driver.js';
import {openAuditPolicyDb,readAuditAuthority} from '../packages/core/src/analytics/policy-authority.js';
const dirs:string[]=[];let previous:string|undefined;
const directory=()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'slopie-policy-test-'));dirs.push(dir);return dir;};
const bytes=(file:string)=>Object.fromEntries(['','-wal'].map(suffix=>{try{return [suffix,createHash('sha256').update(fs.readFileSync(file+suffix)).digest('hex')];}catch{return [suffix,null];}}));
function fixture(){const root=directory(),file=path.join(root,'store.db'),config=path.join(root,'config.json'),writer=open({root,file});writer.pragma('wal_autocheckpoint = 0');writer.pragma('wal_checkpoint(TRUNCATE)');writer.exec("INSERT INTO memory_sources(source_id,harness,native_session_id,availability,created_at) VALUES('codex:public','codex','public','live','2026-10-07')");return {root,file,config,writer};}
for(const mode of ['better-sqlite3','node'] as const)describe(`cheap audit policy authority ${mode}`,()=>{
 beforeEach(()=>{previous=process.env.POTSHERD_SQLITE;process.env.POTSHERD_SQLITE=mode;resetDriverCache();});
 afterEach(()=>{if(previous===undefined)delete process.env.POTSHERD_SQLITE;else process.env.POTSHERD_SQLITE=previous;resetDriverCache();dirs.splice(0).forEach(dir=>fs.rmSync(dir,{recursive:true,force:true}));});
 it('uses committed privacy rows without changing DB/WAL history with a live writer or uncommitted writes',()=>{const {file,config,writer}=fixture();try{writer.exec("BEGIN;INSERT INTO forget_tombstones VALUES('pending-uncommitted','codex:public',NULL,'scope','2026-10-07','complete','{}')");const before=bytes(file),authority=readAuditAuthority(file,config);expect(authority.forgottenSourceIds.size).toBe(0);expect(bytes(file)).toEqual(before);const reader=openAuditPolicyDb(file);try{expect(()=>reader.exec("UPDATE memory_epochs SET deletion_epoch=1")).toThrow();}finally{reader.close();}expect(bytes(file)).toEqual(before);writer.exec('ROLLBACK');}finally{writer.close();}});
 it('detects manual tombstones, availability revocation and ignore changes while ordinary epochs do not revoke',()=>{const {file,config,writer}=fixture();try{const first=readAuditAuthority(file,config);writer.exec('UPDATE memory_epochs SET evidence_epoch=evidence_epoch+1,notes_epoch=notes_epoch+1,lineage_epoch=lineage_epoch+1');expect(readAuditAuthority(file,config).commitment).toBe(first.commitment);writer.exec("INSERT INTO forget_tombstones VALUES('manual','codex:public',NULL,'scope','2026-10-07','complete','{}')");const second=readAuditAuthority(file,config);expect(second.forgottenSourceIds.has('codex:public')).toBe(true);expect(second.commitment).not.toBe(first.commitment);writer.exec("UPDATE forget_tombstones SET state='reversed';UPDATE memory_sources SET availability='forgotten'");expect(readAuditAuthority(file,config).forgottenSourceIds.has('codex:public')).toBe(true);fs.writeFileSync(config,'{"ignore":["/public"]}');expect(readAuditAuthority(file,config).commitment).not.toBe(second.commitment);}finally{writer.close();}});
 it('allows last-reader close without modifying checkpoint or committed WAL bytes',()=>{const {file,writer}=fixture();try{const target=path.join(directory(),'store.db');fs.copyFileSync(file,target);fs.copyFileSync(file+'-wal',target+'-wal');fs.copyFileSync(file+'-shm',target+'-shm');const before=bytes(target),authority=readAuditAuthority(target,path.join(path.dirname(target),'config.json'));expect(authority.epochs).not.toBeNull();expect(bytes(target)).toEqual(before);expect(fs.existsSync(target+'-shm')).toBe(true);const reader=openAuditPolicyDb(target);reader.close();expect(bytes(target)).toEqual(before);}finally{writer.close();}});
 it('does not silently discard a damaged committed forget when a published WAL index exists',()=>{const {file,writer}=fixture();try{writer.exec("INSERT INTO forget_tombstones VALUES('committed','codex:public',NULL,'scope','2026-10-07','complete','{}')");const target=path.join(directory(),'store.db');for(const suffix of ['','-wal','-shm'])fs.copyFileSync(file+suffix,target+suffix);readAuditAuthority(target,path.join(path.dirname(target),'config.json'));const wal=fs.readFileSync(target+'-wal'),page=wal.readUInt32BE(8),last=32+Math.floor((wal.length-32)/(page+24)-1)*(page+24);wal[last+24+100]^=1;fs.writeFileSync(target+'-wal',wal);expect(()=>readAuditAuthority(target,path.join(path.dirname(target),'config.json'))).toThrow();}finally{writer.close();}});
 it('refuses nonempty WAL without a published SHM commit boundary before SQLite recovery',()=>{const {file,writer}=fixture();try{const target=path.join(directory(),'store.db');fs.copyFileSync(file,target);fs.copyFileSync(file+'-wal',target+'-wal');const before=bytes(target);expect(()=>readAuditAuthority(target,path.join(path.dirname(target),'config.json'))).toThrow('audit_sqlite_wal_index_unavailable');expect(bytes(target)).toEqual(before);expect(fs.existsSync(target+'-shm')).toBe(false);}finally{writer.close();}});
 it('refuses nonempty rollback journal and missing/future schemas without creating a store',()=>{const root=directory(),file=path.join(root,'store.db'),empty=openDatabase(file);empty.exec('CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY); INSERT INTO schema_migrations VALUES(99)');empty.close();expect(()=>openAuditPolicyDb(file)).toThrow();fs.writeFileSync(file+'-journal','held');expect(()=>openAuditPolicyDb(file)).toThrow('audit_policy_rollback_journal_unavailable');const absent=path.join(root,'absent.db');expect(()=>openAuditPolicyDb(absent)).toThrow();expect(fs.existsSync(absent)).toBe(false);});
});
