import {describe,it,expect} from 'vitest';
import {auditCellWidth,applyAuditEvent} from '../packages/cli/src/audit-ui/index.js';
import {buildLaunchScreen,renderLaunchPlain,createWallNavigation,turnWall,wallMode,freezeWall,resizeWall,buildWallboard,buildReportHelp,transferFrameVisible,applyLaunchPrivacyEvent,launchEvidenceCanPublish,launchResultAfterPrivacy,applyLaunchPreviewInvalidation,launchResultAfterPreview} from '../packages/cli/src/audit-ui/launch-terminal.js';
import type {LaunchPrivacyView} from '../packages/cli/src/audit-ui/launch-terminal.js';
import {buildReportLoader,buildEvidenceDocument} from '../packages/cli/src/audit-ui/report-document.js';
import {rankedFeedback,repeatedLines,wallNumber,readableModelName,wallPhraseText} from '../packages/cli/src/audit-ui/wallboard.js';
import {reportFixture,loadingFixture} from './audit-report-fixture.js';
import {evidenceFixture} from './audit-ui/fixture.js';
import type {AuditEvent} from '../packages/core/src/analytics/contracts.js';
const plain=(screen:readonly (readonly {text:string}[])[])=>screen.map(line=>line.map(segment=>segment.text).join('')).join('\n');
const transfer:Extract<AuditEvent,{type:'transfer'}>={type:'transfer',snapshotId:'fixture-audit',sequence:8,model:'jev-free',recipients:['OpenCode Zen','TypeSafe/Jev'],attempt:1,selectedSegments:4,notice:'Selected redacted conversation text will be sent to OpenCode Zen and TypeSafe/Jev.',ackId:'request-1'};
describe('approved fullscreen wallboard',()=>{
 it('crops only an exact leading paste wrapper while preserving source text, count and reference',()=>{
  const snapshot=reportFixture(),phrase=snapshot.launch!.languageLines![0]!,suffix='Public source suffix with 界 emoji 👩‍💻 and meaningful wording that stays available in full',original='[Pasted text #17 +4 lines] '+suffix;phrase.text=original;phrase.occurrences=7;
  expect(wallPhraseText(original)).toBe(suffix);for(const text of ['[Pasted text #17 +4 lines]','[Pasted text #17 +4 lines]  ','Quoted [Pasted text #17 +4 lines] actual words','[Pasted text #17] actual words'])expect(wallPhraseText(text)).toBe(text);
  for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const){const layout=buildWallboard(snapshot,{columns,rows}),page=layout.pages.find(item=>item.anchors.some(anchor=>anchor.label===original))!,anchor=page.anchors.find(item=>item.label===original)!,line=plain([page.lines[anchor.row]!]),visible=line.match(/“([^”]+)”/)![1]!;expect(line).not.toContain('[Pasted text');expect(line).toContain('×7');expect(auditCellWidth(visible)).toBeLessThanOrEqual(36);expect(suffix.startsWith(visible.replace(/…$/,''))).toBe(true);expect(anchor.route).toBe(phrase.samples[0]!.route);expect(page.lines.length).toBeLessThanOrEqual(rows-1);}
  expect(phrase.text).toBe(original);expect(phrase.occurrences).toBe(7);expect(renderLaunchPlain(snapshot,{width:160}).replace(/\s+/g,' ')).toContain(original);
 });
 it('aligns price and input bars despite different figure widths and preserves full prices',()=>{
  const snapshot=reportFixture(),models=snapshot.launch!.facts!.models;models[0]!.valueUsd=123456.78;models[1]!.valueUsd=4;for(const [index,project] of snapshot.projects.entries())project.nativeUserInputs=[99999,12,0][index]!;
  for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const){const layout=buildWallboard(snapshot,{columns,rows});expect(plain(layout.pages.flatMap(page=>page.lines))).toContain('$123,456.78');for(const page of layout.pages)for(const line of page.lines)expect(auditCellWidth(plain([line]))).toBeLessThanOrEqual(columns);}
  const lines=buildWallboard(snapshot,{columns:120,rows:40}).pages[0]!.lines.map(line=>plain([line])),priced=lines.filter(line=>line.includes('$')&&!line.includes('API-equivalent'));
  expect(new Set(priced.map(line=>auditCellWidth(line.slice(0,line.search(/[█·]+\s+\$/))))).size).toBe(1);
  const projects=lines.filter(line=>line.includes('▰')||line.includes('▱'));expect(new Set(projects.map(line=>auditCellWidth(line.slice(0,line.search(/[▰▱]/))))).size).toBe(1);
 });
 it('keeps six sourced phrases, caps only visual prefixes and skips only empty paste wrappers',()=>{
  const snapshot=reportFixture(),base=snapshot.launch!.languageLines![0]!;const long='PUBLIC source wording with 界 emoji 👩‍💻 and a long recognizable request that remains exact in the captured reference';snapshot.launch!.languageLines=[{...base,id:'wrapper',text:'[Pasted text #8 +2 lines]',occurrences:99},{...base,id:'wrapped-body',text:'[Pasted text #8 +2 lines] Please review the public example',occurrences:98},{...base,id:'long-public',text:long,occurrences:97},...snapshot.launch!.languageLines!];
  const selected=repeatedLines(snapshot);expect(selected).toHaveLength(6);expect(selected.some(line=>line.id==='wrapper')).toBe(false);expect(selected.some(line=>line.id==='wrapped-body')).toBe(true);expect(snapshot.launch!.languageLines.some(line=>line.id==='wrapper')).toBe(true);
  const layout=buildWallboard(snapshot,{columns:120,rows:40}),page=layout.pages[0]!,anchor=page.anchors.find(item=>item.label===long)!;expect(anchor.route).toBe(base.samples[0]!.route);const displayed=plain([page.lines[anchor.row]!]).match(/“([^”]+)”/)![1]!;expect(auditCellWidth(displayed)).toBeLessThanOrEqual(36);expect(displayed.endsWith('…')).toBe(true);expect(long.startsWith(displayed.slice(0,-1))).toBe(true);expect(renderLaunchPlain(snapshot,{width:160}).replace(/\s+/g,' ')).toContain(long);
  snapshot.launch!.facts!.models=snapshot.launch!.facts!.models.map(model=>({...model,model:null,canonicalModel:null}));snapshot.launch!.facts!.favourite=null;expect(buildWallboard(snapshot,{columns:120,rows:40}).pages[0]!.cards).not.toContain('models');
 });
 it('scales model bars to actual value despite opposing token ranks and keeps unknown prices unfilled',()=>{
  const snapshot=reportFixture(),models=snapshot.launch!.facts!.models;models[0]!.valueUsd=1;models[1]!.valueUsd=10;
  const lines=buildWallboard(snapshot,{columns:120,rows:40}).pages[0]!.lines.map(line=>plain([line]));
  const expensive=lines.find(line=>line.includes('GPT-5'))!,tokenLeader=lines.find(line=>line.includes('● Claude Sonnet'))!,unknown=lines.find(line=>line.includes('Á CJK'))!;
  expect((expensive.match(/█/g)??[]).length).toBeGreaterThan((tokenLeader.match(/█/g)??[]).length);expect(unknown).toContain('—');expect(unknown).not.toContain('█');
  expect(lines.some(line=>line.includes('▰'))).toBe(true);expect(lines.some(line=>line.includes('7500'))).toBe(false);
 });
 it('formats display names without changing identities and qualifies recorded provider collisions',()=>{
  expect(readableModelName('anthropic/claude-opus-5')).toBe('Claude Opus 5');expect(readableModelName('openai/gpt-6.1-sol')).toBe('GPT-6.1 Sol');expect(readableModelName('unknown/custom-name')).toBe('unknown/custom-name');
  const snapshot=reportFixture(),models=snapshot.launch!.facts!.models;models[0]!.canonicalModel='openai/gpt-6.1-sol';models[0]!.provider='openai';models[1]!.canonicalModel='gpt-6.1-sol';models[1]!.provider='opencode';
  const output=plain(buildWallboard(snapshot,{columns:120,rows:40}).pages[0]!.lines);
  expect(output).toContain('GPT-6.1 Sol (openai)');expect(output).toContain('GPT-6.1 Sol (opencode)');expect(plain(buildReportHelp(snapshot,{columns:120}).lines)).toContain('Model identity: openai/gpt-6.1-sol');
  expect(wallNumber(9770422701)).toBe('9.77B');expect(wallNumber(0)).toBe('0');expect(wallNumber(null)).toBe('—');
 });
 it('uses one120/80column board and three mixed narrow layouts without dropped core rows',()=>{const snapshot=reportFixture();for(const [columns,rows,count] of [[120,40,1],[80,24,1],[40,20,3]] as const){const layout=buildWallboard(snapshot,{columns,rows});expect(layout.pages).toHaveLength(count);const output=plain(layout.pages.flatMap(page=>page.lines));for(const model of ['Claude Sonnet','GPT-5','Gemini','Qwen3'])expect(output).toContain(model);for(const project of snapshot.projects)expect(output).toContain(project.displayName);for(const line of snapshot.launch!.languageLines!)expect(output).toContain(line.text.slice(0,18));expect(output.toLowerCase()).toContain('roasted');expect(output.toLowerCase()).toContain('praised');expect(output).toContain('make sure tests pass');expect(layout.pages.every(page=>page.cards.length>=2)).toBe(true);expect(layout.pages.every(page=>page.lines.length<=rows-1)).toBe(true);}});
 it('shows real value, known tokens, chats/projects, favourite and requested lexical focus without a fixedheader',()=>{const output=plain(buildLaunchScreen(reportFixture(),createWallNavigation(),{columns:120,rows:40}));expect(output).toContain('$16.50');expect(output).toContain('10K known tokens');expect(output).toContain('517 chats');expect(output).toContain('3 projects');expect(output).toContain('● Claude Sonnet');expect(output).toContain('Debugging');expect(output).not.toMatch(/Slopie|\[Overview\]|Hall of Fame|Uncertain filler|pricing-sha|https:\/\//);});
 it('uses complete repeated-line groups and separately directed reaction rates, never singleword/match/global counts',()=>{const snapshot=reportFixture(),output=plain(buildWallboard(snapshot,{columns:120,rows:40}).pages[0]!.lines);expect(output).toMatch(/“what the hell is this” +×5/);expect(output).toMatch(/“fuck yeah great work” +×2/);expect(output).toContain('14.0% 14/100');expect(output).toContain('6.0% 18/300');expect(output).not.toContain('damn ×13');expect(output).not.toContain('damn ×8');expect(output).not.toContain('Unattributed model');expect(rankedFeedback(snapshot,'negative')[0]!.model).toBe('GPT-5');expect(rankedFeedback(snapshot,'praise')[0]!.model).toBe('Gemini 2.5 Flash');snapshot.launch!.languageLines=undefined;expect(repeatedLines(snapshot)).toEqual([]);});
 it('omits unsupported/empty language/reaction/moment cards and does not generate semantic filler',()=>{const snapshot=reportFixture();snapshot.launch!.languageLines=[];snapshot.launch!.modelFeedback=[];snapshot.launch!.semantics!.hallOfFame=[];snapshot.projects=snapshot.projects.map(project=>({...project,focus:[]}));const output=plain(buildWallboard(snapshot).pages.flatMap(page=>page.lines));expect(output).not.toMatch(/YOUR REPEATED|REACTIONS|Hall|no supported selection|Requests:|Uncertain filler/);});
 for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const)it(`fits every measured card page at${columns}x${rows} with Unicode/ASCII names and one shortfooter`,()=>{const snapshot=reportFixture();for(const ascii of [false,true]){const layout=buildWallboard(snapshot,{columns,rows,ascii});for(let page=0;page<layout.pages.length;page++){const screen=buildLaunchScreen(snapshot,{...createWallNavigation(),page},{columns,rows,ascii});expect(screen).toHaveLength(rows);for(const line of screen)expect(auditCellWidth(plain([line]))).toBeLessThanOrEqual(columns);expect(plain([screen.at(-1)!])).toContain('? help');expect(plain(screen)).not.toContain('scroll');}expect(plain(layout.pages.flatMap(page=>page.lines))).toContain('Á CJK');}});
 it('keeps null/value/reference/rate unknown distinct from measured zero with one coveragecue',()=>{const snapshot=reportFixture(),facts=snapshot.launch!.facts!;facts.valueUsd=null;facts.referenceValueUsd=4;facts.referenceProviders=[{provider:'Anthropic',model:'Claude Sonnet 4.6',basis:'first-party',valueUsd:4,pricedResponses:1}];let output=plain(buildWallboard(snapshot,{columns:120,rows:40}).pages[0]!.lines);expect(output).toContain('$4.00');expect(renderLaunchPlain(snapshot)).toContain('Anthropic reference pricing; actual provider unknown');expect(output.match(/Partial/g)).toHaveLength(1);facts.valueUsd=null;facts.referenceValueUsd=null;facts.knownTokenResponses=0;output=plain(buildWallboard(snapshot).pages[0]!.lines);expect(output).toContain('Value unavailable');expect(output).toContain('Tokens unavailable');facts.valueUsd=0;expect(plain(buildWallboard(snapshot).pages[0]!.lines)).toContain('$0.00');const unknown=reportFixture().launch!.facts!.models[2]!;expect(unknown.valueUsd).toBeNull();});
 it('preserves exact fullname identities behind help while long labels use explicit clipping, not silent tail loss',()=>{const snapshot=reportFixture();snapshot.projects[0]!.displayName='A very long source project name 界 👩‍💻 exceeding a compact card';const pages=buildWallboard(snapshot,{columns:40,rows:20});expect(plain(pages.pages.flatMap(page=>page.lines))).toContain('…');for(const page of pages.pages)expect(page.lines.length).toBeLessThanOrEqual(19);});
 it('optional plain output emits the entire artifact beyond40rows including fullphrases/attribution/rates',()=>{const snapshot=reportFixture();snapshot.launch!.facts!.models=Array.from({length:60},(_,i)=>({...snapshot.launch!.facts!.models[0]!,id:`model-${i}`,model:`Real retained model ${i}`,canonicalModel:`Real retained model ${i}`}));const output=renderLaunchPlain(snapshot,{width:40});expect(output.split('\n').length).toBeGreaterThan(100);expect(output).toContain('Real retained model 59');expect(output.replace(/\s+/g,' ')).toContain('show the evidence before calling it done');expect(output).toContain('what the hell is this');expect(output).toContain('14/100');expect(output).not.toContain('q quit');});
 it('shows pricing/coverage/fullscopes/denominator and actualrecipienthistory only in optionalhelp',()=>{const help=plain(buildReportHelp(reportFixture(),{},[transfer]).lines);expect(help).toContain('pricing-sha-sentinel');expect(help).toContain('nativeFilesDiscovered: 10');expect(help).toContain('2026-10-01T00:00:00Z');expect(help).toContain('OpenCode Zen, TypeSafe/Jev');expect(help.replace(/\s+/g,' ')).toContain('not objective model quality');expect(help).not.toContain('Scroll one');});
 it('renders captured evidence separately, with authority revocation distinct from ordinary source capture',()=>{expect(plain(buildEvidenceDocument(evidenceFixture()).lines)).toContain('PRIVATE_EXACT_TEXT');const revoked=plain(buildEvidenceDocument(evidenceFixture('stale')).lines);expect(revoked).toContain('Privacy authority changed');expect(revoked).not.toContain('PRIVATE_EXACT_TEXT');});
 it('sanitizes terminal controls in project names, line quotes and evidence',()=>{const snapshot=reportFixture();snapshot.projects[0]!.displayName='Clean\x1b[2J\x1b]0;hidden\x07 project';snapshot.launch!.languageLines![0]!.text='line\x1b[2J words';expect(plain(buildWallboard(snapshot).pages.flatMap(page=>page.lines))).not.toContain('\x1b');expect(plain(buildEvidenceDocument({...evidenceFixture(),text:'A\x1b[2J\nB'}).lines)).not.toContain('\x1b');});
});
describe('wallboard interaction and honest loading/transfer states',()=>{
 it('withdraws an explicitly revoked frozen price preview but permits later allowed final facts',()=>{
  const snapshot=reportFixture();snapshot.launch!.stage='sizing';snapshot.launch!.factProgress={state:'collecting',completedSources:2,totalSources:8,representedSources:2,cacheHits:0,coverage:'completed_sources',origin:'fresh'};
  const view:LaunchPrivacyView={snapshot,nav:wallMode(freezeWall(createWallNavigation()),'help'),frozen:snapshot,evidence:evidenceFixture(),busy:true,generation:10,revoked:null};
  const invalid={...snapshot,sequence:snapshot.sequence+1,coverage:{...snapshot.coverage,gapCodes:['native_price_preview_revoked']},launch:{...snapshot.launch!,facts:null,factProgress:{...snapshot.launch!.factProgress!,representedSources:0}}},event:AuditEvent={type:'snapshot',snapshot:invalid},cleared=applyLaunchPreviewInvalidation(view,event)!;
  expect(cleared.nav.mode).toBe('help');expect(cleared.nav.frozen).toBe(false);expect(cleared.frozen).toBeNull();expect(cleared.evidence).toBeNull();expect(cleared.busy).toBe(false);expect(cleared.generation).toBe(11);expect(cleared.revoked).toBeNull();expect(cleared.snapshot.launch!.facts).toBeNull();expect(launchEvidenceCanPublish(10,cleared.generation,false)).toBe(false);
  const floor={snapshotId:invalid.snapshotId,sequence:invalid.sequence};expect(launchResultAfterPreview(snapshot,invalid,floor)).toBe(invalid);const allowed={...reportFixture(),sequence:invalid.sequence+1};expect(launchResultAfterPreview(allowed,invalid,floor)).toBe(allowed);expect(applyLaunchPreviewInvalidation(cleared,{type:'snapshot',snapshot:allowed})).toBeNull();
  expect(applyLaunchPreviewInvalidation(view,{type:'snapshot',snapshot:{...invalid,coverage:{...invalid.coverage,gapCodes:['excluded_by_policy']}}})).toBeNull();expect(applyLaunchPreviewInvalidation(view,{type:'snapshot',snapshot:{...snapshot,sequence:snapshot.sequence+1}})).toBeNull();expect(applyLaunchPreviewInvalidation({...view,snapshot:invalid,frozen:invalid},event)).toBeNull();
 });
 it('distinguishes the priced subtotal from actually checked sources without dropping narrow cards',()=>{
  const snapshot=reportFixture();snapshot.status='parsing';snapshot.launch!.stage='sizing';snapshot.launch!.factProgress={state:'collecting',completedSources:232,totalSources:653,representedSources:2,cacheHits:1,coverage:'completed_sources',origin:'mixed'};
  for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const){const layout=buildWallboard(snapshot,{columns,rows}),output=plain(layout.pages.flatMap(page=>page.lines));expect(output).toContain('prices from 2 sources');expect(output.toLowerCase()).toContain('checked 232/653');expect(output).toContain('Subtotal');expect(layout.pages.every(page=>page.lines.length<=rows-1)).toBe(true);expect(new Set(layout.pages.flatMap(page=>page.cards))).toEqual(new Set(['value','models','projects','phrases','reactions','moment']));for(const page of layout.pages)for(const line of page.lines)expect(auditCellWidth(plain([line]))).toBeLessThanOrEqual(columns);}
  delete snapshot.launch!.factProgress.representedSources;expect(plain(buildWallboard(snapshot,{columns:120,rows:40}).pages[0]!.lines)).not.toContain('Subtotal');snapshot.launch!.factProgress.representedSources=232;expect(plain(buildWallboard(snapshot,{columns:120,rows:40}).pages[0]!.lines)).not.toContain('Subtotal');
 });
 it('revokes a frozen captured view on an explicit privacy error and rejects late evidence/results',()=>{
  const snapshot=reportFixture();snapshot.launch!.semantics!.attempts=1;const layout=buildWallboard(snapshot,{columns:40,rows:20}),nav=wallMode(freezeWall(turnWall(createWallNavigation(),2,layout.pages.length,layout)),'help');
  const view:LaunchPrivacyView={snapshot,nav,frozen:snapshot,evidence:{...evidenceFixture(),text:'PUBLIC captured evidence'},busy:true,generation:7,revoked:null};
  const cleared=applyLaunchPrivacyEvent(view,{type:'error',snapshotId:snapshot.snapshotId,code:'source_or_privacy_changed',message:'Controlled public authority revocation'})!;
  expect(cleared.nav.mode).toBe('help');expect(cleared.nav.boardPage).toBe(2);expect(cleared.nav.frozen).toBe(false);expect(cleared.frozen).toBeNull();expect(cleared.evidence).toBeNull();expect(cleared.busy).toBe(false);expect(cleared.generation).toBe(8);expect(cleared.snapshot.launch!.facts).toBeNull();expect(cleared.snapshot.metrics.conversations.value).toBeNull();
  const output=renderLaunchPlain(cleared.snapshot);expect(output).not.toContain('$16.50');expect(output).not.toContain('what the hell is this');expect(output).not.toContain('Rotor Notes');expect(output).not.toContain('No analysis requests made');expect(cleared.snapshot.launch!.semantics!.attempts).toBe(1);
  expect(launchEvidenceCanPublish(7,cleared.generation,true)).toBe(false);expect(launchEvidenceCanPublish(8,cleared.generation,true)).toBe(false);
  expect(launchResultAfterPrivacy(snapshot,cleared.revoked)).toBe(cleared.snapshot);
  expect(applyLaunchPrivacyEvent(cleared,{type:'snapshot',snapshot:{...snapshot,sequence:999}})!.snapshot).toBe(cleared.snapshot);
 });
 it('revokes an unavailable privacy snapshot while preserving ordinary append and valid partial facts',()=>{
  const snapshot=reportFixture(),view:LaunchPrivacyView={snapshot,nav:freezeWall(createWallNavigation()),frozen:snapshot,evidence:null,busy:false,generation:4,revoked:null};
  const append={...snapshot,sequence:snapshot.sequence+1};expect(applyLaunchPrivacyEvent(view,{type:'snapshot',snapshot:append})).toBeNull();
  const partial={...append,coverage:{...append.coverage,gapCodes:['excluded_by_policy']}};expect(applyLaunchPrivacyEvent(view,{type:'snapshot',snapshot:partial})).toBeNull();
  const excluded={...partial,launch:{...partial.launch!,facts:null}};expect(applyLaunchPrivacyEvent(view,{type:'snapshot',snapshot:excluded})).toBeNull();
  const unavailable={...excluded,coverage:{...excluded.coverage,gapCodes:['source_or_policy_changed']}};const cleared=applyLaunchPrivacyEvent(view,{type:'snapshot',snapshot:unavailable})!;expect(cleared.nav.frozen).toBe(false);expect(cleared.snapshot.launch!.languageLines).toEqual([]);expect(cleared.snapshot.launch!.semantics!.hallOfFame).toEqual([]);expect(cleared.snapshot.projects).toEqual([]);
  expect(applyLaunchPrivacyEvent(view,{type:'snapshot',snapshot:{...unavailable,coverage:{...unavailable.coverage,gapCodes:['privacy_epoch_mismatch']}}})).not.toBeNull();
  expect(applyLaunchPrivacyEvent(view,{type:'snapshot',snapshot:{...unavailable,sequence:snapshot.sequence-1}})).toBeNull();expect(applyLaunchPrivacyEvent(view,{type:'error',snapshotId:'different-capture',code:'privacy_revoked',message:'Stale public event'})).toBeNull();
 });
 it('shows sourced early facts with collecting/cache scope and hides unavailable chat/project totals',()=>{
  const snapshot=reportFixture();snapshot.status='parsing';snapshot.launch!.stage='sizing';snapshot.launch!.facts!.records=[];snapshot.launch!.facts!.recordsIncluded=false;snapshot.launch!.factProgress={state:'collecting',completedSources:2,totalSources:8,cacheHits:2,coverage:'completed_sources',origin:'cache'};snapshot.progress.label='Reading native usage';snapshot.metrics.conversations.state='unavailable';snapshot.metrics.projects.state='unavailable';
  const nav=createWallNavigation(),output=plain(buildLaunchScreen(snapshot,nav,{columns:120,rows:40}));expect(output).toContain('$16.50');expect(output).toContain('10K known tokens');expect(output).toContain('Cached · Collecting · 2/8 sources · Reading native usage');expect(output).not.toMatch(/0 chats|517 chats|3 projects|Report ready/);
  const measured=buildWallboard(snapshot,{columns:120,rows:40,frame:0}),a=buildLaunchScreen(snapshot,nav,{columns:120,rows:40,frame:0},measured),b=buildLaunchScreen(snapshot,nav,{columns:120,rows:40,frame:1},measured);expect(a.map((line,index)=>plain([line])===plain([b[index]!]))).toEqual(a.map((_,index)=>index!==2));expect(plain(measured.pages[0]!.lines)).toContain('[-.-]');
  expect(buildLaunchScreen(snapshot,nav,{columns:120,rows:40,frame:0})).not.toEqual(buildLaunchScreen(snapshot,nav,{columns:120,rows:40,frame:1}));snapshot.launch!.factProgress.origin='mixed';expect(plain(buildLaunchScreen(snapshot,nav,{columns:40,rows:20}))).toContain('Collect 2/8 src · cache+fresh');snapshot.launch!.factProgress.origin='cache';snapshot.launch!.stage='ready';snapshot.status='ready';snapshot.launch!.factProgress.state='complete';expect(plain(buildLaunchScreen(snapshot,nav,{columns:120,rows:40}))).toContain('Cached · partial sources');expect(buildLaunchScreen(snapshot,nav,{frame:0})).toEqual(buildLaunchScreen(snapshot,nav,{frame:1}));
 });
 it('preserves every mixed-page card anchor and viewport bounds through120→40→80→120 and help',()=>{
  const snapshot=reportFixture(),small=buildWallboard(snapshot,{columns:40,rows:20});
  for(let page=0;page<small.pages.length;page++){
   let nav=turnWall(createWallNavigation(),page,small.pages.length,small);
   const anchor=nav.anchor;
   for(const [columns,rows] of [[120,40],[40,20],[80,24],[120,40]] as const){
    nav=wallMode(wallMode(nav,'help'),'board');
    const layout=buildWallboard(snapshot,{columns,rows});nav=resizeWall(nav,layout);
    expect(nav.anchor).toBe(anchor);expect(layout.pages[nav.page]!.cards).toContain(anchor);
    const screen=buildLaunchScreen(snapshot,nav,{columns,rows});
    expect(screen).toHaveLength(rows);expect(screen.every(line=>auditCellWidth(plain([line]))<=columns)).toBe(true);
    expect(plain([screen.at(-1)!])).toContain(layout.pages.length>1?`${nav.page+1}/${layout.pages.length}`:'? help');
   }
  }
 });
 it('clamps arrows, restores page/context from help and preserves nearest card after resize',()=>{const snapshot=reportFixture(),narrow=buildWallboard(snapshot,{columns:40,rows:20}),wide=buildWallboard(snapshot,{columns:120,rows:40});let nav=turnWall(createWallNavigation(),2,narrow.pages.length,narrow);const selected=nav.page,anchor=nav.anchor;nav=wallMode(nav,'help');nav=turnWall(nav,1,5);nav=wallMode(nav,'board');expect(nav.page).toBe(selected);expect(nav.anchor).toBe(anchor);expect(resizeWall(nav,wide).page).toBe(0);expect(resizeWall(resizeWall(nav,wide),narrow).anchor).toBe(anchor);expect(turnWall(createWallNavigation(),-99,3).page).toBe(0);expect(turnWall(nav,99,3).page).toBe(2);});
 it('freezes presentation without disabling pages/help or changing frozen data',()=>{const layout=buildWallboard(reportFixture(),{columns:40,rows:20});let nav=freezeWall(createWallNavigation());nav=turnWall(nav,1,layout.pages.length,layout);expect(nav.frozen).toBe(true);expect(nav.page).toBe(1);nav=wallMode(nav,'help');expect(nav.frozen).toBe(true);expect(wallMode(nav,'board').page).toBe(1);expect(freezeWall(wallMode(nav,'board')).frozen).toBe(false);});
 it('shows checking until true census, completed0files only aftercheck, no recipient claim duringlocalwork',()=>{const snapshot=loadingFixture();let output=plain(buildReportLoader(snapshot,{columns:40,rows:20}));expect(output).toContain('Claude Code checking');expect(output).not.toContain('0 files');snapshot.sources[0]!.state='available';snapshot.sources[0]!.census={checked:true,files:31,bytes:5000,roots:1,unit:'file'};snapshot.sources[1]!.state='absent';snapshot.sources[1]!.census={checked:true,files:0,bytes:0,roots:2,unit:'file'};output=plain(buildReportLoader(snapshot,{columns:40,rows:20}));expect(output).toContain('Claude Code 31 files');expect(output).toContain('Codex 0 files');expect(output).toContain('OpenCode checking');expect(output).not.toContain('TypeSafe');});
 it('has coherent fixed-extent loading motion but a ready board is frame-independent',()=>{const snapshot=loadingFixture(),a=buildLaunchScreen(snapshot,createWallNavigation(),{columns:80,rows:24,frame:0}),b=buildLaunchScreen(snapshot,createWallNavigation(),{columns:80,rows:24,frame:1});expect(a).not.toEqual(b);const ready=reportFixture();expect(buildLaunchScreen(ready,createWallNavigation(),{frame:0})).toEqual(buildLaunchScreen(ready,createWallNavigation(),{frame:9}));});
 it('renders actual transfer notices in every mode/frozen view and verifies fullvisibility beforeACK',()=>{for(const mode of ['board','help','detail'] as const){for(const [columns,rows] of [[120,40],[80,24],[40,20]] as const){const screen=buildLaunchScreen(reportFixture(),{...createWallNavigation(),mode,frozen:true},{columns,rows,transfer});expect(transferFrameVisible(screen,transfer)).toBe(true);}}expect(applyAuditEvent(reportFixture(),transfer)).toEqual(reportFixture());});
 it('does not acknowledge a notice which cannot fit the frame',()=>{const event={...transfer,notice:'a'.repeat(800)+'OpenCode Zen TypeSafe/Jev'};expect(transferFrameVisible(buildLaunchScreen(loadingFixture(),createWallNavigation(),{columns:40,rows:20,transfer:event}),event)).toBe(false);});
 it('does not imply sends from offline/cached/constructor notices and retains local failure versus actualquota honesty',()=>{const loading=loadingFixture();loading.status='partial';loading.launch!.stage='ready';loading.coverage.gapCodes=['store_policy_unavailable','audit_sqlite_rollback_journal_unavailable'];let output=plain(buildWallboard(loading).pages[0]!.lines);expect(output).toContain('Local SQLite rollback journal');expect(output).toContain('No analysis requests made');expect(output).not.toMatch(/pending|Jev unavailable|OpenCode Zen/);const provider=reportFixture();provider.launch!.semantics!.state='unavailable';provider.launch!.semantics!.attempts=1;provider.launch!.semantics!.gaps=['free_quota_unavailable'];output=plain(buildWallboard(provider).pages.flatMap(page=>page.lines));expect(output).toContain('Jev quota exhausted');expect(output).toContain('$16.50');});
});
