import {describe,it,expect,vi} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {open} from '../packages/core/src/db.js';
import type {ParseResult} from '../packages/core/src/adapters/types.js';
import {hash} from '../packages/core/src/memory/spans.js';
import {publishSource,readEpochs} from '../packages/core/src/memory/source.js';
import {LocalMemoryService} from '../packages/core/src/memory/service.js';
import {defaultBudget} from '../packages/core/src/memory/budget.js';
import {MaintenanceWorker} from '../packages/core/src/memory/maintenance.js';
import {loadSpanTokenizer} from '../packages/core/src/memory/tokenization.js';
import {SpanDenseLane} from '../packages/core/src/memory/dense.js';
import {inspectAssets} from '../packages/core/src/memory/assets.js';
function parsed(text:string,sourcePath='/synthetic/activation',status:'live'|'archived'='live'):ParseResult{return {session:{id:'activation-source',harness:'claude',sourcePath,project:'/activation',projectSlug:'activation',gitBranch:'main',startedAt:'',endedAt:'',isSidechain:false,counts:{userPrompts:1,assistantTurns:0,toolCalls:0,bytes:0},status},records:[{unitKey:'record',role:'user',text,eventAt:'2025-12-01T00:00:00Z',timeBasis:'record',project:'/activation',branch:'main',locator:{recordKey:'record',mapping:'unavailable'},locatorFidelity:'record_id',recordType:'user'}],exchanges:[],unknownTypes:{},endOffset:text.length,malformedLines:0,evidenceVersion:'activation-test'};}
const scope={project:'/activation',branch:'main',asOf:'2026-02-01T00:00:00Z'};
const recall=async(service:LocalMemoryService,query:string,learnedBy:string,includeHistory=false)=> (await service.recall({query,mode:'literal',scope:{...scope,learnedBy,...(includeHistory?{includeHistory:true}:{})},budget:defaultBudget()})).response as any;
describe('actual source activation timeline',()=>{
 it('selects A→B→A by activation while preserving immutable observation time and future exclusion',async()=>{const db=open({file:':memory:'});try{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-01-01T00:00:00Z'));const a=publishSource(db,{parsed:parsed('ACTIVATION_A old wheel'),artifactHash:hash('A'),artifactBytes:1});vi.setSystemTime(new Date('2026-01-02T00:00:00Z'));const b=publishSource(db,{parsed:parsed('ACTIVATION_B new wheel'),artifactHash:hash('B'),artifactBytes:1});vi.setSystemTime(new Date('2026-01-03T00:00:00Z'));const again=publishSource(db,{parsed:parsed('ACTIVATION_A old wheel'),artifactHash:hash('A'),artifactBytes:1});expect(again.revisionId).toBe(a.revisionId);expect(db.prepare('SELECT observed_at FROM source_revisions WHERE revision_id=?').get(a.revisionId)).toMatchObject({observed_at:'2026-01-01T00:00:00.000Z'});const service=new LocalMemoryService(db);
  const before=await recall(service,'ACTIVATION_A','2026-01-01T00:00:00Z');expect(before.evidence[0].ref.revisionId).toBe(a.revisionId);expect(before.coverage.state).toBe('complete_snapshot');expect(before.coverage.capturedThrough).toBe('2026-01-01T00:00:00.000Z');expect((await recall(service,'ACTIVATION_B','2026-01-01T00:00:00Z')).evidence).toHaveLength(0);
  expect((await recall(service,'ACTIVATION_B','2026-01-02T00:00:00Z')).evidence[0].ref.revisionId).toBe(b.revisionId);expect((await recall(service,'ACTIVATION_A','2026-01-02T00:00:00Z')).evidence).toHaveLength(0);expect((await recall(service,'ACTIVATION_A','2026-01-02T00:00:00Z',true)).evidence[0].ref.revisionId).toBe(a.revisionId);
  const after=await recall(service,'ACTIVATION_A','2026-01-03T00:00:00Z');expect(after.evidence[0].observedAt).toBe('2026-01-01T00:00:00.000Z');expect(after.coverage.capturedThrough).toBe('2026-01-03T00:00:00.000Z');expect(db.prepare('SELECT COUNT(*) n FROM source_activations').get()).toMatchObject({n:3});expect(service.inspect(scope).capturedThrough).toBe('2026-01-03T00:00:00.000Z');
 }finally{vi.useRealTimers();db.close();}});
 it('uses proven same-millisecond commit order and rolls failed publication out of the ledger',async()=>{const db=open({file:':memory:'});try{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-01-01T00:00:00Z'));publishSource(db,{parsed:parsed('ORDER_A first'),artifactHash:'A',artifactBytes:1});const b=publishSource(db,{parsed:parsed('ORDER_B last'),artifactHash:'B',artifactBytes:1});expect(()=>publishSource(db,{parsed:parsed('ORDER_C failed'),artifactHash:'C',artifactBytes:1,publishAuxiliary(){throw new Error('required_stage_failed');}})).toThrow('required_stage_failed');const service=new LocalMemoryService(db);expect((await recall(service,'ORDER_B','2026-01-01T00:00:00Z')).evidence[0].ref.revisionId).toBe(b.revisionId);expect((await recall(service,'ORDER_A','2026-01-01T00:00:00Z')).evidence).toHaveLength(0);expect(db.prepare('SELECT COUNT(*) n FROM source_activations').get()).toMatchObject({n:2});expect(db.prepare('SELECT COUNT(*) n FROM source_revisions').get()).toMatchObject({n:2});}finally{vi.useRealTimers();db.close();}});
 it('does not activate a newly observed older archive prefix',async()=>{const db=open({file:':memory:'});try{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-01-02T00:00:00Z'));const current=publishSource(db,{parsed:parsed('PREFIX_FULL first and second'),artifactHash:hash('prefix\nfull\n'),artifactBytes:12});vi.setSystemTime(new Date('2026-01-03T00:00:00Z'));const old=publishSource(db,{parsed:parsed('PREFIX_OLD first','/synthetic/older','archived'),artifactHash:hash('prefix\n'),artifactBytes:7,olderArchivedPrefix:true,prefixCompatibleArtifactHashes:[hash('prefix\nfull\n')]});expect(old.activated).toBe(false);expect(db.prepare('SELECT observed_at FROM source_revisions WHERE revision_id=?').get(old.revisionId)).toMatchObject({observed_at:'2026-01-03T00:00:00.000Z'});const service=new LocalMemoryService(db);expect((await recall(service,'PREFIX_FULL','2026-01-04T00:00:00Z')).evidence[0].ref.revisionId).toBe(current.revisionId);expect((await recall(service,'PREFIX_OLD','2026-01-04T00:00:00Z')).evidence).toHaveLength(0);expect((await recall(service,'PREFIX_OLD','2026-01-04T00:00:00Z',true)).evidence[0].ref.revisionId).toBe(old.revisionId);expect(db.prepare('SELECT COUNT(*) n FROM source_activations').get()).toMatchObject({n:1});}finally{vi.useRealTimers();db.close();}});
 it('upgrades genuine schema17 shape with a truthful current witness and unknown earlier activation history',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-activation-upgrade-'));let db=open({root});try{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-01-01T00:00:00Z'));const a=publishSource(db,{parsed:parsed('LEGACY_OLD observed'),artifactHash:'A',artifactBytes:1});vi.setSystemTime(new Date('2026-01-02T00:00:00Z'));const b=publishSource(db,{parsed:parsed('LEGACY_NEW observed'),artifactHash:'B',artifactBytes:1});vi.useRealTimers();db.exec('DROP TABLE source_activations;DROP TABLE source_activation_baselines;DROP INDEX source_revisions_source_revision;DELETE FROM schema_migrations WHERE version=18');db.close();db=open({root});const service=new LocalMemoryService(db);const past=await recall(service,'LEGACY_OLD','2026-01-01T00:00:00Z');expect(past.evidence).toHaveLength(0);expect(past.coverage.state).toBe('partial');expect(past.coverage.omittedKinds).toContain('activation_history_unknown');expect((await recall(service,'LEGACY_OLD','2026-01-01T00:00:00Z',true)).evidence[0].ref.revisionId).toBe(a.revisionId);expect(db.prepare('SELECT revision_id,basis FROM source_activations').get()).toMatchObject({revision_id:b.revisionId,basis:'migration_current'});expect(db.prepare('SELECT observed_at FROM source_revisions WHERE revision_id=?').get(a.revisionId)).toMatchObject({observed_at:'2026-01-01T00:00:00.000Z'});}finally{vi.useRealTimers();db.close();fs.rmSync(root,{recursive:true,force:true});}});

});
