import { it,expect } from 'vitest';
import { open } from '../packages/core/src/db.js';
import { ingestSession } from '../packages/core/src/ingest.js';
import { backfillLegacy,backfillLegacyGhosts } from '../packages/core/src/memory/backfill.js';
import { backfillLegacyNotes,inspectNotes } from '../packages/core/src/memory/notes-store.js';
import { listSourceSpans,sourceId,inspectCoverage } from '../packages/core/src/memory/source.js';
import type { ParseResult } from '../packages/core/src/adapters/types.js';
function parsed(id:string):ParseResult{return {session:{id,harness:'claude',sourcePath:`/unavailable/${id}`,project:'/p',projectSlug:'p',startedAt:'',endedAt:'',isSidechain:false,counts:{userPrompts:1,assistantTurns:1,toolCalls:0,bytes:0},status:'archived'},exchanges:[{id:`e-${id}`,sessionId:id,seq:0,ts:'2026-01-01T00:00:00Z',userText:'legacy prompt',assistantText:'legacy answer',toolCalls:[],filesTouched:[],isSidechain:false,redacted:true}],unknownTypes:{},endOffset:0,malformedLines:0};}
it('backfills per source restartably without claiming absent raw hashes or offsets',()=>{const db=open({file:':memory:'});try{ingestSession(db,parsed('a'));ingestSession(db,parsed('b'));expect(inspectCoverage(db).state).toBe('partial');expect(backfillLegacy(db,{limit:1})).toEqual({completed:1,remaining:1});db.exec("CREATE TRIGGER injected_fail BEFORE INSERT ON evidence_units WHEN NEW.source_id=(SELECT source_id FROM memory_sources WHERE native_session_id='b') BEGIN SELECT RAISE(ABORT,'backfill failure'); END");expect(()=>backfillLegacy(db)).toThrow('backfill failure');expect(listSourceSpans(db,sourceId('claude','a')).evidence).toHaveLength(2);db.exec('DROP TRIGGER injected_fail');expect(backfillLegacy(db,{limit:1})).toEqual({completed:1,remaining:0});expect(backfillLegacy(db)).toEqual({completed:0,remaining:0});const result=listSourceSpans(db,sourceId('claude','b'));expect(result.source).toMatchObject({artifactBasis:'legacy_projection',artifactBytes:0,archiveRelativePath:null,completeness:'legacy'});expect(result.evidence.every(e=>e.provenance?.locator.mapping==='unavailable'&&e.provenance?.locator.rawStart===undefined)).toBe(true);expect(db.prepare('SELECT COUNT(*) n FROM exchanges').get()).toEqual({n:2});}finally{db.close();}});
it('retains ghost prompts with separate ghost role and migrates legacy author ambiguity',()=>{const db=open({file:':memory:'});try{db.prepare("INSERT INTO ghosts(session_id,harness,project,prompt_count,source) VALUES('ghost','claude','/p',1,'history')").run();db.prepare("INSERT INTO ghost_prompts(id,session_id,seq,text) VALUES('prompt','ghost',0,'ghost prompt only')").run();expect(backfillLegacyGhosts(db)).toBe(1);expect(backfillLegacyGhosts(db)).toBe(0);const ghost=listSourceSpans(db,sourceId('claude','ghost'));expect(ghost.evidence.map(x=>x.role)).toEqual(['ghost_prompt']);expect(ghost.source).toMatchObject({artifactBasis:'legacy_projection',availability:'lost',completeness:'partial'});ingestSession(db,parsed('a'));backfillLegacy(db);db.prepare("INSERT INTO notes(thread_id,session_id,decided,author,via,written_at) VALUES('a','a','legacy decision','user','cli','2026-01-01T00:00:00Z')").run();expect(backfillLegacyNotes(db)).toBe(1);expect(backfillLegacyNotes(db)).toBe(0);expect(inspectNotes(db,{project:'/p'})).toMatchObject([{authority:'unknown',authorClaim:'user',origin:'migration'}]);expect(db.prepare('SELECT decided FROM notes').get()).toEqual({decided:'legacy decision'});}finally{db.close();}});
it('rebuilds source-less conservative spans with verified tokenizer while retaining old notes/citations/tombstones',async()=>{const db=open({file:':memory:'});try{ingestSession(db,parsed('a'));backfillLegacy(db);const old=listSourceSpans(db,sourceId('claude','a'));const before=old.source!.revisionId;const oldRef=old.evidence[0]!.ref;const {writeMemoryNotes,queryCurrentNotes}=await import('../packages/core/src/memory/notes-store.js');const note=writeMemoryNotes(db,{requestKey:'supported',scope:{project:'/p'},originSourceId:oldRef.sourceId,origin:'api',entries:[{kind:'observation',text:'retained assertion',supports:[oldRef]}]});const {rebuildEvidenceSpans}=await import('../packages/core/src/memory/backfill.js');const tokenizer={assetHash:'synthetic-test-only',id:'synthetic',sourceBoundaries:(s:string)=>[0,...Array.from(s).map((_,i)=>i+1)].map((offsetUtf16,tokenEndOrdinal)=>({offsetUtf16,tokenEndOrdinal})),boundaries:(s:string)=>[0,...Array.from(s).map((_,i)=>i+1)],count:(s:string)=>s.length};expect(rebuildEvidenceSpans(db,{tokenizer})).toEqual({rebuilt:1,remaining:0});const current=listSourceSpans(db,oldRef.sourceId);expect(current.source!.revisionId).not.toBe(before);expect(current.source).toMatchObject({artifactBasis:'legacy_projection',artifactBytes:0,completeness:'legacy',archiveRelativePath:null});expect(listSourceSpans(db,oldRef.sourceId,before).evidence[0]!.ref).toEqual(oldRef);expect(queryCurrentNotes(db,{project:'/p'})).toMatchObject([{noteId:note.noteIds[0],supportRefs:[oldRef]}]);expect(rebuildEvidenceSpans(db,{tokenizer})).toEqual({rebuilt:0,remaining:0});expect(db.prepare('SELECT COUNT(*) n FROM forget_tombstones').get()).toEqual({n:0});}finally{db.close();}});
