import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {open,openSqliteReadOnly} from '../packages/core/src/db.js';
import {ingestSession} from '../packages/core/src/ingest.js';
import type {ParseResult} from '../packages/core/src/adapters/types.js';
import {MaintenanceWorker} from '../packages/core/src/memory/maintenance.js';
import {parseClaudeTranscript} from '../packages/core/src/parser/claude.js';
import {hash} from '../packages/core/src/memory/spans.js';
import {publishSource} from '../packages/core/src/memory/source.js';
import {NORMALIZATION_VERSION} from '../packages/core/src/memory/source.js';
import {CLAUDE_EVIDENCE_VERSION} from '../packages/core/src/parser/evidence.js';
import {enqueueJob} from '../packages/core/src/memory/jobs.js';
const cli=path.resolve('packages/cli/dist/potsherd.js');
function legacy():ParseResult{return {session:{id:'legacy-session',harness:'claude',sourcePath:'/unavailable/legacy-session',project:'/fictional/migrate',projectSlug:'migrate',startedAt:'',endedAt:'',isSidechain:false,counts:{userPrompts:1,assistantTurns:1,toolCalls:0,bytes:0},status:'archived'},exchanges:[{id:'legacy-exchange',sessionId:'legacy-session',seq:0,ts:'2026-01-01T00:00:00Z',userText:'legacy prompt',assistantText:'legacy response',toolCalls:[],filesTouched:[],isSidechain:false,redacted:true}],unknownTypes:{},endOffset:0,malformedLines:0};}
describe('explicit initialization acknowledgement and pipeline invalidation',()=>{
 it('acknowledges schema+all legacy note backfill despite missing semantic assets',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-init-'));const db=open({root});try{ingestSession(db,legacy());const insert=db.prepare("INSERT INTO notes(thread_id,session_id,decided,author,via,written_at) VALUES('legacy-session','legacy-session',?,'claimed-user','cli','2026-01-01T00:00:00Z')");for(let i=0;i<243;i++)insert.run('LEGACY_NOTE_'+i);db.close();const result=spawnSync(process.execPath,[cli,'maintain','--migrate','--json','--potsherd-dir',root],{env:{...process.env,POTSHERD_OFFLINE:'1'},encoding:'utf8',timeout:15000});expect(result.status,result.stderr).toBe(0);const receipt=JSON.parse(result.stdout);expect(receipt.initialization).toEqual({state:'ready',schemaVersion:18});expect(receipt.assets.state).toBe('missing_assets');expect(receipt.debt.blocked).toBeGreaterThan(0);const reader=openSqliteReadOnly(path.join(root,'potsherd.db'));try{expect(reader.prepare('SELECT COUNT(DISTINCT legacy_note_id) n FROM memory_note_events').get()).toMatchObject({n:243});expect(reader.prepare("SELECT COUNT(*) n FROM maintenance_jobs WHERE kind='rebuild' AND state<>'done'").get()).toMatchObject({n:0});}finally{reader.close();}}finally{try{db.close();}catch{}fs.rmSync(root,{recursive:true,force:true});}});
 it('does not acknowledge initialization over failed capture debt',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-init-failure-'));const db=open({root});try{enqueueJob(db,{kind:'capture',targetId:'not-enrolled',inputHash:'capture-debt'});db.close();const result=spawnSync(process.execPath,[cli,'maintain','--migrate','--json','--potsherd-dir',root],{env:{...process.env,POTSHERD_OFFLINE:'1'},encoding:'utf8',timeout:15000});expect(result.status,result.stderr).toBe(1);expect(JSON.parse(result.stdout).initialization.state).toBe('pending');}finally{try{db.close();}catch{}fs.rmSync(root,{recursive:true,force:true});}});
 it('requeues unchanged enrolled source metadata after an older pipeline even when old stat job was done',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-pipeline-')),claude=path.join(root,'claude'),dir=path.join(claude,'projects','p'),id='11111111-1111-4111-8111-111111111111';fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,id+'.jsonl');fs.writeFileSync(file,JSON.stringify({type:'user',uuid:'r1',sessionId:id,promptId:'p1',cwd:'/fictional/pipeline',message:{role:'user',content:'PIPELINE_UNCHANGED_42'}})+'\n');const result=spawnSync(process.execPath,[cli,'index','--no-embed','--quiet','--harness','claude','--claude-dir',claude,'--potsherd-dir',root],{env:{...process.env,POTSHERD_OFFLINE:'1'},encoding:'utf8',timeout:15000});expect(result.status,result.stderr).toBe(0);const db=open({root}),worker=new MaintenanceWorker(root,{db});try{const older=await parseClaudeTranscript(file);older.evidenceVersion='claude-records-v1';publishSource(db,{parsed:older,artifactHash:hash(fs.readFileSync(file)),artifactBytes:fs.statSync(file).size,fingerprint:hash(fs.readFileSync(file))});const stat=fs.statSync(file),oldInput=hash(file+'\0'+hash(JSON.stringify([stat.dev,stat.ino,stat.size,stat.mtimeMs,stat.ctimeMs])));enqueueJob(db,{kind:'capture',targetId:id,inputHash:oldInput});db.prepare("UPDATE maintenance_jobs SET state='done' WHERE kind='capture'").run();await worker.drainOnce();const revision=db.prepare('SELECT r.adapter_version,r.normalization_version FROM memory_sources s JOIN source_revisions r ON r.revision_id=s.active_revision_id WHERE s.native_session_id=?').get(id);expect(revision).toMatchObject({adapter_version:CLAUDE_EVIDENCE_VERSION,normalization_version:NORMALIZATION_VERSION});expect(db.prepare("SELECT COUNT(*) n FROM maintenance_jobs WHERE kind='capture' AND state='done'").get()).toMatchObject({n:2});}finally{await worker.close();db.close();fs.rmSync(root,{recursive:true,force:true});}});
});
