import { defaultBudget } from '../packages/core/src/memory/budget.js';
import type { EvidenceItem, MemoryResponse } from '../packages/core/src/memory/contracts.js';
export function compactFixture():MemoryResponse {
  const ref={sourceId:'s'.repeat(64),revisionId:'r'.repeat(64),spanId:'a'.repeat(64)};
  const text='Exact "cache.X_9" 日本語 😀\n';
  const evidence:EvidenceItem={ref,role:'tool_result',text,startUtf16:10,endUtf16:10+text.length,sourceEventAt:null,observedAt:'2026-09-01T00:00:00Z',project:'/toy',branch:null,toolOutcome:'unknown',authority:'source_evidence',citation:`span:${ref.sourceId}:${ref.revisionId}:${ref.spanId}@10-${10+text.length}`,historical:false,quoteBasis:'redacted_unit',provenance:{harness:'codex',nativeSessionId:'native',artifactHash:'h'.repeat(64),artifactBytes:42,artifactBasis:'raw_prefix',adapterVersion:'test',normalizationVersion:'test',locator:{recordKey:'record',mapping:'unavailable',extra:JSON.parse('{"__proto__":{"polluted":true},"constructor":"ordinary JSON", "empty":""}')},locatorFidelity:'record_id',timeBasis:'unknown',availability:'live',manifestHash:'m'.repeat(64),unitRevisionId:'u'.repeat(64),unitKey:'record',unitTextHash:'t'.repeat(64),spanTextHash:'z'.repeat(64),chunkPolicy:'span-v1',spanStartUtf16:0,spanEndUtf16:200,unitToolName:null,unitToolCallId:null,parentNativeSessionId:null,producerNameBasis:'unavailable'}};
  const second=structuredClone(evidence);second.ref.spanId='b'.repeat(64);second.citation=`span:${second.ref.sourceId}:${second.ref.revisionId}:${second.ref.spanId}`;
  return {contractVersion:2,requestId:'toy',coverage:{state:'complete_snapshot',snapshotEpochs:{evidence:1,notes:0,lineage:0,deletion:0,vector:0},scope:{project:'/toy'},capturedThrough:null,pendingSources:0,failedSources:0,omittedKinds:[],semantic:'disabled'},support:{state:'unassessed',method:'none',requirements:[{id:'r',text:'unassessed host claim',state:'unassessed',refs:[ref]}],unresolved:[]},evidence:[evidence,second],assertions:[],candidates:[{ref:{...ref,spanId:'c'.repeat(64)},score:0.1,lanes:['literal']}],budget:{tokenizerId:defaultBudget().tokenizerId,usedTokens:0,remainingTokens:0,truncated:false,omittedItems:0},warnings:[]};
}
