import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {describe,it,expect,vi} from 'vitest';
import {open,openSqliteReadOnly,type Db} from '../packages/core/src/db.js';
import {publishSource,readEpochs,readSpan} from '../packages/core/src/memory/source.js';
import {SpanDenseLane} from '../packages/core/src/memory/dense.js';
import {MaintenanceWorker,ensureSpanSpace,queueHistoricalEmbeddings,commitSpanVector} from '../packages/core/src/memory/maintenance.js';
import {LocalMemoryService} from '../packages/core/src/memory/service.js';
import {defaultBudget} from '../packages/core/src/memory/budget.js';
import {validSpanVector,validatedSpanVectorBlob} from '../packages/core/src/memory/vector-validation.js';
import {embeddingToBlob} from '../packages/core/src/embeddings.js';
import * as assets from '../packages/core/src/memory/assets.js';
import {claimLease} from '../packages/core/src/memory/leases.js';import {claimJob} from '../packages/core/src/memory/jobs.js';
import type {ParseResult} from '../packages/core/src/adapters/types.js';
const point=(coordinate=0)=>Array.from({length:384},(_,i)=>i===coordinate?1:0);
const scalarBounds=(text:string)=>[0,...Array.from(text).reduce<number[]>((out,c)=>{out.push((out.at(-1)??0)+c.length);return out;},[])];
// Synthetic geometry only. No real assets/model are loaded by these corruption controls.
const tokenizer={id:'synthetic-corruption-control',assetHash:assets.TOKENIZER_HASH,count:(s:string)=>Array.from(s).length,boundaries:scalarBounds,sourceBoundaries:(s:string)=>scalarBounds(s).map((offsetUtf16,tokenEndOrdinal)=>({offsetUtf16,tokenEndOrdinal}))};
function parsed(id:string,text:string,project='/synthetic'):ParseResult{return {session:{id,harness:'claude',sourcePath:'',project,projectSlug:'synthetic',startedAt:'',endedAt:'',isSidechain:false,counts:{userPrompts:1,assistantTurns:0,toolCalls:0,bytes:0},status:'live'},records:[{unitKey:'record',role:'user',text,eventAt:null,timeBasis:'unknown',project,locator:{recordKey:'record',mapping:'unavailable'},locatorFidelity:'record_id',recordType:'user'}],exchanges:[],endOffset:0,malformedLines:0,unknownTypes:{},evidenceVersion:'synthetic-corruption-v1'};}
function fixture(n=2){const root=fs.mkdtempSync(path.join(os.tmpdir(),'vector-corruption-')),db=open({root});ensureSpanSpace(db);const refs=[];for(let i=0;i<n;i++){const r=publishSource(db,{parsed:parsed('source'+i,'LEXICAL_FACT42 record '+i),artifactHash:'synthetic'+i,artifactBytes:0,tokenizer});const row=db.prepare('SELECT p.span_id,p.embedding_input_hash FROM revision_spans rs JOIN evidence_spans p ON p.span_id=rs.span_id WHERE rs.revision_id=?').get(r.revisionId) as {span_id:string;embedding_input_hash:string};db.prepare('INSERT INTO span_embeddings VALUES(?,?,?,?,?,NULL)').run(row.span_id,assets.DEFAULT_SPACE_ID,row.embedding_input_hash,embeddingToBlob(point()),'2026-01-01T00:00:00.000Z');refs.push({...r,spanId:row.span_id,inputHash:row.embedding_input_hash});}db.prepare("UPDATE maintenance_jobs SET state='done'").run();return {root,db,refs,close(){db.close();fs.rmSync(root,{recursive:true,force:true});}};}
function fakeEncoder(query=point()){return {encode:vi.fn(async()=>query),encodeBatch:vi.fn(async(texts:string[])=>texts.map(()=>point())),close:vi.fn(async()=>{})} as unknown as assets.LocalEncoder;}
async function search(db:Db,root:string,encoder=fakeEncoder()){const lane=new SpanDenseLane(db,{root,cacheDir:root,encoder});try{return await lane.search({query:'LEXICAL_FACT42',scope:{project:'/synthetic'},snapshotEpochs:readEpochs(db),limit:64});}finally{await lane.close();}}
function ready(){return vi.spyOn(assets,'inspectAssets').mockReturnValue({state:'ready'} as ReturnType<typeof assets.inspectAssets>);}
function corrupt(db:Db,span:string,vector:readonly number[]){db.prepare('UPDATE span_embeddings SET vector_blob=? WHERE span_id=? AND space_id=?').run(embeddingToBlob(vector),span,assets.DEFAULT_SPACE_ID);}
describe('structural validation of the pinned normalized representation',()=>{
 it('validates dimensions, finite Float32 values and norm without claiming general corruption detection',()=>{
  expect(validSpanVector(point())).toBe(true);expect(validatedSpanVectorBlob(embeddingToBlob(point()))).not.toBeNull();
  for(const value of [Array(384).fill(NaN),Array(384).fill(Infinity),Array(384).fill(0),Array(384).fill(1),point().slice(0,383)])expect(validSpanVector(value)).toBe(false);
  const overflowing=point();overflowing[0]=Number.MAX_VALUE;expect(Number.isFinite(overflowing[0]!)).toBe(true);expect(validatedSpanVectorBlob(embeddingToBlob(overflowing))).toBeNull();expect(validatedSpanVectorBlob(Buffer.alloc(1535))).toBeNull();
 });
 it('rejects invalid commits after conversion while preserving original payloads',()=>{const f=fixture(1);try{const at=claimLease(f.db,'maintenance')!;f.db.prepare("UPDATE maintenance_jobs SET state='pending'").run();const job=claimJob(f.db,at)!,ref=f.refs[0]!,before=f.db.prepare('SELECT vector_blob FROM span_embeddings').get();for(const value of [Array(384).fill(0),Array(384).fill(NaN),[Number.MAX_VALUE,...Array(383).fill(0)],point().slice(0,383)])expect(()=>commitSpanVector(f.db,at,job,ref.spanId,ref.inputHash,value)).toThrow('embedding_dimensions');expect(f.db.prepare('SELECT vector_blob FROM span_embeddings').get()).toEqual(before);
 }finally{f.close();}});
});
describe('read-only honest dense health and usable lexical evidence',()=>{
 it.each(['mixed','all'])('reports failed for %s nonfinite payloads and keeps valid candidates/evidence',async(mode)=>{const f=fixture(),mock=ready();try{corrupt(f.db,f.refs[0]!.spanId,Array(384).fill(NaN));if(mode==='all')corrupt(f.db,f.refs[1]!.spanId,Array(384).fill(NaN));const changes=f.db.prepare('SELECT total_changes() n').get(),jobs=f.db.prepare('SELECT * FROM maintenance_jobs').all();const result=await search(f.db,f.root);expect(result.state).toBe('failed');expect(result.candidates).toHaveLength(mode==='all'?0:1);expect(f.db.prepare('SELECT total_changes() n').get()).toEqual(changes);expect(f.db.prepare('SELECT * FROM maintenance_jobs').all()).toEqual(jobs);
  const readonly=openSqliteReadOnly(path.join(f.root,'potsherd.db'));try{const lane=new SpanDenseLane(readonly,{root:f.root,cacheDir:f.root,encoder:fakeEncoder()}),service=new LocalMemoryService(readonly,{root:f.root,dense:lane});const response=(await service.recall({query:'LEXICAL_FACT42',scope:{project:'/synthetic'},budget:defaultBudget()})).response;expect(response.coverage.semantic).toBe('failed');expect(response.evidence.some(item=>item.text.includes('LEXICAL_FACT42'))).toBe(true);expect((await search(readonly,f.root)).state).toBe('failed');}finally{readonly.close();}
 }finally{mock.mockRestore();f.close();}});
 it.each(['short','nan','zero','unnormalized'])('rejects %s query vectors without certifying readiness',async(kind)=>{const f=fixture(),mock=ready();try{const query=kind==='short'?point().slice(0,383):kind==='nan'?Array(384).fill(NaN):kind==='zero'?Array(384).fill(0):Array(384).fill(1);const result=await search(f.db,f.root,fakeEncoder(query));expect(result.state).toBe('failed');expect(result.candidates).toEqual([]);expect(queueHistoricalEmbeddings(f.db)).toBe(0);}finally{mock.mockRestore();f.close();}});
 it('keeps valid controls ready and handles missing/stale input hashes as building',async()=>{const f=fixture(),mock=ready();try{expect((await search(f.db,f.root)).state).toBe('ready');expect(queueHistoricalEmbeddings(f.db)).toBe(0);f.db.prepare('UPDATE span_embeddings SET input_hash=? WHERE span_id=?').run('wrong-input',f.refs[0]!.spanId);const incomplete=await search(f.db,f.root);expect(incomplete.state).toBe('building');expect(incomplete.candidates).toHaveLength(1);expect(queueHistoricalEmbeddings(f.db)).toBe(1);}finally{mock.mockRestore();f.close();}});
});
describe('repairable corruption debt and bounded maintenance',()=>{
 it.each(['nan','zero','unnormalized','wrong_dimension'])('repairs %s payloads, preserves valid payloads, and reopens completed repair debt',async(kind)=>{const f=fixture(),mock=ready(),encoder=fakeEncoder();let worker=new MaintenanceWorker(f.root,{db:f.db,encoder});try{const goodBefore=f.db.prepare('SELECT vector_blob FROM span_embeddings WHERE span_id=?').get(f.refs[1]!.spanId);
  if(kind==='wrong_dimension'){f.db.exec('DROP TRIGGER span_vector_bytes_update');f.db.prepare('UPDATE span_embeddings SET vector_blob=? WHERE span_id=?').run(Buffer.alloc(8),f.refs[0]!.spanId);f.db.exec("CREATE TRIGGER span_vector_bytes_update BEFORE UPDATE ON span_embeddings WHEN length(NEW.vector_blob)<>(SELECT dimensions*4 FROM embedding_spaces WHERE space_id=NEW.space_id) BEGIN SELECT RAISE(ABORT,'vector dimensions mismatch'); END");}else corrupt(f.db,f.refs[0]!.spanId,kind==='nan'?Array(384).fill(NaN):kind==='zero'?Array(384).fill(0):Array(384).fill(1));
  expect((await search(f.db,f.root)).state).toBe('failed');expect(queueHistoricalEmbeddings(f.db)).toBe(1);await worker.drainOnce();expect(encoder.encodeBatch).toHaveBeenCalledTimes(1);expect((await search(f.db,f.root)).state).toBe('ready');expect(f.db.prepare('SELECT vector_blob FROM span_embeddings WHERE span_id=?').get(f.refs[1]!.spanId)).toEqual(goodBefore);expect(queueHistoricalEmbeddings(f.db)).toBe(0);
  const job=f.db.prepare("SELECT job_id FROM maintenance_jobs WHERE target_revision_id=? AND input_hash<>(SELECT manifest_hash FROM source_revisions WHERE revision_id=?)").get(f.refs[0]!.revisionId,f.refs[0]!.revisionId) as {job_id:string};corrupt(f.db,f.refs[0]!.spanId,Array(384).fill(NaN));expect(queueHistoricalEmbeddings(f.db)).toBe(1);expect(f.db.prepare('SELECT state,error_code FROM maintenance_jobs WHERE job_id=?').get(job.job_id)).toMatchObject({state:'pending',error_code:'vector_repair_required'});await worker.close();worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fakeEncoder()});await worker.drainOnce();expect((await search(f.db,f.root)).state).toBe('ready');const reopened=openSqliteReadOnly(path.join(f.root,'potsherd.db'));try{expect((await search(reopened,f.root)).state).toBe('ready');}finally{reopened.close();}
 }finally{await worker.close();mock.mockRestore();f.close();}});
 it('repairs all invalid targets while keeping batches at most2 and exact memberships/hashes intact',async()=>{const f=fixture(5),mock=ready(),encoder=fakeEncoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder});try{const rows=f.db.prepare('SELECT span_id,space_id,input_hash FROM span_embeddings ORDER BY span_id').all();for(const ref of f.refs)corrupt(f.db,ref.spanId,Array(384).fill(NaN));expect(queueHistoricalEmbeddings(f.db)).toBe(5);await worker.drainOnce();expect(f.db.prepare('SELECT span_id,space_id,input_hash FROM span_embeddings ORDER BY span_id').all()).toEqual(rows);expect((encoder.encodeBatch as ReturnType<typeof vi.fn>).mock.calls.every(call=>(call[0] as string[]).length<=2)).toBe(true);expect((await search(f.db,f.root)).state).toBe('ready');expect(queueHistoricalEmbeddings(f.db)).toBe(0);expect(f.db.prepare("SELECT COUNT(*) n FROM maintenance_jobs WHERE state<>'done'").get()).toEqual({n:0});for(const ref of f.refs)expect(readSpan(f.db,ref)?.text).toContain('LEXICAL_FACT42');
 }finally{await worker.close();mock.mockRestore();f.close();}});
});
describe('bounded multi-page repair and representation fences',()=>{
 it('repairs131 spans in one revision through bounded pages/batches without losing tail memberships',async()=>{const f=fixture(0),mock=ready(),encoder=fakeEncoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder});try{const p=parsed('large',''),records=Array.from({length:131},(_,i)=>({...parsed('large','LEXICAL_FACT42 tail '+i).records![0]!,unitKey:'record'+i,locator:{recordKey:'record'+i,mapping:'unavailable' as const}}));p.records=records;const publication=publishSource(f.db,{parsed:p,artifactHash:'many-records',artifactBytes:0,tokenizer});const refs=f.db.prepare('SELECT p.span_id,p.embedding_input_hash FROM revision_spans rs JOIN evidence_spans p ON p.span_id=rs.span_id WHERE rs.revision_id=? ORDER BY rs.ordinal').all(publication.revisionId) as {span_id:string;embedding_input_hash:string}[];for(const row of refs)f.db.prepare('INSERT INTO span_embeddings VALUES(?,?,?,?,?,NULL)').run(row.span_id,assets.DEFAULT_SPACE_ID,row.embedding_input_hash,embeddingToBlob(Array(384).fill(NaN)),'2026-01-01T00:00:00.000Z');f.db.prepare("UPDATE maintenance_jobs SET state='done'").run();expect((await search(f.db,f.root)).state).toBe('failed');expect(queueHistoricalEmbeddings(f.db)).toBe(1);await worker.drainOnce();expect((encoder.encodeBatch as ReturnType<typeof vi.fn>).mock.calls).toHaveLength(66);expect((encoder.encodeBatch as ReturnType<typeof vi.fn>).mock.calls.slice(0,-1).every(call=>(call[0] as string[]).length===2)).toBe(true);expect((encoder.encodeBatch as ReturnType<typeof vi.fn>).mock.calls.at(-1)![0]).toHaveLength(1);expect((await search(f.db,f.root)).state).toBe('ready');expect(f.db.prepare('SELECT COUNT(*) n FROM span_embeddings').get()).toEqual({n:131});expect(queueHistoricalEmbeddings(f.db)).toBe(0);expect(readSpan(f.db,{sourceId:publication.sourceId,revisionId:publication.revisionId,spanId:refs.at(-1)!.span_id})?.text).toContain('tail 130');
 }finally{await worker.close();mock.mockRestore();f.close();}});
 it('never accepts wrong-space/context vectors as repaired current representation',async()=>{const f=fixture(1),mock=ready(),encoder=fakeEncoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder});try{const old=f.refs[0]!;f.db.prepare("INSERT INTO embedding_spaces SELECT 'wrong-space',model_id,model_revision,model_asset_hash,tokenizer_hash,runtime_version,dtype,'cls',query_prefix,normalization,dimensions,chunk_policy,created_at,'retired' FROM embedding_spaces WHERE space_id=?").run(assets.DEFAULT_SPACE_ID);f.db.prepare("UPDATE span_embeddings SET space_id='wrong-space'").run();const prior=f.db.prepare('SELECT * FROM span_embeddings').all();const newer=publishSource(f.db,{parsed:parsed('source0','LEXICAL_FACT42 record 0','/different-context'),artifactHash:'synthetic0',artifactBytes:0,tokenizer});expect(queueHistoricalEmbeddings(f.db)).toBe(2);await worker.drainOnce();expect(encoder.encodeBatch).toHaveBeenCalledTimes(2);expect(f.db.prepare("SELECT * FROM span_embeddings WHERE space_id='wrong-space'").all()).toEqual(prior);const currentRef=f.db.prepare('SELECT span_id FROM revision_spans WHERE revision_id=?').get(newer.revisionId) as {span_id:string};expect(f.db.prepare('SELECT COUNT(*) n FROM span_embeddings WHERE span_id=? AND space_id=?').get(currentRef.span_id,assets.DEFAULT_SPACE_ID)).toEqual({n:1});
 }finally{await worker.close();mock.mockRestore();f.close();}});
 it('a replacement lease prevents a corrupt-target repair commit',async()=>{const f=fixture(1),mock=ready(),encoder=fakeEncoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder});try{corrupt(f.db,f.refs[0]!.spanId,Array(384).fill(NaN));(encoder.encodeBatch as ReturnType<typeof vi.fn>).mockImplementation(async(texts:string[])=>{f.db.prepare("UPDATE maintenance_leases SET generation=generation+1,owner_token='replacement' WHERE lane='maintenance'").run();return texts.map(()=>point());});await expect(worker.drainOnce()).rejects.toThrow('lease_superseded');expect(validatedSpanVectorBlob((f.db.prepare('SELECT vector_blob FROM span_embeddings').get() as {vector_blob:Buffer}).vector_blob)).toBeNull();expect((await search(f.db,f.root)).state).toBe('failed');
 }finally{await worker.close();mock.mockRestore();f.close();}});
});
it('records the independent2-source corruption case and actual deterministic repair',async()=>{const f=fixture(),mock=ready(),encoder=fakeEncoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder});try{for(const ref of f.refs)corrupt(f.db,ref.spanId,Array(384).fill(NaN));const invalid=await search(f.db,f.root);expect(invalid).toMatchObject({state:'failed',candidates:[]});const queued=queueHistoricalEmbeddings(f.db);expect(queued).toBe(2);await worker.drainOnce();const repaired=await search(f.db,f.root);expect(repaired.state).toBe('ready');expect(repaired.candidates).toHaveLength(2);const remaining=queueHistoricalEmbeddings(f.db);expect(remaining).toBe(0);if(process.env.POTSHERD_VECTOR_REPAIR_RECEIPT)fs.writeFileSync(process.env.POTSHERD_VECTOR_REPAIR_RECEIPT,JSON.stringify({createdAt:new Date().toISOString(),protocol:'Actual task-private2-source corruption injection, valid normalized deterministic query/repair encoder, no inference',driver:process.env.POTSHERD_SQLITE??'default',invalid,queued,repaired,remaining,encoderBatches:(encoder.encodeBatch as ReturnType<typeof vi.fn>).mock.calls.map(call=>(call[0] as string[]).length),allCommittedPayloadsValid:(f.db.prepare('SELECT vector_blob FROM span_embeddings').all() as {vector_blob:Buffer}[]).every(row=>validatedSpanVectorBlob(row.vector_blob)!==null)},null,2)+'\n');
}finally{await worker.close();mock.mockRestore();f.close();}});
async function until(check:()=>boolean){for(let i=0;i<100;i++){if(check())return;await new Promise(resolve=>setTimeout(resolve,5));}throw new Error('configured maintainer did not complete the bounded control');}
describe('explicit maintainer lifecycle owns unattended repair',()=>{
 it('detects post-start idle corruption on the60s poll cycle and reopens completed debt with a controlled clock',async()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-01-01T00:00:00Z'));const f=fixture(1),mock=ready(),encoder=fakeEncoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder,intervalMs:10});try{worker.start();await new Promise(resolve=>setTimeout(resolve,20));expect(encoder.encodeBatch).not.toHaveBeenCalled();expect(f.db.prepare("SELECT COUNT(*) n FROM maintenance_jobs WHERE state<>'done'").get()).toEqual({n:0});for(let cycle=1;cycle<=2;cycle++){corrupt(f.db,f.refs[0]!.spanId,Array(384).fill(NaN));vi.setSystemTime(new Date(Date.UTC(2026,0,1,0,cycle,1)));await until(()=>validatedSpanVectorBlob((f.db.prepare('SELECT vector_blob FROM span_embeddings').get() as {vector_blob:Buffer}).vector_blob)!==null);await until(()=>(f.db.prepare("SELECT COUNT(*) n FROM maintenance_jobs WHERE state<>'done'").get() as {n:number}).n===0);}expect(encoder.encodeBatch).toHaveBeenCalledTimes(2);expect((await search(f.db,f.root)).state).toBe('ready');
 }finally{await worker.close();mock.mockRestore();f.close();vi.useRealTimers();}});
 it('repairs post-start corruption through an actual configured timer without manual drain or reader writes',async()=>{const f=fixture(1),mock=ready(),encoder=fakeEncoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder,intervalMs:10,vectorValidationIntervalMs:25});try{worker.start();await new Promise(resolve=>setTimeout(resolve,20));corrupt(f.db,f.refs[0]!.spanId,Array(384).fill(NaN));await until(()=>validatedSpanVectorBlob((f.db.prepare('SELECT vector_blob FROM span_embeddings').get() as {vector_blob:Buffer}).vector_blob)!==null);expect(encoder.encodeBatch).toHaveBeenCalledTimes(1);expect((await search(f.db,f.root)).state).toBe('ready');
 }finally{await worker.close();mock.mockRestore();f.close();}});
 it('an already-aborted validation pass publishes no repair jobs or temporary state',()=>{const f=fixture(),controller=new AbortController();try{corrupt(f.db,f.refs[0]!.spanId,Array(384).fill(NaN));controller.abort(new Error('validation cancelled'));const jobs=f.db.prepare('SELECT * FROM maintenance_jobs').all();expect(()=>queueHistoricalEmbeddings(f.db,{signal:controller.signal})).toThrow('validation cancelled');expect(f.db.prepare('SELECT * FROM maintenance_jobs').all()).toEqual(jobs);expect(f.db.prepare("SELECT name FROM temp.sqlite_master WHERE name LIKE 'memory_vector_%'").all()).toEqual([]);}finally{f.close();}});
});
