import { it,expect } from 'vitest';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { open } from '../packages/core/src/db.js';
import { publishSource,readSpan } from '../packages/core/src/memory/source.js';
import { writeMemoryNotes,queryCurrentNotes } from '../packages/core/src/memory/notes-store.js';
import { applyForget,previewForget,recoverForget } from '../packages/core/src/memory/delete.js';
import { hash } from '../packages/core/src/memory/spans.js';
import type { ParseResult } from '../packages/core/src/adapters/types.js';
function parsed(id:string):ParseResult{return {session:{id,harness:'claude',sourcePath:`/synthetic/${id}`,project:'/p',projectSlug:'p',startedAt:'',endedAt:'',isSidechain:false,counts:{userPrompts:1,assistantTurns:0,toolCalls:0,bytes:3},status:'live'},exchanges:[],unknownTypes:{},endOffset:3,malformedLines:0,evidenceVersion:'test',records:[{unitKey:'user:record',role:'user',text:'retained quote',eventAt:'2026-01-01T00:00:00Z',timeBasis:'record',project:'/p',locator:{recordKey:'record',mapping:'unavailable'},locatorFidelity:'record_id',recordType:'user'}]};}
function span(db:ReturnType<typeof open>,p:ReturnType<typeof publishSource>){const row=db.prepare('SELECT span_id FROM revision_spans WHERE revision_id=?').get(p.revisionId) as {span_id:string};return {sourceId:p.sourceId,revisionId:p.revisionId,spanId:row.span_id};}
it('forgets source-linked prose conservatively while preserving independent evidence and durable suppression',()=>{const db=open({file:':memory:'});try{const p=parsed('one');const a=publishSource(db,{parsed:p,artifactHash:hash('raw'),artifactBytes:3});const b=publishSource(db,{parsed:parsed('two'),artifactHash:hash('raw2'),artifactBytes:4});const ar=span(db,a),br=span(db,b);const derived=writeMemoryNotes(db,{requestKey:'derived',origin:'mcp',scope:{project:'/p'},originSourceId:a.sourceId,entries:[{kind:'observation',text:'source quote paraphrase',supports:[ar]}]});const shared=writeMemoryNotes(db,{requestKey:'shared',origin:'mcp',scope:{project:'/p'},entries:[{kind:'decision',text:'jointly linked assertion',supports:[ar,br]}]});const preview=previewForget(db,{sourceId:a.sourceId});expect(preview.noteIds).toEqual([...derived.noteIds,...shared.noteIds].sort());const receipt=applyForget(db,{requestKey:'forget',target:{sourceId:a.sourceId}},{expectedPreviewHash:preview.previewHash});expect(receipt.logicalForgetComplete).toBe(true);expect(readSpan(db,ar)).toBeNull();expect(readSpan(db,br)).not.toBeNull();expect(queryCurrentNotes(db,{project:'/p'})).toEqual([]);expect(()=>publishSource(db,{parsed:p,artifactHash:hash('raw'),artifactBytes:3})).toThrow('forgotten');expect(applyForget(db,{requestKey:'forget',target:{sourceId:a.sourceId}})).toEqual(receipt);expect(db.prepare("SELECT COUNT(*) n FROM maintenance_jobs WHERE target_id=? AND state<>'cancelled'").get(a.sourceId)).toEqual({n:0});}finally{db.close();}});
it('keeps archive deletion pending without a root then recovers without losing tombstones',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-forget-'));const db=open({root});try{const bytes=Buffer.from('raw');const artifactHash=hash(bytes);const relative=`archive/evidence/${artifactHash}.jsonl`;fs.mkdirSync(path.join(root,'archive','evidence'),{recursive:true});fs.writeFileSync(path.join(root,relative),bytes);const a=publishSource(db,{parsed:parsed('one'),artifactHash,artifactBytes:3,archiveRelativePath:relative});const receipt=applyForget(db,{requestKey:'forget',target:{sourceId:a.sourceId}});expect(receipt.logicalForgetComplete).toBe(false);expect(fs.existsSync(path.join(root,relative))).toBe(true);expect(recoverForget(db,{root})[0]).toMatchObject({logicalForgetComplete:true,archivePending:0});expect(fs.existsSync(path.join(root,relative))).toBe(false);expect(db.prepare("SELECT state FROM forget_tombstones WHERE source_id=?").get(a.sourceId)).toEqual({state:'complete'});}finally{db.close();fs.rmSync(root,{recursive:true,force:true});}});
it('does not unlink an immutable artifact still owned by another retained source',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-shared-'));const db=open({root});try{const artifactHash=hash('same raw');const relative=`archive/evidence/${artifactHash}.jsonl`;fs.mkdirSync(path.join(root,'archive','evidence'),{recursive:true});fs.writeFileSync(path.join(root,relative),'same raw');const a=publishSource(db,{parsed:parsed('one'),artifactHash,artifactBytes:8,archiveRelativePath:relative});const b=publishSource(db,{parsed:parsed('two'),artifactHash,artifactBytes:8,archiveRelativePath:relative});expect(applyForget(db,{requestKey:'a',target:{sourceId:a.sourceId}},{root}).logicalForgetComplete).toBe(true);expect(fs.existsSync(path.join(root,relative))).toBe(true);expect(readSpan(db,span(db,b))).not.toBeNull();expect(applyForget(db,{requestKey:'b',target:{sourceId:b.sourceId}},{root}).logicalForgetComplete).toBe(true);expect(fs.existsSync(path.join(root,relative))).toBe(false);}finally{db.close();fs.rmSync(root,{recursive:true,force:true});}});
it('rejects a stale preview and leaves all writes intact',()=>{const db=open({file:':memory:'});try{const a=publishSource(db,{parsed:parsed('one'),artifactHash:hash('raw'),artifactBytes:3});const preview=previewForget(db,{sourceId:a.sourceId});writeMemoryNotes(db,{requestKey:'new',scope:{project:'/p'},originSourceId:a.sourceId,origin:'api',entries:[{kind:'observation',text:'new source note',supports:[span(db,a)]}]});expect(()=>applyForget(db,{requestKey:'forget',target:{sourceId:a.sourceId}},{expectedPreviewHash:preview.previewHash})).toThrow('stale');expect(readSpan(db,span(db,a))).not.toBeNull();expect(queryCurrentNotes(db,{project:'/p'})).toHaveLength(1);expect(db.prepare('SELECT COUNT(*) n FROM forget_tombstones').get()).toEqual({n:0});}finally{db.close();}});
it('journals legacy card ownership before deleting compatibility rows when root is temporarily unavailable',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-card-forget-'));const db=open({root});try{const {ingestSession}=await import('../packages/core/src/ingest.js');const p=parsed('one');ingestSession(db,p);const card=path.join(root,'cards','claude','p','one.md');fs.mkdirSync(path.dirname(card),{recursive:true});fs.writeFileSync(card,'source derived private card');const a=publishSource(db,{parsed:p,artifactHash:hash('raw'),artifactBytes:3});const receipt=applyForget(db,{requestKey:'forget',target:{sourceId:a.sourceId}});expect(receipt.logicalForgetComplete).toBe(false);expect(fs.existsSync(card)).toBe(true);expect(db.prepare('SELECT COUNT(*) n FROM sessions').get()).toEqual({n:0});expect(recoverForget(db,{root})[0]!.logicalForgetComplete).toBe(true);expect(fs.existsSync(card)).toBe(false);}finally{db.close();fs.rmSync(root,{recursive:true,force:true});}});

it('does not use an unrelated surviving ref to retain copied forgotten prose, while B-only notes survive',()=>{const db=open({file:':memory:'});try{const a=publishSource(db,{parsed:parsed('A'),artifactHash:hash('A'),artifactBytes:1});const p=parsed('B');p.records![0]!.text='unrelated surviving source';const b=publishSource(db,{parsed:p,artifactHash:hash('B'),artifactBytes:1});const ar=span(db,a),br=span(db,b);const linked=writeMemoryNotes(db,{requestKey:'copied-A',scope:{project:'/p'},origin:'api',entries:[{kind:'observation',text:'retained quote',supports:[ar,br]}]});const onlyB=writeMemoryNotes(db,{requestKey:'only-B',scope:{project:'/p'},origin:'api',originSourceId:b.sourceId,entries:[{kind:'observation',text:'B author assertion',supports:[br]}]});applyForget(db,{requestKey:'forget-A',target:{sourceId:a.sourceId}});const notes=queryCurrentNotes(db,{project:'/p'});expect(notes.map(n=>n.noteId)).toEqual(onlyB.noteIds);expect(db.prepare('SELECT 1 FROM memory_note_events WHERE note_id=?').get(linked.noteIds[0])).toBeUndefined();expect(readSpan(db,br)).not.toBeNull();expect(db.prepare('SELECT COUNT(*) n FROM memory_notes_fts WHERE memory_notes_fts MATCH ?').get('retained')).toEqual({n:0});}finally{db.close();}});

it('preserves foreign legacy annotations and mapped B notes when canonical A shares the native ID',async()=>{
 const {ingestSession}=await import('../packages/core/src/ingest.js');const {addNote}=await import('../packages/core/src/notes.js');const {applyTags,pinSession,linkSessions}=await import('../packages/core/src/tags.js');const {backfillLegacyNotes}=await import('../packages/core/src/memory/notes-store.js');
 const db=open({file:':memory:'});try{
  const b=parsed('same');b.session.harness='codex';b.records![0]!.text='B independently retained';ingestSession(db,b);const pb=publishSource(db,{parsed:b,artifactHash:hash('B'),artifactBytes:1});
  applyTags(db,'same',{add:['b-tag']});pinSession(db,'same');linkSessions(db,'same','peer','B link');const note=addNote(db,{sessionId:'same',decided:'B original note',via:'api'});expect(backfillLegacyNotes(db)).toBe(1);
  const a=parsed('same');const pa=publishSource(db,{parsed:a,artifactHash:hash('A'),artifactBytes:1});const ar=span(db,pa),br=span(db,pb);const aNote=writeMemoryNotes(db,{requestKey:'A-note',scope:{project:'/p'},originSourceId:pa.sourceId,entries:[{kind:'observation',text:'A source note',supports:[ar]}],origin:'api'});
  const before={tags:db.prepare('SELECT * FROM tags').all(),pins:db.prepare('SELECT * FROM pins').all(),links:db.prepare('SELECT * FROM links').all(),legacy:db.prepare('SELECT * FROM notes').all(),bNotes:queryCurrentNotes(db,{sourceIds:[pb.sourceId]})};
  const receipt=applyForget(db,{requestKey:'A-forget',target:{sourceId:pa.sourceId}});expect(receipt.removedNotes).toBe(1);expect(receipt.logicalForgetComplete).toBe(false);expect(receipt.archivePending).toBe(0);expect(receipt.retainedLegacyAnnotations).toEqual([{nativeSessionId:'same',ownership:'ambiguous',notes:0,tags:1,pins:1,links:1}]);expect(applyForget(db,{requestKey:'A-forget',target:{sourceId:pa.sourceId}})).toEqual(receipt);expect(db.prepare('SELECT state FROM forget_tombstones WHERE source_id=?').get(pa.sourceId)).toEqual({state:'complete'});expect(readSpan(db,ar)).toBeNull();expect(readSpan(db,br)).not.toBeNull();expect(()=>publishSource(db,{parsed:a,artifactHash:hash('A'),artifactBytes:1})).toThrow('forgotten');
  expect(db.prepare('SELECT * FROM tags').all()).toEqual(before.tags);expect(db.prepare('SELECT * FROM pins').all()).toEqual(before.pins);expect(db.prepare('SELECT * FROM links').all()).toEqual(before.links);expect(db.prepare('SELECT * FROM notes').all()).toEqual(before.legacy);expect(queryCurrentNotes(db,{sourceIds:[pb.sourceId]})).toEqual(before.bNotes);expect(db.prepare('SELECT harness FROM sessions WHERE id=?').get('same')).toEqual({harness:'codex'});expect(db.prepare('SELECT 1 FROM memory_note_events WHERE note_id=?').get(aNote.noteIds[0])).toBeUndefined();expect(db.prepare('SELECT decided FROM notes WHERE id=?').get(note.note.id)).toEqual({decided:'B original note'});expect(db.prepare("SELECT COUNT(*) n FROM notes_fts WHERE notes_fts MATCH 'original'").get()).toEqual({n:1});db.prepare("INSERT INTO notes_fts(notes_fts,rank) VALUES('integrity-check',1)").run();
 }finally{db.close();}
});
it('retains ambiguous unmapped legacy notes without assigning them to a surviving source',async()=>{
 const {ingestSession}=await import('../packages/core/src/ingest.js');const {addNote}=await import('../packages/core/src/notes.js');const {backfillLegacyNotes}=await import('../packages/core/src/memory/notes-store.js');const {LocalMemoryService}=await import('../packages/core/src/memory/service.js');
 const db=open({file:':memory:'});try{const a=parsed('same');ingestSession(db,a);const pa=publishSource(db,{parsed:a,artifactHash:hash('A'),artifactBytes:1});const b=parsed('same');b.session.harness='codex';const pb=publishSource(db,{parsed:b,artifactHash:hash('B'),artifactBytes:1});const note=addNote(db,{sessionId:'same',decided:'ambiguous retained assertion',via:'api'});expect(backfillLegacyNotes(db)).toBe(0);const receipt=applyForget(db,{requestKey:'forget-A',target:{sourceId:pa.sourceId}});expect(receipt.logicalForgetComplete).toBe(false);expect(receipt.retainedLegacyAnnotations).toEqual([{nativeSessionId:'same',ownership:'ambiguous',notes:1,tags:0,pins:0,links:0}]);ingestSession(db,b);expect(backfillLegacyNotes(db)).toBe(0);expect(queryCurrentNotes(db,{sourceIds:[pb.sourceId]})).toEqual([]);expect(db.prepare('SELECT decided FROM notes WHERE id=?').get(note.note.id)).toEqual({decided:'ambiguous retained assertion'});const coverage=new LocalMemoryService(db).inspect({sourceIds:[pb.sourceId]});expect(coverage.state).toBe('partial');expect(coverage.omittedKinds).toContain('legacy_note_ownership_ambiguous');}finally{db.close();}
});
it('clears ordinary unique-source legacy annotations and mapped note prose',async()=>{
 const {ingestSession}=await import('../packages/core/src/ingest.js');const {addNote}=await import('../packages/core/src/notes.js');const {applyTags,pinSession,linkSessions}=await import('../packages/core/src/tags.js');const {backfillLegacyNotes}=await import('../packages/core/src/memory/notes-store.js');
 const db=open({file:':memory:'});try{const p=parsed('unique');ingestSession(db,p);const pub=publishSource(db,{parsed:p,artifactHash:hash('unique'),artifactBytes:1});applyTags(db,'unique',{add:['owned']});pinSession(db,'unique');linkSessions(db,'unique','peer','owned');addNote(db,{sessionId:'unique',decided:'source-owned note',open:'owned unresolved',next:'owned followup',via:'api'});expect(backfillLegacyNotes(db)).toBe(1);const receipt=applyForget(db,{requestKey:'forget-unique',target:{sourceId:pub.sourceId}});expect(applyForget(db,{requestKey:'forget-unique',target:{sourceId:pub.sourceId}})).toEqual(receipt);expect(db.prepare("SELECT COUNT(*) n FROM notes_fts WHERE notes_fts MATCH 'owned'").get()).toEqual({n:0});db.prepare("INSERT INTO notes_fts(notes_fts,rank) VALUES('integrity-check',1)").run();expect(db.prepare('PRAGMA integrity_check').get()).toEqual({integrity_check:'ok'});expect(db.prepare('SELECT * FROM tags').all()).toEqual([]);expect(db.prepare('SELECT * FROM pins').all()).toEqual([]);expect(db.prepare('SELECT * FROM links').all()).toEqual([]);expect(db.prepare('SELECT decided,open,next_step FROM notes').all()).toEqual([{decided:'',open:'',next_step:''}]);expect(queryCurrentNotes(db)).toEqual([]);}finally{db.close();}
});

it('rolls back a failed forget without changing annotations, source visibility or search index',async()=>{
 const {ingestSession}=await import('../packages/core/src/ingest.js');const {addNote}=await import('../packages/core/src/notes.js');const {backfillLegacyNotes}=await import('../packages/core/src/memory/notes-store.js');
 const db=open({file:':memory:'});try{const p=parsed('rollback');ingestSession(db,p);const pub=publishSource(db,{parsed:p,artifactHash:hash('rollback'),artifactBytes:1});const ref=span(db,pub);addNote(db,{sessionId:'rollback',decided:'rollback owned note',via:'api'});expect(backfillLegacyNotes(db)).toBe(1);const original=queryCurrentNotes(db);db.prepare("CREATE TRIGGER fail_forget BEFORE DELETE ON evidence_units BEGIN SELECT RAISE(ABORT,'controlled_forget_failure'); END").run();expect(()=>applyForget(db,{requestKey:'rollback-forget',target:{sourceId:pub.sourceId}})).toThrow('controlled_forget_failure');expect(queryCurrentNotes(db)).toEqual(original);expect(readSpan(db,ref)).not.toBeNull();expect(db.prepare('SELECT COUNT(*) n FROM forget_tombstones').get()).toEqual({n:0});expect(db.prepare("SELECT COUNT(*) n FROM notes_fts WHERE notes_fts MATCH 'rollback'").get()).toEqual({n:1});db.prepare("INSERT INTO notes_fts(notes_fts,rank) VALUES('integrity-check',1)").run();db.prepare('DROP TRIGGER fail_forget').run();expect(applyForget(db,{requestKey:'rollback-forget',target:{sourceId:pub.sourceId}}).removedNotes).toBe(1);expect(readSpan(db,ref)).toBeNull();expect(queryCurrentNotes(db)).toEqual([]);expect(db.prepare("SELECT COUNT(*) n FROM notes_fts WHERE notes_fts MATCH 'rollback'").get()).toEqual({n:0});}finally{db.close();}
});

it('does not call explicitly mapped foreign-only notes ambiguous retention',async()=>{const {ingestSession}=await import('../packages/core/src/ingest.js');const {addNote}=await import('../packages/core/src/notes.js');const {backfillLegacyNotes}=await import('../packages/core/src/memory/notes-store.js');const db=open({file:':memory:'});try{const b=parsed('mapped-only');b.session.harness='codex';ingestSession(db,b);const pb=publishSource(db,{parsed:b,artifactHash:hash('B-only'),artifactBytes:1});addNote(db,{sessionId:'mapped-only',decided:'B mapped assertion',via:'api'});backfillLegacyNotes(db);const a=parsed('mapped-only');const pa=publishSource(db,{parsed:a,artifactHash:hash('A-only'),artifactBytes:1});const before=queryCurrentNotes(db,{sourceIds:[pb.sourceId]});const receipt=applyForget(db,{requestKey:'A-mapped-only',target:{sourceId:pa.sourceId}});expect(receipt.logicalForgetComplete).toBe(true);expect(receipt.retainedLegacyAnnotations).toBeUndefined();expect(queryCurrentNotes(db,{sourceIds:[pb.sourceId]})).toEqual(before);}finally{db.close();}});

it('retains ambiguity for foreign legacy-only projections after canonical A is forgotten',async()=>{const {ingestSession}=await import('../packages/core/src/ingest.js');const {addNote}=await import('../packages/core/src/notes.js');const {backfillLegacyNotes}=await import('../packages/core/src/memory/notes-store.js');const {mustResolve}=await import('../packages/cli/src/session-ref.js');const db=open({file:':memory:'});try{const a=publishSource(db,{parsed:parsed('legacy-only'),artifactHash:hash('A-legacy-only'),artifactBytes:1});const b=parsed('legacy-only');b.session.harness='codex';ingestSession(db,b);addNote(db,{sessionId:'legacy-only',decided:'unmapped ambiguous legacy note',via:'api'});expect(backfillLegacyNotes(db)).toBe(0);expect(()=>mustResolve(db,'legacy-only','pin')).toThrow('multiple harnesses');const receipt=applyForget(db,{requestKey:'A-legacy-only',target:{sourceId:a.sourceId}});expect(receipt.logicalForgetComplete).toBe(false);expect(receipt.retainedLegacyAnnotations![0]!.notes).toBe(1);expect(()=>mustResolve(db,'legacy-only','pin')).toThrow('multiple harnesses');expect(backfillLegacyNotes(db)).toBe(0);expect(queryCurrentNotes(db)).toEqual([]);const unique=parsed('legacy-unique');unique.session.harness='codex';ingestSession(db,unique);expect(mustResolve(db,'legacy-unique','pin').id).toBe('legacy-unique');addNote(db,{sessionId:'legacy-unique',decided:'ordinary known legacy assertion',via:'api'});expect(backfillLegacyNotes(db)).toBe(1);db.prepare("UPDATE sessions SET harness='' WHERE id='legacy-unique'").run();expect(()=>mustResolve(db,'legacy-unique','pin')).toThrow('organization is ambiguous');}finally{db.close();}});
