import { testModelCache } from './model-cache.js';
import { describe,it,expect,afterEach,vi } from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { open } from '../packages/core/src/db.js';
import { publishSource,sourceId,readSpan } from '../packages/core/src/memory/source.js';
import { hash,spanWindows,reassembleUnit } from '../packages/core/src/memory/spans.js';
import { indexAll } from '../packages/core/src/ingest.js';
import type { ParseResult } from '../packages/core/src/adapters/types.js';
const cache=testModelCache('/nonexistent/potsherd-test-models');
const dirs:string[]=[];afterEach(()=>{dirs.splice(0).forEach(x=>fs.rmSync(x,{recursive:true,force:true}));});
function parsed(text='hello 😀'.repeat(150)):ParseResult{return {session:{id:'n',harness:'claude',sourcePath:'/synthetic/n',project:'/p',projectSlug:'p',startedAt:'',endedAt:'',isSidechain:false,counts:{userPrompts:1,assistantTurns:0,toolCalls:0,bytes:10},status:'live'},exchanges:[],unknownTypes:{},endOffset:10,malformedLines:0,evidenceVersion:'test-v1',records:[{unitKey:'user:r',role:'user',text,eventAt:null,timeBasis:'unknown',locator:{recordKey:'r',mapping:'unavailable'},locatorFidelity:'record_id',recordType:'user'}]};}
describe('immutable canonical evidence',()=>{
 it('reassembles Unicode exactly, quotes stored redacted spans and retains historical revision',()=>{const db=open({file:':memory:'});try{const p=parsed();const a=publishSource(db,{parsed:p,artifactHash:hash('raw'),artifactBytes:3});const ids=db.prepare('SELECT span_id FROM revision_spans WHERE revision_id=? ORDER BY ordinal').all(a.revisionId) as {span_id:string}[];expect(ids.length).toBeGreaterThan(1);const old=readSpan(db,{...a,spanId:ids[0]!.span_id})!;expect(old.text).toBe(p.records![0]!.text.slice(old.startUtf16,old.endUtf16));expect(reassembleUnit(spanWindows(p.records![0]!.text))).toBe(p.records![0]!.text);publishSource(db,{parsed:parsed('changed'),artifactHash:hash('raw2'),artifactBytes:4});expect(readSpan(db,old.ref)).toMatchObject({text:old.text,historical:true,quoteBasis:'redacted_unit'});}finally{db.close();}});
 it('changes snapshot identity for changed event metadata without losing prior membership',()=>{const db=open({file:':memory:'});try{const p=parsed('same');const a=publishSource(db,{parsed:p,artifactHash:'a',artifactBytes:1});p.records![0]!.eventAt='2026-01-01T00:00:00Z';p.records![0]!.timeBasis='record';const b=publishSource(db,{parsed:p,artifactHash:'a',artifactBytes:1});expect(a.revisionId).not.toBe(b.revisionId);expect(db.prepare('SELECT COUNT(*) n FROM evidence_units').get()).toEqual({n:2});}finally{db.close();}});
 it('redacts before persistence and atomically rolls back failed required stages',()=>{const db=open({file:':memory:'});try{expect(()=>publishSource(db,{parsed:parsed('password=supersecret1234567890'),artifactHash:'a',artifactBytes:1,publishAuxiliary:()=>{throw new Error('ledger');}})).toThrow('ledger');expect(db.prepare('SELECT COUNT(*) n FROM memory_sources').get()).toEqual({n:0});publishSource(db,{parsed:parsed('password=supersecret1234567890'),artifactHash:'a',artifactBytes:1});expect(JSON.stringify(db.prepare('SELECT text FROM evidence_units').all())).not.toContain('supersecret1234567890');}finally{db.close();}});
});
describe('capture acknowledgments',()=>{
 function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-capture-'));dirs.push(root);const claude=path.join(root,'claude');const project=path.join(claude,'projects','-tmp-project');fs.mkdirSync(project,{recursive:true});const file=path.join(project,'11111111-1111-4111-8111-111111111111.jsonl');fs.writeFileSync(file,JSON.stringify({type:'user',uuid:'r1',sessionId:'11111111-1111-4111-8111-111111111111',promptId:'p1',timestamp:'2026-01-01T00:00:00Z',cwd:'/p',message:{role:'user',content:'first'}})+'\n');const db=open({root});return {root,claude,file,db};}
 it('L2 retries required lineage failure on unchanged bytes and rolls back body/FTS/stamp',async()=>{const f=fixture();try{f.db.exec("CREATE TRIGGER injected_fail BEFORE INSERT ON session_record_ids BEGIN SELECT RAISE(ABORT,'fault'); END");const one=await indexAll({db:f.db,root:f.root,claudeDir:f.claude,harnesses:['claude'],embed:false});expect(one.totals.failed).toBe(1);expect(f.db.prepare('SELECT COUNT(*) n FROM sessions').get()).toEqual({n:0});expect(f.db.prepare('SELECT value FROM sync_state WHERE key=?').get('index:claude')).toBeUndefined();f.db.exec('DROP TRIGGER injected_fail');const two=await indexAll({db:f.db,root:f.root,claudeDir:f.claude,harnesses:['claude'],embed:false});expect(two.totals.parsed).toBe(1);expect(f.db.prepare('SELECT COUNT(*) n FROM session_record_ids').get()).toEqual({n:1});expect((await indexAll({db:f.db,root:f.root,claudeDir:f.claude,harnesses:['claude'],embed:false})).totals.skipped).toBe(1);}finally{f.db.close();}});
 it('captures appended assistant/tool outcomes on an open exchange and detects same-stat rewrite',async()=>{const f=fixture();try{await indexAll({db:f.db,root:f.root,claudeDir:f.claude,harnesses:['claude'],embed:false});fs.appendFileSync(f.file,JSON.stringify({type:'assistant',uuid:'a1',sessionId:'11111111-1111-4111-8111-111111111111',timestamp:'2026-01-01T00:00:01Z',message:{role:'assistant',content:[{type:'text',text:'done'},{type:'tool_use',id:'t1',name:'shell',input:{cmd:'echo ok'}}]}})+'\n'+JSON.stringify({type:'user',uuid:'t2',sessionId:'11111111-1111-4111-8111-111111111111',message:{role:'user',content:[{type:'tool_result',tool_use_id:'t1',is_error:false,content:'ok'}]}})+'\n');await indexAll({db:f.db,root:f.root,claudeDir:f.claude,harnesses:['claude'],embed:false});expect(f.db.prepare("SELECT role,outcome FROM evidence_units WHERE role='tool_result'").get()).toEqual({role:'tool_result',outcome:'success'});const stat=fs.statSync(f.file);fs.writeFileSync(f.file,fs.readFileSync(f.file,'utf8').replace('first','other'));fs.utimesSync(f.file,stat.atime,stat.mtime);const next=await indexAll({db:f.db,root:f.root,claudeDir:f.claude,harnesses:['claude'],embed:false});expect(next.totals.parsed).toBe(1);expect(f.db.prepare('SELECT text FROM evidence_units u JOIN revision_units ru ON ru.unit_revision_id=u.unit_revision_id JOIN memory_sources s ON s.active_revision_id=ru.revision_id WHERE u.role=?').get('user')).toEqual({text:'other'});expect(sourceId('claude','n')).not.toBe(sourceId('codex','n'));}finally{f.db.close();}});
});
describe('enrolled source roots and public provenance',()=>{
 it('does not add real source roots on an unqualified follow-up',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-enroll-'));dirs.push(root);const claude=path.join(root,'empty-claude');fs.mkdirSync(claude);const db=open({root});try{const first=await indexAll({db,root,claudeDir:claude,harnesses:['claude'],embed:false});expect(first.harnesses.map(x=>x.harness)).toEqual(['claude']);const next=await indexAll({db,root,embed:false});expect(next.harnesses.map(x=>x.harness)).toEqual(['claude']);expect(next.harnesses[0]!.sourceDir).toContain(claude);}finally{db.close();}});
 it('exposes raw and normalized provenance without alias paths',()=>{const db=open({file:':memory:'});try{const p=parsed('quote');const a=publishSource(db,{parsed:p,artifactHash:hash('raw'),artifactBytes:3});const row=db.prepare('SELECT span_id FROM revision_spans WHERE revision_id=?').get(a.revisionId) as {span_id:string};const item=readSpan(db,{...a,spanId:row.span_id})!;expect(item.provenance).toMatchObject({harness:'claude',nativeSessionId:'n',artifactBasis:'raw_prefix',locator:{mapping:'unavailable'},timeBasis:'unknown'});expect(JSON.stringify(item)).not.toContain('/synthetic/n');}finally{db.close();}});
});

it('rejects stale async capture and ownership-fence loss without changing active evidence',()=>{const db=open({file:':memory:'});try{const a=publishSource(db,{parsed:parsed('a'),artifactHash:hash('a'),artifactBytes:1,expectedActiveRevisionId:null});const b=publishSource(db,{parsed:parsed('b'),artifactHash:hash('b'),artifactBytes:1,expectedActiveRevisionId:a.revisionId});expect(()=>publishSource(db,{parsed:parsed('stale'),artifactHash:hash('stale'),artifactBytes:5,expectedActiveRevisionId:a.revisionId})).toThrow('stale');expect(()=>publishSource(db,{parsed:parsed('lost'),artifactHash:hash('lost'),artifactBytes:4,expectedActiveRevisionId:b.revisionId,beforeCommit:()=>{throw new Error('lease lost');}})).toThrow('lease lost');expect(db.prepare('SELECT active_revision_id FROM memory_sources WHERE source_id=?').get(a.sourceId)).toEqual({active_revision_id:b.revisionId});expect(db.prepare('SELECT COUNT(*) n FROM source_revisions').get()).toEqual({n:2});}finally{db.close();}});
it('binds compatibility, evidence, lineage and archive to one immutable snapshot during original rewrite',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-snapshot-'));dirs.push(root);const claude=path.join(root,'claude');const project=path.join(claude,'projects','p');fs.mkdirSync(project,{recursive:true});const id='11111111-1111-4111-8111-111111111111';const file=path.join(project,`${id}.jsonl`);const original=JSON.stringify({type:'user',uuid:'record-old',sessionId:id,promptId:'old',cwd:'/p',message:{role:'user',content:'snapshot old'}})+'\n';fs.writeFileSync(file,original);const replacement=original.replace('snapshot old','snapshot new').replace('record-old','record-new');const writeFile=fs.writeFileSync;let injected=false;const spy=vi.spyOn(fs,'writeFileSync').mockImplementation(((target:fs.PathOrFileDescriptor,data:string|NodeJS.ArrayBufferView,opts:fs.WriteFileOptions)=>{writeFile(target,data,opts);if(typeof target==='string'&&target.includes('capture-scratch')&&!injected){injected=true;writeFile(file,replacement);}}) as typeof fs.writeFileSync);const db=open({root});try{const report=await indexAll({db,root,claudeDir:claude,harnesses:['claude'],embed:false});expect(report.totals.failed).toBe(0);expect(db.prepare('SELECT user_text FROM exchanges').get()).toEqual({user_text:'snapshot old'});expect(db.prepare('SELECT text FROM evidence_units').get()).toEqual({text:'snapshot old'});expect(db.prepare('SELECT record_id FROM session_record_ids').get()).toEqual({record_id:'record-old'});const revision=db.prepare('SELECT artifact_hash,archive_relative_path FROM source_revisions').get() as {artifact_hash:string;archive_relative_path:string};expect(revision.artifact_hash).toBe(hash(original));expect(fs.readFileSync(path.join(root,revision.archive_relative_path),'utf8')).toBe(original);spy.mockRestore();expect((await indexAll({db,root,embed:false})).totals.parsed).toBe(1);expect(db.prepare('SELECT user_text FROM exchanges').get()).toEqual({user_text:'snapshot new'});}finally{spy.mockRestore();db.close();}});

it('L1 retries a transient stable-metadata read failure without losing the successful source',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-retry-'));dirs.push(root);const claude=path.join(root,'claude');const project=path.join(claude,'projects','p');fs.mkdirSync(project,{recursive:true});const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222'];const files=ids.map(id=>{const file=path.join(project,`${id}.jsonl`);fs.writeFileSync(file,JSON.stringify({type:'user',uuid:`r-${id}`,sessionId:id,promptId:'p',cwd:'/p',message:{role:'user',content:'durable retry'}})+'\n');return file;});const db=open({root});const read=fs.readFileSync;const spy=vi.spyOn(fs,'readFileSync').mockImplementation(((file:fs.PathOrFileDescriptor,opts:unknown)=>{if(file===files[1]){const err=new Error('injected EACCES') as NodeJS.ErrnoException;err.code='EACCES';throw err;}return read(file,opts as never);}) as typeof fs.readFileSync);try{const first=await indexAll({db,root,claudeDir:claude,harnesses:['claude'],embed:false});expect(first.totals.parsed).toBe(1);expect(first.totals.failed).toBe(1);expect(db.prepare('SELECT value FROM sync_state WHERE key=?').get('index:claude')).toBeUndefined();spy.mockRestore();const second=await indexAll({db,root,embed:false});expect(second.totals.parsed).toBe(1);expect(second.totals.skipped).toBe(1);expect(second.totals.failed).toBe(0);expect((await indexAll({db,root,embed:false})).totals.skipped).toBe(2);}finally{spy.mockRestore();db.close();}});
it('bounds immutable record context separately from exact quoted partitions',()=>{const tokenizer={assetHash:'synthetic-scalar-tokenizer',id:'synthetic-test-only',boundaries:(s:string)=>[0,...Array.from(s).reduce<number[]>((a,c)=>{a.push((a.at(-1)??0)+c.length);return a;},[])],count:(s:string)=>Array.from(s).length};const text='A😀 '.repeat(400);const windows=spanWindows(text,tokenizer,'x'.repeat(100));expect(reassembleUnit(windows)).toBe(text);expect(windows.some(s=>s.isPartition===false)).toBe(true);for(const s of windows){const context=JSON.parse(s.embeddingContextJson).context as string;expect(context.length).toBeLessThanOrEqual(64);expect(tokenizer.count(`${context}

${s.text}`)+2).toBeLessThanOrEqual(384);expect(s.text).toBe(text.slice(s.startUtf16,s.endUtf16));expect(s.text).not.toContain('x');}});
it.skipIf(!fs.existsSync(path.join(cache,'Xenova/bge-small-en-v1.5/tokenizer.json')))('pins real cached BGE wordpieces for long synthetic Unicode/identifier spans',async()=>{const {loadSpanTokenizer}=await import('../packages/core/src/memory/tokenization.js');const {spanEmbeddingText}=await import('../packages/core/src/memory/spans.js');const tokenizer=await loadSpanTokenizer(cache);expect(tokenizer).not.toBeNull();if(!tokenizer)throw new Error('verified cached tokenizer missing');const text=(`cache_retry_counter identifier_really_long_multipart_symbol_123 Café 日本語 😀

`).repeat(120);const windows=spanWindows(text,tokenizer,`[project:/synthetic/p]
[role:tool_result]
[tool:shell]
[outcome:success]`);expect(reassembleUnit(windows)).toBe(text);for(const window of windows){expect(tokenizer.count(spanEmbeddingText(window.text,window.embeddingContextJson))+2).toBeLessThanOrEqual(384);expect(window.embeddingInputHash).toBe(hash(spanEmbeddingText(window.text,window.embeddingContextJson)));expect(window.text).toBe(text.slice(window.startUtf16,window.endUtf16));expect(JSON.parse(window.embeddingContextJson).contextTokens).toBeLessThanOrEqual(64);}});
it('retains conflicting alias revisions without changing active evidence or acknowledging the conflict',()=>{const db=open({file:':memory:'});try{const original=parsed('original');const first=publishSource(db,{parsed:original,artifactHash:hash('raw original'),artifactBytes:12});const other=parsed('different');other.session.sourcePath='/synthetic/other-alias';const publishCompatibility=vi.fn();const second=publishSource(db,{parsed:other,artifactHash:hash('raw different'),artifactBytes:13,expectedActiveRevisionId:first.revisionId,publishCompatibility});expect(second.conflict).toBe(true);expect(publishCompatibility).not.toHaveBeenCalled();expect(db.prepare('SELECT active_revision_id,availability FROM memory_sources WHERE source_id=?').get(first.sourceId)).toEqual({active_revision_id:first.revisionId,availability:'conflict'});expect(db.prepare('SELECT acknowledged_revision_id,error_code FROM capture_checkpoints WHERE source_id=?').get(first.sourceId)).toEqual({acknowledged_revision_id:first.revisionId,error_code:'alias_conflict'});expect(db.prepare('SELECT COUNT(*) n FROM source_revisions').get()).toEqual({n:2});expect(publishSource(db,{parsed:other,artifactHash:hash('raw different'),artifactBytes:13}).conflict).toBe(true);}finally{db.close();}});
it('keeps newer live append active when an older complete-prefix archive is rediscovered',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-prefix-'));dirs.push(root);const claude=path.join(root,'claude');const slug='-tmp-prefix';const id='11111111-1111-4111-8111-111111111111';const project=path.join(claude,'projects',slug);fs.mkdirSync(project,{recursive:true});const file=path.join(project,`${id}.jsonl`);const first=JSON.stringify({type:'user',uuid:'u',sessionId:id,promptId:'p',cwd:'/p',message:{role:'user',content:'prefix prompt'}})+'\n';const append=JSON.stringify({type:'assistant',uuid:'a',sessionId:id,message:{role:'assistant',content:'new observed answer'}})+'\n';fs.writeFileSync(file,first);const db=open({root});try{await indexAll({db,root,claudeDir:claude,harnesses:['claude'],embed:false});fs.appendFileSync(file,append);await indexAll({db,root,embed:false});const latest=db.prepare('SELECT active_revision_id FROM memory_sources WHERE native_session_id=?').get(id) as {active_revision_id:string};const archive=path.join(root,'archive','claude',slug,`${id}.jsonl`);fs.mkdirSync(path.dirname(archive),{recursive:true});fs.writeFileSync(archive,first+'{"pending":');fs.unlinkSync(file);const older=await indexAll({db,root,embed:false});expect(older.totals.failed).toBe(0);expect(older.totals.parsed).toBe(1);expect(db.prepare('SELECT active_revision_id,availability FROM memory_sources WHERE native_session_id=?').get(id)).toMatchObject({active_revision_id:latest.active_revision_id,availability:'archived'});expect(db.prepare('SELECT assistant_text FROM exchanges').get()).toEqual({assistant_text:'new observed answer'});expect(db.prepare('SELECT acknowledged_revision_id,error_code FROM capture_checkpoints').get()).toEqual({acknowledged_revision_id:latest.active_revision_id,error_code:null});expect((await indexAll({db,root,embed:false})).totals.skipped).toBe(1);}finally{db.close();}});
