import { it,expect,describe } from 'vitest';
import { open } from '../packages/core/src/db.js';
import { writeMemoryNotes,inspectNotes,queryCurrentNotes } from '../packages/core/src/memory/notes-store.js';
import type { WriteInput } from '../packages/core/src/memory/contracts.js';
const write=(requestKey:string,text:string,extra:Partial<WriteInput>={}):WriteInput=>({requestKey,scope:{project:'/p',branch:'main'},entries:[{kind:'decision',text}],origin:'mcp',...extra});
describe('durable sourced author assertions',()=>{
 it('is redacted/idempotent, rejects changed retries and claimed human authority',()=>{const db=open({file:':memory:'});try{const input=write('one','password=supersecret1234567890',{authorClaim:'user'});const a=writeMemoryNotes(db,input);expect(a.authority).toBe('agent_assertion');expect(a.redacted).toBe(true);expect(writeMemoryNotes(db,input)).toEqual(a);expect(()=>writeMemoryNotes(db,write('one','changed'))).toThrow('idempotency');expect(()=>writeMemoryNotes(db,{...write('two','human'),authority:'user_attested' as never})).toThrow('attestation');expect(queryCurrentNotes(db,{project:'/p'})[0]!.text).not.toContain('supersecret1234567890');expect(db.prepare('SELECT COUNT(*) n FROM memory_note_events').get()).toEqual({n:1});expect(db.prepare("SELECT COUNT(*) n FROM memory_notes_fts WHERE memory_notes_fts MATCH 'password'").get()).toEqual({n:1});}finally{db.close();}});
 it('preserves history, uses explicit same-scope supersession and rejects cross-branch changes',()=>{const db=open({file:':memory:'});try{const first=writeMemoryNotes(db,write('first','use library A',{entries:[{kind:'decision',text:'use library A',eventAt:'2026-01-01T00:00:00Z'}]}));const second=writeMemoryNotes(db,write('second','use library B',{entries:[{kind:'decision',text:'use library B',eventAt:'2026-01-02T00:00:00Z',supersedes:first.noteIds}]}));expect(queryCurrentNotes(db,{project:'/p',branch:'main'}).map(n=>n.noteId)).toEqual(second.noteIds);expect(inspectNotes(db,{project:'/p',includeHistory:true})).toHaveLength(2);expect(queryCurrentNotes(db,{project:'/p',branch:'main',asOf:'2026-01-01T12:00:00Z'}).map(n=>n.noteId)).toEqual(first.noteIds);expect(()=>writeMemoryNotes(db,write('bad','other',{scope:{project:'/p',branch:'fork'},entries:[{kind:'decision',text:'other',supersedes:second.noteIds}]}))).toThrow('scope');expect(db.prepare('SELECT COUNT(*) n FROM memory_write_receipts').get()).toEqual({n:2});}finally{db.close();}});
 it('does not infer newest truth, does not promote unknown dates under strict asOf, rejects oversize writes atomically',()=>{const db=open({file:':memory:'});try{writeMemoryNotes(db,write('a','A'));writeMemoryNotes(db,write('b','B'));expect(queryCurrentNotes(db,{project:'/p',branch:'main'})).toHaveLength(2);expect(queryCurrentNotes(db,{project:'/p',asOf:'2026-01-01T00:00:00Z'})).toEqual([]);expect(()=>writeMemoryNotes(db,write('c','x'.repeat(2001)))).toThrow('limits');expect(db.prepare('SELECT COUNT(*) n FROM memory_write_receipts').get()).toEqual({n:2});}finally{db.close();}});
});
it('serializes actual parallel CLI writers before idempotency reads and durably returns identical receipts',async()=>{const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path');const {spawn}=await import('node:child_process');const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-parallel-notes-'));const db=open({root});db.close();const writeInput={requestKey:'same-parallel-request',scope:{project:'/parallel'},entries:[{kind:'observation',text:'durably committed parallel assertion'}],origin:'cli'};const run=()=>new Promise<{code:number|null;stdout:string;stderr:string}>(resolve=>{const child=spawn(process.execPath,[path.resolve('packages/cli/bin/potsherd.js'),'note','--potsherd-dir',root,'--input-json',JSON.stringify(writeInput)],{env:{...process.env,POTSHERD_SQLITE:process.env.POTSHERD_SQLITE??'better-sqlite3'}});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);child.on('close',code=>resolve({code,stdout,stderr}));});try{const results=await Promise.all(Array.from({length:6},run));for(const result of results)expect(result.code,result.stderr).toBe(0);const receipts=results.map(r=>JSON.parse(r.stdout));expect(receipts.every(r=>r.noteIds[0]===receipts[0].noteIds[0])).toBe(true);const stored=open({root});try{expect(stored.prepare('SELECT COUNT(*) n FROM memory_note_events').get()).toEqual({n:1});expect(stored.prepare('SELECT COUNT(*) n FROM memory_write_receipts').get()).toEqual({n:1});expect(stored.prepare('PRAGMA synchronous').get()).toMatchObject({synchronous:2});}finally{stored.close();}}finally{fs.rmSync(root,{recursive:true,force:true});}},30000);
it('honors public CLI note budgets before commit and keeps response budget out of write identity',async()=>{const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path');const {spawnSync}=await import('node:child_process');const {defaultBudget,countTokens}=await import('../packages/core/src/memory/budget.js');const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-cli-budget-'));open({root}).close();const input={requestKey:'budget-stable',scope:{project:'/synthetic'},entries:[{kind:'decision',text:'budget respects durable receipt'}]};const run=(maxTokens:number)=>spawnSync(process.execPath,[path.resolve('packages/cli/bin/potsherd.js'),'note','--potsherd-dir',root,'--input-json',JSON.stringify({...input,budget:defaultBudget(maxTokens)})],{encoding:'utf8',env:{...process.env,POTSHERD_SQLITE:process.env.POTSHERD_SQLITE??'node'}});try{const small=run(64);expect(small.status).toBe(1);expect(countTokens(small.stdout)).toBeLessThanOrEqual(64);const first=open({root});expect(first.prepare('SELECT COUNT(*) n FROM memory_note_events').get()).toEqual({n:0});first.close();const accepted=run(1024),retry=run(2048);expect(accepted.status,accepted.stderr).toBe(0);expect(retry.status,retry.stderr).toBe(0);expect(JSON.parse(accepted.stdout).noteIds).toEqual(JSON.parse(retry.stdout).noteIds);const final=open({root});expect(final.prepare('SELECT COUNT(*) n FROM memory_note_events').get()).toEqual({n:1});final.close();}finally{fs.rmSync(root,{recursive:true,force:true});}},30000);
