import fs from 'node:fs';import path from 'node:path';import {afterEach,describe,it,expect} from 'vitest';
import {db as store,indexAll,LocalMemoryService,defaultBudget,showSession,inspectNotes,readSpan,listSourceSpans,sourceId,writeMemoryNotes,NORMALIZATION_VERSION} from '@potsherd/core';
import {parseClaudeTranscript} from '../packages/core/src/parser/claude.js';import {hash,identity,spanWindows} from '../packages/core/src/memory/spans.js';import {redact} from '../packages/core/src/redact.js';import {tempDir,rmrf} from './helpers.js';
const synthetic='0a1b2c3d4e5f60718293a4b5c6d7e8f9';const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(rmrf));
function insert(db:store.Db,table:string,row:Record<string,unknown>){const keys=Object.keys(row);db.prepare(`INSERT INTO ${table} (${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).run(...keys.map(key=>row[key]));}
/** Valid synthetic ledger in the earlier, explicitly declared v2 normalization. */
async function oldStore(){
 const root=tempDir('privacy-refresh-');roots.push(root);const claude=path.join(root,'claude'),dir=path.join(claude,'projects','synthetic');fs.mkdirSync(dir,{recursive:true});const native='privacy-native',file=path.join(dir,native+'.jsonl'),project='/tmp/synthetic-privacy',at='2026-01-01T00:00:00.000Z';
 const rows=[{type:'user',uuid:'u',promptId:'p',message:{role:'user',content:'Inspect the socket client'}},{type:'assistant',uuid:'a',message:{role:'assistant',content:[{type:'tool_use',id:'call',name:'Bash',input:{command:'inspect socket client'}}]}},{type:'user',uuid:'r',message:{role:'user',content:[{type:'tool_result',tool_use_id:'call',is_error:false,content:`COMMAND_MARKER --socket-auth ${synthetic} completed`}]}}].map(row=>({...row,sessionId:native,cwd:project,gitBranch:'main',timestamp:at}));const raw=Buffer.from(rows.map(row=>JSON.stringify(row)).join('\n')+'\n');fs.writeFileSync(file,raw);const parsed=await parseClaudeTranscript(file),db=store.open({root}),sid=sourceId('claude',native),norm='redacted-evidence-v2';
 const units=parsed.records!.map(record=>{const locator=JSON.stringify(record.locator),uid=identity(sid,record.unitKey,hash(record.text),norm,record.role,locator,record.eventAt??'',record.timeBasis,record.project??'',record.branch??'',record.toolName??'',record.toolCallId??'',record.outcome??'',record.locatorFidelity);const windows=spanWindows(record.text,undefined,`[project:${record.project??'unknown'}]\n[role:${record.role}]\n[tool:${record.toolName??'none'}]\n[outcome:${record.outcome??'unknown'}]`);return {record,locator,uid,windows};});
 const manifest=hash(JSON.stringify(units.map(unit=>({id:unit.uid,partitions:unit.windows.map(window=>[window.startUtf16,window.endUtf16,window.chunkPolicy])})))),digest=hash(raw),rid=identity(sid,digest,parsed.evidenceVersion!,norm,manifest),relative=path.join('archive','evidence',digest+'.jsonl');fs.mkdirSync(path.join(root,path.dirname(relative)),{recursive:true});fs.writeFileSync(path.join(root,relative),raw);
 insert(db,'memory_sources',{source_id:sid,harness:'claude',native_session_id:native,active_revision_id:null,project,availability:'live',created_at:at});insert(db,'source_revisions',{revision_id:rid,source_id:sid,artifact_hash:digest,artifact_bytes:raw.length,archive_relative_path:relative,adapter_version:parsed.evidenceVersion,normalization_version:norm,manifest_hash:manifest,event_min:at,event_max:at,observed_at:at,project,branch:'main',completeness:'complete',coverage_gaps_json:'{}'});
 const refs:{ref:{sourceId:string;revisionId:string;spanId:string};role:string}[]=[];let ordinal=0;units.forEach((unit,index)=>{const r=unit.record;db.prepare('INSERT INTO evidence_units VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(unit.uid,sid,r.unitKey,r.role,r.text,hash(r.text),norm,r.toolName??null,r.toolCallId??null,r.outcome??null,r.eventAt,r.timeBasis,r.project??null,r.branch??null,unit.locator,r.locatorFidelity,r.exchangeId??null,r.seq??null);db.prepare('INSERT INTO revision_units VALUES(?,?,?)').run(rid,unit.uid,index);for(const w of unit.windows){const spanId=identity(sid,unit.uid,String(w.startUtf16),String(w.endUtf16),w.chunkPolicy),added=db.prepare('INSERT INTO evidence_spans(span_id,unit_revision_id,start_utf16,end_utf16,text,text_hash,chunk_policy,embedding_input_hash,embedding_context_json) VALUES(?,?,?,?,?,?,?,?,?)').run(spanId,unit.uid,w.startUtf16,w.endUtf16,w.text,hash(w.text),w.chunkPolicy,w.embeddingInputHash,w.embeddingContextJson);db.prepare('INSERT INTO spans_fts(rowid,text) VALUES(?,?)').run(added.lastInsertRowid,w.text);db.prepare('INSERT INTO revision_spans VALUES(?,?,?)').run(rid,spanId,ordinal++);refs.push({ref:{sourceId:sid,revisionId:rid,spanId},role:r.role});}});
 db.prepare('UPDATE memory_sources SET active_revision_id=? WHERE source_id=?').run(rid,sid);insert(db,'source_aliases',{source_id:sid,path:file,kind:'live',last_seen_at:at,last_stat_json:JSON.stringify({bytes:raw.length}),artifact_hash:digest,missing_at:null});insert(db,'capture_checkpoints',{source_id:sid,discovered_fingerprint:digest,acknowledged_fingerprint:digest,acknowledged_revision_id:rid,consumed_offset:raw.length,reopen_offset:0,prefix_hash:digest,continuation_json:JSON.stringify(parsed.continuation),last_success_at:at,last_error_at:null,error_code:null});
 insert(db,'memory_note_events',{note_id:'old-sensitive-note',batch_id:'old-batch',origin_source_id:sid,kind:'observation',text:`NOTE_MARKER --socket-auth ${synthetic}`,text_hash:hash(`NOTE_MARKER --socket-auth ${synthetic}`),project,branch:'main',event_at:at,observed_at:at,author_claim:'claimed-author',origin:'api',authority:'unknown',support_status:'unverified',normalization_version:norm});
 const e=parsed.exchanges[0]!;insert(db,'sessions',{id:native,harness:'claude',project,git_branch:'main'});insert(db,'exchanges',{id:e.id,session_id:native,seq:e.seq,user_text:e.userText,assistant_text:e.assistantText});insert(db,'tool_calls',{id:e.id+':0',exchange_id:e.id,name:'Bash',input:e.toolCalls[0]!.input,result:e.toolCalls[0]!.result,is_error:0});
 db.exec("INSERT INTO exchanges_fts(exchanges_fts) VALUES('rebuild'); INSERT INTO memory_notes_fts(memory_notes_fts) VALUES('rebuild')");
 return {root,claude,db,sid,refs,raw,relative,project};
}
describe('current privacy policy over prior immutable values',()=>{
 it('masks space/equals/quoted socket-auth arguments but retains flags and variable/placeholders',()=>{for(const text of [`--socket-auth ${synthetic}`,`--socket-auth=${synthetic}`,`--socket-auth "${synthetic}"`,`"--socket-auth" '${synthetic}'`]){const result=redact(text);expect(result.text).not.toContain(synthetic);expect(result.text).toContain('--socket-auth');expect(result.hits).toHaveLength(1);}for(const text of ['--socket-auth $SOCKET_AUTH','--socket-auth "example-value"'])expect(redact(text).text).toBe(text);});
 it('refuses affected old refs/notes, preserves identity and storage, then reprocesses unchanged input without rewriting old proof',async()=>{
  const f=await oldStore();try{const service=new LocalMemoryService(f.db);const sensitive=f.refs.find(item=>item.role==='tool_result')!.ref,safe=f.refs.find(item=>item.role==='user')!.ref,before=f.db.prepare('SELECT unit_revision_id,text,text_hash FROM evidence_units ORDER BY unit_revision_id').all();
   const response=service.read({refs:[sensitive],scope:{project:f.project},budget:defaultBudget()}).response;if(!('evidence' in response))throw new Error('budget failed');expect(response.evidence).toEqual([]);expect(response.warnings).toContain('privacy_refresh_required');expect(JSON.stringify(response)).not.toContain(synthetic);expect(readSpan(f.db,safe)?.text).toBe('Inspect the socket client');
   const notes=inspectNotes(f.db,{project:f.project});expect(notes[0]).toMatchObject({noteId:'old-sensitive-note',authorClaim:'claimed-author',authority:'unknown',text:'',availability:'privacy_refresh_required'});expect(JSON.stringify(showSession(f.db,'privacy-native'))).not.toContain(synthetic);
   expect(()=>writeMemoryNotes(f.db,{requestKey:'bad-old-support',scope:{project:f.project,branch:'main'},entries:[{kind:'next',text:'inspect safely',supports:[sensitive]}],origin:'api'})).toThrow('privacy_refresh_required');
   expect(f.db.prepare('SELECT unit_revision_id,text,text_hash FROM evidence_units ORDER BY unit_revision_id').all()).toEqual(before);const indexed=await indexAll({db:f.db,root:f.root,claudeDir:f.claude,harnesses:['claude'],embed:false});expect(indexed.totals.parsed,JSON.stringify({harnesses:indexed.harnesses,totals:indexed.totals,normalizer:NORMALIZATION_VERSION})).toBe(1);expect(indexed.totals.failed).toBe(0);
   const current=listSourceSpans(f.db,f.sid);expect(current.source!.normalizationVersion).toBe(NORMALIZATION_VERSION);expect(JSON.stringify(current.evidence)).not.toContain(synthetic);expect(current.source!.revisionId).not.toBe(sensitive.revisionId);expect(readSpan(f.db,sensitive)).toBeNull();expect(readSpan(f.db,safe)?.text).toBe('Inspect the socket client');expect(fs.readFileSync(path.join(f.root,f.relative))).toEqual(f.raw);expect(fs.readFileSync(path.join(f.claude,'projects','synthetic','privacy-native.jsonl'))).toEqual(f.raw);
   const hint=service.read({refs:[sensitive],scope:{project:f.project},budget:defaultBudget()}).response;if(!('candidates' in hint))throw new Error('budget failed');expect(hint.candidates).toHaveLength(1);expect(readSpan(f.db,hint.candidates[0]!.ref)).not.toBeNull();expect(JSON.stringify(hint)).not.toContain(synthetic);service.close();
  }finally{f.db.close();}
 });
});
