import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {open} from '../packages/core/src/db.js';
import {claimLease,assertFence,heartbeatLease,releaseLease} from '../packages/core/src/memory/leases.js';
import {enqueueJob,claimJob,finishJob,recoverJobs,spoolRequest,drainSpool} from '../packages/core/src/memory/jobs.js';
import {inspectAssets,LocalEncoder} from '../packages/core/src/memory/assets.js';
import {MaintenanceWorker,prepareMigration} from '../packages/core/src/memory/maintenance.js';
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'potsherd-runtime-'));const db=open({root});return {root,db,close(){db.close();fs.rmSync(root,{recursive:true,force:true});}};}
describe('durable runtime ownership and queues',()=>{
 it('generation fences reject old heartbeat release and protected mutation',()=>{const f=fixture();try{const a=claimLease(f.db,'maintenance')!;expect(a).toBeTruthy();expect(claimLease(f.db,'maintenance',Date.now()+999999)).toBeNull();expect(releaseLease(f.db,a)).toBe(true);const b=claimLease(f.db,'maintenance')!;expect(b.generation).toBe(a.generation+1);expect(heartbeatLease(f.db,a)).toBe(false);expect(releaseLease(f.db,a)).toBe(false);expect(()=>assertFence(f.db,a)).toThrow('lease_superseded');assertFence(f.db,b);}finally{f.close();}});
 it('fair due jobs survive failure without losing identical done input',()=>{const f=fixture();try{const fence=claimLease(f.db,'maintenance')!;enqueueJob(f.db,{kind:'capture',targetId:'old',inputHash:'a'},1000);enqueueJob(f.db,{kind:'capture',targetId:'new',inputHash:'b'},2000);const old=claimJob(f.db,fence,3000)!;expect(old.target_id).toBe('old');finishJob(f.db,fence,old,'retry','capture_failed',3000);expect(claimJob(f.db,fence,3500)?.target_id).toBe('new');const retry=claimJob(f.db,fence,4000)!;expect(retry.target_id).toBe('old');expect(retry.attempts).toBe(2);finishJob(f.db,fence,retry,'done',undefined,4000);enqueueJob(f.db,{kind:'capture',targetId:'old',inputHash:'a'},5000);expect(f.db.prepare('SELECT state FROM maintenance_jobs WHERE job_id=?').get(retry.job_id)).toMatchObject({state:'done'});}finally{f.close();}});
 it('recovers killed-owner running work and only consumes spool after enqueue commits',()=>{const f=fixture();try{const a=claimLease(f.db,'maintenance')!;enqueueJob(f.db,{kind:'capture',targetId:'source',inputHash:'hash'});const j=claimJob(f.db,a)!;releaseLease(f.db,a);const b=claimLease(f.db,'maintenance')!;recoverJobs(f.db,b);expect(f.db.prepare('SELECT state FROM maintenance_jobs WHERE job_id=?').get(j.job_id)).toMatchObject({state:'retry'});const file=spoolRequest(f.root,{kind:'capture',targetId:'spooled',inputHash:'hash2'});expect(fs.statSync(file).mode&0o777).toBe(0o600);expect(drainSpool(f.db,f.root)).toBe(1);expect(fs.existsSync(file)).toBe(false);expect(drainSpool(f.db,f.root)).toBe(0);}finally{f.close();}});
 it('a pass drains jobs enqueued during an awaited handler and shutdown preserves debt',async()=>{const f=fixture();const worker=new MaintenanceWorker(f.root,{db:f.db});try{enqueueJob(f.db,{kind:'forget',targetId:'one',inputHash:'a'});let calls=0;(worker as unknown as {handle:()=>Promise<void>}).handle=async()=>{calls++;if(calls===1){await new Promise<void>(r=>setTimeout(r,10));enqueueJob(f.db,{kind:'forget',targetId:'two',inputHash:'b'});}};await worker.drainOnce();expect(calls).toBe(2);expect(f.db.prepare("SELECT count(*) n FROM maintenance_jobs WHERE state='done'").get()).toMatchObject({n:2});await worker.close();expect(f.db.prepare('SELECT process_started_at FROM maintenance_leases').get()).toMatchObject({process_started_at:'released'});}finally{await worker.close();f.close();}});
 it('missing assets never fetch or create directories and preserve lexical readiness',async()=>{const f=fixture();try{const cache=path.join(f.root,'missing');expect(inspectAssets(cache).state).toBe('missing_assets');const encoder=new LocalEncoder(cache);await expect(encoder.encode('hello')).rejects.toThrow('missing_assets');await encoder.close();expect(fs.existsSync(cache)).toBe(false);}finally{f.close();}});
});

it('pre-upgrade backup includes committed WAL pages without altering source evidence',()=>{const f=fixture();try{f.db.exec('CREATE TABLE synthetic_backup(value TEXT)');f.db.prepare('INSERT INTO synthetic_backup VALUES(?)').run('acknowledged value');f.db.prepare('DELETE FROM schema_migrations WHERE version>13').run();const before=f.db.prepare('SELECT * FROM synthetic_backup').all();const backup=prepareMigration(f.root);expect(backup).toBeTruthy();const reader=open({file:backup!,readonly:true});try{expect(reader.prepare('SELECT * FROM synthetic_backup').all()).toEqual(before);}finally{reader.close();}expect(f.db.prepare('SELECT * FROM synthetic_backup').all()).toEqual(before);}finally{f.close();}});
