import {describe,it,expect,vi,afterAll} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {open,sqliteDriverName,type Db} from '../packages/core/src/db.js';
import {publishSource} from '../packages/core/src/memory/source.js';
import {MaintenanceWorker,ensureSpanSpace,queueHistoricalEmbeddings} from '../packages/core/src/memory/maintenance.js';
import {EmbeddingWorkset} from '../packages/core/src/memory/embedding-workset.js';
import {enqueueJob,enqueueEmbeddingJob,enqueueRequest,captureStatus} from '../packages/core/src/memory/jobs.js';
import {claimLease,assertFence,releaseLease} from '../packages/core/src/memory/leases.js';
import {DEFAULT_SPACE_ID,CLS_SPACE_ID,inspectAssets,type LocalEncoder} from '../packages/core/src/memory/assets.js';
import {loadSpanTokenizer} from '../packages/core/src/memory/tokenization.js';
import {embeddingToBlob} from '../packages/core/src/embeddings.js';
import {validatedSpanVectorBlob} from '../packages/core/src/memory/vector-validation.js';
import {identity} from '../packages/core/src/memory/spans.js';
import type {ParseResult} from '../packages/core/src/adapters/types.js';
const observations:Record<string,unknown>={};
afterAll(()=>{if(process.env.POTSHERD_PROGRESS_REPAIR_RECEIPT)fs.writeFileSync(process.env.POTSHERD_PROGRESS_REPAIR_RECEIPT,JSON.stringify({class:'actual SQLite/source controls; deterministic fake encoder; no inference or latency claim',driver:sqliteDriverName(),...observations},null,2)+'\n');});
const cache=process.env.POTSHERD_TEST_MODELS_DIR;
const point=()=>[1,...Array(383).fill(0)];
const setting=(db:Db,name:string)=>Number(Object.values(db.prepare('PRAGMA '+name).get() as Record<string,unknown>)[0]);
async function fixture(){
 if(!cache||!path.isAbsolute(cache)||inspectAssets(cache).state!=='ready')throw new Error('explicit verified private public assets required; no home fallback');
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-progress-')),db=open({root});fs.symlinkSync(cache,path.join(root,'models'),'dir');const tokenizer=(await loadSpanTokenizer(cache))!;
 ensureSpanSpace(db);
 function publish(id:string,n=8,textPrefix='benign progress',artifact='raw-'+id){const parsed:ParseResult={session:{id,harness:'claude',sourcePath:'',project:'/fictional/'+id,projectSlug:'p',startedAt:'',endedAt:'',isSidechain:false,status:'live',counts:{userPrompts:n,assistantTurns:0,toolCalls:0,bytes:0}},exchanges:[],records:Array.from({length:n},(_,i)=>({unitKey:'unit-'+i,role:'user' as const,text:textPrefix+' unit '+i,eventAt:null,timeBasis:'unknown' as const,project:'/fictional/'+id,branch:'main',locator:{recordKey:'unit-'+i,mapping:'unavailable' as const},locatorFidelity:'record_id' as const,recordType:'user'})),endOffset:0,malformedLines:0,unknownTypes:{},evidenceVersion:'claude-records-v4'};return publishSource(db,{parsed,artifactHash:artifact,artifactBytes:0,tokenizer});}
 return{root,db,tokenizer,publish,close(){db.close();fs.rmSync(root,{recursive:true,force:true});}};
}
const encoder=(run?:(texts:string[],signal?:AbortSignal)=>Promise<number[][]>)=>({encodeBatch:vi.fn(run??(async(texts:string[])=>texts.map(point))),close:vi.fn(async()=>{})}) as unknown as LocalEncoder;
const stats=(worker:MaintenanceWorker)=>(worker as unknown as {workset:EmbeddingWorkset}).workset.statistics;
const good=(db:Db)=>(db.prepare('SELECT vector_blob FROM span_embeddings').all() as {vector_blob:Buffer}[]).every(row=>validatedSpanVectorBlob(row.vector_blob)!==null);
describe('bounded connection-owned embedding workset',()=>{
 it('verifies actual compile FILE/cache settings, indexed lookup, foreign TEMP refusal and reuse',async()=>{const f=await fixture();const fence=claimLease(f.db,'maintenance')!;try{
  const before=[setting(f.db,'temp_store'),setting(f.db,'temp.cache_size')];
  f.db.exec('CREATE TEMP TABLE foreign_temp(value TEXT);INSERT INTO foreign_temp VALUES(\'keep\')');
  expect(()=>new EmbeddingWorkset(f.db,DEFAULT_SPACE_ID,()=>assertFence(f.db,fence))).toThrow('connection_busy');expect(f.db.prepare('SELECT * FROM foreign_temp').all()).toEqual([{value:'keep'}]);expect([setting(f.db,'temp_store'),setting(f.db,'temp.cache_size')]).toEqual(before);f.db.exec('DROP TABLE foreign_temp');
  const one=new EmbeddingWorkset(f.db,DEFAULT_SPACE_ID,()=>assertFence(f.db,fence));observations.tempConfiguration={...one.configuration};expect(one.configuration).toMatchObject({tempStore:1,tempCacheKiB:-2048});expect([0,1,2]).toContain(one.configuration.compileTempStore);
  const plan=f.db.prepare(`EXPLAIN QUERY PLAN SELECT span_id FROM ${one.pendingTable} WHERE space_id=? AND revision_id=? ORDER BY ordinal,span_id LIMIT 2`).all(DEFAULT_SPACE_ID,'target') as {detail:string}[];expect(plan.some(row=>/SEARCH.*PRIMARY KEY/.test(row.detail))).toBe(true);const deletion=f.db.prepare(`EXPLAIN QUERY PLAN DELETE FROM temp.${one.pendingTable} WHERE space_id=? AND revision_id=? AND ordinal=? AND span_id=? AND input_hash=?`).all(DEFAULT_SPACE_ID,'target',1,'span','hash') as {detail:string}[];expect(deletion.some(row=>/PRIMARY KEY.*ordinal=\?.*span_id=\?/.test(row.detail))).toBe(true);observations.pendingDeletePlan=deletion;
  expect(()=>new EmbeddingWorkset(f.db,DEFAULT_SPACE_ID,()=>assertFence(f.db,fence))).toThrow('connection_busy');expect(setting(f.db,'temp.cache_size')).toBe(-2048);one.close();expect(one.cleanup).toEqual({settingsRestored:true,foreignTempObjectsPresent:false});expect([setting(f.db,'temp_store'),setting(f.db,'temp.cache_size')]).toEqual(before);
  const two=new EmbeddingWorkset(f.db,DEFAULT_SPACE_ID,()=>assertFence(f.db,fence));two.close();expect(f.db.prepare('SELECT name FROM temp.sqlite_master').all()).toEqual([]);
 }finally{releaseLease(f.db,fence);f.close();}});
 it('never mutates foreign fixed-name TEMP objects through standalone or initial worker validation',async()=>{const f=await fixture();f.publish('foreign',1);f.db.exec("CREATE TEMP TABLE memory_vector_membership_scan(span_id TEXT NOT NULL,revision_id TEXT NOT NULL,source_id TEXT NOT NULL,PRIMARY KEY(span_id,revision_id)) WITHOUT ROWID;INSERT INTO memory_vector_membership_scan VALUES('keep','keep','keep');CREATE TEMP TABLE memory_vector_debt_scan(revision_id TEXT PRIMARY KEY,source_id TEXT NOT NULL);INSERT INTO memory_vector_debt_scan VALUES('keep','keep')");const before=f.db.prepare('SELECT * FROM memory_vector_membership_scan').all(),settings=[setting(f.db,'temp_store'),setting(f.db,'temp.cache_size')],worker=new MaintenanceWorker(f.root,{db:f.db,encoder:encoder()});try{expect(()=>queueHistoricalEmbeddings(f.db)).toThrow('connection_busy');await expect(worker.drainOnce()).rejects.toThrow('connection_busy');expect(f.db.prepare('SELECT * FROM memory_vector_membership_scan').all()).toEqual(before);expect(f.db.prepare('SELECT * FROM memory_vector_debt_scan').all()).toEqual([{revision_id:'keep',source_id:'keep'}]);expect([setting(f.db,'temp_store'),setting(f.db,'temp.cache_size')]).toEqual(settings);}finally{await worker.close();f.close();}});
 it('qualifies private TEMP accesses and never falls back to a same-named MAIN table',async()=>{const f=await fixture(),ref=f.publish('fallback',1),fence=claimLease(f.db,'maintenance')!,work=new EmbeddingWorkset(f.db,DEFAULT_SPACE_ID,()=>assertFence(f.db,fence));try{const manifest=(f.db.prepare('SELECT manifest_hash FROM source_revisions WHERE revision_id=?').get(ref.revisionId) as {manifest_hash:string}).manifest_hash;work.take(ref.revisionId,manifest);f.db.exec(`CREATE TABLE main.${work.pendingTable}(space_id TEXT,revision_id TEXT,ordinal INTEGER,span_id TEXT,input_hash TEXT);INSERT INTO main.${work.pendingTable} VALUES('foreign','foreign',1,'foreign','foreign');DROP TABLE temp.${work.pendingTable}`);expect(()=>work.take(ref.revisionId,manifest)).toThrow();expect(()=>work.reset()).toThrow();expect(f.db.prepare(`SELECT * FROM main.${work.pendingTable}`).all()).toEqual([{space_id:'foreign',revision_id:'foreign',ordinal:1,span_id:'foreign',input_hash:'foreign'}]);}finally{work.close();releaseLease(f.db,fence);f.close();}});
 it('rejects a compile-time memory-only TEMP configuration before any connection settings change',async()=>{const f=await fixture(),fence=claimLease(f.db,'maintenance')!;try{const before=[setting(f.db,'temp_store'),setting(f.db,'temp.cache_size')];const declaredMemoryOnly=new Proxy(f.db,{get(db,key){if(key!=='prepare'){const value=Reflect.get(db,key);return typeof value==='function'?value.bind(db):value;}return(sql:string)=>sql==='PRAGMA compile_options'?{all:()=>[{compile_options:'TEMP_STORE=3'}]}:db.prepare(sql);}});expect(()=>new EmbeddingWorkset(declaredMemoryOnly as Db,DEFAULT_SPACE_ID,()=>assertFence(f.db,fence))).toThrow('embedding_file_temp_unsupported');expect([setting(f.db,'temp_store'),setting(f.db,'temp.cache_size')]).toEqual(before);expect(f.db.prepare('SELECT name FROM temp.sqlite_master').all()).toEqual([]);observations.memoryOnlyCompileControl='injected build metadata rejected before settings; no claim of real memory-only driver run';}finally{releaseLease(f.db,fence);f.close();}});
 it('preserves unexpected later TEMP objects and reports restoration limitation without changing commit truth',async()=>{const f=await fixture();const fence=claimLease(f.db,'maintenance')!;try{const work=new EmbeddingWorkset(f.db,DEFAULT_SPACE_ID,()=>assertFence(f.db,fence));f.db.exec('CREATE TEMP TABLE later_foreign(value TEXT);INSERT INTO later_foreign VALUES(\'keep\')');const ref=f.publish('committed',1),span=f.db.prepare('SELECT p.span_id,p.embedding_input_hash FROM evidence_spans p JOIN revision_spans rs ON rs.span_id=p.span_id WHERE rs.revision_id=?').get(ref.revisionId) as {span_id:string;embedding_input_hash:string};f.db.prepare('INSERT INTO span_embeddings VALUES(?,?,?,?,?,NULL)').run(span.span_id,DEFAULT_SPACE_ID,span.embedding_input_hash,embeddingToBlob(point()),'2026-01-01T00:00:00Z');work.close();expect(work.cleanup).toEqual({settingsRestored:false,foreignTempObjectsPresent:true});expect(f.db.prepare('SELECT * FROM later_foreign').all()).toEqual([{value:'keep'}]);expect(good(f.db)).toBe(true);expect(f.db.prepare('SELECT count(*) n FROM span_embeddings').get()).toEqual({n:1});}finally{releaseLease(f.db,fence);f.close();}});
});
describe('actual source progress and exact canonical queue targets',()=>{
 it('drains70 UNIQUE unfinished targets with linear bounded initialization/completion scans and2-span fairness',async()=>{const f=await fixture(),fake=encoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{for(let i=0;i<70;i++)f.publish('unique-'+i,8);expect(f.db.prepare("SELECT count(*) n FROM maintenance_jobs WHERE kind='embed'").get()).toEqual({n:70});await worker.drainOnce();expect(f.db.prepare('SELECT count(*) n FROM span_embeddings').get()).toEqual({n:560});expect(good(f.db)).toBe(true);observations.uniqueTargetProgress={targets:70,spans:560,...stats(worker)};expect(stats(worker)).toMatchObject({targetScans:140,scannedRows:1120,maxPageRows:8});expect(stats(worker).pendingLookups).toBeGreaterThan(280);expect((fake.encodeBatch as ReturnType<typeof vi.fn>).mock.calls.every(args=>(args[0] as string[]).length<=2)).toBe(true);expect(f.db.prepare("SELECT count(*) n FROM maintenance_jobs WHERE state<>'done'").get()).toEqual({n:0});}finally{await worker.close();expect(worker.progressCleanup).toEqual([{settingsRestored:true,foreignTempObjectsPresent:false}]);f.close();}},30000);
 it('deduplicates publication/history idempotently and preserves legacy aliases through normal fenced completion',async()=>{const f=await fixture(),fake=encoder(),worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{const ref=f.publish('mixed',8),manifest=(f.db.prepare('SELECT manifest_hash FROM source_revisions WHERE revision_id=?').get(ref.revisionId) as {manifest_hash:string}).manifest_hash;const canonical=enqueueEmbeddingJob(f.db,ref.sourceId,ref.revisionId,DEFAULT_SPACE_ID);expect(queueHistoricalEmbeddings(f.db)).toBe(1);expect(queueHistoricalEmbeddings(f.db)).toBe(1);expect(f.db.prepare("SELECT count(*) n FROM maintenance_jobs WHERE kind='embed'").get()).toEqual({n:1});const legacy=enqueueJob(f.db,{kind:'embed',targetId:ref.sourceId,targetRevisionId:ref.revisionId,inputHash:manifest});await worker.drainOnce();expect((fake.encodeBatch as ReturnType<typeof vi.fn>).mock.calls).toHaveLength(4);observations.canonicalAndLegacyJobs=f.db.prepare('SELECT job_id,target_id,target_revision_id,input_hash,state FROM maintenance_jobs ORDER BY job_id').all();expect(f.db.prepare('SELECT job_id,state FROM maintenance_jobs ORDER BY job_id').all()).toEqual([canonical,legacy].sort().map(job_id=>({job_id,state:'done'})));expect(queueHistoricalEmbeddings(f.db)).toBe(0);expect(f.db.prepare('SELECT count(*) n FROM span_embeddings').get()).toEqual({n:8});}finally{await worker.close();f.close();}});
 it('keeps distinct named-space debt blocked and never completes a foreign running legacy alias',async()=>{const f=await fixture(),ref=f.publish('namespace',4),other=enqueueEmbeddingJob(f.db,ref.sourceId,ref.revisionId,CLS_SPACE_ID);let foreign='';const fake=encoder(async(texts)=>{if(!foreign){foreign=enqueueJob(f.db,{kind:'embed',targetId:ref.sourceId,targetRevisionId:ref.revisionId,inputHash:identity('historical-space-backfill/v1',DEFAULT_SPACE_ID,ref.revisionId)});f.db.prepare("UPDATE maintenance_jobs SET state='running',owner_token='other-owner',lease_generation=987 WHERE job_id=?").run(foreign);}return texts.map(point);}),worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{await worker.drainOnce();expect(f.db.prepare('SELECT state,error_code FROM maintenance_jobs WHERE job_id=?').get(other)).toEqual({state:'blocked',error_code:'embedding_space_unsupported'});expect(f.db.prepare('SELECT state,owner_token,lease_generation FROM maintenance_jobs WHERE job_id=?').get(foreign)).toEqual({state:'running',owner_token:'other-owner',lease_generation:987});expect(f.db.prepare('SELECT DISTINCT space_id FROM span_embeddings').all()).toEqual([{space_id:DEFAULT_SPACE_ID}]);}finally{await worker.close();expect(f.db.prepare('SELECT state,owner_token FROM maintenance_jobs WHERE job_id=?').get(foreign)).toEqual({state:'running',owner_token:'other-owner'});f.close();}});
 it('validates shared growing-history vectors once and maps one corruption to every retained revision',async()=>{const f=await fixture();for(let n=1;n<=40;n++)f.publish('history',n,'benign shared','prefix-'+n);const spans=f.db.prepare('SELECT span_id,embedding_input_hash FROM evidence_spans').all() as {span_id:string;embedding_input_hash:string}[];for(const span of spans)f.db.prepare('INSERT INTO span_embeddings VALUES(?,?,?,?,?,NULL)').run(span.span_id,DEFAULT_SPACE_ID,span.embedding_input_hash,embeddingToBlob(point()),'2026-01-01T00:00:00Z');let reads=0;const observed=new Proxy(f.db,{get(db,key){if(key!=='prepare'){const value=Reflect.get(db,key);return typeof value==='function'?value.bind(db):value;}return(sql:string)=>{const stmt=db.prepare(sql);return new Proxy(stmt,{get(stmt,key){const value=Reflect.get(stmt,key);if(typeof value!=='function')return value;return(...args:unknown[])=>{const answer=value.apply(stmt,args);if(key==='all'&&sql.startsWith('SELECT p.span_id,p.span_rowid,e.vector_blob'))reads+=answer.length;return answer;};}});};}});try{expect(f.db.prepare('SELECT count(*) n FROM revision_spans').get()).toEqual({n:820});expect(spans).toHaveLength(40);expect(queueHistoricalEmbeddings(observed as Db)).toBe(0);expect(reads).toBe(40);reads=0;const first=(f.db.prepare('SELECT p.span_id FROM evidence_spans p JOIN evidence_units u ON u.unit_revision_id=p.unit_revision_id WHERE u.unit_key=?').get('unit-0') as {span_id:string}).span_id;f.db.prepare('UPDATE span_embeddings SET vector_blob=? WHERE span_id=?').run(embeddingToBlob(Array(384).fill(0)),first);expect(queueHistoricalEmbeddings(observed as Db)).toBe(40);expect(reads).toBe(40);expect(f.db.prepare("SELECT count(*) n FROM maintenance_jobs WHERE kind='embed'").get()).toEqual({n:40});observations.sharedHistory={revisions:40,memberships:820,uniqueSpans:40,globalValidationRowsPerPass:reads,affectedRevisions:40};expect(f.db.prepare('SELECT name FROM temp.sqlite_master').all()).toEqual([]);}finally{f.close();}});
 it('reconstructs after partial close/reopen and reuses durable vectors rather than trusting a saved cursor',async()=>{const f=await fixture();f.publish('restart',8);let calls=0,close:Promise<void>|undefined,worker:MaintenanceWorker;const first=encoder(async(texts)=>{if(++calls===2)close=worker.close();return texts.map(point);});worker=new MaintenanceWorker(f.root,{db:f.db,encoder:first});try{await worker.drainOnce();await close;expect(f.db.prepare('SELECT count(*) n FROM span_embeddings').get()).toEqual({n:2});expect(f.db.prepare('SELECT name FROM temp.sqlite_master').all()).toEqual([]);f.db.prepare("UPDATE maintenance_jobs SET next_attempt_at='2000-01-01T00:00:00Z' WHERE state='retry'").run();const second=encoder();worker=new MaintenanceWorker(f.root,{db:f.db,encoder:second});await worker.drainOnce();expect((second.encodeBatch as ReturnType<typeof vi.fn>).mock.calls.flatMap(args=>args[0] as string[])).toHaveLength(6);expect(f.db.prepare('SELECT count(*) n FROM span_embeddings').get()).toEqual({n:8});expect(good(f.db)).toBe(true);}finally{await worker.close();f.close();}});
 it('finds corruption in an already committed prefix before completion and repairs it',async()=>{const f=await fixture();f.publish('corrupt',4);let calls=0;const fake=encoder(async(texts)=>{if(++calls===2)f.db.prepare('UPDATE span_embeddings SET vector_blob=? WHERE span_id=(SELECT span_id FROM span_embeddings LIMIT 1)').run(embeddingToBlob(Array(384).fill(NaN)));return texts.map(point);});const worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{await worker.drainOnce();expect((fake.encodeBatch as ReturnType<typeof vi.fn>).mock.calls.map(args=>(args[0] as string[]).length)).toEqual([2,2,1]);expect(good(f.db)).toBe(true);expect(queueHistoricalEmbeddings(f.db)).toBe(0);}finally{await worker.close();f.close();}});
 it('refills corrupt prefixes during an active backlog at the configured validation interval',async()=>{vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-01-01T00:00:00Z'));const f=await fixture();for(let i=0;i<3;i++)f.publish('periodic-'+i,8);let calls=0;const fake=encoder(async(texts)=>{if(++calls===3){f.db.prepare('UPDATE span_embeddings SET vector_blob=? WHERE span_id=(SELECT span_id FROM span_embeddings LIMIT 1)').run(embeddingToBlob(Array(384).fill(NaN)));vi.setSystemTime(new Date(Date.now()+60001));}return texts.map(point);}),worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{await worker.drainOnce();expect(good(f.db)).toBe(true);expect((fake.encodeBatch as ReturnType<typeof vi.fn>).mock.calls.flatMap(args=>args[0] as string[])).toHaveLength(25);expect(f.db.prepare("SELECT count(*) n FROM maintenance_jobs WHERE state<>'done'").get()).toEqual({n:0});}finally{await worker.close();f.close();vi.useRealTimers();}});
 it('retains old revision work independently when a newer revision arrives during fake encoding',async()=>{const f=await fixture(),old=f.publish('changed',4,'before immutable'),fake=encoder();let newer:ReturnType<typeof f.publish>|undefined;fake.encodeBatch=vi.fn(async(texts:string[])=>{newer??=f.publish('changed',4,'after immutable','new-raw');return texts.map(point);});const worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{await worker.drainOnce();expect(newer!.revisionId).not.toBe(old.revisionId);for(const revision of [old.revisionId,newer!.revisionId])expect(f.db.prepare('SELECT count(*) n FROM revision_spans rs JOIN span_embeddings e ON e.span_id=rs.span_id WHERE rs.revision_id=? AND e.space_id=?').get(revision,DEFAULT_SPACE_ID)).toEqual({n:4});expect(good(f.db)).toBe(true);}finally{await worker.close();f.close();}});
 it('cannot remove pending work or stamp vectors after an owner replacement',async()=>{const f=await fixture();f.publish('fenced',4);const fake=encoder(async(texts)=>{f.db.prepare("UPDATE maintenance_leases SET owner_token='replacement',generation=generation+1 WHERE lane='maintenance'").run();return texts.map(point);}),worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{await expect(worker.drainOnce()).rejects.toThrow('lease_superseded');expect(f.db.prepare('SELECT count(*) n FROM span_embeddings').get()).toEqual({n:0});expect(f.db.prepare("SELECT owner_token FROM maintenance_leases WHERE lane='maintenance'").get()).toEqual({owner_token:'replacement'});}finally{await worker.close();expect(f.db.prepare("SELECT owner_token FROM maintenance_leases WHERE lane='maintenance'").get()).toEqual({owner_token:'replacement'});f.close();}});
 it('keeps an ineligible commit as visible retry rather than losing pending work or hot-looping',async()=>{const f=await fixture();f.publish('retired',2);const fake=encoder(async(texts)=>{f.db.prepare("UPDATE embedding_spaces SET state='retired' WHERE space_id=?").run(DEFAULT_SPACE_ID);return texts.map(point);});let worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{await worker.drainOnce();expect(fake.encodeBatch).toHaveBeenCalledTimes(1);expect(f.db.prepare('SELECT count(*) n FROM span_embeddings').get()).toEqual({n:0});expect(f.db.prepare("SELECT state,error_code FROM maintenance_jobs WHERE kind='embed'").get()).toEqual({state:'retry',error_code:'maintenance_failed'});await worker.close();f.db.prepare("UPDATE maintenance_jobs SET next_attempt_at='2000-01-01T00:00:00Z'").run();worker=new MaintenanceWorker(f.root,{db:f.db,encoder:encoder()});await worker.drainOnce();expect(f.db.prepare('SELECT count(*) n FROM span_embeddings').get()).toEqual({n:2});expect(good(f.db)).toBe(true);}finally{await worker.close();f.close();}});
 it('streams128-row initialization and publishes no complete marker after cancellation midscan',async()=>{const f=await fixture(),ref=f.publish('large',131),fence=claimLease(f.db,'maintenance')!,controller=new AbortController();let pages=0;const observed=new Proxy(f.db,{get(db,key){if(key!=='prepare'){const value=Reflect.get(db,key);return typeof value==='function'?value.bind(db):value;}return(sql:string)=>{const stmt=db.prepare(sql);return new Proxy(stmt,{get(target,method){const value=Reflect.get(target,method);if(typeof value!=='function')return value;return(...args:unknown[])=>{const result=value.apply(target,args);if(method==='all'&&sql.startsWith('SELECT rs.ordinal,p.span_id')&&++pages===2)controller.abort(new Error('scan_cancelled'));return result;};}});};}});try{const work=new EmbeddingWorkset(observed as Db,DEFAULT_SPACE_ID,()=>assertFence(f.db,fence)),manifest=(f.db.prepare('SELECT manifest_hash FROM source_revisions WHERE revision_id=?').get(ref.revisionId) as {manifest_hash:string}).manifest_hash;expect(()=>work.take(ref.revisionId,manifest,controller.signal)).toThrow('scan_cancelled');expect(f.db.prepare(`SELECT * FROM ${work.targetTable}`).all()).toEqual([]);expect(f.db.prepare(`SELECT * FROM ${work.pendingTable}`).all()).toEqual([]);expect(work.statistics.maxPageRows).toBe(128);work.close();}finally{releaseLease(f.db,fence);f.close();}});
 it('shares full concurrent close completion through the CLI signal-then-finally pattern',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-close-shared-')),db=open({root});let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),fake=encoder();fake.close=vi.fn(()=>gate);const worker=new MaintenanceWorker(root,{db,encoder:fake});let callerDbClosed=false;try{await worker.runExplicit(()=>{});const fence=(worker as unknown as {fence:Parameters<typeof assertFence>[1]}).fence;const work=new EmbeddingWorkset(db,DEFAULT_SPACE_ID,()=>assertFence(db,fence));(worker as unknown as {workset:EmbeddingWorkset}).workset=work;const signalClose=worker.close(),finallyClose=worker.close();expect(finallyClose).toBe(signalClose);let returned=false;void finallyClose.then(()=>returned=true);await Promise.resolve();await Promise.resolve();expect(returned).toBe(false);expect(fake.close).toHaveBeenCalledTimes(1);release();await finallyClose;expect(work.cleanup).toEqual({settingsRestored:true,foreignTempObjectsPresent:false});expect(db.prepare("SELECT process_started_at FROM maintenance_leases WHERE lane='maintenance'").get()).toEqual({process_started_at:'released'});db.close();callerDbClosed=true;await signalClose;expect(worker.cleanupFailures).toEqual([]);observations.concurrentClose={samePromise:true,secondWaitedForEncoder:true,leaseReleasedBeforeCallerDbClose:true,encoderCloseCalls:1};}finally{release();await worker.close();if(!callerDbClosed)db.close();fs.rmSync(root,{recursive:true,force:true});}});
 it('waits for a delayed in-flight task and still releases the lease after TEMP teardown failure',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-close-task-')),db=open({root}),fake=encoder(),worker=new MaintenanceWorker(root,{db,encoder:fake});let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),ready=new Promise<void>(resolve=>entered=resolve);try{enqueueJob(db,{kind:'forget',targetId:'owned',inputHash:'owned'});(worker as unknown as {handle:()=>Promise<void>}).handle=async()=>{entered();await gate;};const pass=worker.drainOnce();void pass.catch(()=>{});await ready;const fence=(worker as unknown as {fence:Parameters<typeof assertFence>[1]}).fence;const work=new EmbeddingWorkset(db,DEFAULT_SPACE_ID,()=>assertFence(db,fence));(worker as unknown as {workset:EmbeddingWorkset}).workset=work;const actual=work.close.bind(work);work.close=()=>{actual();throw new Error('controlled_temp_cleanup_failure');};const first=worker.close(),second=worker.close();void first.catch(()=>{});expect(second).toBe(first);let returned=false;void second.then(()=>returned=true,()=>returned=true);await Promise.resolve();await Promise.resolve();expect(returned).toBe(false);release();await pass.catch(()=>{});await expect(first).rejects.toThrow('controlled_temp_cleanup_failure');expect(db.prepare("SELECT process_started_at FROM maintenance_leases WHERE lane='maintenance'").get()).toEqual({process_started_at:'released'});expect(worker.cleanupFailures).toMatchObject([{stage:'temporary_workset'}]);expect(db.prepare('SELECT name FROM temp.sqlite_master').all()).toEqual([]);}finally{release();await worker.close().catch(()=>{});db.close();fs.rmSync(root,{recursive:true,force:true});}});
 it('services capture between2-span batches without admitting another worker on the shared connection',async()=>{const f=await fixture();f.publish('fair',8);const claude=path.join(f.root,'claude'),dir=path.join(claude,'projects','synthetic');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'request.jsonl'),JSON.stringify({sessionId:'request',cwd:'/fictional/capture',type:'user',uuid:'request',timestamp:'2026-02-01T00:00:00Z',message:{role:'user',content:'benign capture during work'}})+'\n');let request='',calls=0;const competing=new MaintenanceWorker(f.root,{db:f.db,encoder:encoder()});const fake=encoder(async(texts)=>{expect(texts.length).toBeLessThanOrEqual(2);if(calls++===0){request=enqueueRequest(f.db,{kind:'capture',targetId:'*',inputHash:'fair capture',capture:{claudeDir:claude,harnesses:['claude']}});await competing.drainOnce();}else expect(captureStatus(f.db,request)).toMatchObject({state:'done',captured:true});return texts.map(point);}),worker=new MaintenanceWorker(f.root,{db:f.db,encoder:fake});try{await worker.drainOnce();expect(captureStatus(f.db,request)).toMatchObject({state:'done',captured:true});expect(f.db.prepare("SELECT count(*) n FROM maintenance_jobs WHERE kind='embed' AND state<>'done'").get()).toEqual({n:0});}finally{await competing.close();await worker.close();f.close();}});
});
