import {describe,it,expect} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {execFileSync,spawn} from 'node:child_process';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
import {open,openSqliteReadOnly} from '../packages/core/src/db.js';
import {claimLease,releaseLease} from '../packages/core/src/memory/leases.js';
import {MaintenanceWorker} from '../packages/core/src/memory/maintenance.js';
import {captureStatus,drainSpool,spoolRequest} from '../packages/core/src/memory/jobs.js';
import {defaultBudget} from '../packages/core/src/memory/budget.js';
const sdkRequire=createRequire(path.resolve('packages/mcp/package.json'));
const {Client}=await import(pathToFileURL(sdkRequire.resolve('@modelcontextprotocol/sdk/client/index.js')).href);
const {StdioClientTransport}=await import(pathToFileURL(sdkRequire.resolve('@modelcontextprotocol/sdk/client/stdio.js')).href);
const cli=path.resolve('packages/cli/dist/potsherd.js'),mcp=path.resolve('packages/mcp/dist/index.js');
function record(id:string,text:string,project='/fictional/concurrent'){return JSON.stringify({type:'user',uuid:'record-one',sessionId:id,promptId:'prompt-one',cwd:project,gitBranch:'main',timestamp:'2026-01-01T00:00:00Z',message:{role:'user',content:text}})+'\n';}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-cooperative-')),claude=path.join(root,'claude'),dir=path.join(claude,'projects','p'),id='11111111-1111-4111-8111-111111111111';fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,id+'.jsonl');fs.writeFileSync(file,record(id,'COOPERATIVE_OLD_42 initial state'));return {root,claude,file,id};}
function runCli(args:string[]):Promise<{code:number;stdout:string;stderr:string;ms:number}> {return new Promise((resolve,reject)=>{const start=Date.now(),child=spawn(process.execPath,[cli,...args],{env:{...process.env,POTSHERD_OFFLINE:'1'},stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);const timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('CLI timeout'));},12000);child.once('error',reject);child.once('close',code=>{clearTimeout(timer);resolve({code:code??1,stdout,stderr,ms:Date.now()-start});});});}
async function until(fn:()=>boolean){const start=Date.now();while(!fn()){if(Date.now()-start>5000)throw new Error('owner startup timeout');await new Promise<void>(r=>setTimeout(r,25));}}
function read<T>(root:string,fn:(db:ReturnType<typeof openSqliteReadOnly>)=>T):T {const db=openSqliteReadOnly(path.join(root,'potsherd.db'));try{return fn(db);}finally{db.close();}}
describe('public concurrent indexing cooperation',()=>{
 it('active MCP accepts changed-source and new-root enrollment requests, while temporal public tools retain old knowledge',async()=>{const f=fixture();let client:any;try{execFileSync(process.execPath,[cli,'index','--no-embed','--quiet','--harness','claude','--claude-dir',f.claude,'--potsherd-dir',f.root],{env:{...process.env,POTSHERD_OFFLINE:'1'},timeout:15000});const cutoff=new Date().toISOString();await new Promise<void>(r=>setTimeout(r,10));const transport=new StdioClientTransport({command:process.execPath,args:[mcp,'--potsherd-dir',f.root],env:{...process.env,POTSHERD_OFFLINE:'1'} as Record<string,string>});client=new Client({name:'cooperative-runtime',version:'test'},{capabilities:{}});await client.connect(transport);await until(()=>Boolean(read(f.root,db=>db.prepare("SELECT 1 FROM maintenance_leases WHERE lane='maintenance' AND process_started_at<>'released'").get())));const owner=read(f.root,db=>db.prepare("SELECT owner_token,generation FROM maintenance_leases WHERE lane='maintenance'").get());
  fs.writeFileSync(f.file,record(f.id,'COOPERATIVE_NEW_42 rewritten state'));const changed=await runCli(['index','--no-embed','--json','--harness','claude','--claude-dir',f.claude,'--potsherd-dir',f.root]);expect(changed.code,changed.stderr).toBe(0);const changedReceipt=JSON.parse(changed.stdout);expect(changedReceipt.totals?.failed??0).toBe(0);expect(changedReceipt.captured).not.toBe(false);expect(changed.ms).toBeLessThan(5500);expect(read(f.root,db=>db.prepare("SELECT owner_token,generation FROM maintenance_leases WHERE lane='maintenance'").get())).toEqual(owner);
  const old=await client.callTool({name:'potsherd_recall',arguments:{query:'COOPERATIVE_OLD_42',mode:'literal',scope:{project:'/fictional/concurrent',asOf:'2026-02-01T00:00:00Z',learnedBy:cutoff},budget:defaultBudget()}});const oldResponse=JSON.parse((old.content as {text:string}[])[0]!.text);expect(oldResponse.evidence[0].text).toContain('COOPERATIVE_OLD_42');expect(oldResponse.coverage.state).toBe('complete_snapshot');expect(Date.parse(oldResponse.coverage.capturedThrough)).toBeLessThanOrEqual(Date.parse(cutoff));
  const future=await client.callTool({name:'potsherd_recall',arguments:{query:'COOPERATIVE_NEW_42',mode:'literal',scope:{project:'/fictional/concurrent',learnedBy:cutoff},budget:defaultBudget()}});expect(JSON.parse((future.content as {text:string}[])[0]!.text).evidence).toHaveLength(0);
  const cliPast=await runCli(['find','--input-json',JSON.stringify({query:'COOPERATIVE_OLD_42',mode:'literal',scope:{project:'/fictional/concurrent',learnedBy:cutoff},budget:defaultBudget()}),'--potsherd-dir',f.root]);expect(cliPast.code,cliPast.stderr).toBe(0);expect(JSON.parse(cliPast.stdout).evidence[0].text).toContain('COOPERATIVE_OLD_42');
  const other=path.join(f.root,'claude-other'),otherDir=path.join(other,'projects','q'),otherId='22222222-2222-4222-8222-222222222222';fs.mkdirSync(otherDir,{recursive:true});fs.writeFileSync(path.join(otherDir,otherId+'.jsonl'),record(otherId,'COOPERATIVE_ENROLLED_42 new root','/fictional/enrolled'));const enrolled=await runCli(['index','--no-embed','--json','--harness','claude','--claude-dir',other,'--potsherd-dir',f.root]);expect(enrolled.code,enrolled.stderr).toBe(0);expect(JSON.parse(enrolled.stdout).captured).not.toBe(false);expect(enrolled.ms).toBeLessThan(5500);const enrollment=read(f.root,db=>db.prepare("SELECT value FROM sync_state WHERE key='memory:source-enrollment'").get()) as {value:string};expect(JSON.parse(enrollment.value).options.claudeDir).toBe(other);expect(read(f.root,db=>db.prepare("SELECT owner_token,generation FROM maintenance_leases WHERE lane='maintenance'").get())).toEqual(owner);const result=await client.callTool({name:'potsherd_recall',arguments:{query:'COOPERATIVE_ENROLLED_42',mode:'literal',budget:defaultBudget()}});expect(JSON.parse((result.content as {text:string}[])[0]!.text).evidence[0].text).toContain('COOPERATIVE_ENROLLED_42');expect(read(f.root,db=>db.prepare('SELECT COUNT(*) n FROM memory_sources').get())).toMatchObject({n:2});
 }finally{await client?.close();fs.rmSync(f.root,{recursive:true,force:true});}},30000);
 it('returns a bounded durable queued receipt without claiming publication when a live owner is paused',async()=>{const f=fixture();const db=open({root:f.root});const owner=claimLease(db,'maintenance')!;const worker=new MaintenanceWorker(f.root,{db});try{const result=await runCli(['index','--no-embed','--json','--harness','claude','--claude-dir',f.claude,'--potsherd-dir',f.root]);expect(result.code,result.stderr).toBe(0);const receipt=JSON.parse(result.stdout);expect(receipt).toMatchObject({durable:true,captured:false});expect(result.ms).toBeLessThan(5000);expect(db.prepare("SELECT owner_token,generation FROM maintenance_leases WHERE lane='maintenance'").get()).toMatchObject({owner_token:owner.ownerToken,generation:owner.generation});expect(db.prepare('SELECT COUNT(*) n FROM source_revisions').get()).toMatchObject({n:0});expect(fs.readdirSync(path.join(f.root,'maintenance-spool')).filter(x=>x.endsWith('.json')).length).toBe(1);releaseLease(db,owner);await worker.drainOnce();expect(captureStatus(db,receipt.jobId)).toMatchObject({state:'done',captured:true,durable:true});expect(db.prepare('SELECT COUNT(*) n FROM source_revisions').get()).toMatchObject({n:1});}finally{await worker.close();db.close();fs.rmSync(f.root,{recursive:true,force:true});}},15000);
 it('commits whitelist request metadata with jobs before removing spool and rejects arbitrary payloads',()=>{const f=fixture(),db=open({root:f.root});try{spoolRequest(f.root,{kind:'capture',targetId:'*',inputHash:'safe',capture:{claudeDir:f.claude,harnesses:['claude'],full:false}});expect(drainSpool(db,f.root)).toBe(1);expect(db.prepare("SELECT COUNT(*) n FROM maintenance_events WHERE kind='capture_request'").get()).toMatchObject({n:1});const bad=spoolRequest(f.root,{kind:'capture',targetId:'*',inputHash:'unsafe',capture:{transcript:'never accepted'} as any});expect(drainSpool(db,f.root)).toBe(0);expect(fs.existsSync(bad)).toBe(true);expect(db.prepare("SELECT COUNT(*) n FROM maintenance_jobs WHERE input_hash='unsafe'").get()).toMatchObject({n:0});}finally{db.close();fs.rmSync(f.root,{recursive:true,force:true});}});
});
