import { testModelCache } from './model-cache.js';
import {it,expect}from'vitest';import fs from'node:fs';import os from'node:os';import path from'node:path';
import{LocalEncoder,inspectAssets}from'../packages/core/src/memory/assets.js';import{loadSpanTokenizer}from'../packages/core/src/memory/tokenization.js';import{publishSource}from'../packages/core/src/memory/source.js';import{open}from'../packages/core/src/db.js';import{MaintenanceWorker}from'../packages/core/src/memory/maintenance.js';import type{ParseResult}from'../packages/core/src/adapters/types.js';
import{enqueueRequest,captureStatus}from'../packages/core/src/memory/jobs.js';
const cache=testModelCache('/nonexistent/potsherd-test-models');
it.skipIf(inspectAssets(cache).state!=='ready')('reuses one persistent session and preserves ragged batch mask/pooling against single inference',async()=>{const encoder=new LocalEncoder(cache,{batchInference:true});try{const texts=['short checkpoint', 'long artifact scope recovery '.repeat(35),'Café 日本語 😀 namespace'];const vectors=await encoder.encodeBatch(texts);expect(encoder.statistics.workerStarts).toBe(1);for(let i=0;i<texts.length;i++){const single=await encoder.encode(texts[i]!);let dot=0;for(let j=0;j<single.length;j++)dot+=single[j]!*vectors[i]![j]!;expect(dot).toBeGreaterThan(.99);expect(Math.sqrt(vectors[i]!.reduce((a,v)=>a+v*v,0))).toBeCloseTo(1,4);}expect(encoder.statistics.workerStarts).toBe(1);const c=new AbortController(),at=Date.now(),pending=encoder.encodeBatch(Array(4).fill('cancel repeated work '.repeat(70)),c.signal);setTimeout(()=>c.abort(new Error('cancel_batch')),1);await expect(pending).rejects.toThrow('cancel_batch');await encoder.close();expect(Date.now()-at).toBeLessThan(5000);}finally{await encoder.close();}},30000);
it.skipIf(inspectAssets(cache).state!=='ready')('reuses exact input/space payload across distinct immutable span identities with independent commits',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-payload-reuse-'));fs.symlinkSync(cache,path.join(root,'models'),'dir');const db=open({root}),encoder=new LocalEncoder(cache),worker=new MaintenanceWorker(root,{db,encoder});try{const tokenizer=(await loadSpanTokenizer(cache))!;const parsed:ParseResult={session:{id:'reuse',harness:'claude',sourcePath:'/synthetic/reuse',project:'/p',projectSlug:'p',startedAt:'',endedAt:'',isSidechain:false,counts:{userPrompts:0,assistantTurns:9,toolCalls:0,bytes:0},status:'live'},records:Array.from({length:9},(_,i)=>({unitKey:'distinct-'+i,role:'assistant' as const,text:'Identical exact recipe reuse payload.',eventAt:null,timeBasis:'unknown' as const,project:'/p',locator:{recordKey:'distinct-'+i,mapping:'unavailable' as const},locatorFidelity:'record_id' as const,recordType:'assistant'})),exchanges:[],unknownTypes:{},endOffset:0,malformedLines:0,evidenceVersion:'synthetic-reuse'};publishSource(db,{parsed,artifactHash:'synthetic',artifactBytes:0,tokenizer});await worker.drainOnce();expect(db.prepare('SELECT COUNT(*) spans,COUNT(DISTINCT embedding_input_hash) inputs FROM evidence_spans').get()).toMatchObject({spans:9,inputs:1});expect(db.prepare('SELECT COUNT(*) n FROM span_embeddings').get()).toMatchObject({n:9});expect(encoder.statistics.rows).toBe(1);expect(encoder.statistics.workerStarts).toBe(1);}finally{await worker.close();await encoder.close();db.close();fs.rmSync(root,{recursive:true,force:true});}},30000);
it.skipIf(inspectAssets(cache).state!=='ready')('yields after at most two long spans to publish a capture arriving during actual inference',async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-embedding-fairness-'));fs.symlinkSync(cache,path.join(root,'models'),'dir');const db=open({root}),encoder=new LocalEncoder(cache),worker=new MaintenanceWorker(root,{db,encoder});
 try{const tokenizer=(await loadSpanTokenizer(cache))!,claude=path.join(root,'claude'),dir=path.join(claude,'projects','p'),id='33333333-3333-4333-8333-333333333333';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,id+'.jsonl'),JSON.stringify({type:'user',uuid:'new-request',sessionId:id,cwd:'/fairness',timestamp:'2026-01-01T00:00:00Z',message:{role:'user',content:'CAPTURE_DURING_INFERENCE_42'}})+'\n');
 const parsed:ParseResult={session:{id:'long-work',harness:'claude',sourcePath:'/synthetic/fairness',project:'/fairness',projectSlug:'p',startedAt:'',endedAt:'',isSidechain:false,counts:{userPrompts:0,assistantTurns:6,toolCalls:0,bytes:0},status:'live'},records:Array.from({length:6},(_,i)=>({unitKey:'long-'+i,role:'assistant' as const,text:'artifact durable namespace checkpoint '.repeat(75)+' unique '+i,eventAt:null,timeBasis:'unknown' as const,project:'/fairness',locator:{recordKey:'long-'+i,mapping:'unavailable' as const},locatorFidelity:'record_id' as const,recordType:'assistant'})),exchanges:[],unknownTypes:{},endOffset:0,malformedLines:0,evidenceVersion:'synthetic-fairness'};publishSource(db,{parsed,artifactHash:'fairness-artifact',artifactBytes:0,tokenizer});
 let calls=0,requestId='',arrivedAt=0,publishedMs=0;const forward=encoder.encodeBatch.bind(encoder);encoder.encodeBatch=async(...args)=>{expect(args[0].length).toBeLessThanOrEqual(2);if(calls++===0){arrivedAt=Date.now();requestId=enqueueRequest(db,{kind:'capture',targetId:'*',inputHash:'fairness-capture',capture:{claudeDir:claude,harnesses:['claude']}});}else if(!publishedMs){expect(captureStatus(db,requestId)).toMatchObject({state:'done',captured:true});publishedMs=Date.now()-arrivedAt;expect(publishedMs).toBeLessThan(5000);}return forward(...args);};
 await worker.drainOnce();expect(publishedMs).toBeGreaterThan(0);expect(db.prepare("SELECT COUNT(*) n FROM maintenance_jobs WHERE state<>'done'").get()).toMatchObject({n:0});expect(db.prepare('SELECT COUNT(*) n FROM evidence_spans').get()).toEqual(db.prepare('SELECT COUNT(*) n FROM span_embeddings').get());expect(encoder.statistics.effectiveThreads).toBe(4);expect(encoder.statistics.workerProgramHash).toMatch(/^[a-f0-9]{64}$/u);
 }finally{await worker.close();db.close();fs.rmSync(root,{recursive:true,force:true});}
},30000);
