import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {it,expect,afterEach} from 'vitest';
import {parseClaudeTranscript} from '../packages/core/src/parser/claude.js';
import {parseCodexTranscript} from '../packages/core/src/parser/codex.js';
import {indexAll} from '../packages/core/src/ingest.js';
import {open} from '../packages/core/src/db.js';
import {publishSource,listSourceSpans,sourceId} from '../packages/core/src/memory/source.js';
import {hash} from '../packages/core/src/memory/spans.js';
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(root=>fs.rmSync(root,{recursive:true,force:true})));
function write(records:unknown[]){const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-call-names-'));roots.push(root);const file=path.join(root,'11111111-1111-4111-8111-111111111111.jsonl');fs.writeFileSync(file,records.map(r=>JSON.stringify(r)).join('\n')+'\n');return {root,file};}
it('resolves Claude paired name within consumed records, preserves orphan/ambiguous unknown names and explicit outcomes',async()=>{const {file}=write([{type:'assistant',uuid:'input',sessionId:'native',message:{role:'assistant',content:[{type:'tool_use',id:'paired',name:'Bash',input:{command:'echo ok'}},{type:'tool_use',id:'ambiguous',name:'Bash',input:{}},{type:'tool_use',id:'ambiguous',name:'Read',input:{}}]}},{type:'user',uuid:'results',sessionId:'native',message:{role:'user',content:[{type:'tool_result',tool_use_id:'paired',is_error:false,content:'ok'},{type:'tool_result',tool_use_id:'ambiguous',is_error:true,content:'error'},{type:'tool_result',tool_use_id:'orphan',content:'unknown'}]}}]);const parsed=await parseClaudeTranscript(file);const results=parsed.records!.filter(r=>r.role==='tool_result');expect(results.map(r=>r.toolName??null)).toEqual(['Bash',null,null]);expect(results.map(r=>r.outcome)).toEqual(['success','error','unknown']);expect(parsed.evidenceVersion).toBe('claude-records-v4');});
it('resolves Codex paired exec name without inventing a name for missing/ambiguous input metadata',async()=>{const {file}=write([{type:'session_meta',payload:{id:'native',cwd:'/p'}},{type:'response_item',payload:{type:'function_call',name:'exec_command',call_id:'paired',arguments:'{}'}},{type:'response_item',payload:{type:'function_call',call_id:'missing',arguments:'{}'}},{type:'response_item',payload:{type:'function_call',name:'A',call_id:'ambiguous',arguments:'{}'}},{type:'response_item',payload:{type:'function_call',name:'B',call_id:'ambiguous',arguments:'{}'}},...['paired','missing','ambiguous','orphan'].map(call_id=>({type:'response_item',payload:{type:'function_call_output',call_id,output:'ordinary output'}}))]);const parsed=await parseCodexTranscript(file);const results=parsed.records!.filter(r=>r.role==='tool_result');expect(results.map(r=>r.toolName??null)).toEqual(['exec_command',null,null,null]);expect(results.every(r=>r.outcome==='unknown')).toBe(true);expect(parsed.evidenceVersion).toBe('codex-records-v6');});
it('reparses unchanged old-pipeline sources and preserves old immutable refs with missing name metadata',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'p12-name-upgrade-'));roots.push(root);const claude=path.join(root,'claude'),project=path.join(claude,'projects','p');fs.mkdirSync(project,{recursive:true});const id='11111111-1111-4111-8111-111111111111',file=path.join(project,id+'.jsonl');fs.writeFileSync(file,[{type:'user',uuid:'u',promptId:'p',sessionId:id,cwd:'/p',message:{role:'user',content:'run tool'}},{type:'assistant',uuid:'a',sessionId:id,message:{role:'assistant',content:[{type:'tool_use',id:'call',name:'Bash',input:{}}]}},{type:'user',uuid:'r',sessionId:id,message:{role:'user',content:[{type:'tool_result',tool_use_id:'call',is_error:false,content:'ok'}]}}].map(r=>JSON.stringify(r)).join('\n')+'\n');const parsed=await parseClaudeTranscript(file);parsed.evidenceVersion='claude-records-v1';parsed.records=parsed.records!.map(r=>r.role==='tool_result'?{...r,toolName:undefined,locator:{recordKey:r.locator.recordKey,rawStart:r.locator.rawStart,rawEnd:r.locator.rawEnd,mapping:r.locator.mapping}}:r);const db=open({root});try{const old=publishSource(db,{parsed,artifactHash:hash(fs.readFileSync(file)),artifactBytes:fs.statSync(file).size,fingerprint:hash(fs.readFileSync(file))});const report=await indexAll({db,root,claudeDir:claude,harnesses:['claude'],embed:false});expect(report.totals.parsed).toBe(1);expect(listSourceSpans(db,sourceId('claude',id)).evidence.find(e=>e.role==='tool_result')!.provenance!.unitToolName).toBe('Bash');expect(listSourceSpans(db,old.sourceId,old.revisionId).evidence.find(e=>e.role==='tool_result')!.provenance!.unitToolName).toBeNull();}finally{db.close();}});
