import {describe,it,expect,vi} from 'vitest';
import fs from 'node:fs';import path from 'node:path';
import {rescue} from '../packages/core/src/rescue.js';
import {open} from '../packages/core/src/db.js';
import {copyFixtureClaude,tempDir,rmrf} from './helpers.js';
describe('hash-proven archive publication',()=>{
 it('repairs same-size corrupted archive and captures same-stat source rewrite',async()=>{const claude=copyFixtureClaude(),root=tempDir('p12-rescue-hash-');try{await rescue({claudeDir:claude,root});const db=open({root,readonly:true});let row:{source_path:string;archive_path:string};try{row=db.prepare("SELECT source_path,archive_path FROM archive_files WHERE source_path LIKE '%.jsonl' AND source_path NOT LIKE '%history%' LIMIT 1").get() as typeof row;}finally{db.close();}const original=fs.readFileSync(row!.source_path),stat=fs.statSync(row!.source_path);fs.writeFileSync(row!.archive_path,Buffer.alloc(original.length,88));const corrupt=await rescue({claudeDir:claude,root});expect(corrupt.filesCopied).toBeGreaterThan(0);expect(fs.readFileSync(row!.archive_path)).toEqual(original);const changed=Buffer.from(original);changed[0]=original[0]===123?32:123;fs.writeFileSync(row!.source_path,changed);fs.utimesSync(row!.source_path,stat.atime,stat.mtime);const rewrite=await rescue({claudeDir:claude,root});expect(rewrite.filesCopied).toBeGreaterThan(0);expect(fs.readFileSync(row!.archive_path)).toEqual(changed);}finally{rmrf(path.dirname(claude));rmrf(root);}});
 it('rejects a changing copy before rename and preserves the last hash-verified archive',async()=>{const claude=copyFixtureClaude(),root=tempDir('p12-rescue-copy-');let spy:ReturnType<typeof vi.spyOn>|undefined;try{await rescue({claudeDir:claude,root});const db=open({root,readonly:true});let row:{source_path:string;archive_path:string};try{row=db.prepare("SELECT source_path,archive_path FROM archive_files WHERE source_path LIKE '%.jsonl' AND source_path NOT LIKE '%history%' LIMIT 1").get() as typeof row;}finally{db.close();}const original=fs.readFileSync(row!.archive_path);fs.appendFileSync(row!.source_path,'\n');const copy=fs.copyFileSync;spy=vi.spyOn(fs,'copyFileSync').mockImplementation((a,b,flags)=>{copy(a,b,flags);if(a===row!.source_path)fs.appendFileSync(b,'unexpected rewrite');});const result=await rescue({claudeDir:claude,root});expect(result.filesFailed.some(f=>f.path===row!.source_path)).toBe(true);expect(fs.readFileSync(row!.archive_path)).toEqual(original);spy.mockRestore();const retry=await rescue({claudeDir:claude,root});expect(retry.filesFailed).toHaveLength(0);expect(fs.readFileSync(row!.archive_path)).toEqual(fs.readFileSync(row!.source_path));}finally{spy?.mockRestore();rmrf(path.dirname(claude));rmrf(root);}});
});
