import {afterEach,describe,it,expect,vi} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {createAuditSession,publicAuditSnapshot,composeJevJudgments} from '../../packages/core/src/analytics/index.js';
import {JEV_MODEL,type JevRequest} from '../../packages/core/src/analytics/jev-contract.js';
import {digest} from '../../packages/core/src/analytics/source.js';
import type {AuditSession,AuditSemanticSelection} from '../../packages/core/src/analytics/contracts.js';
const roots:string[]=[],sessions:AuditSession[]=[];
afterEach(()=>{sessions.splice(0).forEach(s=>s.dispose());roots.splice(0).forEach(root=>fs.rmSync(root,{recursive:true,force:true}));vi.restoreAllMocks();vi.unstubAllEnvs();});
function fixture(texts=['Build a public widget.','Thanks.']){const root=fs.mkdtempSync(path.join(os.tmpdir(),'jev-session-public-'));roots.push(root);const claude=path.join(root,'claude'),file=path.join(claude,'projects','p','c.jsonl');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,texts.map((text,i)=>JSON.stringify({type:'user',uuid:'u'+i,promptId:'p'+i,sessionId:'c',entrypoint:'cli',cwd:'/synthetic/public',timestamp:new Date(Date.parse('2026-10-01T00:00:00Z')+i*3600000).toISOString(),message:{role:'user',content:text}})).join('\n')+'\n');const s=createAuditSession({claudeDir:claude,potsherdDir:path.join(root,'owned'),harnesses:['claude']});sessions.push(s);return {root,file,s};}
const select=(id:string,extra:Partial<AuditSemanticSelection>={}):AuditSemanticSelection=>({conversationIds:[id],maxPrompts:10,maxRequests:10,budgetUsd:0.2,consent:true,...extra});
function answer(req:JevRequest){const target=(req.state as any).target.text;return new Response(JSON.stringify({model:JEV_MODEL,answers:Object.fromEntries(Object.entries(req.questions).map(([id,q])=>[id,q.type==='noul'?{type:'noul',noul:0.5}:{type:'choice',choice:target==='Thanks.'?'insufficient_context':'feature_build',confidence:target==='Thanks.'?1:0.68,probabilities:Object.fromEntries(Object.keys((q as any).criteria).map(key=>[key,target==='Thanks.'?key==='insufficient_context'?1:0:key==='feature_build'?0.7:0.02]))}])),usage:{input_tokens:1000,output_tokens:60}}));}

describe('explicit private semantic session integration — mocks only',()=>{
 it('rejects changed approved request bodies or policy versions before any provider call',async()=>{
  vi.stubEnv('TYPESAFE_API_KEY','synthetic-key');vi.stubEnv('POTSHERD_TYPESAFE_API_KEY','');const fetch=vi.spyOn(globalThis,'fetch');const {s}=fixture(['Public fixture request.']),snapshot=await s.run(),id=snapshot.conversations[0]!.id,preview=await s.preview!(select(id));
  await expect(s.classify(select(id,{approvedRequestHashes:['0'.repeat(64)],approvedPolicyVersion:preview.preparedRequests[0]!.policyVersion}))).rejects.toThrow('semantic_approved_request_changed');
  await expect(s.classify(select(id,{approvedRequestHashes:preview.preparedRequests.map(p=>p.requestHash),approvedPolicyVersion:'prior-policy'}))).rejects.toThrow('semantic_approved_policy_changed');expect(fetch).not.toHaveBeenCalled();
 });
 it('never uploads on run/preview/key presence, then keeps source metrics stable and warm cache makes zero new calls',async()=>{
  vi.stubEnv('TYPESAFE_API_KEY','synthetic-key');vi.stubEnv('POTSHERD_TYPESAFE_API_KEY','');const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(_url,init)=>answer(JSON.parse(String(init?.body))));const {s}=fixture();const base=await s.run(),id=base.conversations[0]!.id,preview=await s.preview!(select(id));expect(fetch).not.toHaveBeenCalled();expect(preview.selectedPrompts).toBe(2);expect(preview.samples.length).toBeLessThanOrEqual(3);expect(preview.keyAvailable).toBe(true);expect(preview.windowCoverage).toBe('partial');expect(preview.outgoingFields).toContain('assistantContext:unavailable');
  await expect(s.classify({...select(id),consent:false} as any)).rejects.toThrow('consent_required');expect(fetch).not.toHaveBeenCalled();const first=await s.classify(select(id));expect(fetch).toHaveBeenCalledTimes(2);expect(first.metrics).toEqual(base.metrics);expect(first.usage).toEqual(base.usage);expect(first.semantics.qualified).toBe(false);expect(first.semantics.classifiedPrompts).toBe(1);expect(first.semantics.unclassifiedPrompts).toBe(1);expect(first.semantics.uncertainPrompts).toBe(1);expect(first.judgments).toHaveLength(2);expect(first.judgments![0]!.questionDefinitions).toBeDefined();expect(first.judgments!.every(j=>j.windowCoverage==='partial')).toBe(true);expect(JSON.stringify(publicAuditSnapshot(first))).not.toContain('Build a public widget.');expect(publicAuditSnapshot(first).judgments).toEqual([]);
  const warm=await s.classify(select(id,{confidenceThreshold:0.9}));expect(fetch).toHaveBeenCalledTimes(2);expect(warm.semantics.requestCount).toBe(0);expect(warm.semantics.cacheHits).toBe(2);expect(warm.semantics.classifiedPrompts).toBe(0);const local=composeJevJudgments(warm.judgments!,warm.semantics,0.6);expect(local.semantics.classifiedPrompts).toBe(1);expect(local.semantics.requestCount).toBe(0);expect(fetch).toHaveBeenCalledTimes(2);
 });
 it('marks clipped windows uncertain, excludes unknown programmatic origins, and has explicit no-key without fetch',async()=>{
  vi.stubEnv('TYPESAFE_API_KEY','');vi.stubEnv('POTSHERD_TYPESAFE_API_KEY','');const fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(_url,init)=>answer(JSON.parse(String(init?.body))));const {s}=fixture(['x'.repeat(4000)]);const base=await s.run(),id=base.conversations[0]!.id,preview=await s.preview!(select(id));expect(preview.windowCoverage).toBe('truncated');expect(preview.samples[0]!.excerpt.length).toBeLessThanOrEqual(160);expect((await s.classify(select(id))).semantics.state).toBe('no_key');expect(fetch).not.toHaveBeenCalled();
  vi.stubEnv('TYPESAFE_API_KEY','synthetic-key');const result=await s.classify(select(id));expect(result.judgments![0]!.windowCoverage).toBe('truncated');expect(result.judgments![0]!.abstained).toBe(true);expect(result.semantics.classifiedPrompts).toBe(0);expect(result.semantics.unclassifiedPrompts).toBe(1);
 });
 it('keeps private source navigation usable after401 and cancellation',async()=>{
  vi.stubEnv('TYPESAFE_API_KEY','synthetic-key');vi.stubEnv('POTSHERD_TYPESAFE_API_KEY','');const fetch=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response('{}',{status:401}));const {s}=fixture(['Public fixture request.']);const base=await s.run(),id=base.conversations[0]!.id,result=await s.classify(select(id));expect(result.semantics.errorCode).toBe('auth');expect(result.semantics.unresolvedCostUsd).toBeGreaterThan(0);expect((await s.prompts(id)).prompts[0]!.text).toBe('Public fixture request.');
  fetch.mockImplementation(()=>new Promise<Response>(()=>{}));const controller=new AbortController(),pending=s.classify(select(id,{signal:controller.signal}));controller.abort();const cancelled=await pending;expect(cancelled.semantics.state).toBe('cancelled');expect((await s.prompts(id)).prompts).toHaveLength(1);
 });
 it('aborts and clears private derived data when source/privacy changes during a queued model response',async()=>{
  vi.stubEnv('TYPESAFE_API_KEY','synthetic-key');vi.stubEnv('POTSHERD_TYPESAFE_API_KEY','');let release:(response:Response)=>void=()=>{};let sent:JevRequest|null=null;vi.spyOn(globalThis,'fetch').mockImplementation((_url,init)=>{sent=JSON.parse(String(init?.body));return new Promise<Response>(resolve=>{release=resolve;});});const {root,s}=fixture(['Public fixture request.']);const base=await s.run(),id=base.conversations[0]!.id,pending=s.classify(select(id));await new Promise(resolve=>setTimeout(resolve,0));fs.mkdirSync(path.join(root,'owned'),{recursive:true});fs.writeFileSync(path.join(root,'owned','config.json'),JSON.stringify({ignore:['/synthetic/public']}));release(answer(sent!));const result=await pending;expect(result.semantics.state).toBe('cancelled');expect(result.judgments).toEqual([]);expect(result.insights).toEqual([]);expect(result.phrases).toEqual([]);expect(result.conversations).toEqual([]);await expect(s.preview!(select(id))).rejects.toThrow('stale');expect(result.semantics.requestCount).toBe(1);
 });
 it('rejects stale input before sending any source excerpts',async()=>{
  vi.stubEnv('TYPESAFE_API_KEY','synthetic-key');vi.stubEnv('POTSHERD_TYPESAFE_API_KEY','');const fetch=vi.spyOn(globalThis,'fetch'),{file,s}=fixture(['Public fixture request.']),base=await s.run(),id=base.conversations[0]!.id;fs.appendFileSync(file,'{}\n');await expect(s.classify(select(id))).rejects.toThrow('stale');expect(fetch).not.toHaveBeenCalled();
 });
 it('keeps bounded-off eligible inputs in the selected-scope denominator',async()=>{
  vi.stubEnv('TYPESAFE_API_KEY','synthetic-key');vi.stubEnv('POTSHERD_TYPESAFE_API_KEY','');vi.spyOn(globalThis,'fetch').mockImplementation(async(_url,init)=>answer(JSON.parse(String(init?.body))));const {s}=fixture(Array.from({length:100},(_,i)=>'Public fixture request '+i));const base=await s.run(),id=base.conversations[0]!.id,preview=await s.preview!(select(id,{maxPrompts:2}));expect(preview.eligiblePrompts).toBe(100);expect(preview.selectedPrompts).toBe(2);const result=await s.classify(select(id,{maxPrompts:2}));expect(result.semantics.classifiedPrompts).toBe(2);expect(result.semantics.eligiblePrompts).toBe(100);expect(result.semantics.unclassifiedPrompts).toBe(98);expect(result.semantics.work[0]!.denominator).toBe(100);expect(result.semantics.state).toBe('partial');
 });
 it('returns every full bounded private request from the exact same preparation used by dispatch',async()=>{
  vi.stubEnv('TYPESAFE_API_KEY','synthetic-key');vi.stubEnv('POTSHERD_TYPESAFE_API_KEY','');const sent:JevRequest[]=[],fetch=vi.spyOn(globalThis,'fetch').mockImplementation(async(_url,init)=>{const request=JSON.parse(String(init?.body)) as JevRequest;sent.push(request);return answer(request);});const {s}=fixture(['Synthetic private consent text '.repeat(12),'Later public fixture request.']);const base=await s.run(),id=base.conversations[0]!.id,selection=select(id,{maxRequests:2}),preview=await s.preview!(selection);expect(fetch).not.toHaveBeenCalled();expect(preview.preparedRequests).toHaveLength(2);expect(preview.preparedRequests[0]!.request.state.target.text.length).toBeGreaterThan(preview.samples[0]!.excerpt.length);expect(preview.preparedRequests[1]!.request.state.precedingUser[0]!.role).toBe('user');expect(preview.preparedRequests[1]!.request.state.precedingUser[0]!.text).toBe(preview.preparedRequests[0]!.request.state.target.text);for(const item of preview.preparedRequests){expect(item.requestHash).toBe(digest(JSON.stringify(item.request)));expect(item.requestBytes).toBe(Buffer.byteLength(JSON.stringify(item.request)));expect(item.scopeHash).toBeTruthy();expect(item.sourceVersion).toBeTruthy();expect(item.contentHash).toBeTruthy();expect(item.normalizationVersion).toBeTruthy();expect(item.sourceRoute.basis).toBe('transient_snapshot');expect(Object.isFrozen(item.request.state)).toBe(true);}const classified=await s.classify(selection);expect(sent).toEqual(preview.preparedRequests.map(item=>item.request));expect(publicAuditSnapshot(classified)).not.toHaveProperty('preparedRequests');expect(JSON.stringify(publicAuditSnapshot(classified))).not.toContain('Synthetic private consent text');
 });
});
