import {describe,it,expect} from 'vitest';
import {createHash} from 'node:crypto';
import {aggregateLaunchFacts,bundledModelCatalog,resolveCatalogModel,resolveCanonicalModel,validateModelCatalog,valueInference,type ModelCatalog} from '../../packages/core/src/analytics/model-catalog.js';
import type {RecordedInference} from '../../packages/core/src/analytics/launch-contracts.js';
const record=(extra:Partial<RecordedInference>={}):RecordedInference=>({id:'one',conversationId:'c',harness:'codex',eventAt:null,project:null,provider:'openai',model:'gpt-5.4',canonicalModel:null,inputTokens:100,outputTokens:20,cacheReadTokens:40,cacheWriteTokens:0,reasoningTokens:5,inputIncludesCache:true,outputIncludesReasoning:true,reportedCostUsd:null,basis:'synthetic',gaps:[],...extra});
const catalog=():ModelCatalog=>{const models=[{provider:'p',id:'model',canonical:'canonical/model',rates:{input:2,output:10,cache_read:0.5,cache_write:3},tiers:[{threshold:200,rates:{input:4,output:20}}]},{provider:'free',id:'model',canonical:'canonical/model',rates:{input:0,output:0,cache_read:0,cache_write:0}}];return {basis:{source:'https://models.dev/api.json?type=all',retrievedAt:'2026-10-07T00:00:00Z',sha256:createHash('sha256').update(JSON.stringify(models)).digest('hex')},models};};
describe('current catalog inference valuation',()=>{
 it('ranks the explicitly known token portion while retaining unknown totals and coverage',()=>{const f=aggregateLaunchFacts([record({provider:'p',model:'model'}),record({id:'unknown',conversationId:'d',provider:'p',model:'model',inputTokens:null})],catalog());expect(f.models[0]!.totalTokens).toBeNull();expect(f.models[0]!.knownTokens).toBe(120);expect(f.favourite?.tokenShare).toBe(1);expect(f.favourite?.conversationShare).toBe(1);expect(f.favourite?.gaps).toContain('token_share_known_portion_only');});

 it('bundles a validated reduced and reproducible snapshot of the verified public catalog',()=>{expect(validateModelCatalog(bundledModelCatalog)).toBe(true);expect(bundledModelCatalog.models.length).toBeGreaterThan(1000);expect(bundledModelCatalog.models.length).toBeLessThan(1500);expect(bundledModelCatalog.basis.retrievedAt).toContain('2026-10-07');});
 it('matches exact endpoints and model revisions only',()=>{expect(resolveCatalogModel('openai','gpt-5.4')).not.toBeNull();expect(resolveCatalogModel('private','gpt-5.4')).toBeNull();expect(resolveCatalogModel('openai','gpt-5.4-custom')).toBeNull();expect(resolveCatalogModel(null,'gpt-5.4')).toBeNull();});
 it('resolves unambiguous canonical metadata for unknown endpoints without borrowing a rate',()=>{expect(resolveCanonicalModel(null,'model',catalog())).toBe('canonical/model');const v=valueInference(record({provider:null,model:'model'}),catalog());expect(v.canonicalModel).toBe('canonical/model');expect(v.valueUsd).toBeNull();const c=catalog();expect(resolveCanonicalModel(null,'model',{...c,models:[...c.models,{provider:'other',id:'model',canonical:'different/model',rates:{input:1}}]})).toBeNull();});
 it('prices disjoint buckets and never double adds included cache/reasoning',()=>{const v=valueInference(record({provider:'p',model:'model'}),catalog());expect(v.valueUsd).toBe(0.00034);expect(v.record.reportedCostUsd).toBeNull();expect(v.canonicalModel).toBe('canonical/model');});
 it('applies tier threshold from all recorded context input, not uncached input alone',()=>{const v=valueInference(record({provider:'p',model:'model',inputTokens:100,cacheReadTokens:120,inputIncludesCache:false}),catalog());expect(v.rates!.input).toBe(4);expect(v.valueUsd).toBe(0.00086);});
 it('explicit hosted zero remains zero while absent price and unknown buckets remain unknown',()=>{expect(valueInference(record({provider:'free',model:'model'}),catalog()).valueUsd).toBe(0);expect(valueInference(record({provider:'missing',model:'model'}),catalog()).valueUsd).toBeNull();expect(valueInference(record({provider:'p',model:'model',cacheReadTokens:null}),catalog()).valueUsd).toBeNull();});
 it('labels local reference valuation separately and requires an explicit reference',()=>{const r=record({provider:'local',model:'model',canonicalModel:'canonical/model'});expect(valueInference(r,catalog()).valueUsd).toBeNull();const v=valueInference(r,catalog(),{localReferences:{'local/model':{provider:'p',model:'model'}}});expect(v.valueUsd).toBeNull();expect(v.referenceValueUsd).toBe(0.00034);});
 it('retains tiny rates and rejects a hosted reference to a different canonical local model',()=>{const c=catalog();const tiny={...c,models:[{...c.models[0]!,rates:{input:0.000005,output:0,cache_read:0,cache_write:0},tiers:[]}]};expect(valueInference(record({provider:'p',model:'model',inputTokens:1_000_000,outputTokens:0,cacheReadTokens:0}),tiny).valueUsd).toBe(0.000005);const v=valueInference(record({provider:'local',model:'model',canonicalModel:'different/model'}),c,{localReferences:{'local/model':{provider:'p',model:'model'}}});expect(v.referenceValueUsd).toBeNull();expect(v.gaps).toContain('local_reference_model_mismatch');});
 it('aggregates known value coverage, deduplicates inherited IDs and combines token share with conversation participation',()=>{const r=record({provider:'p',model:'model'});const f=aggregateLaunchFacts([r,r,record({id:'two',conversationId:'d',provider:'free',model:'model'}),record({id:'three',provider:'missing',model:'model'})],catalog());expect(f.recordedResponses).toBe(3);expect(f.pricedResponses).toBe(2);expect(f.valueUsd).toBe(0.00034);expect(f.gaps).toContain('pricing_coverage_partial');expect(f.models).toHaveLength(2);expect(f.models[0]!.favouriteScore).toBeCloseTo((2/3+1)/2);expect(f.models[0]!.provider).toBeNull();expect(f.models[0]!.gaps).toContain('multiple_serving_endpoints');expect(f.records[0]!.provider).toBe('p');});
 it('rejects mutated prices, invalid schema values and digest mismatch',()=>{const c=catalog();expect(validateModelCatalog(c)).toBe(true);expect(validateModelCatalog({...c,basis:{...c.basis,sha256:'0'.repeat(64)}})).toBe(false);expect(validateModelCatalog({...c,models:[{...c.models[0],rates:{input:-1}}]})).toBe(false);});
});

describe('approved provider-unknown Anthropic reference valuation',()=>{
 const native=(extra:Partial<RecordedInference>={})=>record({harness:'claude',provider:null,model:'claude-opus-4-8',inputTokens:1000,outputTokens:200,cacheReadTokens:300,cacheWriteTokens:0,reasoningTokens:null,inputIncludesCache:false,outputIncludesReasoning:true,gaps:['provider_unrecorded'],...extra});
 it('values the independently calculated hand fixture at the named first-party rates while preserving the unknown endpoint',()=>{
  // 1,000 uncached × $5/M + 200 output × $25/M + 300 cached × $0.5/M = $0.01015.
  const r=native(),v=valueInference(r);expect(v.valueUsd).toBeNull();expect(v.referenceValueUsd).toBe(0.01015);expect(v.provider).toBeNull();expect(v.record.provider).toBeNull();expect(v.referenceProvider).toBe('anthropic');expect(v.referenceModel).toBe('claude-opus-4-8');expect(v.referenceBasis).toBe('approved_anthropic_first_party');expect(v.canonicalModel).toBe('anthropic/claude-opus-4-8');expect(v.rates).toMatchObject({input:5,output:25,cacheRead:0.5});expect(r).toEqual(native());
 });
 it('allows precisely the five approved exact IDs, including metadata without an explicit first-party canonical field',()=>{
  const expected:Record<string,number>={'claude-opus-4-8':0.01015,'claude-fable-5':0.0203,'claude-opus-5':0.01015,'claude-haiku-4-5-20251001':0.00203,'claude-sonnet-5':0.00406};
  for(const [model,value] of Object.entries(expected)){const v=valueInference(native({model}));expect(v.referenceValueUsd).toBe(value);expect(v.canonicalModel).toBe(`anthropic/${model}`);expect(v.valueUsd).toBeNull();}
 });
 it('preserves a recorded explicitly free hosted endpoint and never introduces a paid reference',()=>{
  const v=valueInference(native({provider:'opencode',model:'jev-1.13-free',cacheReadTokens:0}));expect(v.valueUsd).toBe(0);expect(v.referenceValueUsd).toBeNull();expect(v.referenceProvider).toBeNull();expect(v.referenceBasis).toBeNull();
  const c:ModelCatalog={...bundledModelCatalog,models:[...bundledModelCatalog.models,{provider:'explicit-free',id:'claude-opus-4-8',canonical:'anthropic/claude-opus-4-8',rates:{input:0,output:0,cache_read:0,cache_write:0}}]};const free=valueInference(native({provider:'explicit-free'}),c);expect(free.valueUsd).toBe(0);expect(free.referenceValueUsd).toBeNull();
 });
 it('keeps unknown/synthetic models and unrecognized non-null endpoints unavailable',()=>{
  for(const extra of [{model:null},{model:'<synthetic>'},{model:'claude-opus-4-8-custom'},{provider:'unrecognized-private-endpoint'}]){const v=valueInference(native(extra));expect(v.valueUsd).toBeNull();expect(v.referenceValueUsd).toBeNull();expect(v.referenceProvider).toBeNull();}
  expect(valueInference(native(),bundledModelCatalog,{approvedFirstPartyReferences:{}}).referenceValueUsd).toBeNull();
 });
 it('blocks cache-duration and unknown-token gaps without substituting zeros',()=>{
  const blocked=valueInference(native({gaps:['provider_unrecorded','cache_write_duration_unknown'],cacheWriteTokens:50}));expect(blocked.referenceValueUsd).toBeNull();expect(blocked.gaps).toContain('cache_write_duration_unknown');expect(blocked.referenceProvider).toBe('anthropic');
  const unknown=valueInference(native({inputTokens:null}));expect(unknown.record.inputTokens).toBeNull();expect(unknown.referenceValueUsd).toBeNull();
 });
 it('blocks conflicting recorded or cross-provider canonical metadata',()=>{
  const mismatch=valueInference(native({canonicalModel:'anthropic/different-model'}));expect(mismatch.referenceValueUsd).toBeNull();expect(mismatch.gaps).toContain('first_party_reference_canonical_conflict');
  const conflict:ModelCatalog={...bundledModelCatalog,models:[...bundledModelCatalog.models,{provider:'conflicting',id:'claude-opus-4-8',canonical:'different/model',rates:{input:100}}]};expect(valueInference(native(),conflict).referenceValueUsd).toBeNull();
 });
 it('counts reference and endpoint coverage distinctly and lists the actual named reference basis',()=>{
  const original=native();const f=aggregateLaunchFacts([original,native({id:'blocked',gaps:['cache_write_duration_unknown']}),native({id:'synthetic',model:'<synthetic>'}),native({id:'zero',provider:'opencode',model:'jev-1.13-free',cacheReadTokens:0})]);expect(f.valueUsd).toBe(0);expect(f.referenceValueUsd).toBe(0.01015);expect(f.pricedResponses).toBe(1);expect(f.referencePricedResponses).toBe(1);expect(f.equivalentPricedResponses).toBe(2);expect(f.referenceProviders).toEqual([{provider:'anthropic',model:'claude-opus-4-8',basis:'approved_anthropic_first_party',pricedResponses:1,valueUsd:0.01015}]);expect(f.records[0]!.provider).toBeNull();expect(f.gaps).toContain('equivalent_pricing_coverage_partial');
 });
 it('never expands the five-model approval through a caller map or a cross-model/highest-provider substitution',()=>{
  const unapproved=valueInference(native({model:'model'}),catalog(),{approvedFirstPartyReferences:{model:{provider:'anthropic',model:'model'}}});expect(unapproved.referenceValueUsd).toBeNull();
  const remap=valueInference(native(),bundledModelCatalog,{approvedFirstPartyReferences:{'claude-opus-4-8':{provider:'anthropic',model:'claude-fable-5'}}});expect(remap.referenceValueUsd).toBeNull();
 });
});
