import {describe,it,expect,vi,afterEach} from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {DerivedCache,type DerivedCacheBinding} from '../../packages/core/src/analytics/derived-cache.js';
import {indexHistoryBytes,historyMayOverlap,validateHistoryDateIndex} from '../../packages/core/src/analytics/history-index.js';
import {createAuditSession} from '../../packages/core/src/analytics/index.js';
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();});
const binding:DerivedCacheBinding={sourceId:'s',sourceIdentity:'inode-1',contentHash:'hash-one',currentness:'fresh-one',privacyPolicy:'policy1',forgetEpoch:'0',normalizationVersion:'native-v1'};
const validate=(v:unknown):v is {count:number}=>!!v&&typeof v==='object'&&typeof (v as {count?:unknown}).count==='number';
describe('private persistent derived cache and date inventory',()=>{
 it('keeps generic durability and opts regenerable caches into atomic replacement with the same permissions and values',()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'launch-atomic-derived-'));try{const sync=vi.spyOn(fs,'fsyncSync'),durable=new DerivedCache(path.join(dir,'durable')),atomic=new DerivedCache(path.join(dir,'atomic'));durable.write('usage',binding,{count:2},validate);expect(sync).toHaveBeenCalledTimes(2);sync.mockClear();atomic.write('native-facts',binding,{count:2},validate,{durability:'atomic'});expect(sync).not.toHaveBeenCalled();expect(atomic.read('native-facts',binding,validate)).toEqual(durable.read('usage',binding,validate));atomic.write('semantic-answer',binding,{count:2},validate,{durability:'atomic'});expect(sync).toHaveBeenCalledTimes(2);sync.mockClear();atomic.write('public-catalog',binding,{count:2},validate,{durability:'atomic'});expect(sync).toHaveBeenCalledTimes(2);expect(fs.statSync(atomic.directory).mode&0o777).toBe(0o700);expect(fs.statSync(path.join(atomic.directory,fs.readdirSync(atomic.directory)[0]!)).mode&0o777).toBe(0o600);}finally{fs.rmSync(dir,{recursive:true,force:true});}
 });
 it('preserves the old atomic entry after failed replacement and treats lost, truncated, corrupt or mismatched entries as misses',()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'launch-atomic-fault-'));try{const cache=new DerivedCache(dir);cache.write('native-facts',binding,{count:2},validate,{durability:'atomic'});const file=path.join(dir,fs.readdirSync(dir)[0]!),original=fs.readFileSync(file);const rename=vi.spyOn(fs,'renameSync').mockImplementation(()=>{throw new Error('public_rename_failure');});expect(()=>cache.write('native-facts',binding,{count:3},validate,{durability:'atomic'})).toThrow('public_rename_failure');rename.mockRestore();expect(cache.read('native-facts',binding,validate)).toEqual({count:2});expect(fs.readdirSync(dir).filter(f=>f.endsWith('.tmp'))).toHaveLength(0);fs.writeFileSync(path.join(dir,'.launch-public-crash.tmp'),'partial',{mode:0o600});expect(cache.read('native-facts',binding,validate)).toEqual({count:2});fs.unlinkSync(file);expect(cache.read('native-facts',binding,validate)).toBeNull();for(const text of [original.subarray(0,original.length/2),'not-json',JSON.stringify({...JSON.parse(original.toString()),binding:'replaced'})]){fs.writeFileSync(file,text,{mode:0o600});expect(cache.read('native-facts',binding,validate)).toBeNull();}fs.writeFileSync(file,original,{mode:0o600});for(const change of [{contentHash:'changed'},{sourceIdentity:'replaced'},{privacyPolicy:'manual-forget-no-epoch'},{scopeHash:'changed'},{normalizationVersion:'changed'}])expect(cache.read('native-facts',{...binding,...change},validate)).toBeNull();}finally{fs.rmSync(dir,{recursive:true,force:true});}
 });
 it('reparses native facts and rejects a valid JSON cached vector that no longer matches the verified source',async()=>{
  vi.stubEnv('POTSHERD_OFFLINE','1');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'launch-atomic-native-'));try{const owned=path.join(dir,'owned'),claude=path.join(dir,'claude'),native=path.join(claude,'projects','public');fs.mkdirSync(owned);fs.writeFileSync(path.join(owned,'config.json'),'{}');fs.mkdirSync(native,{recursive:true});fs.writeFileSync(path.join(native,'public.jsonl'),JSON.stringify({type:'assistant',sessionId:'public',uuid:'public-response',cwd:'/public',timestamp:'2026-10-06T00:00:00Z',message:{id:'public-response',role:'assistant',model:'claude-sonnet-4-6',provider:'anthropic',usage:{input_tokens:1000,output_tokens:100,cache_read_input_tokens:0,cache_creation_input_tokens:0}}})+'\n');const options={potsherdDir:owned,claudeDir:claude,codexDir:path.join(dir,'codex'),piDir:path.join(dir,'pi'),opencodeDir:path.join(dir,'opencode'),harnesses:['claude'] as const,launch:true},run=async()=>{const session=createAuditSession(options);try{return await session.run();}finally{session.dispose();}};const first=await run();expect(first.launch!.facts!.records[0]!.inputTokens).toBe(1000);const cache=path.join(owned,'audit-derived'),file=path.join(cache,fs.readdirSync(cache).find(f=>f.startsWith('native-facts-'))!),value=JSON.parse(fs.readFileSync(file,'utf8'));value.value.usage[0].inputTokens=9000;fs.writeFileSync(file,JSON.stringify(value),{mode:0o600});const changed=await run();expect(changed.launch!.factProgress!.cacheHits).toBe(0);expect(changed.launch!.facts!.records[0]!.inputTokens).toBe(1000);}finally{fs.rmSync(dir,{recursive:true,force:true});}
 });
 it('persists atomically at 0600 and invalidates changed source/privacy/forget/model/question bindings',()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'launch-derived-'));try{const cache=new DerivedCache(path.join(dir,'derived'));cache.write('usage',binding,{count:2},validate);expect(cache.read('usage',binding,validate)).toEqual({count:2});const entries=fs.readdirSync(cache.directory);expect(entries).toHaveLength(1);expect(fs.statSync(path.join(cache.directory,entries[0]!)).mode&0o777).toBe(0o600);expect(fs.statSync(cache.directory).mode&0o777).toBe(0o700);
   for(const change of [{contentHash:'hash-two'},{sourceIdentity:'inode-2'},{currentness:'stale'},{privacyPolicy:'policy2'},{forgetEpoch:'1'},{model:'different'},{questionVersion:'q2'},{normalizationVersion:'v2'},{segmentationVersion:'new'}])expect(cache.read('usage',{...binding,...change},validate)).toBeNull();expect(fs.readdirSync(cache.directory).filter(f=>f.endsWith('.tmp'))).toHaveLength(0);
  }finally{fs.rmSync(dir,{recursive:true,force:true});}
 });
 it('rejects transcript-bearing payloads and malformed persisted schemas even under permissive validators',()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'launch-derived-'));try{const cache=new DerivedCache(dir);const any=(v:unknown):v is unknown=>true;expect(()=>cache.write('semantic',binding,{answers:{text:'private transcript sentinel'}},any)).toThrow('derived_cache_value_invalid');cache.write('usage',binding,{count:2},validate);const file=path.join(dir,fs.readdirSync(dir)[0]!);fs.writeFileSync(file,'{"schema":"old","value":{"count":2}}');expect(cache.read('usage',binding,validate)).toBeNull();expect(fs.readFileSync(file,'utf8')).not.toContain('private transcript sentinel');}finally{fs.rmSync(dir,{recursive:true,force:true});}
 });
 it('skips warm intervals only from verified complete recorded dates, never file timestamps',()=>{
  const bytes=Buffer.from('{"type":"message","timestamp":"2026-01-01T00:00:00Z"}\n{"type":"message","timestamp":"2026-01-04T00:00:00Z"}\n');const index=indexHistoryBytes(bytes,'pi',binding);expect(validateHistoryDateIndex(index)).toBe(true);expect(index.eventFrom).toBe('2026-01-01T00:00:00.000Z');expect(historyMayOverlap(index,binding,'2026-09-01',null)).toBe(false);expect(historyMayOverlap(index,binding,'2026-01-03','2026-01-05')).toBe(true);expect(historyMayOverlap(index,{...binding,contentHash:'changed'},'2026-09-01',null)).toBe(true);expect(historyMayOverlap(index,{...binding,currentness:'changed'},'2026-09-01',null)).toBe(true);
 });
 it('keeps unknown dates, malformed records, bounds and incomplete tails conservative',()=>{
  for(const bytes of ['{"type":"message"}\n','not-json\n','{"timestamp":"2026-01-01T00:00:00Z"}','{"timestamp":"2026-01-01T00:00:00Z"}\n{"timestamp":"2026-01-02T00:00:00Z"}\n']){const index=indexHistoryBytes(bytes,'pi',binding,{maxRecords:1});expect(index.complete).toBe(false);expect(historyMayOverlap(index,binding,'2026-09-01',null)).toBe(true);}
 });
 it('supports native OpenCode timestamp metadata and rejects invented complete index records',()=>{const i=indexHistoryBytes('[{"id":"one","time":{"created":1767225600000}}]','opencode',binding);expect(i.complete).toBe(true);expect(historyMayOverlap(i,binding,'2026-09-01',null)).toBe(false);expect(validateHistoryDateIndex({...i,unknownDates:3})).toBe(false);});
});
