import {describe,it,expect,afterEach,vi} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {createAuditSession,publicAuditSnapshot} from '../../packages/core/src/analytics/index.js';
import type {AuditSession} from '../../packages/core/src/analytics/contracts.js';
const roots:string[]=[],sessions:AuditSession[]=[];
afterEach(()=>{sessions.splice(0).forEach(s=>s.dispose());roots.splice(0).forEach(r=>fs.rmSync(r,{recursive:true,force:true}));vi.restoreAllMocks();});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'launch-integrated-'));roots.push(root);return {root,options:{potsherdDir:path.join(root,'owned'),claudeDir:path.join(root,'claude'),codexDir:path.join(root,'codex'),piDir:path.join(root,'pi'),opencodeDir:path.join(root,'opencode'),launch:true,launchPrepareOnly:true}};}
function write(file:string,rows:unknown[]){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,rows.map(r=>JSON.stringify(r)).join('\n')+'\n');return file;}
const user=(id:string,cwd:string)=>({type:'user',sessionId:'c',uuid:id,promptId:id,cwd,timestamp:'2026-10-07T05:00:00Z',message:{role:'user',content:'Please repair the public fixture export.'}});
const assistant=(id:string,cwd:string,model='claude-sonnet-4-6')=>({type:'assistant',sessionId:'c',uuid:id,cwd,timestamp:'2026-10-07T05:01:00Z',message:{id,role:'assistant',model,provider:'anthropic',content:'The export tests passed.',usage:{input_tokens:1000,output_tokens:200,cache_read_input_tokens:300,cache_creation_input_tokens:0}}});
function session(options:Parameters<typeof createAuditSession>[0]){const s=createAuditSession(options);sessions.push(s);return s;}
describe('integrated terminal launch privacy and facts',()=>{
 it('settles the real terminal stage when source policy holds and never dispatches',async()=>{const f=fixture();fs.mkdirSync(f.options.potsherdDir,{recursive:true});fs.writeFileSync(path.join(f.options.potsherdDir,'config.json'),'invalid policy JSON');write(path.join(f.options.claudeDir,'projects','p','c.jsonl'),[user('u','/fixture/repair')]);const fetch=vi.spyOn(globalThis,'fetch').mockRejectedValue(new Error('network forbidden'));const result=await session(f.options).run();expect(result.status).toBe('partial');expect(result.launch!.stage).toBe('ready');expect(result.launch!.semantics!.state).toBe('unavailable');expect(result.launch!.semantics!.attempts).toBe(0);expect(result.launch!.facts).toBeNull();expect(fetch).not.toHaveBeenCalled();expect(result.launch!.semantics!.gaps).toContain('ignore_policy_unavailable');});
 it('values recorded responses, preserves recipient disclosure and writes only body-free derived results',async()=>{const f=fixture(),file=write(path.join(f.options.claudeDir,'projects','p','c.jsonl'),[user('u','/fixture/repair'),assistant('a','/fixture/repair')]),before=fs.readFileSync(file);const fetch=vi.spyOn(globalThis,'fetch').mockRejectedValue(new Error('network forbidden'));const result=await session({...f.options,harnesses:['claude']}).run();
  expect(result.launch!.facts!.recordedResponses).toBe(1);expect(result.launch!.facts!.models[0]!.model).toBe('claude-sonnet-4-6');expect(result.launch!.facts!.valueUsd).toBeGreaterThan(0);expect(result.projects[0]!.displayName).toBe('repair');expect(result.launch!.semantics!.state).toBe('unavailable');expect(result.launch!.notice).toContain('OpenCode Zen');expect(fetch).not.toHaveBeenCalled();expect(fs.readFileSync(file).equals(before)).toBe(true);
  const cache=path.join(f.options.potsherdDir,'audit-derived'),text=fs.readdirSync(cache).map(name=>fs.readFileSync(path.join(cache,name),'utf8')).join('\n');expect(text).not.toContain('Please repair');expect(text).not.toContain('export tests passed');expect(fs.readdirSync(cache).every(name=>(fs.statSync(path.join(cache,name)).mode&0o077)===0)).toBe(true);
  const publicText=JSON.stringify(publicAuditSnapshot(result));expect(publicText).not.toContain('/fixture/repair');expect(publicText).not.toContain('Please repair');
 });
 it('drops ignored per-record usage/context and invalidates launch data when a source changes',async()=>{const f=fixture(),ignored='/fixture/ignored',allowed='/fixture/allowed';fs.mkdirSync(f.options.potsherdDir,{recursive:true});fs.writeFileSync(path.join(f.options.potsherdDir,'config.json'),JSON.stringify({ignore:[ignored]}));const file=write(path.join(f.options.claudeDir,'projects','p','c.jsonl'),[user('x',ignored),assistant('secret-a',ignored),user('u',allowed),assistant('a',allowed)]),s=session({...f.options,harnesses:['claude']});const result=await s.run();expect(result.launch!.facts!.recordedResponses).toBe(1);expect(JSON.stringify(result.launch)).not.toContain(ignored);const id=result.conversations[0]!.id;fs.appendFileSync(file,JSON.stringify(user('changed',allowed))+'\n');await expect(s.prompts(id)).rejects.toThrow('stale');expect(s.snapshot().launch!.facts).toBeNull();expect(s.snapshot().launch!.semantics).toBeNull();
 });
 it('reuses unchanged body-free factual entries and refuses them after privacy policy changes',async()=>{const f=fixture();write(path.join(f.options.claudeDir,'projects','p','c.jsonl'),[user('u','/fixture/repair'),assistant('a','/fixture/repair')]);const a=await session({...f.options,harnesses:['claude']}).run(),b=await session({...f.options,harnesses:['claude']}).run();expect(a.launch!.facts).toEqual(b.launch!.facts);fs.writeFileSync(path.join(f.options.potsherdDir,'config.json'),JSON.stringify({ignore:['/fixture/repair']}));const c=await session({...f.options,harnesses:['claude']}).run();expect(c.launch!.facts!.recordedResponses).toBe(0);expect(c.metrics.humanPrompts.value).toBe(0);
 });
});
