import {afterEach,describe,it,expect,vi} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createAuditSession} from '../../packages/core/src/analytics/index.js';
import {streamNativeFacts} from '../../packages/core/src/analytics/native-stream.js';
import {createNativeUsageAccumulator} from '../../packages/core/src/analytics/native-usage.js';
import {POTSHERD_CARD_MARKER} from '../../packages/core/src/markers.js';
import {buildLaunchRequest,REQUESTED_USER_QUESTION_VERSION} from '../../packages/core/src/analytics/launch-semantics.js';
import type {AuditSnapshot,AuditSession} from '../../packages/core/src/analytics/contracts.js';
const roots:string[]=[],sessions:AuditSession[]=[];afterEach(()=>{sessions.splice(0).forEach(s=>s.dispose());roots.splice(0).forEach(r=>fs.rmSync(r,{recursive:true,force:true}));vi.restoreAllMocks();vi.unstubAllEnvs();});
const stamp='2026-10-07T05:00:00.000Z';
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'lean-public-audit-'));roots.push(root);const options={potsherdDir:path.join(root,'owned'),claudeDir:path.join(root,'claude'),codexDir:path.join(root,'codex'),piDir:path.join(root,'pi'),opencodeDir:path.join(root,'opencode'),harnesses:['claude'] as const,launch:true,launchPrepareOnly:true};fs.mkdirSync(options.potsherdDir);fs.writeFileSync(path.join(options.potsherdDir,'config.json'),'{}');return {root,options};}
function rows(id:string,input=1000,body='Assistant body sentinel'){return [{type:'user',sessionId:id,uuid:'u-'+id,promptId:'p-'+id,cwd:'/public',timestamp:stamp,message:{role:'user',content:'Please repair the public export.'}},{type:'assistant',sessionId:id,uuid:'a-'+id,requestId:'r-'+id,cwd:'/public',timestamp:stamp,message:{id:'response-'+id,role:'assistant',model:'claude-sonnet-4-6',provider:'anthropic',content:body,usage:{input_tokens:input,output_tokens:20,cache_read_input_tokens:300,cache_creation_input_tokens:0}}}];}
function write(f:ReturnType<typeof fixture>,name:string,records:unknown[]){const p=path.join(f.options.claudeDir,'projects','p',name+'.jsonl');fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,records.map(r=>JSON.stringify(r)).join('\n')+'\n');return p;}
function session(f:ReturnType<typeof fixture>){const s=createAuditSession(f.options);sessions.push(s);return s;}
describe('lean complete-source progressive audit',()=>{
 it('uses parsed record ingestion with exact source positions and cumulative accounting',()=>{const records=[{type:'session_meta',payload:{id:'public',cwd:'/public'}},{type:'turn_context',payload:{model:'gpt-6.1-sol'}},{type:'event_msg',timestamp:stamp,payload:{type:'token_count',info:{last_token_usage:{input_tokens:10,output_tokens:2,cached_input_tokens:1},total_token_usage:{input_tokens:10,output_tokens:2,cached_input_tokens:1}}}},{type:'event_msg',timestamp:stamp,payload:{type:'token_count',info:{total_token_usage:{input_tokens:25,output_tokens:5,cached_input_tokens:3}}}}];const text=createNativeUsageAccumulator('codex','public'),parsed=createNativeUsageAccumulator('codex','public');let at=0;for(const r of records){const line=JSON.stringify(r),end=at+Buffer.byteLength(line)+1;text.pushLine(line);parsed.pushRecord(r,{rawStart:at,rawEnd:end});at=end;}expect(parsed.records()).toEqual(text.records());expect(parsed.counts()).toEqual(text.counts());});
 it('never captures assistant/tool bodies and retains all eligible user text and model metadata',async()=>{const f=fixture(),file=write(f,'body',rows('body',1000,'x'.repeat(1024*1024)));const result=await streamNativeFacts(file,'claude',{signal:new AbortController().signal,maxBytes:4*1024*1024,captureBytes:0,accept:()=>true});expect(result.facts.bytes.length).toBe(0);expect(result.facts.events[0]!.text).toBe('Please repair the public export.');expect(result.usage[0]!.inputTokens).toBe(1000);expect(result.language.some(r=>r.role==='assistant'&&r.model==='claude-sonnet-4-6')).toBe(true);expect(result.facts.gaps).not.toContain('context_capture_partial');});
 it('publishes only completed eligible sources and retracts no late-optout records into an early total',async()=>{const f=fixture();write(f,'small',rows('small'));write(f,'late', [...rows('late',9000,'x'.repeat(100000)),{type:'user',sessionId:'late',uuid:'optout',message:{role:'user',content:POTSHERD_CARD_MARKER}}]);const snapshots:AuditSnapshot[]=[];const result=await session(f).run(e=>{if(e.type==='snapshot'&&e.snapshot.launch?.factProgress)snapshots.push(e.snapshot);});const partial=snapshots.find(s=>s.launch!.factProgress!.state==='collecting'&&s.launch!.facts!.recordedResponses>0)!;expect(partial.launch!.facts!.records).toEqual([]);expect(partial.launch!.facts!.recordsIncluded).toBe(false);expect(partial.launch!.factProgress!.completedSources).toBe(1);expect(snapshots.every(s=>(s.launch!.facts?.recordedResponses??0)<=1)).toBe(true);expect(result.launch!.facts!.recordsIncluded).toBe(true);expect(result.launch!.facts!.records).toHaveLength(1);expect(result.launch!.factProgress!.state).toBe('complete');});
 it('binds warm facts to verified content and rejects a changed prefix even when stat hints are forged',async()=>{const f=fixture(),file=write(f,'warm',rows('warm'));const a=await session(f).run();expect(a.launch!.factProgress!.cacheHits).toBe(0);const warm=await session(f).run();expect(warm.launch!.factProgress!.cacheHits).toBe(1);const old=fs.statSync(file,{bigint:true});fs.writeFileSync(file,fs.readFileSync(file,'utf8').replace('"input_tokens":1000','"input_tokens":9000'));const original=fs.statSync;vi.spyOn(fs,'statSync').mockImplementation(((p:any,o:any)=>String(p)===file&&o?.bigint?old:original(p,o)) as typeof fs.statSync);const changed=await session(f).run();expect(changed.launch!.factProgress!.cacheHits).toBe(0);expect(changed.launch!.facts!.records[0]!.inputTokens).toBe(9000);});
 it('keeps appended alias user inputs and whole usage vectors without retaining source bodies',async()=>{const f=fixture(),prefix=rows('alias');write(f,'small',prefix);write(f,'larger',[...prefix,{...prefix[0],uuid:'new-user',promptId:'new-prompt',message:{role:'user',content:'Please add public pagination.'}},{...prefix[1],uuid:'new-assistant',requestId:'new-request',message:{...prefix[1]!.message,id:'new-response',usage:{input_tokens:2000,output_tokens:30,cache_read_input_tokens:400,cache_creation_input_tokens:0}}}]);const result=await session(f).run();expect(result.metrics.nativeUserInputs!.value).toBe(2);expect(result.launch!.facts!.recordedResponses).toBe(2);expect(result.coverage.gapCodes).not.toContain('source_alias_conflict');});
 it('revokes cached early pricing after an actual ignore policy change',async()=>{const f=fixture();write(f,'cache',rows('cache'));await session(f).run();const s=session(f);let changed=false;const result=await s.run(e=>{if(!changed&&e.type==='snapshot'&&e.snapshot.launch?.factProgress?.cacheHits){changed=true;fs.writeFileSync(path.join(f.options.potsherdDir,'config.json'),JSON.stringify({ignore:['/public']}));}});expect(changed).toBe(true);expect(result.launch!.facts).toBeNull();expect(result.coverage.gapCodes).toContain('audit_snapshot_stale');});
 it('cancels after a real completed-source fact without reading the remaining inventory',async()=>{const f=fixture();write(f,'a',rows('a'));write(f,'b',rows('b',2000,'x'.repeat(10000)));const s=session(f);const result=await s.run(e=>{if(e.type==='snapshot'&&e.snapshot.launch?.factProgress?.state==='collecting'&&e.snapshot.launch.facts?.recordedResponses)s.cancel();});expect(result.status).toBe('cancelled');expect(result.funnel!.nativeFilesParsed).toBe(1);expect(result.launch!.semantics!.attempts).toBe(0);});
 it('preserves Codex assistant model/provider reaction context without token-count records or assistant prose',async()=>{const f=fixture(),file=path.join(f.options.codexDir,'sessions','rollout-public.jsonl');fs.mkdirSync(path.dirname(file),{recursive:true});const records=[{type:'session_meta',payload:{id:'public-codex',cwd:'/public',source:'cli'}},{type:'turn_context',payload:{model:'previous-context-model',model_provider:'previous-provider'}},{type:'event_msg',timestamp:stamp,payload:{type:'user_message',message:'Please repair the public export.'}},{type:'response_item',model:'gpt-6.1-sol',timestamp:stamp,payload:{type:'message',role:'assistant',model_provider:'openai',content:[{type:'output_text',text:'ASSISTANT BODY OMITTED SENTINEL'}]}},{type:'event_msg',timestamp:stamp,payload:{type:'user_message',message:'You fucking missed this, why is the public export broken?'}}];fs.writeFileSync(file,records.map(r=>JSON.stringify(r)).join('\n')+'\n');const streamed=await streamNativeFacts(file,'codex',{signal:new AbortController().signal,maxBytes:100000,captureBytes:0,accept:()=>true});expect(streamed.language.filter(r=>r.role==='assistant')).toEqual([expect.objectContaining({model:'gpt-6.1-sol',provider:'openai',text:''})]);const s=createAuditSession({...f.options,harnesses:['codex']});sessions.push(s);const result=await s.run();expect(result.launch!.modelFeedback).toContainEqual(expect.objectContaining({model:'gpt-6.1-sol',provider:'openai',directedNegativeInputs:1}));expect(result.metrics.nativeUserInputs!.value).toBe(2);expect(JSON.stringify(result.launch)).not.toContain('ASSISTANT BODY OMITTED SENTINEL');});
 it('keeps user-only semantic requests free of assistant/tool prose and completion choices',()=>{const record={id:'u',conversationId:'public',parentId:null,harness:'claude' as const,eventAt:stamp,project:'/public',role:'user' as const,text:'Please repair the public export.',model:null,provider:null,directUser:true,route:null},segment={id:'s',conversationId:'public',parentId:null,project:'/public',eventFrom:stamp,eventTo:stamp,records:[record,{...record,id:'a',role:'assistant' as const,text:'ASSISTANT COMPLETION SENTINEL'},{...record,id:'t',role:'tool' as const,text:'TOOL RESULT SENTINEL'}],promptIds:['u'],coverage:'complete' as const,gaps:[],contentHash:'public-hash'};const request=buildLaunchRequest(segment,'requested_user');expect(JSON.stringify(request)).not.toContain('ASSISTANT COMPLETION SENTINEL');expect(JSON.stringify(request)).not.toContain('TOOL RESULT SENTINEL');expect(Object.keys((request.questions.outcome as {criteria:Record<string,string>}).criteria)).toEqual(['attempted','uncertain']);expect(REQUESTED_USER_QUESTION_VERSION).not.toBe('launch-semantic-v1');});
});
