import {it,expect,vi,afterEach} from 'vitest';
import {createHash} from 'node:crypto';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createAuditSession} from '../../packages/core/src/analytics/index.js';
import * as catalog from '../../packages/core/src/analytics/model-catalog.js';
import {extractNativeUsage} from '../../packages/core/src/analytics/native-usage.js';
import {sourceId} from '../../packages/core/src/memory/source-identity.js';
import {POTSHERD_CARD_MARKER} from '../../packages/core/src/markers.js';
const roots:string[]=[];afterEach(()=>{roots.splice(0).forEach(r=>fs.rmSync(r,{recursive:true,force:true}));vi.restoreAllMocks();vi.unstubAllEnvs();});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'cheap-progress-public-'));roots.push(root);const owned=path.join(root,'owned'),claude=path.join(root,'claude'),dir=path.join(claude,'projects','public');fs.mkdirSync(owned);fs.writeFileSync(path.join(owned,'config.json'),'{}');fs.mkdirSync(dir,{recursive:true});return {dir,options:{potsherdDir:owned,claudeDir:claude,codexDir:path.join(root,'codex'),piDir:path.join(root,'pi'),opencodeDir:path.join(root,'opencode'),harnesses:['claude'] as const,launch:true,launchPrepareOnly:false}};}
const response=(session:string,id:string,body='')=>({type:'assistant',sessionId:session,uuid:id,requestId:'request-'+id,cwd:'/public',timestamp:'2026-10-06T00:00:00Z',message:{id,role:'assistant',model:'claude-sonnet-4-6',provider:'anthropic',content:body,usage:{input_tokens:1000,output_tokens:100,cache_read_input_tokens:200,cache_creation_input_tokens:0}}});
it('prices one meaningful subset and one exact final native aggregate for 45000 records across663 public sources',async()=>{vi.stubEnv('POTSHERD_OFFLINE','1');const f=fixture(),expected=[],ordering=new Map<string,{bytes:number;file:string}>();for(let s=0;s<663;s++){const sid='public-'+s,rows=[];for(let i=s;i<45000;i+=663)rows.push(response(sid,'public-response-'+i));const text=rows.map(r=>JSON.stringify(r)).join('\n')+'\n';fs.writeFileSync(path.join(f.dir,sid+'.jsonl'),text);const source=sourceId('claude',sid);ordering.set(source,{bytes:Buffer.byteLength(text),file:path.join(f.dir,sid+'.jsonl')});expected.push(...extractNativeUsage(text,'claude',source));}expected.sort((a,b)=>ordering.get(a.conversationId)!.bytes-ordering.get(b.conversationId)!.bytes||ordering.get(a.conversationId)!.file.localeCompare(ordering.get(b.conversationId)!.file));const spy=vi.spyOn(catalog,'aggregateLaunchFacts'),session=createAuditSession(f.options);try{let early=false;const result=await session.run(e=>{if(e.type==='snapshot'&&e.snapshot.launch?.factProgress?.state==='collecting'&&e.snapshot.launch.facts?.equivalentPricedResponses){early=true;expect(e.snapshot.launch.facts.recordsIncluded).toBe(false);expect(e.snapshot.launch.factProgress.representedSources).toBeLessThanOrEqual(e.snapshot.launch.factProgress.completedSources);}});expect(early).toBe(true);expect(spy).toHaveBeenCalledTimes(2);const actual={...result.launch!.facts!};delete actual.recordsIncluded;const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');expect(digest(actual)).toBe(digest(catalog.aggregateLaunchFacts(expected)));expect(result.launch!.factProgress).toMatchObject({state:'complete',completedSources:663,totalSources:663,representedSources:663});}finally{session.dispose();}},30000);
it('immediately clears a represented preview when a later verified whole-source optout is discovered',async()=>{vi.stubEnv('POTSHERD_OFFLINE','1');const f=fixture(),sid='public-optout';fs.writeFileSync(path.join(f.dir,'first.jsonl'),JSON.stringify(response(sid,'first'))+'\n');fs.writeFileSync(path.join(f.dir,'late.jsonl'),[response(sid,'late','x'.repeat(100000)),{type:'user',sessionId:sid,message:{role:'user',content:POTSHERD_CARD_MARKER}}].map(r=>JSON.stringify(r)).join('\n')+'\n');const session=createAuditSession(f.options);try{let preview=false,cleared=false;const result=await session.run(e=>{if(e.type!=='snapshot'||e.snapshot.launch?.factProgress?.state!=='collecting')return;if(e.snapshot.launch.facts?.equivalentPricedResponses)preview=true;if(preview&&e.snapshot.launch.facts===null&&e.snapshot.launch.factProgress.representedSources===0)cleared=true;});expect(preview).toBe(true);expect(cleared).toBe(true);expect(result.launch!.facts!.recordedResponses).toBe(0);}finally{session.dispose();}});
