import {afterAll,afterEach,beforeAll,describe,it,expect,vi} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {build} from 'esbuild';import {createHash} from 'node:crypto';
import {createNativeScanPool,type NativeScanExecutor,type NativeScanJob} from '../../packages/core/src/analytics/native-pool.js';
import {createAuditSession} from '../../packages/core/src/analytics/index.js';
import {streamNativeFacts} from '../../packages/core/src/analytics/native-stream.js';
import {sourceId as pureSourceId} from '../../packages/core/src/memory/source-identity.js';
import {sourceId as memorySourceId} from '../../packages/core/src/memory/source.js';
import {POTSHERD_CARD_MARKER} from '../../packages/core/src/markers.js';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'native-pool-public-')),entry=path.join(directory,'worker.mjs'),roots:string[]=[],pools:NativeScanExecutor[]=[];
beforeAll(async()=>{await build({entryPoints:[path.resolve('packages/cli/src/audit-native-worker.ts')],outfile:entry,bundle:true,platform:'node',format:'esm',target:'node22',logLevel:'silent'});});
afterEach(async()=>{await Promise.all(pools.splice(0).map(p=>p.close()));roots.splice(0).forEach(r=>fs.rmSync(r,{recursive:true,force:true}));vi.restoreAllMocks();});afterAll(()=>fs.rmSync(directory,{recursive:true,force:true}));
const timestamp='2026-10-07T00:00:00.000Z';
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'native-pool-fixture-'));roots.push(root);const options={potsherdDir:path.join(root,'owned'),claudeDir:path.join(root,'claude'),codexDir:path.join(root,'codex'),piDir:path.join(root,'pi'),opencodeDir:path.join(root,'opencode'),harnesses:['claude'] as const,launch:true,launchPrepareOnly:true};fs.mkdirSync(options.potsherdDir);fs.writeFileSync(path.join(options.potsherdDir,'config.json'),'{}');return {root,options};}
function records(id:string,body='x'.repeat(10000)){return [{type:'user',sessionId:id,uuid:'user-'+id,promptId:'prompt-'+id,cwd:'/public',timestamp,message:{role:'user',content:'Please repair the public fixture export.'}},{type:'assistant',sessionId:id,uuid:'assistant-'+id,requestId:'request-'+id,cwd:'/public',timestamp,message:{id:'response-'+id,role:'assistant',model:'claude-sonnet-4-6',provider:'anthropic',content:body,usage:{input_tokens:1000,output_tokens:100,cache_read_input_tokens:300,cache_creation_input_tokens:0}}}];}
function write(f:ReturnType<typeof fixture>,name:string,rows=records(name)){const file=path.join(f.options.claudeDir,'projects','p',name+'.jsonl');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,rows.map(r=>JSON.stringify(r)).join('\n')+'\n');return file;}
function pool(options:Parameters<typeof createNativeScanPool>[1]={}){const p=createNativeScanPool(entry,options);pools.push(p);return p;}
function job(file:string,ordinal=0):NativeScanJob{const s=fs.statSync(file,{bigint:true});return {jobId:'public-'+ordinal,ordinal,file,harness:'claude',bytes:Number(s.size),stamp:{dev:String(s.dev),ino:String(s.ino),size:Number(s.size),mtimeNs:String(s.mtimeNs),ctimeNs:String(s.ctimeNs)},maxBytes:Number(s.size),maxRecords:1000000,maxPromptBytes:64*1024*1024,policy:{authorityCommitment:'public-policy',ignoredProjects:[],forgottenSourceIds:[],project:null,eventFrom:null,asOf:null}};}
describe('bounded native parser pool',()=>{
 it('preserves the exact native identity export for empty, Unicode and embedded separators',()=>{for(const h of ['claude','codex','pi','opencode'])for(const id of ['','public','नमस्ते🦓','a\0b'])expect(pureSourceId(h,id)).toBe(memorySourceId(h,id));});
 it('matches sequential vectors, user text, metadata, offsets, counts and source hash through transfer frames',async()=>{const f=fixture(),a=write(f,'a',records('a','x'.repeat(2*1024*1024))),b=write(f,'b'),p=pool(),signal=new AbortController().signal;const [pooled,other]=await Promise.all([p.scan(job(a),signal),p.scan(job(b,1),signal)]),sequential=await streamNativeFacts(a,'claude',{signal,maxBytes:fs.statSync(a).size,captureBytes:0,accept:()=>true});expect(pooled).toEqual(sequential);expect(other.usage).toHaveLength(1);expect(pooled.facts.bytes.length).toBe(0);});
 it('excludes an entire source with a final escaped optout',async()=>{const f=fixture(),file=write(f,'optout',[...records('optout'),{type:'user',sessionId:'optout',uuid:'late',message:{role:'user',content:POTSHERD_CARD_MARKER}}]);fs.writeFileSync(file,fs.readFileSync(file,'utf8').replace(POTSHERD_CARD_MARKER,POTSHERD_CARD_MARKER.replace('P','\\u0050')));const result=await pool().scan(job(file),new AbortController().signal);expect(result.usage).toEqual([]);expect(result.facts.gaps).toContain('maintenance_source_excluded');});
 it('honors serialized ignore and actual forgotten identities without evaluating supplied code',async()=>{const f=fixture(),file=write(f,'forgotten'),request=job(file);request.policy.forgottenSourceIds=[pureSourceId('claude','forgotten')];await expect(pool().scan(request,new AbortController().signal)).rejects.toThrow('native_source_policy_excluded');});
 it('owns cancellation and rejects every later scan instead of merging late results',async()=>{const f=fixture(),file=write(f,'cancel',records('cancel','x'.repeat(4*1024*1024))),p=pool(),controller=new AbortController(),promise=p.scan(job(file),controller.signal);controller.abort();await expect(promise).rejects.toThrow('cancelled');await p.close();await expect(p.scan(job(file,1),new AbortController().signal)).rejects.toThrow('cancelled');});
 it('rejects changed source identity and keeps captured append prefixes unchanged',async()=>{const f=fixture(),file=write(f,'append'),request=job(file),expected=createHash('sha256').update(fs.readFileSync(file)).digest('hex');fs.appendFileSync(file,JSON.stringify(records('new')[0])+'\n');const result=await pool().scan(request,new AbortController().signal);expect(result.hash).toBe(expected);expect(result.bytes).toBe(request.bytes);expect(result.facts.gaps).toContain('native_appended_after_capture');const replacement=job(file,2);fs.unlinkSync(file);write(f,'append');await expect(pool().scan(replacement,new AbortController().signal)).rejects.toThrow('source_changed');});
 it('reports resource or frame bounds as a failure and never truncates a source result',async()=>{const f=fixture(),file=write(f,'limit');await expect(pool({maxResultBytes:128}).scan(job(file),new AbortController().signal)).rejects.toThrow('native_pool_result_bytes_limit');await expect(pool({maxRssBytes:1}).scan(job(file,1),new AbortController().signal)).rejects.toThrow('native_pool_memory_limit');});
 it('preserves final audit facts, alias inputs and warm source verification with ordered main aggregation',async()=>{const f=fixture(),prefix=records('alias');write(f,'small',prefix);write(f,'big',[...prefix,{...prefix[0],uuid:'second',promptId:'second',message:{role:'user',content:'Please add public pagination.'}},{...prefix[1],uuid:'second-a',requestId:'second-r',message:{...prefix[1]!.message,id:'second-response'}}]);const sequential=createAuditSession(f.options);const a=await sequential.run();sequential.dispose();const pooled=createAuditSession({...f.options,nativeScanExecutor:pool()});const b=await pooled.run();pooled.dispose();expect(b.launch!.facts).toEqual(a.launch!.facts);expect(b.metrics.nativeUserInputs!.value).toBe(a.metrics.nativeUserInputs!.value);expect(b.launch!.factProgress!.cacheHits).toBe(2);},15000);
 it('rechecks actual ignore authority before ordered merging and clears held pricing',async()=>{const f=fixture();write(f,'a');write(f,'b',records('b','x'.repeat(2*1024*1024)));const session=createAuditSession({...f.options,nativeScanExecutor:pool()});let changed=false;const result=await session.run(e=>{if(!changed&&e.type==='snapshot'&&e.snapshot.launch?.facts?.recordedResponses){changed=true;fs.writeFileSync(path.join(f.options.potsherdDir,'config.json'),JSON.stringify({ignore:['/public']}));}});session.dispose();expect(changed).toBe(true);expect(result.launch!.facts).toBeNull();expect(result.coverage.gapCodes).toContain('audit_snapshot_stale');});
});
