import {it,expect,afterEach} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {createAuditSession} from '../../packages/core/src/analytics/index.js';
import {createNativeScanPool} from '../../packages/core/src/analytics/native-pool.js';
import {parseClaudeTranscript} from '../../packages/core/src/parser/claude.js';
import {publishSource,sourceId} from '../../packages/core/src/memory/source.js';
import {open} from '../../packages/core/src/db.js';
import {POTSHERD_CARD_MARKER} from '../../packages/core/src/markers.js';
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(r=>fs.rmSync(r,{recursive:true,force:true})));
const time='2026-10-06T00:00:00Z';
function records(id:string,body='Public assistant prose'){return [{type:'user',sessionId:id,uuid:'u-'+id,promptId:'u-'+id,cwd:'/public',timestamp:time,message:{role:'user',content:id==='opted'?'PUBLIC OPTED USER SENTINEL':'PUBLIC RETAINED USER SENTINEL'}},{type:'assistant',sessionId:id,uuid:'a-'+id,requestId:'r-'+id,cwd:'/public',timestamp:time,message:{id:'response-'+id,role:'assistant',model:'claude-sonnet-4-6',provider:'anthropic',content:body,usage:{input_tokens:1000,output_tokens:100,cache_read_input_tokens:300,cache_creation_input_tokens:0}}}];}
async function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'optout-archive-public-'));roots.push(root);const owned=path.join(root,'owned'),claude=path.join(root,'claude'),dir=path.join(claude,'projects','p');fs.mkdirSync(dir,{recursive:true});const options={potsherdDir:owned,claudeDir:claude,codexDir:path.join(root,'codex'),piDir:path.join(root,'pi'),opencodeDir:path.join(root,'opencode'),harnesses:['claude'] as const,launch:true,launchPrepareOnly:true};const write=(name:string,rows:unknown[])=>{const file=path.join(dir,name+'.jsonl');fs.writeFileSync(file,rows.map(r=>JSON.stringify(r)).join('\n')+'\n');return file;};const db=open({root:owned});for(const id of ['opted','retained']){const file=write(id,records(id)),parsed=await parseClaudeTranscript(file),raw=fs.readFileSync(file),hash=createHash('sha256').update(raw).digest('hex'),relative=path.join('archive','evidence',hash+'.jsonl');fs.mkdirSync(path.dirname(path.join(owned,relative)),{recursive:true});fs.writeFileSync(path.join(owned,relative),raw);const pub=publishSource(db,{parsed,artifactHash:hash,artifactBytes:raw.length,archiveRelativePath:relative});expect(pub.sourceId).toBe(sourceId('claude',id));if(id==='retained')fs.unlinkSync(file);}db.close();write('middle-clean',records('opted','x'.repeat(100000)));write('optout',[...records('opted','x'.repeat(1000000)),{type:'user',sessionId:'opted',uuid:'marker',message:{role:'user',content:POTSHERD_CARD_MARKER}}]);write('last-clean',records('opted','x'.repeat(2000000)));return {options,root};}
for(const pooled of [false,true])it(`propagates verified EOF optout to older archives and earlier/later aliases while retaining unrelated history (${pooled?'pool':'sequential'})`,async()=>{const f=await fixture(),executor=pooled?createNativeScanPool(new URL('../../packages/cli/dist/audit-native-worker.js',import.meta.url)):undefined,session=createAuditSession({...f.options,nativeScanExecutor:executor});try{const result=await session.run();expect(result.launch!.facts!.records.every(r=>r.conversationId!==sourceId('claude','opted'))).toBe(true);expect(result.conversations.some(c=>c.id===sourceId('claude','opted'))).toBe(false);expect(JSON.stringify(result.launch)).not.toContain('PUBLIC OPTED USER SENTINEL');expect(result.launch!.facts!.recordedResponses).toBe(1);expect(result.conversations.some(c=>c.id===sourceId('claude','retained'))).toBe(true);expect(result.funnel!.responsesObserved!-result.funnel!.responsesExcluded!-result.funnel!.responsesDeduplicated!).toBe(result.launch!.facts!.recordedResponses);}finally{session.dispose();await executor?.close();}});
