import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {afterEach,describe,it,expect} from 'vitest';
import {createAuditSession,publicAuditSnapshot} from '../../packages/core/src/analytics/index.js';
import {nativeAuditRoots,censusNativeSources} from '../../packages/core/src/analytics/native-census.js';
import {streamNativeFacts} from '../../packages/core/src/analytics/native-stream.js';
import {extractNativeUsage} from '../../packages/core/src/analytics/native-usage.js';
import {FreeJevProvider,FREE_JEV_MODEL} from '../../packages/core/src/analytics/free-jev.js';
import {aggregateLaunchFacts,valueInference} from '../../packages/core/src/analytics/model-catalog.js';
import {auditProfanity} from '../../packages/core/src/analytics/profanity.js';
import {attributeDirectLanguage} from '../../packages/core/src/analytics/language-models.js';
import {summarizeDirectedLanguage} from '../../packages/core/src/analytics/language-feedback.js';
import {openSessions} from '../../packages/core/src/analytics/opencode.js';
import {open} from '../../packages/core/src/db.js';import {openDatabase} from '../../packages/core/src/sqlite-driver.js';
import type {AuditPrompt,AuditEvent} from '../../packages/core/src/analytics/contracts.js';import type {ContextRecord} from '../../packages/core/src/analytics/launch-contracts.js';
const roots:string[]=[];afterEach(()=>roots.splice(0).forEach(r=>fs.rmSync(r,{recursive:true,force:true})));
const time='2026-10-06T12:00:00Z',bytes=(rows:unknown[])=>Buffer.from(rows.map(r=>JSON.stringify(r)).join('\n')+'\n');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'overhaul-public-'));roots.push(root);const options={launch:true as const,launchPrepareOnly:true,potsherdDir:path.join(root,'owned'),claudeDir:path.join(root,'claude'),codexDir:path.join(root,'codex'),piDir:path.join(root,'pi'),opencodeDir:path.join(root,'opencode')};for(const dir of [path.join(options.claudeDir,'projects','public'),path.join(options.codexDir,'sessions'),path.join(options.codexDir,'archived_sessions'),path.join(options.piDir,'agent','sessions'),options.opencodeDir])fs.mkdirSync(dir,{recursive:true});return {root,options,file:path.join(options.claudeDir,'projects','public','public-session.jsonl')};}
function user(id:string,text:string,cwd='/public-a'){return {type:'user',uuid:id,sessionId:'public-session',promptId:id,timestamp:time,cwd,message:{role:'user',content:text}};}
function assistant(id:string,extra:Record<string,unknown>={}){return {type:'assistant',sessionId:'public-session',timestamp:time,cwd:'/public-a',message:{id,role:'assistant',model:'claude-opus-4-8',usage:{input_tokens:1000,output_tokens:200,cache_read_input_tokens:300,cache_creation_input_tokens:30,cache_creation:{ephemeral_5m_input_tokens:10,ephemeral_1h_input_tokens:20}},...extra}};}
function prompt(id:string,text:string):AuditPrompt{return {id,conversationId:'public',role:'user',originBasis:'unknown',identityBasis:id,eligibleHuman:false,eligibleNativeInput:true,excludedReason:null,eventAt:time,text,route:{basis:'transient_snapshot',sourceId:'public',artifactHash:'public',sourcePath:'/synthetic',recordKey:id,rawStart:0,rawEnd:1,startUtf16:0,endUtf16:text.length,snapshotId:'public'}};}
function record(id:string,role:'user'|'assistant',model:string|null=null):ContextRecord{return {id,conversationId:'public',parentId:null,harness:'claude',project:null,eventAt:time,role,text:'',model,provider:null,directUser:role==='user',route:null};}
describe('native audit overhaul factual contracts',()=>{
 it('uses exact custom/default/environment roots and inventories files before parsing',async()=>{const f=fixture();expect(nativeAuditRoots('claude',{}, {},'/synthetic')).toEqual(['/synthetic/.config/claude/projects','/synthetic/.claude/projects']);expect(nativeAuditRoots('pi',{}, {PI_CODING_AGENT_DIR:'/agent-root'},'/synthetic')).toEqual(['/agent-root/sessions']);expect(nativeAuditRoots('pi',{}, {PI_AGENT_DIR:'/sessions'},'/synthetic')).toEqual(['/sessions']);expect(nativeAuditRoots('opencode',{}, {XDG_DATA_HOME:'/data'},'/synthetic')).toEqual(['/data/opencode']);fs.writeFileSync(f.file,bytes([user('u','Fix this bug'),assistant('a')]));const events:AuditEvent[]=[];const s=createAuditSession(f.options);try{const snapshot=await s.run(e=>events.push(e));expect(events.find(e=>e.type==='progress'&&e.progress.label==='Checking local privacy')).toBeDefined();expect(snapshot.sources.every(h=>h.census?.checked)).toBe(true);expect(snapshot.funnel?.nativeFilesDiscovered).toBe(1);expect(snapshot.launch?.facts?.referenceValueUsd).toBe(0.0104125);}finally{s.dispose();}});
 it('streams full usage while capturing recent COMPLETE turns rather than an initial prefix',async()=>{const f=fixture();fs.writeFileSync(f.file,bytes([user('old','old '.repeat(1000)),assistant('old-response'),user('recent','Fix the new parser bug'),assistant('recent-response')]));const r=await streamNativeFacts(f.file,'claude',{signal:new AbortController().signal,maxBytes:1024*1024,captureBytes:1400,accept:()=>true});expect(r.usage).toHaveLength(2);expect(r.facts.bytes.toString()).toContain('Fix the new parser bug');expect(r.facts.bytes.toString()).not.toContain('old '.repeat(30));expect(r.facts.gaps).toContain('context_capture_partial');});
 it('keeps mixed-project counts separate and scoped requested focus source-backed',async()=>{const f=fixture();fs.writeFileSync(f.file,bytes([user('a','Fix the parser bug','/public-a'),assistant('x'),user('b','Write the README documentation','/public-b'),assistant('y')]));const s=createAuditSession(f.options);try{const r=await s.run();expect(r.metrics.nativeUserInputs?.value).toBe(2);expect(r.projects.map(p=>[p.path,p.nativeUserInputs]).sort()).toEqual([['/public-a',1],['/public-b',1]]);expect(r.projects.find(p=>p.path==='/public-a')?.focus?.[0]?.label).toBe('Debugging');const publicValue=JSON.stringify(publicAuditSnapshot(r));expect(publicValue).not.toContain(f.file);expect(publicAuditSnapshot(r).projects.every(p=>p.focus?.every(t=>t.evidenceRoutes.length===0&&t.promptIds.length===0))).toBe(true);}finally{s.dispose();}});
 it('keeps immutable native detail after append but revokes it on manual forget without epoch bump',async()=>{const f=fixture(),db=open({root:f.options.potsherdDir});db.close();fs.writeFileSync(f.file,bytes([user('a','A captured user line'),assistant('x')]));const s=createAuditSession(f.options);try{const r=await s.run();expect(r.conversations,JSON.stringify(r.coverage)).not.toHaveLength(0);const p=(await s.prompts(r.conversations[0]!.id)).prompts[0]!;fs.appendFileSync(f.file,bytes([user('later','A new tail')]));expect((await s.prompts(p.conversationId)).prompts[0]!.text).toBe('A captured user line');expect((await s.evidence(p.route)).text).toBe('A captured user line');const changed=open({root:f.options.potsherdDir});changed.prepare('INSERT INTO forget_tombstones(tombstone_id,source_id,note_id,scope_hash,created_at,state,receipt_json) VALUES(?,?,?,?,?,?,?)').run('public-forget',r.conversations[0]!.sourceId,null,'public',time,'complete','{}');changed.close();expect((await s.evidence(p.route)).state).toBe('stale');}finally{s.dispose();}});
 it('excludes synthetic usage, namespaces pi nodes and chooses whole duplicate records',()=>{const c=extractNativeUsage(bytes([assistant('a'),assistant('a',{usage:{input_tokens:2,output_tokens:300,cache_read_input_tokens:0,cache_creation_input_tokens:0}}),assistant('synthetic',{model:'<synthetic>'})]),'claude','public');expect(c).toHaveLength(1);expect(c[0]!.inputTokens).toBe(1000);const pi=(id:string)=>extractNativeUsage(bytes([{type:'session',id},{type:'message',id:'same-node',timestamp:time,message:{role:'assistant',model:'public-model',provider:'local',usage:{input:3,output:2,cacheRead:0,cacheWrite:0}}}]),'pi',id);expect(aggregateLaunchFacts([...pi('one'),...pi('two')]).recordedResponses).toBe(2);});
 it('prices explicit TTL buckets independently and leaves unknown positive TTL unpriced',()=>{const r=extractNativeUsage(bytes([assistant('a')]),'claude','public')[0]!;expect(valueInference(r).referenceValueUsd).toBe(0.0104125);expect(valueInference({...r,cacheWrite5mTokens:null,cacheWrite1hTokens:null}).referenceValueUsd).toBeNull();expect(valueInference({...r,model:'claude-opus-4-5'}).referenceValueUsd).toBe(0.0104125);});
 it('counts complete terms/model language beyond eight retained examples',()=>{const prompts=Array.from({length:20},(_,i)=>prompt(String(i),'shit shit fuck'));const profanity=auditProfanity(prompts);expect(profanity.matches).toHaveLength(8);expect(profanity.terms?.find(t=>t.term==='shit')?.occurrences).toBe(40);expect(profanity.terms?.every(t=>t.samples.length<=3)).toBe(true);const contexts=prompts.flatMap(p=>[record(p.id,'user'),record('a'+p.id,'assistant','public-model')]);expect(attributeDirectLanguage(profanity,contexts,prompts)[0]?.occurrences).toBe(60);});
 it('groups actual profane phrases with punctuation/case variants and excludes single-word/default/self attribution',()=>{const inputs=[prompt('a','You fucking missed it!'),prompt('b','you fucking missed it?'),prompt('c','fuck'),prompt('d','shit I forgot'),prompt('e','Good work, you understood me'),prompt('f','```\nYou fucking missed it\n```')];const records=inputs.flatMap(p=>[record('before'+p.id,'assistant','public-model'),record(p.id,'user')]);const result=summarizeDirectedLanguage(inputs,records);expect(result.languageLines.find(l=>l.text==='You fucking missed it!')?.occurrences).toBe(2);expect(result.languageLines.some(l=>l.text==='fuck')).toBe(false);const feedback=result.modelFeedback[0]!;expect(feedback.associatedInputs).toBe(6);expect(feedback.directedNegativeInputs).toBe(2);expect(feedback.praiseInputs).toBe(1);});
});

describe('OpenCode native schema and four-host reconciliation',()=>{
 it('loads all four custom roots, with independent token/cost arithmetic and repeated-period funnel stability',async()=>{const f=fixture();fs.writeFileSync(f.file,bytes([user('u','Fix the parser bug'),assistant('a')]));fs.writeFileSync(path.join(f.options.codexDir,'sessions','rollout-public.jsonl'),bytes([{type:'session_meta',timestamp:time,payload:{id:'public-codex',cwd:'/public-a',model_provider:'openai'}},{type:'turn_context',payload:{model:'gpt-5.4',cwd:'/public-a'}},{type:'event_msg',timestamp:time,payload:{type:'user_message',message:'Write the new CLI feature'}},{type:'event_msg',timestamp:time,payload:{type:'token_count',info:{last_token_usage:{input_tokens:300,output_tokens:20,cached_input_tokens:100,reasoning_output_tokens:5},total_token_usage:{input_tokens:300,output_tokens:20,cached_input_tokens:100,reasoning_output_tokens:5}}}}]));fs.writeFileSync(path.join(f.options.piDir,'agent','sessions','public.jsonl'),bytes([{type:'session',id:'public-pi',timestamp:time,cwd:'/public-a'},{type:'message',id:'u',timestamp:time,message:{role:'user',content:'Review the parser code'}},{type:'message',id:'a',timestamp:time,message:{role:'assistant',content:'Reviewed',model:'claude-sonnet-4-6',provider:'anthropic',usage:{input:10,output:5,cacheRead:2,cacheWrite:0}}}]));const db=openDatabase(path.join(f.options.opencodeDir,'opencode.db'));db.exec('CREATE TABLE session(id TEXT,directory TEXT,parent_id TEXT,title TEXT);CREATE TABLE message(id TEXT,session_id TEXT,time_created INTEGER,data TEXT);CREATE TABLE part(id TEXT,message_id TEXT,data TEXT)');db.prepare('INSERT INTO session VALUES(?,?,NULL,?)').run('public-open','/public-a','public');const insert=db.prepare('INSERT INTO message VALUES(?,?,?,?)');insert.run('u','public-open',Date.parse(time),JSON.stringify({role:'user',time:{created:Date.parse(time)}}));insert.run('a','public-open',Date.parse(time)+1,JSON.stringify({role:'assistant',modelID:'gpt-5.4',providerID:'openai',time:{created:Date.parse(time)+1},tokens:{input:3,output:7,reasoning:2,cache:{read:4,write:0}},cost:0}));db.prepare('INSERT INTO part VALUES(?,?,?)').run('p','u',JSON.stringify({type:'text',text:'Research model pricing'}));db.close();const s=createAuditSession(f.options);try{const r=await s.run(),facts=r.launch!.facts!;expect(r.sources.map(h=>h.census?.files)).toEqual([1,1,1,1]);expect(facts.recordedResponses).toBe(4);expect(facts.models.reduce((n,m)=>n+(m.totalTokens??0),0)).toBe(1883);expect(facts.valueUsd).toBeCloseTo(0.000825+0.0001056+0.0001435,12);expect(facts.referenceValueUsd).toBe(0.0104125);expect(r.metrics.nativeUserInputs?.value).toBe(4);const first=r.funnel!.responsesDeduplicated;const again=await s.analyzePeriod!(7);expect(again.funnel!.responsesDeduplicated).toBe(first);}finally{s.dispose();}});
 it('supports current v2 messages and explicit older fork boundaries without double-counting copied inference',async()=>{const f=fixture(),db=openDatabase(path.join(f.options.opencodeDir,'opencode.db'));db.exec('CREATE TABLE session_v2(id TEXT,directory TEXT,title TEXT,fork_session_id TEXT,fork_boundary TEXT);CREATE TABLE session_message(id TEXT,session_id TEXT,type TEXT,seq INTEGER,time_created INTEGER,data TEXT)');db.prepare('INSERT INTO session_v2 VALUES(?,?,?,NULL,NULL)').run('parent','/public-a','parent');db.prepare('INSERT INTO session_v2 VALUES(?,?,?,?,?)').run('fork','/public-a','fork','parent',JSON.stringify({type:'through',messageID:'pa'}));const insert=db.prepare('INSERT INTO session_message VALUES(?,?,?,?,?,?)'),u={text:'Fix the new feature',time:{created:Date.parse(time)}},a={model:{id:'gpt-5.4',providerID:'openai'},content:[{type:'text',text:'Done'}],time:{created:Date.parse(time)},tokens:{input:10,output:5,reasoning:0,cache:{read:0,write:0}}};for(const [id,session,type,seq,data]of [['pu','parent','user',1,u],['pa','parent','assistant',2,a],['copyu','fork','user',1,u],['copya','fork','assistant',2,a],['fu','fork','user',3,u],['fa','fork','assistant',4,a]] as const)insert.run(id,session,type,seq,Date.parse(time),JSON.stringify(data));db.close();const s=createAuditSession(f.options);try{const r=await s.run();expect(r.launch?.facts?.recordedResponses).toBe(2);expect(r.metrics.nativeUserInputs?.value).toBe(2);expect(r.conversations).toHaveLength(2);}finally{s.dispose();}});
 it('holds malformed fork sequence boundaries instead of widening inherited selection',()=>{const f=fixture(),file=path.join(f.options.opencodeDir,'opencode.db'),db=openDatabase(file);db.exec('CREATE TABLE session_v2(id TEXT,directory TEXT,title TEXT,fork_session_id TEXT,fork_boundary TEXT);CREATE TABLE session_message(id TEXT,session_id TEXT,type TEXT,seq INTEGER,time_created INTEGER,data TEXT)');db.prepare('INSERT INTO session_v2 VALUES(?,?,?,?,?)').run('fork','/public-a','fork','parent',JSON.stringify({type:'through',messageID:'boundary'}));const insert=db.prepare('INSERT INTO session_message VALUES(?,?,?,?,?,?)');insert.run('boundary','parent','assistant','0 OR 1=1',Date.parse(time),'{}');db.close();expect(openSessions(file,10,1024*1024)).toEqual({gap:'opencode_fork_boundary_invalid'});});
 it('groups legacy session/message/part JSON files and never treats parts as conversations',async()=>{const f=fixture(),storage=path.join(f.options.opencodeDir,'storage');for(const dir of ['session/project','message/public-open','part/public-user'])fs.mkdirSync(path.join(storage,dir),{recursive:true});fs.writeFileSync(path.join(storage,'session/project/public-open.json'),JSON.stringify({id:'public-open',directory:'/public-a'}));fs.writeFileSync(path.join(storage,'message/public-open/public-user.json'),JSON.stringify({id:'public-user',sessionID:'public-open',role:'user',time:{created:Date.parse(time)}}));fs.writeFileSync(path.join(storage,'part/public-user/public-part.json'),JSON.stringify({id:'public-part',messageID:'public-user',type:'text',text:'Fix the parser bug'}));fs.writeFileSync(path.join(storage,'message/public-open/public-assistant.json'),JSON.stringify({id:'public-assistant',sessionID:'public-open',role:'assistant',modelID:'gpt-5.4',providerID:'openai',time:{created:Date.parse(time)+1},tokens:{input:10,output:5,reasoning:0,cache:{read:0,write:0}}}));const s=createAuditSession(f.options);try{const r=await s.run();expect(r.sources.find(h=>h.harness==='opencode')?.census).toMatchObject({files:4,unit:'file'});expect(r.conversations).toHaveLength(1);expect(r.launch?.facts?.recordedResponses).toBe(1);expect(r.metrics.nativeUserInputs?.value).toBe(1);}finally{s.dispose();}});
});

it('preserves child inference but excludes orchestration followups from personal language',async()=>{const f=fixture(),child=path.join(f.options.claudeDir,'projects','public','public-session','subagents','agent-public.jsonl');fs.mkdirSync(path.dirname(child),{recursive:true});fs.writeFileSync(f.file,bytes([user('main','Fix the parser bug'),assistant('main-response'),user('feedback','You fucking missed it!')]));fs.writeFileSync(child,bytes([{...user('task','Fix the worker'),isSidechain:true},assistant('child-response'),{...user('child-followup','You fucking missed it!'),isSidechain:true}]));const s=createAuditSession(f.options);try{const r=await s.run();expect(r.launch?.facts?.recordedResponses).toBe(2);expect(r.profanity?.terms?.find(t=>t.term==='fucking')?.occurrences).toBe(1);expect(r.launch?.languageLines?.[0]?.occurrences).toBe(1);expect(r.launch?.modelFeedback?.[0]?.directedNegativeInputs).toBe(1);}finally{s.dispose();}});
it('keeps whole evolving usage after an identity model conflict rather than freezing its first vector',()=>{const rows=[assistant('same',{model:'claude-fable-5',usage:{input_tokens:100,output_tokens:1,cache_read_input_tokens:0,cache_creation_input_tokens:20,cache_creation:{ephemeral_5m_input_tokens:20,ephemeral_1h_input_tokens:0}}}),assistant('same',{model:'claude-opus-4-8',usage:{input_tokens:101,output_tokens:200,cache_read_input_tokens:0,cache_creation_input_tokens:19,cache_creation:{ephemeral_5m_input_tokens:20,ephemeral_1h_input_tokens:0}}})];const r=extractNativeUsage(bytes(rows),'claude','public')[0]!;expect(r.model).toBeNull();expect(r.inputTokens).toBe(101);expect(r.outputTokens).toBe(200);expect(r.cacheWriteTokens).toBe(19);expect(r.gaps).toContain('response_identity_model_conflict');expect(valueInference(r).referenceValueUsd).toBeNull();});
it('retains SDK observed role separately from strict human attestation and rejects workflow model rankings',async()=>{const f=fixture(),file=path.join(f.options.codexDir,'sessions','rollout-sdk.jsonl');fs.writeFileSync(file,bytes([{type:'session_meta',timestamp:time,payload:{id:'public-sdk',cwd:'/public',originator:'codex_exec',source:'exec'}},{type:'turn_context',payload:{model:'codex-auto-review'}},{type:'event_msg',timestamp:time,payload:{type:'user_message',message:'Review the parser code'}},{type:'event_msg',timestamp:time,payload:{type:'token_count',info:{last_token_usage:{input_tokens:10,output_tokens:2,cached_input_tokens:0},total_token_usage:{input_tokens:10,output_tokens:2,cached_input_tokens:0}}}}]));const r=await streamNativeFacts(file,'codex',{signal:new AbortController().signal,maxBytes:10000,captureBytes:2000,accept:()=>true});expect(r.facts.events[0]).toMatchObject({eligible:false,observed:true,origin:'unknown'});expect(r.usage[0]!.model).toBeNull();expect(aggregateLaunchFacts(r.usage).favourite).toBeNull();});

it('bounds a never-acknowledged transfer notice by the attempt timeout without fetching',async()=>{let calls=0;const provider=new FreeJevProvider({route:{kind:'zen-public'},timeoutMs:5,beforeDispatch:()=>new Promise<void>(()=>{}),fetch:(async()=>{calls++;throw new Error('must not fetch');}) as typeof fetch});const run=provider.beginRun({isCurrent:()=>true,retries:0});try{const result=await run.evaluate({model:FREE_JEV_MODEL,state:'Public synthetic state',questions:{check:{type:'noul',instructions:'Classify this public synthetic state.',criteria:{true:'True',false:'False'}}}},{sourceVersion:'public',privacyVersion:'public',segmentationVersion:'public',questionVersion:'public',contentHash:'public',scopeHash:'public'});expect(result).toEqual({state:'failed',code:'attempt_timeout'});expect(calls).toBe(0);}finally{run.dispose();}});
