import {describe,it,expect,afterEach,vi} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import {createAuditSession,publicAuditSnapshot} from '../../packages/core/src/analytics/index.js';
import {open} from '../../packages/core/src/db.js';
import {openDatabase} from '../../packages/core/src/sqlite-driver.js';
import {parseClaudeTranscript} from '../../packages/core/src/parser/claude.js';
import {publishSource,sourceId} from '../../packages/core/src/memory/source.js';
import {digest} from '../../packages/core/src/analytics/source.js';
import {POTSHERD_CARD_MARKER} from '../../packages/core/src/markers.js';
import type {AuditOverviewOptions,AuditEvent,AuditSession} from '../../packages/core/src/analytics/contracts.js';

const roots:string[]=[];const sessions:AuditSession[]=[];
afterEach(()=>{sessions.splice(0).forEach(s=>s.dispose());roots.splice(0).forEach(r=>fs.rmSync(r,{recursive:true,force:true}));vi.restoreAllMocks();});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'audit-local-'));roots.push(root);const options:AuditOverviewOptions={potsherdDir:path.join(root,'owned'),claudeDir:path.join(root,'claude'),codexDir:path.join(root,'codex'),piDir:path.join(root,'pi'),opencodeDir:path.join(root,'opencode')};return {root,options};}
function write(file:string,records:unknown[]){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,records.map(r=>JSON.stringify(r)).join('\n')+'\n');return file;}
function claude(f:ReturnType<typeof fixture>,records:unknown[],name='c',child=false){return write(path.join(f.options.claudeDir!,'projects','p',...(child?['subagents']:[]),name+'.jsonl'),records);}
function user(id:string,text:string,extra:Record<string,unknown>={}){return {type:'user',sessionId:'c',uuid:'u-'+id,promptId:id,cwd:'/private/customer/project',timestamp:'2026-10-01T23:30:00Z',message:{role:'user',content:text},...extra};}
function session(options:AuditOverviewOptions){const s=createAuditSession(options);sessions.push(s);return s;}
function inventory(root:string):Record<string,string>{const result:Record<string,string>={};if(!fs.existsSync(root))return result;for(const item of fs.readdirSync(root,{withFileTypes:true})){const file=path.join(root,item.name);if(item.isDirectory()){for(const [key,value] of Object.entries(inventory(file)))result[path.join(item.name,key)]=value;}else if(item.isFile())result[item.name]=digest(fs.readFileSync(file));}return result;}

describe('bounded local audit session',()=>{
 it('is synchronous initially, scans fresh noDB roots without writes or network, and emits immutable bound progress',async()=>{
  const f=fixture();claude(f,[user('one','build a small tool'),user('two','run its checks')]);const before=inventory(f.root);const network=vi.spyOn(globalThis,'fetch').mockRejectedValue(new Error('network forbidden'));
  const s=session({...f.options,harnesses:['claude'],timezone:'Asia/Kolkata'});expect(s.snapshot().status).toBe('discovering');expect(Object.isFrozen(s.snapshot())).toBe(true);
  const events:AuditEvent[]=[];const result=await s.run(e=>events.push(e));expect(result.metrics.conversations.value).toBe(1);expect(result.metrics.humanPrompts.value).toBe(2);expect(result.usage.inputTokens).toBeNull();expect(result.semantics.state).toBe('not_run');expect(network).not.toHaveBeenCalled();expect(inventory(f.root)).toEqual(before);expect(fs.existsSync(f.options.potsherdDir!)).toBe(false);
  expect(result.activity).toEqual([{date:'2026-10-02',count:2}]);const sequences=events.filter(e=>e.type==='snapshot').map(e=>e.snapshot.sequence);expect(sequences).toEqual([...sequences].sort((a,b)=>a-b));expect(new Set(events.filter(e=>e.type==='progress').map(e=>e.snapshotId)).size).toBe(1);
  const page=await s.prompts(result.conversations[0]!.id,0,1);expect(page.total).toBe(2);expect(page.nextOffset).toBe(1);expect(page.snapshotId).toBe(result.snapshotId);expect((await s.evidence(page.prompts[0]!.route)).text).toBe('build a small tool');
 });
 it('preserves independent repeat prompts and excludes tool/image/injected and child initialization',async()=>{
  const f=fixture();claude(f,[user('a','continue'),user('b','continue'),{...user('a',''),message:{role:'user',content:[{type:'tool_result',tool_use_id:'t',content:'output'}]}},{...user('a',''),message:{role:'user',content:[{type:'image',source:{data:'x'}}]}},user('inject','context',{promptId:undefined})]);claude(f,[user('child','agent task')],'agent',true);
  const s=session({...f.options,harnesses:['claude']});const snap=await s.run();expect(snap.metrics.humanPrompts.value).toBe(2);expect(snap.metrics.conversations.value).toBe(1);expect(snap.metrics.linkedChildren.value).toBe(1);expect(snap.coverage.unknownOriginEvents).toBe(1);
 });
 it('counts modern Codex markers after responses and marker multiplicity despite same-text injection',async()=>{
  const f=fixture();const records:unknown[]=[{type:'session_meta',payload:{id:'code',cwd:'/p'}}];
  for(let i=1;i<=2;i++)records.push({type:'event_msg',payload:{type:'task_started',turn_id:'t'+i}},{type:'response_item',payload:{type:'message',role:'user',content:[{type:'input_text',text:'continue'}]}},{type:'event_msg',timestamp:'2026-10-02T00:00:00Z',payload:{type:'item_completed',turn_id:'t'+i,item:{type:'UserMessage',id:'m'+i,content:[{type:'text',text:'continue'}]}}});
  records.push({type:'response_item',payload:{type:'message',role:'user',content:[{type:'input_text',text:'continue'}]}});write(path.join(f.options.codexDir!,'sessions','a.jsonl'),records);
  const snap=await session({...f.options,harnesses:['codex']}).run();expect(snap.metrics.humanPrompts.value).toBe(2);expect(snap.metrics.conversations.value).toBe(1);expect(snap.coverage.gapCodes).toContain('codex_response_pair_ambiguous');
 });
 it('keeps Codex user text without markers unknown and never falls back to role counts',async()=>{
  const f=fixture();write(path.join(f.options.codexDir!,'sessions','a.jsonl'),[{type:'session_meta',payload:{id:'code'}},{type:'response_item',payload:{type:'message',role:'user',content:[{type:'input_text',text:'unknown origin'}]}}]);const snap=await session({...f.options,harnesses:['codex']}).run();expect(snap.metrics.humanPrompts.value).toBeNull();expect(snap.coverage.unknownOriginEvents).toBe(1);expect(snap.coverage.gapCodes).toContain('codex_human_marker_missing');
 });
 it('declares unknown user-bearing envelopes partial instead of reporting verified zero prompts',async()=>{
  const f=fixture();claude(f,[user('a','unsupported envelope',{type:'future_user_container'})]);const snap=await session({...f.options,harnesses:['claude']}).run();expect(snap.status).toBe('partial');expect(snap.coverage.gapCodes).toContain('unsupported_user_container');expect(snap.coverage.unknownOriginEvents).toBe(1);expect(snap.metrics.humanPrompts.value).toBeNull();
 });
 it('folds proven same-native copied prefixes without deleting distinct repeated continue events',async()=>{
  const f=fixture();claude(f,[user('a','continue')],'copy-short');claude(f,[user('a','continue'),user('b','continue')],'copy-long');const snap=await session({...f.options,harnesses:['claude']}).run();expect(snap.metrics.conversations.value).toBe(1);expect(snap.metrics.humanPrompts.value).toBe(2);
 });
 it('excludes exact known maintenance markers and leaves SDK/exec input attestation unknown',async()=>{
  const f=fixture();claude(f,[user('maintenance',POTSHERD_CARD_MARKER+'\nwrite a card'),user('sdk','programmatic prompt',{entrypoint:'sdk-ts'})]);write(path.join(f.options.codexDir!,'sessions','exec.jsonl'),[{type:'session_meta',payload:{id:'exec',originator:'codex_exec',source:'exec'}},{type:'event_msg',payload:{type:'user_message',message:'programmatic native marker'}}]);const s=session({...f.options,harnesses:['claude','codex']}),snap=await s.run();expect(snap.metrics.humanPrompts.value).toBeNull();expect(snap.coverage.excludedEvents).toBe(1);expect(snap.coverage.unknownOriginEvents).toBe(2);expect(snap.coverage.gapCodes).toContain('human_attestation_unavailable');const page=await s.prompts(snap.conversations.find(c=>c.harness==='claude')!.id);expect(page.prompts.find(p=>p.text.includes(POTSHERD_CARD_MARKER))!.excludedReason).toBe('maintenance_exclusion_marker');
 });
 it('recognizes inherited Claude native UUID+declared-origin commitments while preserving new repeated continue events',async()=>{
  const f=fixture(),original=user('a','continue',{sessionId:'parent'}),copy={...original,sessionId:'fork',session_id:'parent'} as Record<string,unknown>;delete copy.promptId;claude(f,[original],'parent');claude(f,[copy,user('b','continue',{sessionId:'fork'})],'fork');const s=session({...f.options,harnesses:['claude']}),snap=await s.run();expect(snap.metrics.conversations.value).toBe(2);expect(snap.metrics.humanPrompts.value).toBe(2);expect(snap.coverage.unknownOriginEvents).toBe(0);const child=await s.prompts(sourceId('claude','fork'));expect(child.prompts[0]!.excludedReason).toBe('inherited_native_event');expect(child.prompts[1]!.eligibleHuman).toBe(true);expect(snap.conversations.find(c=>c.nativeSessionId==='fork')!.promptCount).toBe(1);
 });
 it('withholds inherited claims without origin evidence and conflicting cross-source native identities',async()=>{
  const f=fixture();claude(f,[user('a','continue',{sessionId:'fork',session_id:'missing'})],'fork');const missing=await session({...f.options,harnesses:['claude']}).run();expect(missing.metrics.humanPrompts.value).toBeNull();expect(missing.coverage.gapCodes).toContain('inherited_origin_source_unavailable');
  fs.rmSync(path.join(f.options.claudeDir!,'projects'),{recursive:true});claude(f,[user('a','continue',{sessionId:'one'})],'one');claude(f,[user('a','continue',{sessionId:'two'})],'two');const collision=await session({...f.options,harnesses:['claude']}).run();expect(collision.metrics.humanPrompts.value).toBeNull();expect(collision.coverage.gapCodes).toContain('cross_source_event_identity_collision');expect(collision.coverage.unknownOriginEvents).toBe(2);
 });
 it('returns stale on changed exact source and unavailable after deletion',async()=>{
  const f=fixture(),file=claude(f,[user('a','original')]);const s=session({...f.options,harnesses:['claude']});const snap=await s.run(),route=(await s.prompts(snap.conversations[0]!.id)).prompts[0]!.route;fs.appendFileSync(file,'{}\n');expect((await s.evidence(route)).state).toBe('stale');fs.unlinkSync(file);expect((await s.evidence(route)).state).toBe('unavailable');
 });
 it('redacts exact snippets and strips private scope paths/titles from the public aggregate serializer',async()=>{
  const f=fixture();claude(f,[user('a','token --socket-auth Ab7qLm93Xz2pRs8Vn4Ty')]);const s=session({...f.options,harnesses:['claude'],project:'/private/customer/project'}),snap=await s.run();const prompt=(await s.prompts(snap.conversations[0]!.id)).prompts[0]!;expect(prompt.text).not.toContain('Ab7qLm93Xz2pRs8Vn4Ty');const publicText=JSON.stringify(publicAuditSnapshot(snap));expect(publicText).not.toContain('/private/customer');expect(publicText).not.toContain('Ab7qLm93Xz2pRs8Vn4Ty');expect(publicText).toContain('Project A');
 });
 it('honors ignores and holds raw on malformed or unsupported stored policy',async()=>{
  const f=fixture();claude(f,[user('a','hidden')]);fs.mkdirSync(f.options.potsherdDir!,{recursive:true});fs.writeFileSync(path.join(f.options.potsherdDir!,'config.json'),JSON.stringify({ignore:['/private/customer/project']}));expect((await session({...f.options,harnesses:['claude']}).run()).metrics.conversations.value).toBe(0);
  fs.writeFileSync(path.join(f.options.potsherdDir!,'config.json'),'invalid');const malformed=await session({...f.options,harnesses:['claude']}).run();expect(malformed.coverage.gapCodes).toContain('raw_lane_policy_hold');expect(malformed.metrics.conversations.value).toBeNull();
  fs.unlinkSync(path.join(f.options.potsherdDir!,'config.json'));const db=openDatabase(path.join(f.options.potsherdDir!,'potsherd.db'),{readonly:false});db.exec('CREATE TABLE old(x)');db.close();const old=await session({...f.options,harnesses:['claude']}).run();expect(old.coverage.gapCodes).toContain('store_policy_unavailable');expect(old.metrics.conversations.value).toBeNull();
 });
 it('blocks cached prompt pages and exact evidence after the ignore policy changes',async()=>{
  const f=fixture();claude(f,[user('a','cached private prompt')]);const s=session({...f.options,harnesses:['claude']}),snap=await s.run(),id=snap.conversations[0]!.id,route=(await s.prompts(id)).prompts[0]!.route;
  fs.mkdirSync(f.options.potsherdDir!,{recursive:true});fs.writeFileSync(path.join(f.options.potsherdDir!,'config.json'),JSON.stringify({ignore:['/private/customer/project']}));await expect(s.prompts(id)).rejects.toThrow('audit_snapshot_stale');expect((await s.evidence(route)).state).toBe('stale');
 });
 it('suppresses tombstoned native files without writes and keeps retained canonical origin/evidence after native loss',async()=>{
  const f=fixture(),file=claude(f,[user('a','retained')]);const db=open({root:f.options.potsherdDir!});const parsed=await parseClaudeTranscript(file),raw=fs.readFileSync(file),hash=digest(raw);const relative=path.join('archive','evidence',hash+'.jsonl');fs.mkdirSync(path.dirname(path.join(f.options.potsherdDir!,relative)),{recursive:true});fs.writeFileSync(path.join(f.options.potsherdDir!,relative),raw);const publication=publishSource(db,{parsed,artifactHash:hash,artifactBytes:raw.length,archiveRelativePath:relative});db.close();fs.unlinkSync(file);
  const before=inventory(f.root),s=session({...f.options,harnesses:['claude']});const snap=await s.run();expect(snap.metrics.humanPrompts.value).toBe(1);const route=(await s.prompts(snap.conversations[0]!.id)).prompts[0]!.route;expect(route.basis).toBe('canonical');expect((await s.evidence(route)).text).toBe('retained');expect(inventory(f.root)).toEqual(before);
  const writer=open({root:f.options.potsherdDir!});writer.prepare("INSERT INTO forget_tombstones VALUES('t',?,NULL,'s','2026-10-02','complete','{}')").run(publication.sourceId);writer.close();await expect(s.prompts(snap.conversations[0]!.id)).rejects.toThrow('audit_snapshot_stale');expect((await s.evidence(route)).state).toBe('stale');expect(s.snapshot().conversations).toEqual([]);write(file,[user('a','retained')]);const forgotten=await session({...f.options,harnesses:['claude']}).run();expect(forgotten.metrics.conversations.value).toBe(0);
 });
 it('reports pi projections honestly and gives unsupported OpenCode stores a concrete first failure',async()=>{
  const f=fixture();write(path.join(f.options.piDir!,'agent','sessions','p.jsonl'),[{type:'session',id:'pi',cwd:'/p'},{type:'message',id:'u',parentId:null,timestamp:'2026-10-01',message:{role:'user',content:'projection user'}},{type:'custom_message',id:'x',message:{role:'user',content:'injected'}}]);const database=path.join(f.options.opencodeDir!,'store.db');fs.mkdirSync(path.dirname(database),{recursive:true});const db=openDatabase(database,{readonly:false});db.exec('CREATE TABLE metadata(x)');db.close();const snap=await session({...f.options,harnesses:['pi','opencode']}).run();expect(snap.metrics.humanPrompts.value).toBeNull();expect(snap.sources.find(s=>s.harness==='pi')!.humanOrigin).toBe('projection');expect(snap.sources.find(s=>s.harness==='opencode')!.firstUnsupportedStep).toBe('opencode_store_unsupported');
 });
 it('reads bounded OpenCode message+part projections without claiming native human origin',async()=>{
  const f=fixture(),file=path.join(f.options.opencodeDir!,'store.db');fs.mkdirSync(path.dirname(file),{recursive:true});const db=openDatabase(file,{readonly:false});db.exec('CREATE TABLE session(id TEXT,directory TEXT); CREATE TABLE message(id TEXT,session_id TEXT,data TEXT); CREATE TABLE part(id TEXT,message_id TEXT,data TEXT)');db.prepare('INSERT INTO session VALUES(?,?)').run('o','/p');db.prepare('INSERT INTO message VALUES(?,?,?)').run('m','o',JSON.stringify({role:'user',time:{created:Date.parse('2026-10-01')}}));db.prepare('INSERT INTO part VALUES(?,?,?)').run('p','m',JSON.stringify({type:'text',text:'native-shaped projection'}));db.close();const before=inventory(f.root),s=session({...f.options,harnesses:['opencode']});const snap=await s.run();expect(snap.metrics.conversations.value).toBe(1);expect(snap.metrics.humanPrompts.value).toBeNull();const prompt=(await s.prompts(snap.conversations[0]!.id)).prompts[0]!;expect(prompt.originBasis).toBe('opencode_user_projection');expect(prompt.route.basis).toBe('projection_snapshot');expect((await s.evidence(prompt.route)).text).toBe('native-shaped projection');expect(inventory(f.root)).toEqual(before);
 });
 it('applies hard bounds and cancellation, validates pagination and original time scope',async()=>{
  const f=fixture();claude(f,[user('a','unknown clock',{timestamp:undefined}),user('b','known')]);const s=session({...f.options,harnesses:['claude'],maxRecordsPerSource:1});const snap=await s.run();expect(snap.coverage.gapCodes).toContain('source_records_limit');expect(snap.coverage.gapCodes).toContain('event_time_unknown');await expect(s.prompts(snap.conversations[0]!.id,-1)).rejects.toThrow('pagination');await expect(s.prompts(snap.conversations[0]!.id,0,101)).rejects.toThrow('pagination');
  const scoped=await session({...f.options,harnesses:['claude'],since:'2026-10-01T00:00:00Z'}).run();expect(scoped.metrics.humanPrompts.value).toBe(1);expect(scoped.coverage.gapCodes).toContain('event_time_unknown');
  const cancelled=session({...f.options,harnesses:['claude']});const result=await cancelled.run(e=>{if(e.type==='progress')cancelled.cancel();});expect(result.status).toBe('cancelled');expect(result.metrics.conversations.value).toBe(0);expect(()=>createAuditSession({...f.options,timezone:'invalid/timezone'})).toThrow();
  const oversize=await session({...f.options,harnesses:['claude'],maxSourceBytes:8}).run();expect(oversize.coverage.gapCodes).toContain('source_bytes_limit');expect(oversize.coverage.omittedSources).toBe(1);
 });
 it('counts OpenCode logical sources in progress and caps combined part bytes before retention',async()=>{
  const f=fixture(),file=path.join(f.options.opencodeDir!,'store.db');fs.mkdirSync(path.dirname(file),{recursive:true});const db=openDatabase(file,{readonly:false});db.exec('CREATE TABLE session(id TEXT,directory TEXT); CREATE TABLE message(id TEXT,session_id TEXT,data TEXT); CREATE TABLE part(id TEXT,message_id TEXT,data TEXT)');
  for(const id of ['one','two']){db.prepare('INSERT INTO session VALUES(?,?)').run(id,'/p');db.prepare('INSERT INTO message VALUES(?,?,?)').run('m-'+id,id,JSON.stringify({role:'user'}));db.prepare('INSERT INTO part VALUES(?,?,?)').run('p-'+id,'m-'+id,JSON.stringify({type:'text',text:'first '+id}));db.prepare('INSERT INTO part VALUES(?,?,?)').run('q-'+id,'m-'+id,JSON.stringify({type:'text',text:'x'.repeat(800)}));}db.close();
  const s=session({...f.options,harnesses:['opencode'],maxTotalBytes:512});const snap=await s.run();expect(snap.metrics.conversations.value).toBe(2);expect(snap.progress.completed).toBe(2);expect(snap.progress.total).toBe(2);expect(snap.sources[0]!.candidateFiles).toBe(1);expect(snap.coverage.gapCodes).toContain('source_bytes_limit');
  const prompt=(await s.prompts(snap.conversations[0]!.id)).prompts[0]!;expect(prompt.text).toBe('first one');expect((await s.evidence(prompt.route)).state).toBe('available');
 });
 it('holds raw and canonical selection when owned privacy policy has a live WAL',async()=>{
  const f=fixture();claude(f,[user('a','private')]);const db=open({root:f.options.potsherdDir!});
  try{expect(fs.statSync(path.join(f.options.potsherdDir!,'potsherd.db-wal')).size).toBeGreaterThan(0);const before=inventory(f.root),snap=await session({...f.options,harnesses:['claude']}).run();expect(snap.metrics.conversations.value).toBeNull();expect(snap.coverage.gapCodes).toContain('audit_sqlite_live_journal_unavailable');expect(snap.coverage.gapCodes).toContain('raw_lane_policy_hold');expect(inventory(f.root)).toEqual(before);}finally{db.close();}
 });
 it('preserves canonical child identity when retained artifact names contain no subagent path',async()=>{
  const f=fixture();claude(f,[user('parent','human request')]);const file=claude(f,[user('init','agent initialization')],'agent',true),parsed=await parseClaudeTranscript(file,{isSidechain:true,parentSessionId:'c'}),raw=fs.readFileSync(file),hash=digest(raw),relative=path.join('archive','evidence',hash+'.jsonl');fs.mkdirSync(path.dirname(path.join(f.options.potsherdDir!,relative)),{recursive:true});fs.writeFileSync(path.join(f.options.potsherdDir!,relative),raw);const db=open({root:f.options.potsherdDir!});publishSource(db,{parsed,artifactHash:hash,artifactBytes:raw.length,archiveRelativePath:relative});db.close();fs.unlinkSync(file);
  const snap=await session({...f.options,harnesses:['claude']}).run();expect(snap.metrics.conversations.value).toBe(1);expect(snap.metrics.linkedChildren.value).toBe(1);expect(snap.metrics.humanPrompts.value).toBe(1);expect(snap.conversations.find(c=>c.child)!.nativeSessionId).toBe('c:agent');
 });
 it('reports active OpenCode WAL data unavailable without reopening the native source',async()=>{
  const f=fixture(),file=path.join(f.options.opencodeDir!,'store.db');fs.mkdirSync(path.dirname(file),{recursive:true});const db=openDatabase(file,{readonly:false});db.pragma('journal_mode=WAL');db.exec('CREATE TABLE session(id TEXT); CREATE TABLE message(id TEXT,session_id TEXT,role TEXT,content TEXT)');db.prepare('INSERT INTO session VALUES(?)').run('o');db.prepare('INSERT INTO message VALUES(?,?,?,?)').run('m','o','user','uncheckpointed');
  try{expect(fs.statSync(file+'-wal').size).toBeGreaterThan(0);const before=inventory(f.root),snap=await session({...f.options,harnesses:['opencode']}).run();expect(snap.metrics.humanPrompts.value).toBeNull();expect(snap.sources[0]!.firstUnsupportedStep).toBe('audit_sqlite_live_journal_unavailable');expect(inventory(f.root)).toEqual(before);}finally{db.close();}
 });
 it('emits at most two final findings from eligible inputs and exact whole redacted wording',async()=>{
  const f=fixture();claude(f,[user('sdk1','continue',{entrypoint:'sdk-ts',timestamp:'2020-01-01'}),user('sdk2','continue',{timestamp:'2030-01-01'}),user('a','continue',{entrypoint:'cli',timestamp:'2026-10-01T09:00:00Z'}),user('b','continue',{timestamp:'2026-10-01T11:30:00Z'}),user('c','Continue',{timestamp:'2026-10-01T10:00:00Z'}),user('d','continue ',{timestamp:undefined})]);const events:AuditEvent[]=[],s=session({...f.options,harnesses:['claude'],timezone:'Asia/Kolkata'}),snap=await s.run(e=>events.push(e));
  for(const event of events)if(event.type==='snapshot'&&['discovering','parsing','normalizing'].includes(event.snapshot.status)){expect(event.snapshot.insights).toEqual([]);expect(event.snapshot.phrases).toEqual([]);}
  expect(snap.insights).toHaveLength(2);const elapsed=snap.insights.find(i=>i.id==='observed-conversation-input-span-v1')!,repeat=snap.insights.find(i=>i.id==='exact-repeated-input-wording-v1')!;expect(elapsed.value.value).toBe(9_000_000);expect(elapsed.value.state).toBe('partial');expect(elapsed.definition).toContain('not working time');expect(elapsed.promptIds).toHaveLength(2);expect(repeat.value.numerator).toBe(2);expect(repeat.value.denominator).toBe(4);
  expect(snap.phrases).toHaveLength(1);const phrase=snap.phrases![0]!;expect(phrase.text).toBe('continue');expect(phrase.prompts).toBe(2);expect(phrase.occurrences).toBe(2);expect(phrase.denominator).toBe(4);expect(phrase.measurementBasis).toBe('exact_redacted_whole_prompt_equality_v1');for(const route of phrase.evidenceRoutes!)expect((await s.evidence(route)).text).toBe('continue');
 });
 it('keeps inherited copies out of repeat findings and publishes aggregate captions without private wording',async()=>{
  const f=fixture(),original=user('a','Customer confidential wording',{sessionId:'parent',timestamp:'2026-10-01T00:00:00Z'}),copy={...original,sessionId:'fork',session_id:'parent'} as Record<string,unknown>;delete copy.promptId;claude(f,[original],'parent');claude(f,[copy,user('b','Customer confidential wording',{sessionId:'fork',timestamp:'2026-10-02T00:00:00Z'})],'fork');const s=session({...f.options,harnesses:['claude']}),snap=await s.run();expect(snap.phrases![0]!.prompts).toBe(2);expect(snap.phrases![0]!.denominator).toBe(2);expect(snap.insights).toHaveLength(1);expect(JSON.stringify(publicAuditSnapshot(snap))).not.toContain('Customer confidential wording');expect(JSON.stringify(publicAuditSnapshot(snap))).not.toContain('sourcePath');
  fs.mkdirSync(f.options.potsherdDir!,{recursive:true});fs.writeFileSync(path.join(f.options.potsherdDir!,'config.json'),JSON.stringify({ignore:['/private/customer/project']}));await expect(s.prompts(snap.conversations[0]!.id)).rejects.toThrow('audit_snapshot_stale');expect(s.snapshot().insights).toEqual([]);expect(s.snapshot().phrases).toEqual([]);
 });
 it('caps literal repeat rows and support routes while retaining measured aggregate occurrence counts',async()=>{
  const f=fixture(),records:unknown[]=[];for(let n=0;n<11;n++)records.push(user('repeat-'+n,'most repeated exact wording'));for(let n=0;n<23;n++){records.push(user('left-'+n,'literal group '+n));records.push(user('right-'+n,'literal group '+n));}claude(f,records);const snap=await session({...f.options,harnesses:['claude']}).run();expect(snap.phrases).toHaveLength(20);const first=snap.phrases![0]!;expect(first.prompts).toBe(11);expect(first.promptIds).toHaveLength(8);expect(first.evidenceRoutes).toHaveLength(8);expect(snap.insights.find(i=>i.id==='exact-repeated-input-wording-v1')!.value.numerator).toBe(57);expect(snap.insights.every(i=>i.promptIds.length<=8&&i.conversationIds.length<=8)).toBe(true);
 });
 it('does not manufacture elapsed spans from a single known clock or findings from programmatic inputs',async()=>{
  const f=fixture();claude(f,[user('a','one',{timestamp:'2026-10-01T00:00:00Z'}),user('b','two',{timestamp:undefined})]);const snap=await session({...f.options,harnesses:['claude']}).run();expect(snap.insights).toEqual([]);expect(snap.phrases).toEqual([]);
  fs.rmSync(path.join(f.options.claudeDir!,'projects'),{recursive:true});claude(f,[user('x','same',{entrypoint:'sdk-ts'}),user('y','same',{entrypoint:'sdk-ts'})]);const automatic=await session({...f.options,harnesses:['claude']}).run();expect(automatic.insights).toEqual([]);expect(automatic.phrases).toEqual([]);
 });
 it('memoizes repeated validated timestamps across progress snapshots without changing timezone counts',async()=>{
  const f=fixture();for(let source=0;source<3;source++)claude(f,Array.from({length:10},(_,i)=>user(`source-${source}-${i}`,'input '+i,{sessionId:'source-'+source})),String(source));const parts=vi.spyOn(Intl.DateTimeFormat.prototype,'formatToParts');const snap=await session({...f.options,harnesses:['claude'],timezone:'Asia/Kolkata'}).run();expect(snap.metrics.humanPrompts.value).toBe(30);expect(snap.activity).toEqual([{date:'2026-10-02',count:30}]);expect(parts).toHaveBeenCalledTimes(1);
 });
});
