#!/usr/bin/env python3
"""
check-privacy.py -- fail when a committed file carries real-corpus content.

This repository is public. Its whole subject is other people's AI transcripts,
so the one bug it must never ship is a committed file that quotes somebody's
live corpus. `scripts/make-screens.sh` has asserted a forbidden-string list over
`docs/screens/` and the README since phase 0; this is that idea over every
tracked file, and it runs in CI.


THE RULE
========

A committed file carries REAL-CORPUS CONTENT when it reproduces -- or lets a
reader reconstruct -- something that was inside a live AI transcript, or inside
the private working tree that transcript ran in. Three families:

  1. TRANSCRIPT PROSE .. what a human typed, or what an agent replied or
     reasoned, verbatim or near-verbatim. Also the subject matter: a topic that
     appears in this repo only because it was in somebody's real sessions is
     the same leak in fewer words.

  2. CORPUS IDENTITY ... a session, thread or composer uuid that indexes a live
     transcript, and a session title.

  3. THE PRIVATE TREE .. a home-directory path or project slug naming a
     directory that is NOT this repository, plus the file names and file
     contents inside it. A project directory name is a fact about somebody's
     private life -- `maths_practice` and `Infant-State-Recognition-System`
     say what a person was studying and building -- and the slug is also the
     join key back to the transcript it came from.

And three things that look like leaks and are NOT, because scrubbing them would
cost the repo something it needs:

  a. THIS REPO'S OWN CHECKOUT PATH. `/Users/<name>/randomness/potsherd` names no
     private work. It appears because pnpm and vitest print their cwd in the
     banner of every pasted run, and the unedited banner is what makes the
     pasted evidence evidence.

  b. A KEPT `--potsherd-dir` CITED AS EVIDENCE. The plans' ground rules require
     it: "a real-corpus run is cited by its kept `--potsherd-dir` and its
     numbers". That path is mandated, not leaked. What must not follow it is the
     transcript-derived prose -- re-examinable does not mean published.

  c. OBVIOUSLY SYNTHETIC PLACEHOLDERS AND THE DEMO CORPUS'S OWN IDS.
     `/path/to/project`, `/Users/example`, `00000000-...`, and everything under
     `evals/fixture/`, `tests/fixtures/` and `docs/screens/`, which are
     generated by `scripts/make-*-corpus.mjs` from a seeded PRNG.

Severity follows from that: (1) and (2) are unconditional. (3) is a violation
even when it is "only a path", because the directory name is the private fact.


WHAT THIS SCRIPT CAN AND CANNOT CHECK
=====================================

No regex recognises prose. Family (1) is caught only by its known vocabulary
(CORPUS_TOPICS) and family (2) not at all. So this guard is a floor, not a
ceiling: passing it does not mean a file is clean, it means the file does not
carry any leak we have already seen. When you add a real-corpus run to the repo,
read what you are committing.


ALLOW vs DEBT
=============

ALLOW exempts a whole tree that is synthetic by construction. Every entry is
justified in place and is expected to stay forever.

DEBT pins a known violation that a specific task was not allowed to fix, by
exact count. Both directions fail: a count that GREW is a new leak, a count that
SHRANK means somebody scrubbed it and forgot to unpin it. That makes the list a
ratchet rather than a place to hide things.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------- rules

# Home-directory paths, in both the `/Users/name/x` and the Claude Code project
# slug `-Users-name-x` form. Matched broadly, then filtered by is_private_home()
# below, because whether a home path is a leak depends on where it points.
HOME_PATH = re.compile(r'[-/]Users[-/][A-Za-z0-9_.]+(?:[-/][A-Za-z0-9_.]+)*')

# Names that are documented stand-ins, not accounts. `x`, `me` and `dana` are
# used by packages/core docstrings; `example` is what the scrubbed docs use.
PLACEHOLDER_USERS = {'example', 'dev', 'dana', 'someone', 'user', 'you',
                     'test', 'x', 'me', 'name'}

# First path segment under the home directory that makes a path this project's
# own rather than somebody's private work. `randomness` holds the repository,
# the plan folder beside it and the kept `--potsherd-dir` evidence corpora;
# `.potsherd` is this tool's own state directory. Citing either by name is what
# the ground rules ask for. See (a) and (b) above.
OWN_TREE_ROOTS = ('randomness', '.potsherd')


def is_private_home(token: str) -> bool:
    """True when a `/Users/...` or `-Users-...` token names somebody's private tree."""
    parts = re.split(r'[-/]', token.lstrip('-/'))
    # parts == ['Users', <account>, <first segment>, ...]
    if len(parts) < 2:
        return False
    account = parts[1]
    if account.lower() in PLACEHOLDER_USERS:
        return False
    # `/Users/zebra` with nothing after it names a home directory and no project.
    if len(parts) == 2:
        return False
    if parts[2] in OWN_TREE_ROOTS:
        return False
    # Terminal output elides long paths mid-word (`-Users-zebra-rando...`). A
    # truncated final segment that is a prefix of an own-tree root is that root.
    if len(parts) == 3 and any(r.startswith(parts[2]) for r in OWN_TREE_ROOTS):
        return False
    return True


# Directory names taken off a real machine. The first six are the list
# `scripts/make-screens.sh` has enforced over the published screens since phase
# 0; the rest are the ones phase-4's HANDOFF recorded as still outstanding
# ("`Fulcrum` / `meghbrain` -- the user's own project names -- remain as
# examples in `--help` and fixtures").
REAL_PROJECT_NAMES = [
    'Meghavi', 'lexaiLMS', 'Veyu', 'anilearn', 'Crimes-cog', 'Ops-Outreach-Engine',
    'Fulcrum', 'meghbrain', 'maths_practice', 'maths-practice',
    'Infant-State-Recognition', 'Protfolio',
]

# Subject matter that is in this repo only because it was in somebody's real
# sessions. A topic is transcript prose with the words taken out.
CORPUS_TOPICS = [
    'astrolog', 'horoscop', 'kundli', 'nakshatra', 'jyotish',
    'DM_master_assignment', 'class_worksheets', 'infant cry',
]

RULES: dict[str, dict] = {
    'home-path': {
        'why': 'an absolute home path or project slug naming a directory that is not this repo',
        'find': lambda line: [m.group(0) for m in HOME_PATH.finditer(line)
                              if is_private_home(m.group(0))],
    },
    'project-name': {
        'why': 'a project directory name off a real machine',
        'find': lambda line: [n for n in REAL_PROJECT_NAMES if n in line],
    },
    'corpus-topic': {
        'why': 'subject matter that is here only because it was in a live corpus',
        'find': lambda line: [t for t in CORPUS_TOPICS if t.lower() in line.lower()],
    },
}

# ---------------------------------------------------------------------- allow

# (glob, rule or '*', why). Whole-tree exemptions. Synthetic by construction.
ALLOW: list[tuple[str, str, str]] = [
    # Generated by scripts/make-demo-corpus.mjs and make-eval-corpus.mjs from a
    # seeded PRNG. No byte of either tree came off a real machine.
    ('evals/fixture/**', '*', 'generated demo corpus, seeded PRNG, no live data'),
    ('tests/fixtures/**', '*', 'hand-written adapter fixtures, no live data'),
    # Rendered from the demo corpus. Held to a STRICTER rule than this one by
    # scripts/make-screens.sh, which bans `/Users/` outright on a published
    # screen. Regenerating them needs a ~6-minute card pass, so they are checked
    # where they are produced, not here.
    ('docs/screens/**', '*', 'demo-corpus renders, guarded by make-screens.sh instead'),
    # These three name every forbidden string in order to forbid it.
    ('scripts/check-privacy.py', '*', 'the guard itself; it must name what it bans'),
    ('scripts/make-screens.sh', 'project-name', 'the screens forbidden-string list'),
    ('tests/adapters/cursor.test.ts', 'project-name',
     'asserts tests/fixtures/cursor contains none of these; it has to spell them'),
    # Not text we wrote.
    ('pnpm-lock.yaml', '*', 'generated lockfile'),
]

# ---------------------------------------------------------------------- debt

# (path, rule, count, why). A KNOWN violation that a task was not allowed to
# fix, pinned to an exact number so it cannot grow. Unpin by scrubbing the file
# and deleting the line.
DEBT: list[tuple[str, str, int, str]] = [
    # ---- RESERVED by T5.7's brief: `packages/**` may not be edited by that
    # task. Docstrings and `--help` copy that explain the slug algorithms using
    # the real directories the algorithms were derived from. Each wants a
    # synthetic example with the same shape -- an underscore, a literal hyphen,
    # a nested path -- which is mechanical, but `--help` is user-visible copy
    # and belongs to whoever owns packages/.
    ('packages/cli/src/filters.ts', 'project-name', 3, 'RESERVED: --help example'),
    ('packages/cli/src/index.ts', 'corpus-topic', 1, 'RESERVED: --help example query'),
    ('packages/cli/src/index.ts', 'project-name', 2, 'RESERVED: --help example'),
    ('packages/core/src/adapters/cursor.ts', 'home-path', 3, 'RESERVED: slug docstrings'),
    ('packages/core/src/adapters/cursor.ts', 'project-name', 7, 'RESERVED: slug docstrings'),
    ('packages/core/src/cards/transcript.ts', 'home-path', 2, 'RESERVED: slug docstring'),
    ('packages/core/src/cards/transcript.ts', 'project-name', 1, 'RESERVED: slug docstring'),
    ('packages/core/src/cards/write.ts', 'home-path', 1, 'RESERVED: slug docstring'),
    ('packages/core/src/cards/write.ts', 'project-name', 1, 'RESERVED: slug docstring'),
    ('packages/core/src/claude/scan.ts', 'home-path', 1, 'RESERVED: slug docstring'),
    ('packages/core/src/claude/scan.ts', 'project-name', 1, 'RESERVED: slug docstring'),
    ('packages/core/src/open-threads.ts', 'home-path', 2, 'RESERVED: docstring example'),
    ('packages/core/src/paths.ts', 'home-path', 2, 'RESERVED: slug docstring'),
    ('packages/core/src/paths.ts', 'project-name', 1, 'RESERVED: slug docstring'),
    ('packages/core/src/recall.ts', 'home-path', 1, 'RESERVED: slug docstring'),
    ('packages/core/src/recall.ts', 'project-name', 2, 'RESERVED: slug docstring'),
    ('packages/mcp/src/tools/find.ts', 'project-name', 2, 'RESERVED: tool description'),
    ('packages/mcp/src/tools/ls.ts', 'project-name', 1, 'RESERVED: tool description'),

    # ---- Asserts the literal text of `find --help`, which lives in
    # packages/cli/src/index.ts above. Scrubbing one side of an equality without
    # the other only makes the test lie; these two unpin together.
    ('tests/filters.test.ts', 'project-name', 1, 'pairs with packages/cli/src/index.ts'),

    # ---- Phase records and pasted evidence from phases 0-4. T5.7 was scoped to
    # docs/, scripts/, ci.yml and phase-5, so it did not edit signed-off phase
    # history. The two highest-value items -- ref-queries.txt and
    # evals-reference-set.txt, which held QUERIES TYPED AGAINST THE LIVE CORPUS --
    # were cleared at integration on 22 aug 2026; the ratchet asked for their DEBT
    # lines to be deleted and they were. What remains is `packages/**` help copy and
    # phase-0..4 evidence, which
    # is family (1) prose, not just a path. Re-running the evidence is the
    # honest fix for the pasted runs; the prose ones can be edited in place with
    # a note, the way this file's header describes.
    ('phases/phase-0/HANDOFF.md', 'project-name', 2, 'audit output naming wiped projects'),
    ('phases/phase-1/WAVE.md', 'home-path', 1, 'finding F15 cites the real slug it resolved'),
    ('phases/phase-1/WAVE.md', 'project-name', 2, 'finding F15 cites the real slug it resolved'),
    ('phases/phase-2/VERIFICATION.md', 'project-name', 1, 'quotes a real prompt from the corpus'),
    ('phases/phase-3/evidence-T3.2-T3.3/help.txt', 'corpus-topic', 1, 'pasted --help, pairs with packages/cli'),
    ('phases/phase-3/evidence-T3.2-T3.3/help.txt', 'project-name', 1, 'pasted --help, pairs with packages/cli'),
    ('phases/phase-4/HANDOFF.md', 'project-name', 2, 'the line that recorded this debt in the first place'),
    ('phases/phase-4/evidence-T4.1/patch-tests.py', 'project-name', 2, 'a patch script against the pre-rename tests'),
    ('phases/phase-4/evidence-T4.3/doctor-privacy.txt', 'home-path', 1, 'pasted `doctor --privacy` over the live corpus'),
    ('phases/phase-4/evidence-T4.3/doctor-privacy.txt', 'project-name', 2, 'pasted `doctor --privacy` over the live corpus'),
    ('phases/phase-4/evidence-T4.3/run1-by-id.txt', 'project-name', 1, 'pasted `ask` run over the live corpus'),
    ('phases/phase-4/evidence-T4.3/run2-by-query.txt', 'project-name', 1, 'pasted `ask` run over the live corpus'),
    ('phases/phase-4/evidence-T4.3/run6-clip-no-tool.txt', 'project-name', 1, 'pasted `ask` run over the live corpus'),
    ('phases/phase-4/registration-T4.1.txt', 'project-name', 1, 'comment on an `ask` input shape'),
]

# --------------------------------------------------------------------- engine

SKIP_SUFFIXES = {'.png', '.jpg', '.jpeg', '.gif', '.pdf', '.zip', '.wasm', '.onnx', '.bin'}


def tracked_files() -> list[str]:
    out = subprocess.run(['git', 'ls-files', '-z'], cwd=REPO,
                         capture_output=True, text=True, check=True)
    return [f for f in out.stdout.split('\0') if f]


def allowed(path: str, rule: str) -> str | None:
    for glob, r, why in ALLOW:
        if r not in ('*', rule):
            continue
        if glob.endswith('/**'):
            if path.startswith(glob[:-2]):
                return why
        elif path == glob:
            return why
    return None


def main(argv: list[str]) -> int:
    files = argv[1:] or tracked_files()
    found: dict[tuple[str, str], list[tuple[int, str]]] = {}
    swept = 0

    for path in files:
        p = REPO / path
        if p.suffix.lower() in SKIP_SUFFIXES or not p.is_file():
            continue
        try:
            text = p.read_text(encoding='utf-8')
        except (UnicodeDecodeError, OSError):
            continue
        swept += 1
        for rule, spec in RULES.items():
            if allowed(path, rule):
                continue
            for n, line in enumerate(text.splitlines(), 1):
                for hit in spec['find'](line):
                    found.setdefault((path, rule), []).append((n, hit))

    pinned = {(path, rule): (count, why) for path, rule, count, why in DEBT}
    new: list[str] = []
    stale: list[str] = []

    for (path, rule), hits in sorted(found.items()):
        if (path, rule) in pinned:
            expected, _why = pinned[(path, rule)]
            if len(hits) > expected:
                new.append(
                    f'  {path}  [{rule}]  pinned at {expected}, found {len(hits)}\n'
                    + '\n'.join(f'      line {n}: {h}' for n, h in hits[expected:]))
            elif len(hits) < expected:
                stale.append(f'  {path}  [{rule}]  pinned at {expected}, found only {len(hits)}')
            continue
        shown = '\n'.join(f'      line {n}: {h}' for n, h in hits[:8])
        if len(hits) > 8:
            shown += f'\n      ... and {len(hits) - 8} more'
        new.append(f"  {path}  [{rule}]  {RULES[rule]['why']}\n{shown}")

    for (path, rule), (expected, _why) in sorted(pinned.items()):
        if (path, rule) not in found:
            stale.append(f'  {path}  [{rule}]  pinned at {expected}, now clean '
                         f'-- delete the DEBT line')

    if not new and not stale:
        print(f'privacy: {swept} tracked text files swept, no real-corpus content, '
              f'{len(DEBT)} pinned known violations all at their expected counts.')
        return 0

    print('=' * 78)
    print('PRIVACY CHECK FAILED -- a committed file carries real-corpus content.')
    print('=' * 78)
    if new:
        print('\nNEW VIOLATIONS:\n')
        print('\n'.join(new))
    if stale:
        print('\nPINNED COUNTS THAT NO LONGER MATCH '
              '(somebody scrubbed a file and left the pin behind):\n')
        print('\n'.join(stale))
    print(f"""
{'-' * 78}
THE RULE, so you can decide what to do about it
{'-' * 78}

This repo is public and its subject is other people's transcripts. A committed
file carries REAL-CORPUS CONTENT when it reproduces, or lets a reader
reconstruct, something that was inside a live AI transcript or the private
working tree that transcript ran in:

  1. transcript prose -- what a human typed, what an agent replied or reasoned,
     and the subject matter of it (a topic is prose with the words taken out);
  2. corpus identity -- a session/thread/composer uuid, or a session title;
  3. the private tree -- a home path or project slug naming a directory that is
     not this repository, and the file names inside it. The directory name IS
     the private fact: `maths_practice` says what somebody was studying.

These are NOT violations, and you should not "fix" them:

  a. this repository's own checkout path, e.g. `/Users/<you>/randomness/potsherd`
     -- it names no private work, and it is in every pasted pnpm/vitest banner,
     which is what makes the pasted run evidence;
  b. a kept `--potsherd-dir` cited as evidence -- the plans' ground rules
     REQUIRE a real-corpus run to be cited by its kept dir and its numbers. What
     must not follow it is the transcript-derived prose. Re-examinable does not
     mean published;
  c. obviously synthetic placeholders and the demo corpus's own ids --
     `/path/to/project`, `/Users/example`, `00000000-...`, and everything under
     `evals/fixture/`, `tests/fixtures/`, `docs/screens/`.

SO: replace the content, keep the structure. A record keeps every key, the same
types, the same nesting and the same ordering -- only the human-authored values
become synthetic, and they stay internally consistent so the format is still
learnable. See docs/upstream/PHASE-1-SCOUT.md for what that looks like done.

If a file genuinely needs the real shape and you cannot change it, add a line to
DEBT in scripts/check-privacy.py with an exact count and a reason. Do not widen
ALLOW to cover it: ALLOW is for trees that are synthetic by construction, DEBT is
for known violations, and the difference is the point.

No regex recognises prose. Passing this check does not mean a file is clean --
it means the file carries no leak we have already seen. Read what you commit.
""")
    return 1


if __name__ == '__main__':
    sys.exit(main(sys.argv))
