#!/usr/bin/env python3
"""
check-privacy.py -- fail when a committed file carries real-corpus content.

This repository is public. Its whole subject is other people's AI transcripts,
so the one bug it must never ship is a committed file that quotes somebody's
live corpus. `scripts/make-screens.sh` has asserted a forbidden-string list over
`docs/screens/` and the README since phase 0; this is that idea over every
tracked file, and it runs in CI.


THE RULE
========

A committed file carries REAL-CORPUS CONTENT when it reproduces -- or lets a
reader reconstruct -- something that was inside a live AI transcript, or inside
the private working tree that transcript ran in. Three families:

  1. TRANSCRIPT PROSE .. what a human typed, or what an agent replied or
     reasoned, verbatim or near-verbatim. Also the subject matter: a topic that
     appears in this repo only because it was in somebody's real sessions is
     the same leak in fewer words.

  2. CORPUS IDENTITY ... a session, thread or composer uuid that indexes a live
     transcript, and a session title.

  3. THE PRIVATE TREE .. a home-directory path or project slug naming a
     directory that is NOT this repository, plus the file names and file
     contents inside it. A project directory name is a fact about somebody's
     private life -- `maths_practice` and `Infant-State-Recognition-System`
     say what a person was studying and building -- and the slug is also the
     join key back to the transcript it came from.

And three things that look like leaks and are NOT, because scrubbing them would
cost the repo something it needs:

  a. THIS REPO'S OWN CHECKOUT PATH. `/Users/<name>/randomness/potsherd` names no
     private work. It appears because pnpm and vitest print their cwd in the
     banner of every pasted run, and the unedited banner is what makes the
     pasted evidence evidence.

  b. A KEPT `--potsherd-dir` CITED AS EVIDENCE. The plans' ground rules require
     it: "a real-corpus run is cited by its kept `--potsherd-dir` and its
     numbers". That path is mandated, not leaked. What must not follow it is the
     transcript-derived prose -- re-examinable does not mean published.

  c. OBVIOUSLY SYNTHETIC PLACEHOLDERS AND THE DEMO CORPUS'S OWN IDS.
     `/path/to/project`, `/Users/example`, `00000000-...`, and everything under
     `evals/fixture/`, `tests/fixtures/` and `docs/screens/`, which are
     generated by `scripts/make-*-corpus.mjs` from a seeded PRNG.

Severity follows from that: (1) and (2) are unconditional. (3) is a violation
even when it is "only a path", because the directory name is the private fact.


WHAT THIS SCRIPT CAN AND CANNOT CHECK
=====================================

No regex recognises prose. This guard is a floor, not a ceiling: passing it does
not mean a file is clean, it means the file carries no leak we have already
seen. When you add a real-corpus run to the repo, read what you are committing.

Rule by rule, what it catches and what it does not:

  home-path ...... catches `/Users/<user>/x` and `/home/<user>/x`, in slash and
                   Claude-Code-slug form, on any account not in
                   PLACEHOLDER_USERS. `..` is resolved before the own-tree
                   exemption is applied, so `/Users/x/randomness/../Client` no
                   longer passes as "the repo's own tree".
                   STILL OPEN: `~/x`, `$HOME/x` and a bare relative slug --
                   `Some-Client/notes.md` is a private path with no home
                   directory in front of it and nothing here will see it.
                   Windows paths (`C:` + backslashes) are not matched either.

  project-name ... an exact-substring list. Exact is the whole weakness: the
                   list held `Meghavi` and `format.ts` shipped `Second-Brain`
                   for a year, because a different substring of the same
                   private name is a different string. Adding a name catches
                   that name and teaches nothing about the next one.

  corpus-id ...... hashed, so the guard can ban an id without publishing it.
                   Catches the ids we know about, in short and uuid form.
                   STILL OPEN: an id nobody has told this file about looks
                   exactly like a synthetic one, because it is 8 hex
                   characters. There is no test that distinguishes them. If you
                   paste a real id, this will not save you.

  corpus-title ... hashed word n-grams, scanned across one line break so a
                   wrapped comment is still one title.
                   STILL OPEN: same as ids -- only titles already listed, and
                   only near-verbatim. Reword a title and it passes.

  corpus-topic ... a known-vocabulary list, and the same exact-substring
                   weakness as project-name. It is the only thing standing
                   between family (1) and the repository, and family (1) is
                   free-form prose. Treat it as a reminder, not a filter.

  transcript-record
                   the one shape of family (1) that a regex CAN see, added in
                   phase 8 after `docs/upstream/PHASE-1-SCOUT.md` published a
                   real `~/.pi` assistant `thinking` block for six phases and
                   every rule above passed it every time. A transcript record
                   is a one-line JSON object -- `"thinking":"`, `"role":
                   "assistant"`, `"parentId":` or `<user_query>` -- pasted into
                   `docs/**` as a format sample. When one carries a prose
                   payload over 100 characters and nothing within 60 lines
                   declares the samples synthetic, this fires.
                   It does not judge whether the prose is real; nothing here
                   can. It enforces a POLICY: say what a sample is, next to it.
                   STILL OPEN: the declaration is an assertion by whoever
                   committed the file, so typing the word walks around it. That
                   is a real limit and, per this file's own history, worth
                   having anyway -- the six-phase leak was nobody being asked
                   the question, not somebody answering it falsely. Also open:
                   a payload UNDER 100 characters is invisible, and a record
                   split across several lines by a formatter is not matched.


THE COMMAND
===========

  check-privacy.py              sweep every tracked text file. This is CI.
  check-privacy.py PATH ...     sweep only these paths.
  check-privacy.py --selftest   run the probes; sweep nothing.

Anything else exits 2 with a usage message. It used to be read as a FILE NAME:
`--list-pins` was swept as a path, found missing, and every pinned violation was
reported as "now clean -- delete the DEBT line". A guard that is confidently
wrong is worse than no guard, because its advice was to break the ratchet.


ALLOW vs DEBT
=============

ALLOW exempts a whole tree that is synthetic by construction. Every entry is
justified in place and is expected to stay forever.

DEBT pins a known violation that a specific task was not allowed to fix, by
exact count. Both directions fail: a count that GREW is a new leak, a count that
SHRANK means somebody scrubbed it and forgot to unpin it. That makes the list a
ratchet rather than a place to hide things. It ran 34 -> 14 -> 0 across phases
7 and 8 and is EMPTY as of 22 aug 2026; an empty DEBT means every violation this
script can see has been repaired, and nothing more than that.
"""

from __future__ import annotations

import hashlib
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# --------------------------------------------------------------------- rules

# Home-directory paths, in both the `/Users/name/x` and the Claude Code project
# slug `-Users-name-x` form. Matched broadly, then filtered by is_private_home()
# below, because whether a home path is a leak depends on where it points.
#
# `home` as well as `Users`: a Linux machine's private tree is `/home/<user>/x`
# and its Claude Code slug is `-home-<user>-x`, and until T5.9 neither was
# matched at all. Every `/home/...` in this repo today is `dev` or `x`, both
# documented placeholders, so widening it costs nothing and closes a whole
# platform.
HOME_PATH = re.compile(r'[-/](?:Users|home)[-/][A-Za-z0-9_.]+(?:[-/][A-Za-z0-9_.]+)*')

# Names that are documented stand-ins, not accounts. `x`, `me` and `dana` are
# used by packages/core docstrings; `example` is what the scrubbed docs use.
PLACEHOLDER_USERS = {'example', 'dev', 'dana', 'someone', 'user', 'you',
                     'test', 'x', 'me', 'name'}

# First path segment under the home directory that makes a path this project's
# own rather than somebody's private work. `randomness` holds the repository,
# the plan folder beside it and the kept `--potsherd-dir` evidence corpora;
# `.potsherd` is this tool's own state directory. Citing either by name is what
# the ground rules ask for. See (a) and (b) above.
OWN_TREE_ROOTS = ('randomness', '.potsherd')


def is_private_home(token: str) -> bool:
    """True when a `/Users/...` or `-Users-...` token names somebody's private tree."""
    parts = re.split(r'[-/]', token.lstrip('-/'))
    # `..` escapes the own-tree exemption. `/Users/zebra/randomness/../Client`
    # matched OWN_TREE_ROOTS on segment 3 and was waved through, while naming a
    # sibling of the repo -- which is exactly the private tree this rule exists
    # for. Resolve the traversal first, then decide.
    resolved: list[str] = []
    for seg in parts:
        if seg == '.':
            continue
        if seg == '..':
            if resolved:
                resolved.pop()
            continue
        resolved.append(seg)
    parts = resolved
    # parts == ['Users', <account>, <first segment>, ...]
    if len(parts) < 2:
        return False
    account = parts[1]
    if account.lower() in PLACEHOLDER_USERS:
        return False
    # `/Users/zebra` with nothing after it names a home directory and no project.
    if len(parts) == 2:
        return False
    if parts[2] in OWN_TREE_ROOTS:
        return False
    # Terminal output elides long paths mid-word (`-Users-zebra-rando...`). A
    # truncated final segment that is a prefix of an own-tree root is that root.
    if len(parts) == 3 and any(r.startswith(parts[2]) for r in OWN_TREE_ROOTS):
        return False
    return True


# Directory names taken off a real machine. The first six are the list
# `scripts/make-screens.sh` has enforced over the published screens since phase
# 0; the rest are the ones phase-4's HANDOFF recorded as still outstanding
# ("`Fulcrum` / `meghbrain` -- the user's own project names -- remain as
# examples in `--help` and fixtures").
REAL_PROJECT_NAMES = [
    'Meghavi', 'lexaiLMS', 'Veyu', 'anilearn', 'Crimes-cog', 'Ops-Outreach-Engine',
    'Fulcrum', 'meghbrain', 'maths_practice', 'maths-practice',
    'Infant-State-Recognition', 'Protfolio',
]

# Subject matter that is in this repo only because it was in somebody's real
# sessions. A topic is transcript prose with the words taken out.
CORPUS_TOPICS = [
    'astrolog', 'horoscop', 'kundli', 'nakshatra', 'jyotish',
    'DM_master_assignment', 'class_worksheets', 'infant cry',
]

# ------------------------------------------------- family (2): corpus identity
#
# THE PROBLEM WITH LISTING A LEAK IN ORDER TO BAN IT. `REAL_PROJECT_NAMES` gets
# away with it: a project name is already public in the sense that it is a word.
# A session id is not -- it is the join key back to a transcript, and writing it
# into a public guard in order to ban it publishes the thing.
#
# So the ids and titles below are stored as truncated SHA-256, and the guard
# hashes what it finds. It can therefore say "line 462 carries a live-corpus
# session id" without ever carrying one itself. Adding a new one costs a
# `sha256(...).hexdigest()[:12]`, and the comment beside it says where it came
# from without saying what it is.
#
# One such id -- named in `plans/06` as a real session, with a real title -- was
# shipping in six committed files when T5.9 found it, including
# `packages/cli/src/index.ts`'s `--help` examples and `commands/show.ts`'s error
# message. Family (2) was, until then, "not checked at all". The `--help` and
# docstring copy now uses the demo corpus's own `9c4d2f18`, which is generated
# from a seeded PRNG and is the id `docs/screens/11-show.txt` already shows.

def _h(s: str) -> str:
    return hashlib.sha256(s.encode()).hexdigest()[:12]


# Truncated hashes of live-corpus session/thread ids, in both the 8-character
# short form and any full uuid form they have appeared in.
REAL_CORPUS_ID_HASHES = {
    '1f658710d374',  # plans/06, the session whose title is pinned below
    '74818f5256a7',  # plans/06, cited beside it
    '0bcfa8fe5899',  # the same short id padded into a uuid, as a test used it
}

# Any hex run long enough to be an id. Checked by hash, both whole and by its
# first 8 characters, because a short id is what actually gets pasted.
HEXISH = re.compile(r'\b[0-9a-f]{8,}(?:-[0-9a-f]{4}){0,3}(?:-[0-9a-f]{12})?\b')


def find_corpus_id(line: str) -> list[str]:
    hits = []
    for m in HEXISH.finditer(line):
        tok = m.group(0)
        for form in (tok, tok[:8]):
            if _h(form) in REAL_CORPUS_ID_HASHES:
                hits.append(f'{form[:4]}… (a live-corpus session id)')
                break
    return hits


# Truncated hashes of live-corpus session TITLES, normalised to lower-case
# words. A title is family (2) and family (1) at once: it indexes a transcript
# and it says what somebody was building.
REAL_CORPUS_TITLE_HASHES = {
    '35229ba8d0ef',  # plans/06 names it as the title of a real session
}
# The word-lengths of the titles above, so a line is only scanned at the sizes
# that could match.
TITLE_LENGTHS = (5,)

WORDS = re.compile(r'[a-z0-9]+')


def find_corpus_title(line: str, nxt: str = '') -> list[str]:
    """Match across a line break, because a title wraps in a comment.

    `// … a session called "Build X chat-only` / `// client"` is one title and
    two lines, and a per-line scan sees neither half. So each line is scanned
    together with the one after it, and only matches that *start* in the first
    line are reported -- otherwise every hit would be counted twice.
    """
    head = WORDS.findall(line.lower())
    words = head + WORDS.findall(nxt.lower())
    hits = []
    for n in TITLE_LENGTHS:
        for i in range(len(words) - n + 1):
            if i >= len(head):
                break
            if _h(' '.join(words[i:i + n])) in REAL_CORPUS_TITLE_HASHES:
                hits.append(f'{words[i]} …{n - 1} more (a live-corpus session title)')
    return hits


# ------------------------------------------ family (1): a transcript RECORD
#
# WHY THIS RULE EXISTS. `docs/upstream/PHASE-1-SCOUT.md` published a real
# assistant `thinking` block from `~/.pi` -- with its `id`, its `parentId` and
# its timestamp -- and a real truncated `<user_query>` from `~/.cursor`, to a
# public repository, from phase 1 until 22 aug 2026. Phase 5 found it, scrubbed
# the ids and the title, assigned the prose scrub, and the prose scrub was never
# done. Every rule above passed the file every time, for the reason this file's
# own header gives: no regex recognises prose.
#
# A regex still cannot read prose. But the leak was not loose prose -- it was a
# TRANSCRIPT RECORD: a one-line JSON object, pasted into a fenced block as a
# format sample, carrying somebody's words in a `thinking` or `text` field. That
# shape a regex can see.
#
# WHAT IT ACTUALLY ENFORCES, said plainly. Not "is this prose real?", which is
# undecidable here, but: **a transcript record sample carrying a substantial
# prose payload must be declared synthetic near where it appears.** That is a
# policy, and the declaration is an assertion by whoever committed it, so yes,
# it can be walked around by typing the word (`09 §10.3`). It is still worth
# having: the six-phase leak was not somebody defeating a check, it was nobody
# being asked the question. This rule asks it, in CI, every time.
#
# It is deliberately scoped to `docs/**`. That is where format research lives
# and where every sample of this kind has ever been committed; `tests/fixtures`
# and `evals/fixture` are generated or hand-written and already ALLOWed.

# The record shapes the real leak had, plus the two that index it. `parentId` is
# the thread pointer pi and Claude Code both carry; `<user_query>` is cursor's
# wrapper around what a human typed.
TRANSCRIPT_MARKERS = re.compile(
    r'"thinking"\s*:\s*"'
    r'|"role"\s*:\s*"assistant"'
    r'|"parentId"\s*:'
    r'|<user_query>'
)

# The fields inside such a record that hold WORDS rather than structure. A
# `parentId`, a model name and a token count are not what leaked.
TRANSCRIPT_PAYLOAD = re.compile(r'"(?:text|thinking|content|summary|title)"\s*:\s*"((?:[^"\\]|\\.)*)"')
TRANSCRIPT_QUERY = re.compile(r'<user_query>(.*?)</user_query>', re.S)

# THE THRESHOLD, and why this number. The `thinking` block that leaked ran to
# **128 characters** -- not a guess: `PHASE-1-SCOUT.md`'s own
# `original \`thinking\` 128 chars` annotation records the length of what was
# elided, and that annotation survived the purge that removed the text. So the
# threshold has to sit below 128 or it does not catch the thing it was written
# for. 100 characters is about a sentence and a half of English -- long enough
# that a matched string is somebody's words and not a field name, a `<redacted>`
# marker, a model id or a two-word test prompt, and 28 characters of headroom
# under the one real measurement available. Lower would be safe too; the cost of
# lower is only that more samples must carry the declaration, which is not a
# cost worth optimising away.
TRANSCRIPT_PAYLOAD_CHARS = 100

# What counts as declaring a block synthetic: the word AND the thing it is said
# about, on one line.
#
# The word alone was not enough, and this is not hypothetical -- it was measured
# while writing the rule. `PHASE-1-SCOUT.md` line 1492 says a harness "injects a
# synthetic summary", about the harness's own behaviour and about nothing in
# this repository, and that one incidental sentence exempted a record 50 lines
# below it. Requiring `record` / `example` / `sample` on the same line kills
# that: all three declarations in `docs/` today say "every record in this block
# is synthetic" or "every example above is ... synthetic", and prose about a
# harness's synthetic summaries does not.
TRANSCRIPT_DECLARED = re.compile(r'\bsynthetic\b|\binvented\b', re.I)
TRANSCRIPT_DECLARED_ABOUT = re.compile(r'\brecords?\b|\bexamples?\b|\bsamples?\b', re.I)

# How far from the record that declaration may sit. MEASURED, not chosen: in
# `docs/upstream/PHASE-1-SCOUT.md` the declaration leads its block and the block
# runs 45 lines past it; in `docs/formats/cursor.md` the declaration is a
# TRAILING note after six samples, 39 lines below the first of them. 60 is the
# widest real gap plus half again. A wider window is a WEAKER rule -- it lets a
# declaration on one block cover an undeclared sample further down -- so this
# number should shrink if it ever can, never grow to fit a new file.
TRANSCRIPT_WINDOW = 60


def find_transcript_records(path: str, lines: list[str]) -> list[tuple[int, str]]:
    """A whole-file rule: it needs the path (docs/ only) and the neighbouring lines."""
    if not path.startswith('docs/'):
        return []
    hits: list[tuple[int, str]] = []
    for i, line in enumerate(lines):
        if not TRANSCRIPT_MARKERS.search(line):
            continue
        payloads = [m.group(1) for m in TRANSCRIPT_PAYLOAD.finditer(line)]
        payloads += TRANSCRIPT_QUERY.findall(line)
        longest = max((len(v) for v in payloads), default=0)
        if longest <= TRANSCRIPT_PAYLOAD_CHARS:
            continue
        lo = max(0, i - TRANSCRIPT_WINDOW)
        hi = min(len(lines), i + TRANSCRIPT_WINDOW + 1)
        if any(TRANSCRIPT_DECLARED.search(l) and TRANSCRIPT_DECLARED_ABOUT.search(l)
               for l in lines[lo:hi]):
            continue
        hits.append((i + 1,
                     f'a transcript record whose longest prose payload is {longest} characters, '
                     f'with nothing within {TRANSCRIPT_WINDOW} lines calling it synthetic'))
    return hits


RULES: dict[str, dict] = {
    'home-path': {
        'why': 'an absolute home path or project slug naming a directory that is not this repo',
        'find': lambda line: [m.group(0) for m in HOME_PATH.finditer(line)
                              if is_private_home(m.group(0))],
    },
    'project-name': {
        'why': 'a project directory name off a real machine',
        'find': lambda line: [n for n in REAL_PROJECT_NAMES if n in line],
    },
    'corpus-id': {
        'why': 'a session/thread id that indexes a live transcript',
        'find': find_corpus_id,
    },
    'corpus-title': {
        'why': 'a live-corpus session title',
        'find': find_corpus_title,
        'lookahead': True,
    },
    'corpus-topic': {
        'why': 'subject matter that is here only because it was in a live corpus',
        'find': lambda line: [t for t in CORPUS_TOPICS if t.lower() in line.lower()],
    },
    'transcript-record': {
        'why': 'a transcript record sample in docs/** carrying a long prose payload that '
               'nothing nearby declares synthetic',
        # `file` instead of `find`: this rule reads the path and the whole file,
        # because "is there a declaration near this line" is not a per-line
        # question. It returns (line number, message) pairs directly.
        'file': find_transcript_records,
    },
}

# ---------------------------------------------------------------------- allow

# (glob, rule or '*', why). Whole-tree exemptions. Synthetic by construction.
ALLOW: list[tuple[str, str, str]] = [
    # Generated by scripts/make-demo-corpus.mjs and make-eval-corpus.mjs from a
    # seeded PRNG. No byte of either tree came off a real machine.
    ('evals/fixture/**', '*', 'generated demo corpus, seeded PRNG, no live data'),
    ('tests/fixtures/**', '*', 'hand-written adapter fixtures, no live data'),
    # Rendered from the demo corpus. Held to a STRICTER rule than this one by
    # scripts/make-screens.sh, which bans `/Users/` outright on a published
    # screen. Regenerating them needs a ~6-minute card pass, so they are checked
    # where they are produced, not here.
    ('docs/screens/**', '*', 'demo-corpus renders, guarded by make-screens.sh instead'),
    # These three name every forbidden string in order to forbid it.
    ('scripts/check-privacy.py', '*', 'the guard itself; it must name what it bans'),
    ('scripts/make-screens.sh', 'project-name', 'the screens forbidden-string list'),
    ('scripts/make-cast.sh', 'project-name', 'the cast forbidden-string list — the same list, and'
     ' for the same reason: a guard has to name what it bans'),
    ('tests/adapters/cursor.test.ts', 'project-name',
     'asserts tests/fixtures/cursor contains none of these; it has to spell them'),
    # Not text we wrote.
    ('pnpm-lock.yaml', '*', 'generated lockfile'),
]

# ---------------------------------------------------------------------- debt

# (path, rule, count, why). A KNOWN violation that a task was not allowed to
# fix, pinned to an exact number so it cannot grow. Unpin by scrubbing the file
# and deleting the line.
DEBT: list[tuple[str, str, int, str]] = [
    # ---- Everything RESERVED by T5.7's brief -- eleven pins across seven files
    # in `packages/**`, docstrings and `--help` copy that explained the slug
    # algorithms using the real directories the algorithms were derived from --
    # was cleared in phase 7, which owned `packages/`. Each example keeps the
    # shape that was measured (an underscore, a literal hyphen, a nested path)
    # and substitutes the name, and each docstring now says that is what it is,
    # so no comment claims a measurement against a directory nobody can see.

    # ---- T5.9's four `corpus-title` hits in `recall.ts` were cleared in phase
    # 7, the way the note here asked: by re-deriving rather than renaming.
    #
    # Two of them (the `titles` weight, and the tie-break among equally
    # matching titles) are now measured on the **committed eval corpus** --
    # `potsherd find "timezone drift"` returns one session, on the strength of
    # its title alone, because that session's body contains neither word.
    # Anyone can re-run it.
    #
    # The other two (the corroboration cap, and `sessionScore`'s shape) cannot
    # be: they needed a 155-exchange session, and every session in the eval
    # corpus is one to three exchanges, so re-scoring every eval query at 0.12
    # and at 0.5 gives the identical ranking. Those two keep the finding and
    # drop the identity -- the shape and the numbers, with the comment saying
    # out loud that the corpus is not in this repository and that the behaviour
    # is pinned by `tests/recall.test.ts` rather than by the eval set. That is
    # this file's own rule: replace the content, keep the structure.
    #
    # The vendored plugin bundles are why it had to be done now rather than
    # later: `plugins/claude-code/dist/*.js` are esbuild output with the
    # comments intact, so a comment in `recall.ts` is a committed artefact
    # twice over. The guard caught it in the same commit that added them.

    # ---- Asserts the literal text of `find --help`, which lives in
    # packages/cli/src/index.ts above. Scrubbing one side of an equality without
    # the other only makes the test lie; these two unpin together.

    # ---- Phase records and pasted evidence from phases 0-4 -- fourteen pins
    # across nine files -- were cleared in phase 8 (T8.A), which leaves this list
    # EMPTY. 34 -> 14 -> 0. Every one of the fourteen was confirmed by this
    # script itself as "pinned at N, now clean" before its line was deleted,
    # because the list is a ratchet and deleting a line without that
    # confirmation is how a ratchet becomes a wish.
    #
    # Two techniques, both named in this file's header:
    #
    #   RE-RUN, for the five pasted command outputs (phase-3's `find --help`,
    #   phase-4's `doctor --privacy` and three `graft` runs). The command was
    #   run again against the synthetic demo corpus built by
    #   scripts/make-demo-corpus.mjs, with --claude-dir and --potsherd-dir
    #   inside a mktemp -d, and the paste replaced. Each file carries a header
    #   saying so and recording the original run's headline numbers, which are
    #   not private.
    #
    #   SUBSTITUTE, for the four prose records and two code/registration files
    #   that only cited a slug, a title or a project name. The identity is
    #   replaced and the structure and the finding are kept, and each carries a
    #   visible note saying it is a substitution so no future reader mistakes it
    #   for the original capture.
    #
    # An empty DEBT is not the same as a clean repository. This list only ever
    # held what this script can SEE, and the header is honest about how little
    # that is: `docs/upstream/PHASE-1-SCOUT.md` carried a real assistant
    # `thinking` block for six phases and no rule here fired once. The
    # `transcript-record` rule added in phase 8 is one shape recovered from that
    # failure, not a general answer to it.
]

# --------------------------------------------------------------------- engine

SKIP_SUFFIXES = {'.png', '.jpg', '.jpeg', '.gif', '.pdf', '.zip', '.wasm', '.onnx', '.bin'}


def tracked_files() -> list[str]:
    out = subprocess.run(['git', 'ls-files', '-z'], cwd=REPO,
                         capture_output=True, text=True, check=True)
    return [f for f in out.stdout.split('\0') if f]


def allowed(path: str, rule: str) -> str | None:
    for glob, r, why in ALLOW:
        if r not in ('*', rule):
            continue
        if glob.endswith('/**'):
            if path.startswith(glob[:-2]):
                return why
        elif path == glob:
            return why
    return None


# ------------------------------------------------------------------ selftest

# (label, line, rules it must trip). A guard nobody has watched fail is a guard
# nobody has watched. Every one of these was NOT CAUGHT before T5.9; the four
# CONTROL rows are the things the header promises are not leaks, and a rule that
# starts catching one of them has become useless in a different direction.
#
# A row may carry a FOURTH element, the pseudo-path the text is pretended to
# live at. Only `transcript-record` reads it, because only that rule is scoped
# to a directory. Rows without one are checked at a path outside `docs/`, which
# is where all eleven original probes have always effectively been.
SELFTEST: list[tuple] = [
    ('a live-corpus session uuid',
     'see session 85ef9531-1c4a-4f2b-9d3e-7a6b5c4d3e2f', ('corpus-id',)),
    ('the same id in short form',
     'potsherd show 85ef9531', ('corpus-id',)),
    ('a live-corpus session title',
     'a session called "Build Instagram chat-only client" wins', ('corpus-title',)),
    ('a title wrapped across a comment',
     '// … a session called "Build Instagram chat-only\n// client" wins',
     ('corpus-title',)),
    ('a Linux home path',
     'wrote /home/hjolt/Some-Private-Client/notes.md', ('home-path',)),
    ('a Linux project slug',
     'projects/-home-hjolt-Some-Private-Client', ('home-path',)),
    ('a traversal out of the own-tree exemption',
     '/Users/zebra/randomness/../Some-Private-Client/notes.md', ('home-path',)),
    ('CONTROL this repository\'s own checkout path',
     '/Users/zebra/randomness/potsherd/packages/core', ()),
    ('CONTROL a demo-corpus id',
     'potsherd show 9c4d2f18', ()),
    ('CONTROL a git sha',
     'commit b86bf59aa1c2d3e4f5061728394a5b6c7d8e9f01', ()),
    ('CONTROL placeholder home directories',
     'HOME=/home/dev/.claude and /Users/example/work', ()),

    # ---- transcript-record. THE HISTORICAL LEAK, RECONSTRUCTED.
    #
    # `git log --all -- docs/upstream/PHASE-1-SCOUT.md` no longer contains the
    # pre-purge blob -- the whole point of the purge -- so the leak cannot be
    # replayed from history. What CAN be replayed is its SHAPE, which the file
    # still documents: a pi `message` record, `role:"assistant"`, a `thinking`
    # block of 128 characters, carrying `id`, `parentId` and a timestamp, pasted
    # as a one-line JSON sample into a fenced block in `docs/`. The fixture below
    # is that record with synthetic words in it, and its `thinking` string is
    # exactly 128 characters long -- the one measurement of the real thing that
    # survives, taken from the file's own `original `thinking` 128 chars`
    # annotation. Only the length is real. If this rule had existed in phase 1,
    # this is the line it would have printed.
    ('the historical leak\'s shape: an undeclared pi assistant thinking record',
     '{"type":"message","id":"aa000004","parentId":"aa000003",'
     '"timestamp":"2026-05-13T08:21:03.196Z","message":{"role":"assistant",'
     '"content":[{"type":"thinking","thinking":"'
     'They want the retry budget raised, but the queue is the thing that is actually '
     'saturated, so I should go measure that one first.'
     '"},{"type":"text","text":"Let me look at the queue depth before changing the '
     'retry budget."}]}}',
     ('transcript-record',), 'docs/formats/pi.md'),

    ('an undeclared cursor <user_query> sample',
     '{"role":"user","message":{"content":[{"type":"text","text":'
     '"<timestamp>Friday, May 8, 2026, 6:05 AM (UTC+5:30)</timestamp>\\n'
     '<user_query>\\nthe importer keeps stalling on the third batch and I cannot '
     'tell whether it is the pool or the writer, can you look\\n</user_query>"}]}}',
     ('transcript-record',), 'docs/formats/cursor.md'),

    # The control that makes the two probes above mean something. Same record,
    # same length, same directory -- and one line saying what it is. This is the
    # shape every sample in `docs/upstream/PHASE-1-SCOUT.md` and
    # `docs/formats/cursor.md` carries today, which is why the sweep is clean.
    ('CONTROL the same record, declared synthetic in the line above it',
     '> every record in this block is **synthetic**: the shape was measured, the words are invented.\n'
     '{"type":"message","id":"aa000004","parentId":"aa000003",'
     '"timestamp":"2026-05-13T08:21:03.196Z","message":{"role":"assistant",'
     '"content":[{"type":"thinking","thinking":"'
     'They want the retry budget raised, but the queue is the thing that is actually '
     'saturated, so I should go measure that one first.'
     '"}]}}',
     (), 'docs/formats/pi.md'),

    # Two more controls, each isolating one half of the rule.
    ('CONTROL the same record shape with a payload under the threshold',
     '{"type":"message","id":"aa000004","parentId":"aa000003","message":{"role":"assistant",'
     '"content":[{"type":"thinking","thinking":"list the directory first"}]}}',
     (), 'docs/formats/pi.md'),

    ('CONTROL an undeclared record outside docs/',
     '{"type":"message","id":"aa000004","parentId":"aa000003","message":{"role":"assistant",'
     '"content":[{"type":"thinking","thinking":"'
     'They want the retry budget raised, but the queue is the thing that is actually '
     'saturated, so I should go measure that one first.'
     '"}]}}',
     (), 'tests/fixtures/pi/session.jsonl'),
]


# (label, argv after the script name, expected exit code). These probe the
# COMMAND, not a rule.
#
# WHY. `main()` was `files = argv[1:] or tracked_files()`, so an argument that
# was not `--selftest` became a file list -- including one that started with a
# dash. `python3 scripts/check-privacy.py --list-pins` therefore swept one
# nonexistent path, found nothing in it, concluded that all fourteen pinned
# violations were "now clean -- delete the DEBT line", and exited 1 with a
# confident and entirely wrong failure. A guard whose failure output can be
# wrong is worse than no guard, because somebody will act on it: the advice it
# gave was to delete a ratchet.
#
# Each probe runs the real command in a subprocess, as a person would type it,
# rather than calling the parser underneath it (`09` rule 12).
ARG_PROBES: list[tuple[str, list[str], int]] = [
    ('an unknown flag is a usage error, not a file list', ['--list-pins'], 2),
    ('a flag-shaped argument after a real path is still a usage error',
     ['scripts/check-privacy.py', '--pins'], 2),
    ('CONTROL an explicit path list is still accepted', ['scripts/check-privacy.py'], 0),
    # The same failure one layer down: a partial sweep used to report every
    # DEBT entry it had not looked at as "now clean -- delete the DEBT line".
    # It judges only the paths it was given now. This probe is worth keeping
    # even while DEBT is empty, because it is what will catch the regression on
    # the day somebody adds a pin back.
    ('a partial sweep does not judge the pins it did not look at',
     ['scripts/check-privacy.py', 'NOTICE'], 0),
]


def _probe_rules(path: str, text: str) -> set[str]:
    """Every rule that fires on one probe's text, at one pseudo-path."""
    lines = text.split('\n')
    got = set()
    for rule, spec in RULES.items():
        if spec.get('file'):
            if spec['file'](path, lines):
                got.add(rule)
            continue
        for n, line in enumerate(lines):
            nxt = lines[n + 1] if n + 1 < len(lines) else ''
            hits = spec['find'](line, nxt) if spec.get('lookahead') else spec['find'](line)
            if hits:
                got.add(rule)
    return got


def selftest() -> int:
    bad = []
    for row in SELFTEST:
        label, text, expect = row[0], row[1], row[2]
        # Rows with no pseudo-path are checked outside docs/, which is where all
        # eleven of the original probes have always effectively lived.
        path = row[3] if len(row) > 3 else 'scripts/probe.txt'
        got = _probe_rules(path, text)
        if got != set(expect):
            bad.append(f'  {label}\n      expected {sorted(expect)}, got {sorted(got)}')
        print(f"  {'ok  ' if got == set(expect) else 'FAIL'}  {label}"
              f"{'  [' + ', '.join(sorted(got)) + ']' if got else ''}")

    for label, args, want in ARG_PROBES:
        proc = subprocess.run([sys.executable, str(Path(__file__).resolve()), *args],
                              cwd=REPO, capture_output=True, text=True)
        ok = proc.returncode == want
        if not ok:
            bad.append(f'  {label}\n      expected exit {want}, got {proc.returncode}')
        print(f"  {'ok  ' if ok else 'FAIL'}  {label}  [exit {proc.returncode}]")

    if bad:
        print('\nSELFTEST FAILED:\n' + '\n'.join(bad))
        return 1
    print(f'\n  {len(SELFTEST) + len(ARG_PROBES)} probes, all as expected.')
    return 0


USAGE = """usage: check-privacy.py [--selftest | PATH ...]

  no arguments   sweep every tracked text file (what CI runs)
  PATH ...       sweep only these paths, relative to the repo root
  --selftest     run the rule probes and the argument probes, sweep nothing

Anything else is an error. It used to be a FILE NAME: `--list-pins` was swept as
a path, found to be missing, and reported every pinned violation as "now clean
-- delete the DEBT line". Being confidently wrong is the one thing a guard may
not do."""


def parse_args(args: list[str]) -> tuple[list[str] | None, str | None]:
    """(files, error). `files == []` means sweep everything tracked.

    Kept separate from main() so the failure has one place to live, and so the
    error text is the same whether the bad flag came first or last.
    """
    if '--selftest' in args:
        if len(args) > 1:
            return None, '--selftest takes no other arguments'
        return None, None
    unknown = [a for a in args if a.startswith('-')]
    if unknown:
        return None, f"unknown option: {' '.join(unknown)}"
    return args, None


def main(argv: list[str]) -> int:
    files, err = parse_args(argv[1:])
    if err:
        print(f'check-privacy.py: {err}\n', file=sys.stderr)
        print(USAGE, file=sys.stderr)
        return 2
    if files is None:
        return selftest()
    # A partial sweep must not report the pins it did not look at. Same failure
    # as the unknown-flag one above, one layer down: given an explicit path
    # list, every DEBT entry for a path NOT in that list is trivially "not
    # found", and the run would advise deleting all of them. So a partial sweep
    # judges only the paths it was given.
    partial = bool(files)
    files = files or tracked_files()
    found: dict[tuple[str, str], list[tuple[int, str]]] = {}
    swept = 0

    for path in files:
        p = REPO / path
        if p.suffix.lower() in SKIP_SUFFIXES or not p.is_file():
            continue
        try:
            text = p.read_text(encoding='utf-8')
        except (UnicodeDecodeError, OSError):
            continue
        swept += 1
        for rule, spec in RULES.items():
            if allowed(path, rule):
                continue
            lines = text.splitlines()
            if spec.get('file'):
                # A whole-file rule: it gets the path and every line, and hands
                # back the (line number, message) pairs itself.
                for n, hit in spec['file'](path, lines):
                    found.setdefault((path, rule), []).append((n, hit))
                continue
            for n, line in enumerate(lines, 1):
                # `find` takes the next line too when it declares a second
                # parameter, so a rule can span a wrapped comment.
                hits = (spec['find'](line, lines[n] if n < len(lines) else '')
                        if spec.get('lookahead') else spec['find'](line))
                for hit in hits:
                    found.setdefault((path, rule), []).append((n, hit))

    pinned = {(path, rule): (count, why) for path, rule, count, why in DEBT}
    new: list[str] = []
    stale: list[str] = []

    for (path, rule), hits in sorted(found.items()):
        if (path, rule) in pinned:
            expected, _why = pinned[(path, rule)]
            if len(hits) > expected:
                new.append(
                    f'  {path}  [{rule}]  pinned at {expected}, found {len(hits)}\n'
                    + '\n'.join(f'      line {n}: {h}' for n, h in hits[expected:]))
            elif len(hits) < expected:
                stale.append(f'  {path}  [{rule}]  pinned at {expected}, found only {len(hits)}')
            continue
        shown = '\n'.join(f'      line {n}: {h}' for n, h in hits[:8])
        if len(hits) > 8:
            shown += f'\n      ... and {len(hits) - 8} more'
        new.append(f"  {path}  [{rule}]  {RULES[rule]['why']}\n{shown}")

    swept_paths = set(files)
    for (path, rule), (expected, _why) in sorted(pinned.items()):
        if partial and path not in swept_paths:
            continue
        if (path, rule) not in found:
            stale.append(f'  {path}  [{rule}]  pinned at {expected}, now clean '
                         f'-- delete the DEBT line')

    if not new and not stale:
        pins = (f'{len(DEBT)} pinned known violations all at their expected counts'
                if DEBT else 'no pinned known violations left to carry')
        print(f'privacy: {swept} tracked text files swept, no real-corpus content, {pins}.')
        return 0

    print('=' * 78)
    print('PRIVACY CHECK FAILED -- a committed file carries real-corpus content.')
    print('=' * 78)
    if new:
        print('\nNEW VIOLATIONS:\n')
        print('\n'.join(new))
    if stale:
        print('\nPINNED COUNTS THAT NO LONGER MATCH '
              '(somebody scrubbed a file and left the pin behind):\n')
        print('\n'.join(stale))
    print(f"""
{'-' * 78}
THE RULE, so you can decide what to do about it
{'-' * 78}

This repo is public and its subject is other people's transcripts. A committed
file carries REAL-CORPUS CONTENT when it reproduces, or lets a reader
reconstruct, something that was inside a live AI transcript or the private
working tree that transcript ran in:

  1. transcript prose -- what a human typed, what an agent replied or reasoned,
     and the subject matter of it (a topic is prose with the words taken out);
  2. corpus identity -- a session/thread/composer uuid, or a session title;
  3. the private tree -- a home path or project slug naming a directory that is
     not this repository, and the file names inside it. The directory name IS
     the private fact: `maths_practice` says what somebody was studying.

These are NOT violations, and you should not "fix" them:

  a. this repository's own checkout path, e.g. `/Users/<you>/randomness/potsherd`
     -- it names no private work, and it is in every pasted pnpm/vitest banner,
     which is what makes the pasted run evidence;
  b. a kept `--potsherd-dir` cited as evidence -- the plans' ground rules
     REQUIRE a real-corpus run to be cited by its kept dir and its numbers. What
     must not follow it is the transcript-derived prose. Re-examinable does not
     mean published;
  c. obviously synthetic placeholders and the demo corpus's own ids --
     `/path/to/project`, `/Users/example`, `00000000-...`, and everything under
     `evals/fixture/`, `tests/fixtures/`, `docs/screens/`.

SO: replace the content, keep the structure. A record keeps every key, the same
types, the same nesting and the same ordering -- only the human-authored values
become synthetic, and they stay internally consistent so the format is still
learnable. See docs/upstream/PHASE-1-SCOUT.md for what that looks like done.

If a file genuinely needs the real shape and you cannot change it, add a line to
DEBT in scripts/check-privacy.py with an exact count and a reason. Do not widen
ALLOW to cover it: ALLOW is for trees that are synthetic by construction, DEBT is
for known violations, and the difference is the point.

No regex recognises prose. Passing this check does not mean a file is clean --
it means the file carries no leak we have already seen. Read what you commit.
""")
    return 1


if __name__ == '__main__':
    sys.exit(main(sys.argv))
