import {describe,it,expect} from 'vitest';
import {createAuditNavigation,auditPush,auditBack,auditMove,auditRows,auditSelectSection,reconcileAuditNavigation,applyAuditEvent,compactAuditWork} from '../../packages/cli/src/audit-ui/index.js';
import {auditFixture,promptFixture} from './fixture.js';
describe('Audit snapshot navigation',()=>{
 it('restores the exact stable row and scroll after a drill-down',()=>{const snapshot=auditFixture();let nav=createAuditNavigation('conversations');nav=auditMove(nav,auditRows(snapshot,nav),17,5);const old=nav;nav=auditPush(nav,{view:'prompts',conversationId:nav.selectedId});nav=auditMove(nav,auditRows(snapshot,nav,promptFixture()),1,5);expect(auditBack(nav)).toEqual(old);});
 it('reconciles stable identity across reordered rows and picks a bounded neighbor when absent',()=>{const snapshot=auditFixture(),base=createAuditNavigation('conversations'),rows=auditRows(snapshot,base);const nav=auditMove(base,rows,8,5);expect(reconcileAuditNavigation(nav,[...rows].reverse(),5).selectedId).toBe(nav.selectedId);const missing=rows.filter(r=>r.id!==nav.selectedId);const changed=reconcileAuditNavigation(nav,missing,5);expect(missing.some(r=>r.id===changed.selectedId)).toBe(true);expect(changed.scroll).toBeLessThan(missing.length);});
 it('preserves screenshot masking through back and section changes',()=>{const nav={...createAuditNavigation('projects'),screenshot:true};expect(auditBack(auditPush(nav,{view:'conversations',projectId:'project-0'})).screenshot).toBe(true);expect(auditSelectSection(nav,'sources').screenshot).toBe(true);});
 it('does not accept a progress event from another snapshot or an older sequence',()=>{const snapshot=auditFixture();expect(applyAuditEvent(snapshot,{type:'progress',snapshotId:'other',sequence:99,progress:{...snapshot.progress,completed:999},sources:[]})).toBe(snapshot);expect(applyAuditEvent(snapshot,{type:'progress',snapshotId:snapshot.snapshotId,sequence:4,progress:{...snapshot.progress,completed:999},sources:[]})).toBe(snapshot);expect(applyAuditEvent(snapshot,{type:'progress',snapshotId:snapshot.snapshotId,sequence:6,progress:{...snapshot.progress,completed:13},sources:snapshot.sources}).progress.completed).toBe(13);});
 it('keeps all taxonomy counts in explicit other rows with the same denominator',()=>{const work=Array.from({length:16},(_,i)=>({label:`label-${i}`,count:i+1,denominator:136,state:'observed' as const}));const compact=compactAuditWork(work,4);expect(compact).toHaveLength(4);expect(compact.at(-1)?.label).toBe('other labels');expect(compact.reduce((sum,r)=>sum+r.count,0)).toBe(136);expect(compact.every(r=>r.denominator===136)).toBe(true);});
});
