import {describe,it,expect,vi} from 'vitest';
import type {AuditSession,AuditSemanticPreview,AuditSnapshot,AuditPromptJudgment} from '../../packages/core/src/analytics/contracts.js';
import {AuditSemanticActions,createAuditSemanticSelection,buildAuditScreen,createAuditNavigation,auditRows} from '../../packages/cli/src/audit-ui/index.js';
import {composeJevJudgments} from '../../packages/core/src/analytics/jev-session.js';
import {auditFixture,promptFixture,evidenceFixture} from './fixture.js';
const lines=(screen:ReturnType<typeof buildAuditScreen>)=>screen.map(row=>row.map(s=>s.text).join('')).join('\n');
const preview=(key=true):AuditSemanticPreview=>({snapshotId:'fixture-audit',model:'Jev1.13.0',selectedConversations:1,eligiblePrompts:2,selectedPrompts:2,maxRequests:50,budgetUsd:.05,estimatedReservationUsd:.003,keyAvailable:key,outgoingFields:['target.role','target.text redacted','precedingUser[].text redacted','assistantContext unavailable'],windowCoverage:'partial',samples:[{promptId:'prompt-0',excerpt:'PRIVATE_PREVIEW_EXCERPT'}],gapCodes:['semantic_gold_unavailable']});
function session(key=true){const snapshot=auditFixture();const classify=vi.fn(async()=>snapshot),localPreview=vi.fn(async()=>preview(key)),cancel=vi.fn();return {snapshot,classify,localPreview,cancel,value:{run:async()=>snapshot,snapshot:()=>snapshot,cancel,prompts:async()=>promptFixture(),evidence:async()=>evidenceFixture(),preview:localPreview,classify,dispose(){}} as AuditSession};}
function judgment(confidence=.7):AuditPromptJudgment{return {promptId:'prompt-0',conversationId:'conversation-0',sourceRoute:promptFixture().prompts[0]!.route,contentHash:'hash',scopeHash:'scope',normalizationVersion:'fixture',questionVersion:'question-fixture',model:'Jev1.13.0',answers:{primary_intent:{type:'choice',choice:'feature_build',probabilities:{feature_build:.7,other:.3},confidence},verification:{type:'noul',noul:.4},relevance:{type:'score',score:1,legend:{'0':'none','1':'direct'},probabilities:{'0':.1,'1':.9},confidence:.9}},windowCoverage:'partial',primaryIntent:'feature_build',abstained:false};}
describe('explicit local preview and semantic consent',()=>{
 it('bounds selected scoped IDs and prefers the focused conversation',()=>{const snapshot=auditFixture();expect(createAuditSemanticSelection(snapshot).conversationIds).toHaveLength(20);expect(createAuditSemanticSelection(snapshot,'conversation-3').conversationIds).toEqual(['conversation-3']);expect(createAuditSemanticSelection(snapshot).maxPrompts).toBe(50);expect(createAuditSemanticSelection(snapshot).budgetUsd).toBe(.05);});
 it('opening preview, Enter without selected Send, and cancel make zero classification calls',async()=>{const s=session(),actions=new AuditSemanticActions(s.value);await actions.preview(s.snapshot,createAuditSemanticSelection(s.snapshot,'conversation-0'));await actions.send(s.snapshot,false);actions.cancel();await actions.send(s.snapshot,true);expect(s.localPreview).toHaveBeenCalledOnce();expect(s.classify).not.toHaveBeenCalled();});
 it('no key or screenshot view disables submission despite explicit Y',async()=>{for(const [key,screenshot] of [[false,false],[true,true]]){const s=session(key),actions=new AuditSemanticActions(s.value);await actions.preview(s.snapshot,createAuditSemanticSelection(s.snapshot,'conversation-0'));expect(await actions.send(s.snapshot,true,screenshot)).toBeNull();expect(s.classify).not.toHaveBeenCalled();}});
 it('explicit confirmation sends exactly approved bounds once, with an AbortSignal',async()=>{const s=session(),actions=new AuditSemanticActions(s.value);await actions.preview(s.snapshot,createAuditSemanticSelection(s.snapshot,'conversation-0'));await actions.send(s.snapshot,true);expect(s.classify).toHaveBeenCalledOnce();expect(s.classify.mock.calls[0]![0]).toMatchObject({consent:true,maxPrompts:50,maxRequests:50,budgetUsd:.05,conversationIds:['conversation-0']});expect(s.classify.mock.calls[0]![0].signal).toBeInstanceOf(AbortSignal);await actions.send(s.snapshot,true);expect(s.classify).toHaveBeenCalledOnce();});
 it('aborts an active job and cancels its source session without a new request',async()=>{const s=session(),actions=new AuditSemanticActions(s.value);s.value.classify=vi.fn(selection=>new Promise(resolve=>selection.signal!.addEventListener('abort',()=>resolve({...s.snapshot,semantics:{...s.snapshot.semantics,state:'cancelled'}}),{once:true})));await actions.preview(s.snapshot,createAuditSemanticSelection(s.snapshot,'conversation-0'));const job=actions.send(s.snapshot,true);await Promise.resolve();actions.cancel(true);expect((await job)?.semantics.state).toBe('cancelled');expect(s.cancel).toHaveBeenCalledOnce();expect(actions.running).toBe(false);});
 it('rejects a changed commitment and keeps old preview-less sessions compatible',async()=>{const s=session(),actions=new AuditSemanticActions(s.value);s.snapshot.commitment='before';await actions.preview(s.snapshot,createAuditSemanticSelection(s.snapshot,'conversation-0'));expect(await actions.send({...s.snapshot,commitment:'after'},true)).toBeNull();delete s.value.preview;expect(await new AuditSemanticActions(s.value).preview(s.snapshot,createAuditSemanticSelection(s.snapshot))).toBeNull();});
 it('masks samples and raw answers in S, without mutating stored source objects',()=>{const snapshot=auditFixture();snapshot.judgments=[judgment()];const p=preview(),nav={...createAuditNavigation(),editing:'semantic' as const};expect(lines(buildAuditScreen(snapshot,nav,{semanticPreview:p}))).toContain('PRIVATE_PREVIEW_EXCERPT');expect(lines(buildAuditScreen(snapshot,{...nav,screenshot:true},{semanticPreview:p}))).not.toContain('PRIVATE_PREVIEW_EXCERPT');const raw={...createAuditNavigation('conversations'),view:'judgment' as const,selectedId:'prompt-0'};expect(lines(buildAuditScreen(snapshot,raw))).toContain('primary_intent');expect(lines(buildAuditScreen(snapshot,{...raw,screenshot:true}))).not.toContain('primary_intent');expect(p.samples[0]!.excerpt).toBe('PRIVATE_PREVIEW_EXCERPT');});
 it('recomposes raw distributions locally and labels results experimental with actual support routes',()=>{const snapshot=auditFixture();snapshot.judgments=[judgment()];snapshot.semantics={...snapshot.semantics,state:'complete',eligiblePrompts:2,classifiedPrompts:1,uncertainPrompts:1,work:[{label:'feature_build',count:1,denominator:2,state:'partial'}]};const before=JSON.stringify(snapshot.judgments),low=composeJevJudgments(snapshot.judgments,snapshot.semantics,.65),high=composeJevJudgments(snapshot.judgments,snapshot.semantics,.8);expect(low.semantics.classifiedPrompts).toBe(1);expect(high.semantics.classifiedPrompts).toBe(0);expect(JSON.stringify(snapshot.judgments)).toBe(before);const viewed={...snapshot,...low};expect(lines(buildAuditScreen(viewed,createAuditNavigation('work')))).toContain('UNQUALIFIED');expect(auditRows(viewed,{...createAuditNavigation('work'),view:'conversations',category:'feature_build'}).map(r=>r.id)).toEqual(['conversation-0']);expect(low.judgments[0]!.sourceRoute).toEqual(snapshot.judgments[0]!.sourceRoute);});
});
