import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {piExtension} from '../../packages/core/src/pi-extension.ts';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'potsherd-pi-native-'));
const fake=path.join(root,'server.mjs');
fs.writeFileSync(fake,`import {createInterface} from 'node:readline';createInterface({input:process.stdin}).on('line',line=>{const x=JSON.parse(line);if(!x.id)return;const result=x.method==='tools/list'?{tools:[{name:'potsherd_read',description:'Read synthetic evidence',inputSchema:{type:'object',properties:{ref:{type:'string'}},required:['ref']}}]}:x.method==='tools/call'?{content:[{type:'text',text:x.params.arguments.ref}]}:{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'synthetic',version:'1'}};console.log(JSON.stringify({jsonrpc:'2.0',id:x.id,result}));});`);
const extension=path.join(root,'potsherd.ts');fs.writeFileSync(extension,piExtension({command:process.execPath,args:[fake]}));
const piPackage=process.env.POTSHERD_PI_NATIVE_PACKAGE;
if(!piPackage)throw new Error('Set POTSHERD_PI_NATIVE_PACKAGE to the installed pi package directory');
const {loadExtensions}=await import(path.join(piPackage,'dist/core/extensions/loader.js'));
const result=await loadExtensions([extension],root);
if(result.errors.length)throw new Error(JSON.stringify(result.errors));
const ext=result.extensions[0];const tool=ext.tools.get('potsherd_read');
const first=await tool.definition.execute('1',{ref:'synthetic-native-evidence'},new AbortController().signal,()=>{},{});
for(const fn of ext.handlers.get('session_shutdown')??[])await fn({},{});
for(const fn of ext.handlers.get('session_start')??[])await fn({},{});
const second=await tool.definition.execute('2',{ref:'fresh-session-evidence'},new AbortController().signal,()=>{},{});
for(const fn of ext.handlers.get('session_shutdown')??[])await fn({},{});
assert.equal(first.content[0].text,'synthetic-native-evidence');assert.equal(second.content[0].text,'fresh-session-evidence');
console.log(JSON.stringify({piVersion:JSON.parse(fs.readFileSync(path.join(piPackage,'package.json'),'utf8')).version,loader:'native',modelTurn:false,tools:[...ext.tools.keys()],first,second}));
fs.rmSync(root,{recursive:true,force:true});
